In [1]:
# Set seed for reproducibility
SEED = 45

# Import necessary libraries
import os

# Set environment variables before importing modules
# Set PYTHONHASHSEED for deterministic hash values
os.environ['PYTHONHASHSEED'] = str(SEED) 
# Set MPLCONFIGDIR to avoid creating config files in the home directory
os.environ['MPLCONFIGDIR'] = os.getcwd() + '/configs/' 

# Suppress warnings
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=Warning)

# Import necessary modules
import logging
import random
import numpy as np

# Set seeds for random number generators in NumPy and Python's 'random'
np.random.seed(SEED)
random.seed(SEED)

# --- PyTorch Setup and Device Configuration ---
import torch
torch.manual_seed(SEED)
from torch import nn
from torch.utils.tensorboard import SummaryWriter
from torch.utils.data import TensorDataset, DataLoader

logs_dir = "tensorboard"

# 1. Check for CUDA (NVIDIA GPU)
if torch.cuda.is_available():
    device = torch.device("cuda")
    torch.cuda.manual_seed_all(SEED)
    # Enable cuDNN benchmark for faster, but sometimes less reproducible, training
    # Set to False if absolute reproducibility is paramount
    torch.backends.cudnn.benchmark = True 
# 3. Default to CPU
else:
    device = torch.device("cpu")

print(f"PyTorch version: {torch.__version__}")
print(f"Device: {device}")
# ---------------------------------------------

# Import other libraries
import copy
import shutil
from itertools import product
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Configure plot display settings (No more %matplotlib inline)
sns.set(font_scale=1.4)
sns.set_style('white')
plt.rc('font', size=14)

2025-11-17 15:22:47.497561: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1763392967.662385      48 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1763392967.715684      48 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

PyTorch version: 2.6.0+cu124
Device: cuda

## 🔄 **Data Preprocessing**

In [2]:
# Load the dataset from a CSV file
df_train = pd.read_csv("/kaggle/input/pirate_pain_train.csv")
df_public_test = pd.read_csv("/kaggle/input/pirate_pain_test.csv")
df_labels = pd.read_csv("/kaggle/input/pirate_pain_train_labels.csv")

In [3]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_labels['label_encoded'] = label_encoder.fit_transform(df_labels['label'])
# This gives: ['high_pain', 'low_pain', 'no_pain']
label_map = {'no_pain': 0, 'low_pain': 1, 'high_pain': 2}
df_labels['label_encoded'] = df_labels['label'].map(label_map)
df_labels.drop(["label"], axis =1)

     sample_index  label_encoded
0               0              0
1               1              0
2               2              1
3               3              0
4               4              0
..            ...            ...
656           656              0
657           657              0
658           658              0
659           659              0
660           660              0

[661 rows x 2 columns]

In [4]:
#df = pd.concat([df_train, df_public_test], axis=0).reset_index(drop=True)

In [5]:
from sklearn.preprocessing import MinMaxScaler
def preProcess_with_2D_PE(df: pd.DataFrame, scaler: MinMaxScaler, fit_scaler: bool = True):
    
    PERIOD = 80

    # --- 1. Feature Engineering and Dropping Columns ---
    pain_cols = ["pain_survey_1", "pain_survey_2", "pain_survey_3", "pain_survey_4"]
    existing_pain_cols = [c for c in pain_cols if c in df.columns]
    
    if existing_pain_cols:
        df["pain_survey"] = np.floor(df[existing_pain_cols].median(axis=1)).astype(int)
        df.drop(columns=existing_pain_cols, inplace=True)

    # merged_n_features
    if all(col in df.columns for col in ['n_legs', 'n_hands', 'n_eyes']):
        df['merged_n_features'] = np.where(
            (df['n_legs'] == 'two') & (df['n_hands'] == 'two') & (df['n_eyes'] == 'two'),
            0, 
            1 
        )
        df.drop(columns=['n_legs', 'n_hands', 'n_eyes'], inplace=True)
    
    # Drop joint_30 if exists
    if 'joint_30' in df.columns:
        df.drop(columns=['joint_30'], inplace=True)
    
    # --- 2. 2D Sinusoidal Encoding ---
    if 'time' in df.columns:
        df["time_sin"] = np.sin(2 * np.pi * df["time"] / PERIOD)
        df["time_cos"] = np.cos(2 * np.pi * df["time"] / PERIOD)
        df.drop(columns=["time"], inplace=True)

    # --- 3. Scaling ---
    pe_cols = ["time_sin", "time_cos"]
    cols_to_scale = [col for col in df.columns if col not in ['sample_index', "label_encoded"] + pe_cols]
    
    if cols_to_scale:
        if fit_scaler:
            df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])
        else:
            df[cols_to_scale] = scaler.transform(df[cols_to_scale])

feature_scaler = MinMaxScaler()
preProcess_with_2D_PE(df_train, feature_scaler, fit_scaler=True)
preProcess_with_2D_PE(df_public_test, feature_scaler, fit_scaler=False)

In [6]:
df_train.head()

,sample_index,joint_00,joint_01,joint_02,joint_03,joint_04,joint_05,joint_06,joint_07,joint_08,...,joint_24,joint_25,joint_26,joint_27,joint_28,joint_29,pain_survey,merged_n_features,time_sin,time_cos
0,0,0.777507,0.738252,0.779512,0.804419,0.714916,0.736643,0.639301,0.733981,0.478382,...,3.162813e-04,0.000004,0.014214,0.011376,0.018978,0.020291,0.5,0.0,0.000000,1.000000
1,0,0.806256,0.765147,0.761153,0.838021,0.735684,0.729533,0.654605,0.760554,0.486231,...,9.828599e-07,0.000000,0.010748,0.000000,0.009473,0.010006,1.0,0.0,0.078459,0.996917
2,0,0.767592,0.721439,0.772834,0.777832,0.724497,0.734962,0.692340,0.787647,0.441994,...,6.626013e-05,0.000003,0.013097,0.006830,0.017065,0.016856,1.0,0.0,0.156434,0.987688
3,0,0.666220,0.810416,0.763971,0.785928,0.679928,0.722504,0.589127,0.793524,0.469554,...,1.199337e-06,0.000000,0.009505,0.006274,0.020264,0.017981,1.0,0.0,0.233445,0.972370
4,0,0.774297,0.773366,0.772162,0.767017,0.747710,0.743156,0.677764,0.725437,0.477740,...,1.307199e-06,0.000007,0.004216,0.002132,0.023389,0.018477,1.0,0.0,0.309017,0.951057

In [7]:
#TIMESTAMP_COLS = ["time"]
#non_null_counts_per_user = df_train.groupby("sample_index")[TIMESTAMP_COLS].apply(
#    lambda x: x.notna().any().any()
#)
#users_with_all_nulls = non_null_counts_per_user[non_null_counts_per_user == False].index.tolist()

In [8]:
#total_non_nulls_per_user = df_train.groupby("sample_index")[TIMESTAMP_COLS].count().sum(axis=1)
#users_with_all_nulls_simple = total_non_nulls_per_user[total_non_nulls_per_user == 0].index.tolist()
#(users_with_all_nulls_simple, total_non_nulls_per_user)

In [9]:
#import pandas as pd
#import numpy as np

# --- Setup (Based on your context) ---
#USER_ID_COLUMN = 'sample_index' 
#TIMESTAMP_COLS = ["time"]
# Define a threshold for "low variance." A common starting point is 1e-6 (0.000001).
# You may need to adjust this based on the expected scale of your data.
#VARIANCE_THRESHOLD = 1000

# Assuming df_train is your DataFrame

# --- 1. Calculate Variance per User and Feature ---
# Group by user ID and calculate the variance for each timestamp column
#variance_per_user_feature = df_train.groupby("sample_index")[TIMESTAMP_COLS].var()

# --- 2. Check if Variance is Low for BOTH Features ---
# Create a boolean mask: True if the variance is BELOW the threshold.
#low_variance_mask = (variance_per_user_feature < VARIANCE_THRESHOLD)

# Check if BOTH 'time_sin' AND 'time_cos' are below the threshold for a given user.
# .all(axis=1) checks horizontally (across the features)
#users_with_low_variance_timestamps = low_variance_mask.all(axis=1)

# Get the list of user IDs that satisfy the condition
#users_to_flag = users_with_low_variance_timestamps[users_with_low_variance_timestamps == True].index.tolist()

# --- 3. Output Results ---
#print(f"Total unique users checked: {df_train[USER_ID_COLUMN].nunique()}")
#print(f"Variance check threshold: {VARIANCE_THRESHOLD}")
#print("---")

#if users_to_flag:
#    print(f"⚠️ Found {len(users_to_flag)} user(s) with low variance in ALL checked timestamp features:")
#    print(users_to_flag)
    
    # Optional: Display the actual variance for the first problematic user
#    first_flagged_user = users_to_flag[0]
#    print(f"\nExample Variance for User {first_flagged_user}:")
#    print(variance_per_user_feature.loc[first_flagged_user])
#else:
#    print("✅ No users found with variance below the threshold in both 'time_sin' and 'time_cos'.")

In [10]:
df_train["sample_index"]

0           0
1           0
2           0
3           0
4           0
         ...
105755    660
105756    660
105757    660
105758    660
105759    660
Name: sample_index, Length: 105760, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

user_labels = df_labels.copy()

train_users, val_users = train_test_split(
    user_labels['sample_index'],
    test_size=0.2,  # 20% validation
    stratify=user_labels['label'], # This is the key for imbalance
    random_state=SEED
)

df_train_full = df_train.copy()

# Filter the full dataframe to get rows for train/val users
df_train_fold = df_train_full[df_train_full['sample_index'].isin(train_users)]
df_val_fold   = df_train_full[df_train_full['sample_index'].isin(val_users)]

# Merge labels back in
df_train_fold = df_train_fold.merge(user_labels[['sample_index', 'label', 'label_encoded']], on='sample_index', how='left')
df_val_fold   = df_val_fold.merge(user_labels[['sample_index', 'label', 'label_encoded']], on='sample_index', how='left')

df_train_fold = df_train_fold.drop(columns=['label'])
df_val_fold = df_val_fold.drop(columns=['label'])

In [12]:
# Features to float32
feature_cols_fold = [c for c in df_train_fold.columns if c not in ['sample_index', 'label_encoded']]
df_train_fold[feature_cols_fold] = df_train_fold[feature_cols_fold].astype('float32')
df_val_fold[feature_cols_fold] = df_val_fold[feature_cols_fold].astype('float32')

# Labels to int64
df_train_fold['label_encoded'] = df_train_fold['label_encoded'].astype('int64')
df_val_fold['label_encoded'] = df_val_fold['label_encoded'].astype('int64')

In [13]:
df_train_labeled = df_train.merge(
    user_labels[['sample_index', 'label', 'label_encoded']],
    on='sample_index',
    how='left'
)
df_train_labeled = df_train_labeled.drop(columns=["label"])

feature_cols_fold = [c for c in df_train_fold.columns if c not in ['sample_index', 'label_encoded']]

df_train_labeled[feature_cols_fold] = df_train_labeled[feature_cols_fold].astype('float32')

# Labels to int64
df_train_labeled['label_encoded'] = df_train_labeled['label_encoded'].astype('int64')
df_train_labeled.head()

,sample_index,joint_00,joint_01,joint_02,joint_03,joint_04,joint_05,joint_06,joint_07,joint_08,...,joint_25,joint_26,joint_27,joint_28,joint_29,pain_survey,merged_n_features,time_sin,time_cos,label_encoded
0,0,0.777507,0.738252,0.779512,0.804419,0.714916,0.736643,0.639301,0.733981,0.478382,...,0.000004,0.014214,0.011376,0.018978,0.020291,0.5,0.0,0.000000,1.000000,0
1,0,0.806256,0.765147,0.761153,0.838021,0.735684,0.729533,0.654604,0.760554,0.486231,...,0.000000,0.010748,0.000000,0.009473,0.010006,1.0,0.0,0.078459,0.996917,0
2,0,0.767592,0.721439,0.772834,0.777832,0.724497,0.734962,0.692340,0.787647,0.441994,...,0.000003,0.013097,0.006830,0.017065,0.016856,1.0,0.0,0.156434,0.987688,0
3,0,0.666220,0.810416,0.763971,0.785928,0.679928,0.722504,0.589127,0.793524,0.469554,...,0.000000,0.009505,0.006274,0.020264,0.017981,1.0,0.0,0.233445,0.972370,0
4,0,0.774297,0.773366,0.772162,0.767017,0.747710,0.743156,0.677764,0.725437,0.477740,...,0.000007,0.004216,0.002132,0.023389,0.018477,1.0,0.0,0.309017,0.951057,0

In [14]:
feature_cols = [col for col in df_train_fold.columns if 'joint_' in col]
feature_cols.extend(['pain_survey', 'merged_n_features'])


X_data_2d = df_train_fold[[col for col in df_train_fold.columns if col.startswith('joint_') or col in ['pain_survey', 'merged_n_features']]].values
Y_target_1d = df_train_fold['label_encoded'].values

# Check final count of X features:
num_features = X_data_2d.shape[1]

print(f"Raw X shape: {X_data_2d.shape}")
print(f"Raw Y shape: {Y_target_1d.shape}")

Raw X shape: (84480, 32)
Raw Y shape: (84480,)

### IMPORTANT
Now the CNN it's built, the CNN takes in input the time series with the slicing windows.
For this reason i guess that is possible to proceede as always and after that continue with the training.

## Prepare data for training

In [15]:
def make_loader(ds, batch_size, shuffle, drop_last):
    # Determine optimal number of worker processes for data loading
    cpu_cores = os.cpu_count() or 2
    num_workers = max(2, min(4, cpu_cores))

    # Create DataLoader with performance optimizations
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
        pin_memory=True,  # Faster GPU transfer
        pin_memory_device="cuda" if torch.cuda.is_available() else "",
        prefetch_factor=4,  # Load 4 batches ahead
    )

In [28]:
from typing import Optional, Tuple, List

def build_sequences(
    df: pd.DataFrame, 
    feature_cols: List[str], 
    id_col: str = 'sample_index', 
    label_col: Optional[str] = 'label_encoded', 
    window: int = 200, 
    stride: int = 200
) -> Tuple[np.ndarray, Optional[np.ndarray], Optional[np.ndarray]]:
    """
    Builds sequences from a time-series dataframe, optionally handling labels and
    always returning the sample_index for each generated window.
    
    Args:
        df (pd.DataFrame): The input DataFrame (e.g., df_train_fold).
        feature_cols (list): A list of column names to be used as features.
        id_col (str): The name of the column for unique sample IDs.
        label_col (Optional[str]): The name of the column for the labels. 
                                   Set to None if the DataFrame has no labels (e.g., test set).
        window (int): The size of each sequence (window).
        stride (int): The step size between sequences.
        
    Returns:
        sequences (np.ndarray): The 3D array of sequences (N_sequences, window, N_features).
        labels (Optional[np.ndarray]): The 1D array of labels, or None if label_col is None.
        sample_ids (np.ndarray): The 1D array of original sample IDs for each window.
    """
    num_features = len(feature_cols)
    dataset = []
    labels = []
    sample_ids = [] # NEW: List to collect the sample ID for each window
    
    # Check if we should extract labels
    extract_labels = (label_col is not None) and (label_col in df.columns)

    # Iterate over unique sample IDs
    for sample_id in df[id_col].unique():
        
        # Get the dataframe for the current sample
        temp_df = df[df[id_col] == sample_id]

        # Extract feature data for the current ID
        temp_features = temp_df[feature_cols].values

        if extract_labels:
            # Retrieve the single label for the current ID and convert to int
            label = int(temp_df[label_col].iloc[0])

        # Calculate padding length to ensure full windows (if not using the sliding window end condition)
        # Note: Your original code uses padding. If your final pipeline uses standard sliding
        # window logic (range(0, total_steps - window + 1, stride)) without padding, 
        # you might remove this padding block for consistency. Assuming you keep it for now.
        padding_len = (window - len(temp_features) % window) % window
        
        if padding_len > 0:
            # Create zero padding and concatenate with the data
            padding = np.zeros((padding_len, num_features), dtype='float32')
            temp_features = np.concatenate((temp_features, padding))

        # Build feature windows and associate them with labels and IDs
        idx = 0
        while idx + window <= len(temp_features):
            dataset.append(temp_features[idx:idx + window])
            
            # CRITICAL: Append the sample ID for this window
            sample_ids.append(sample_id) 
            
            if extract_labels:
                labels.append(label)
            
            idx += stride

    # Convert lists to numpy arrays for further processing
    sequences = np.array(dataset, dtype=np.float32)
    sample_ids_array = np.array(sample_ids, dtype=df[id_col].dtype) # Use appropriate dtype

    if extract_labels:
        labels_array = np.array(labels, dtype=np.int64)
        # Return 3 elements: sequences, labels, sample_ids
        return sequences, labels_array, sample_ids_array
    else:
        # Return 3 elements: sequences, None, sample_ids
        return sequences, None, sample_ids_array

## 🛠️ **Model Building**

In [17]:
def recurrent_summary(model, input_size):
    """
    Custom summary function that emulates torchinfo's output while correctly
    counting parameters for RNN/GRU/LSTM layers.

    This function is designed for models whose direct children are
    nn.Linear, nn.RNN, nn.GRU, or nn.LSTM layers.

    Args:
        model (nn.Module): The model to analyze.
        input_size (tuple): Shape of the input tensor (e.g., (seq_len, features)).
    """

    # Dictionary to store output shapes captured by forward hooks
    output_shapes = {}
    # List to track hook handles for later removal
    hooks = []

    def get_hook(name):
        """Factory function to create a forward hook for a specific module."""
        def hook(module, input, output):
            # Handle RNN layer outputs (returns a tuple)
            if isinstance(output, tuple):
                # output[0]: all hidden states with shape (batch, seq_len, hidden*directions)
                shape1 = list(output[0].shape)
                shape1[0] = -1  # Replace batch dimension with -1

                # output[1]: final hidden state h_n (or tuple (h_n, c_n) for LSTM)
                if isinstance(output[1], tuple):  # LSTM case: (h_n, c_n)
                    shape2 = list(output[1][0].shape)  # Extract h_n only
                else:  # RNN/GRU case: h_n only
                    shape2 = list(output[1].shape)

                # Replace batch dimension (middle position) with -1
                shape2[1] = -1

                output_shapes[name] = f"[{shape1}, {shape2}]"

            # Handle standard layer outputs (e.g., Linear)
            else:
                shape = list(output.shape)
                shape[0] = -1  # Replace batch dimension with -1
                output_shapes[name] = f"{shape}"
        return hook

    # 1. Determine the device where model parameters reside
    try:
        device = next(model.parameters()).device
    except StopIteration:
        device = torch.device("cpu")  # Fallback for models without parameters

    # 2. Create a dummy input tensor with batch_size=1
    dummy_input = torch.randn(1, *input_size).to(device)

    # 3. Register forward hooks on target layers
    # Iterate through direct children of the model (e.g., self.rnn, self.classifier)
    for name, module in model.named_children():
        if isinstance(module, (nn.Linear, nn.RNN, nn.GRU, nn.LSTM)):
            # Register the hook and store its handle for cleanup
            hook_handle = module.register_forward_hook(get_hook(name))
            hooks.append(hook_handle)

    # 4. Execute a dummy forward pass in evaluation mode
    model.eval()
    with torch.no_grad():
        try:
            model(dummy_input)
        except Exception as e:
            print(f"Error during dummy forward pass: {e}")
            # Clean up hooks even if an error occurs
            for h in hooks:
                h.remove()
            return

    # 5. Remove all registered hooks
    for h in hooks:
        h.remove()

    # --- 6. Print the summary table ---

    print("-" * 79)
    # Column headers
    print(f"{'Layer (type)':<25} {'Output Shape':<28} {'Param #':<18}")
    print("=" * 79)

    total_params = 0
    total_trainable_params = 0

    # Iterate through modules again to collect and display parameter information
    for name, module in model.named_children():
        if name in output_shapes:
            # Count total and trainable parameters for this module
            module_params = sum(p.numel() for p in module.parameters())
            trainable_params = sum(p.numel() for p in module.parameters() if p.requires_grad)

            total_params += module_params
            total_trainable_params += trainable_params

            # Format strings for display
            layer_name = f"{name} ({type(module).__name__})"
            output_shape_str = str(output_shapes[name])
            params_str = f"{trainable_params:,}"

            print(f"{layer_name:<25} {output_shape_str:<28} {params_str:<15}")

    print("=" * 79)
    print(f"Total params: {total_params:,}")
    print(f"Trainable params: {total_trainable_params:,}")
    print(f"Non-trainable params: {total_params - total_trainable_params:,}")
    print("-" * 79)

In [18]:
class CSHN_ConvBlock(nn.Module):
    """ Implements the CSHN Core: Conv1D -> BatchNorm1D -> LeakyReLU. """
    def __init__(self, in_channels, out_channels, kernel_size, padding):
        super(CSHN_ConvBlock, self).__init__()
        self.conv = nn.Conv1d(in_channels, out_channels, kernel_size, padding=padding)
        self.bn = nn.BatchNorm1d(out_channels)
        self.act = nn.SiLU()

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        x = self.act(x)
        return x

class CSHN_FeatureExtractor(nn.Module):
    """ 3-layer CNN feature extractor with tunable filter sizes. """
    def __init__(self, num_raw_features, c1_filters, c2_filters, c3_filters, cnn_dropout_rate):
        super(CSHN_FeatureExtractor, self).__init__()
        
        # Fixed Kernel/Padding based on your architecture
        C1_KERNEL, C2_KERNEL, C3_KERNEL = 8, 5, 3 
        C2_PADDING, C3_PADDING = 2, 1
        
        # C1 (Input features -> C1_FILTERS)
        self.c1 = CSHN_ConvBlock(num_raw_features, c1_filters, C1_KERNEL, padding=0)
        # C2 (C1_FILTERS -> C2_FILTERS)
        self.c2 = CSHN_ConvBlock(c1_filters, c2_filters, C2_KERNEL, padding=C2_PADDING)  
        # C3 (C2_FILTERS -> C3_FILTERS)
        self.c3 = CSHN_ConvBlock(c2_filters, c3_filters, C3_KERNEL, padding=C3_PADDING)
        
        self.dropout = nn.Dropout(cnn_dropout_rate)

    def forward(self, x):
        # x enters as (Batch, Time, Features) -> Permute to (Batch, Features, Time) for Conv1D
        x = x.transpose(1, 2)
        
        x = self.c1(x) 
        x = self.c2(x) 
        x = self.c3(x) 
        
        # Permute back for the RNN input: (Batch, Features, Time) -> (Batch, Time, Features)
        x = x.transpose(1, 2)
        
        x = self.dropout(x)
        return x

In [19]:
class RecurrentClassifier(nn.Module):
    """
    Generic RNN classifier (RNN, LSTM, GRU).
    Uses the last hidden state for classification.
    """
    def __init__(
            self,
            input_size,
            hidden_size,
            num_layers,
            num_classes,
            rnn_type='GRU',        # 'RNN', 'LSTM', or 'GRU'
            bidirectional=False,
            dropout_rate=0.2
            ):
        super().__init__()

        self.rnn_type = rnn_type
        self.num_layers = num_layers
        self.hidden_size = hidden_size
        self.bidirectional = bidirectional

        # Map string name to PyTorch RNN class
        rnn_map = {
            'RNN': nn.RNN,
            'LSTM': nn.LSTM,
            'GRU': nn.GRU
        }

        if rnn_type not in rnn_map:
            raise ValueError("rnn_type must be 'RNN', 'LSTM', or 'GRU'")

        rnn_module = rnn_map[rnn_type]

        # Dropout is only applied between layers (if num_layers > 1)
        dropout_val = dropout_rate if num_layers > 1 else 0

        # Create the recurrent layer
        self.rnn = rnn_module(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,       # Input shape: (batch, seq_len, features)
            bidirectional=bidirectional,
            dropout=dropout_val
        )

        # Calculate input size for the final classifier
        if self.bidirectional:
            classifier_input_size = hidden_size * 2 # Concat fwd + bwd
        else:
            classifier_input_size = hidden_size

        # Final classification layer
        self.classifier = nn.Linear(classifier_input_size, num_classes)

    def forward(self, x):
        """
        x shape: (batch_size, seq_length, input_size)
        """

        # rnn_out shape: (batch_size, seq_len, hidden_size * num_directions)
        rnn_out, hidden = self.rnn(x)

        # LSTM returns (h_n, c_n), we only need h_n
        if self.rnn_type == 'LSTM':
            hidden = hidden[0]

        # hidden shape: (num_layers * num_directions, batch_size, hidden_size)

        if self.bidirectional:
            # Reshape to (num_layers, 2, batch_size, hidden_size)
            hidden = hidden.view(self.num_layers, 2, -1, self.hidden_size)

            # Concat last fwd (hidden[-1, 0, ...]) and bwd (hidden[-1, 1, ...])
            # Final shape: (batch_size, hidden_size * 2)
            hidden_to_classify = torch.cat([hidden[-1, 0, :, :], hidden[-1, 1, :, :]], dim=1)
        else:
            # Take the last layer's hidden state
            # Final shape: (batch_size, hidden_size)
            hidden_to_classify = hidden[-1]

        # Get logits
        logits = self.classifier(hidden_to_classify)
        return logits

In [20]:
class CSHN_HybridClassifier(nn.Module):
    """ Combines the CNN feature extractor and the RNN classification head. """
    def __init__(self, cnn_params: dict, rnn_params: dict, num_raw_features: int, num_classes: int):
        super(CSHN_HybridClassifier, self).__init__()
        
        # 1. Feature Extractor (CNN)
        self.cnn = CSHN_FeatureExtractor(
            num_raw_features=num_raw_features,
            c1_filters=cnn_params['c1_filters'],
            c2_filters=cnn_params['c2_filters'],
            c3_filters=cnn_params['c3_filters'],
            cnn_dropout_rate=cnn_params['cnn_dropout']
        )
        
        # The input size for the RNN is the output channel count of the final CNN layer (C3_FILTERS)
        rnn_input_size = cnn_params['c3_filters']
        
        # 2. Recurrent Classification Head (RNN)
        self.rnn = RecurrentClassifier(
            input_size=rnn_input_size,
            hidden_size=rnn_params['hidden_size'],
            num_layers=rnn_params['num_layers'],
            num_classes=num_classes,
            dropout_rate=rnn_params['rnn_dropout'],
            bidirectional=rnn_params['bidirectional'],
            rnn_type=rnn_params['rnn_type']
        )
        
    def forward(self, x):
        # x shape: (N, T_in, F_in)
        x = self.cnn(x)
        # x shape after CNN: (N, T_out, F_out) - This is the sequence for the RNN
        x = self.rnn(x)
        # x shape after RNN: (N, num_classes)
        return x

In [21]:
def initialize_weights(model: nn.Module, init_scheme: str):
    """
    Initializes weights, correctly skipping 1D tensors (like biases) 
    that cause 'Fan in and fan out' errors.
    """
    for name, param in model.named_parameters():
        # Skip parameters with fewer than 2 dimensions (typically biases and BatchNorm params)
        if param.dim() < 2:
            # Optionally initialize biases to zero, or skip them
            if 'bias' in name:
                torch.nn.init.constant_(param.data, 0.0)
            continue

        # Apply initialization schemes only to weight matrices (dim >= 2)
        if init_scheme == 'xavier_uniform':
            torch.nn.init.xavier_uniform_(param.data)
        elif init_scheme == 'kaiming_normal':
            # Good for ReLU/Leaky ReLU (common in surrounding layers)
            torch.nn.init.kaiming_normal_(param.data, mode='fan_in', nonlinearity='leaky_relu')
        elif init_scheme == 'orthogonal':
            torch.nn.init.orthogonal_(param.data)

In [22]:
def train_one_epoch(model, train_loader, criterion, optimizer, scaler, device, l1_lambda=0, l2_lambda=0):
    """
    Perform one complete training epoch through the entire training dataset.

    Args:
        model (nn.Module): The neural network model to train
        train_loader (DataLoader): PyTorch DataLoader containing training data batches
        criterion (nn.Module): Loss function (e.g., CrossEntropyLoss, MSELoss)
        optimizer (torch.optim): Optimization algorithm (e.g., Adam, SGD)
        scaler (GradScaler): PyTorch's gradient scaler for mixed precision training
        device (torch.device): Computing device ('cuda' for GPU, 'cpu' for CPU)
        l1_lambda (float): Lambda for L1 regularization
        l2_lambda (float): Lambda for L2 regularization

    Returns:
        tuple: (average_loss, f1 score) - Training loss and f1 score for this epoch
    """
    model.train()  # Set model to training mode

    running_loss = 0.0
    all_predictions = []
    all_targets = []

    # Iterate through training batches
    for batch_idx, (inputs, targets) in enumerate(train_loader):
        # Move data to device (GPU/CPU)
        inputs, targets = inputs.to(device), targets.to(device)

        # Clear gradients from previous step
        optimizer.zero_grad(set_to_none=True)

        # Forward pass with mixed precision (if CUDA available)
        with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
            logits = model(inputs)
            loss = criterion(logits, targets)

            # Add L1 and L2 regularization
            l1_norm = sum(p.abs().sum() for p in model.parameters())
            l2_norm = sum(p.pow(2).sum() for p in model.parameters())
            loss = loss + l1_lambda * l1_norm + l2_lambda * l2_norm


        # Backward pass with gradient scaling
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        # Accumulate metrics
        running_loss += loss.item() * inputs.size(0)
        predictions = logits.argmax(dim=1)
        all_predictions.append(predictions.cpu().numpy())
        all_targets.append(targets.cpu().numpy())

    # Calculate epoch metrics
    epoch_loss = running_loss / len(train_loader.dataset)
    epoch_f1 = f1_score(
        np.concatenate(all_targets),
        np.concatenate(all_predictions),
        average='weighted'
    )

    return epoch_loss, epoch_f1

In [23]:
def validate_one_epoch(model, val_loader, criterion, device):
    """
    Perform one complete validation epoch through the entire validation dataset.

    Args:
        model (nn.Module): The neural network model to evaluate (must be in eval mode)
        val_loader (DataLoader): PyTorch DataLoader containing validation data batches
        criterion (nn.Module): Loss function used to calculate validation loss
        device (torch.device): Computing device ('cuda' for GPU, 'cpu' for CPU)

    Returns:
        tuple: (average_loss, accuracy) - Validation loss and accuracy for this epoch

    Note:
        This function automatically sets the model to evaluation mode and disables
        gradient computation for efficiency during validation.
    """
    model.eval()  # Set model to evaluation mode

    running_loss = 0.0
    all_predictions = []
    all_targets = []

    # Disable gradient computation for validation
    with torch.no_grad():
        for inputs, targets in val_loader:
            # Move data to device
            inputs, targets = inputs.to(device), targets.to(device)

            # Forward pass with mixed precision (if CUDA available)
            with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
                logits = model(inputs)
                loss = criterion(logits, targets)

            # Accumulate metrics
            running_loss += loss.item() * inputs.size(0)
            predictions = logits.argmax(dim=1)
            all_predictions.append(predictions.cpu().numpy())
            all_targets.append(targets.cpu().numpy())

    # Calculate epoch metrics
    epoch_loss = running_loss / len(val_loader.dataset)
    epoch_accuracy = f1_score(
        np.concatenate(all_targets),
        np.concatenate(all_predictions),
        average='weighted'
    )

    return epoch_loss, epoch_accuracy

In [24]:
def log_metrics_to_tensorboard(writer, epoch, train_loss, train_f1, val_loss, val_f1, model):
    """
    Log training metrics and model parameters to TensorBoard for visualization.

    Args:
        writer (SummaryWriter): TensorBoard SummaryWriter object for logging
        epoch (int): Current epoch number (used as x-axis in TensorBoard plots)
        train_loss (float): Training loss for this epoch
        train_f1 (float): Training f1 score for this epoch
        val_loss (float): Validation loss for this epoch
        val_f1 (float): Validation f1 score for this epoch
        model (nn.Module): The neural network model (for logging weights/gradients)

    Note:
        This function logs scalar metrics (loss/f1 score) and histograms of model
        parameters and gradients, which helps monitor training progress and detect
        issues like vanishing/exploding gradients.
    """
    # Log scalar metrics
    writer.add_scalar('Loss/Training', train_loss, epoch)
    writer.add_scalar('Loss/Validation', val_loss, epoch)
    writer.add_scalar('F1/Training', train_f1, epoch)
    writer.add_scalar('F1/Validation', val_f1, epoch)

    # Log model parameters and gradients
    for name, param in model.named_parameters():
        if param.requires_grad:
            # Check if the tensor is not empty before adding a histogram
            if param.numel() > 0:
                writer.add_histogram(f'{name}/weights', param.data, epoch)
            if param.grad is not None:
                # Check if the gradient tensor is not empty before adding a histogram
                if param.grad.numel() > 0:
                    if param.grad is not None and torch.isfinite(param.grad).all():
                        writer.add_histogram(f'{name}/gradients', param.grad.data, epoch)

In [25]:
import torch
import torch.nn as nn
import optuna
# Importa la funzione di utilità se necessario (anche se lo faremo manualmente) 7
# import torch.nn.utils as nn_utils 

def fit(model, train_loader, val_loader, epochs, criterion, optimizer, scaler, device,
        l1_lambda=0, l2_lambda=0, patience=0, evaluation_metric="val_f1", mode='max',
        restore_best_weights=True, writer=None, verbose=10, experiment_name="",
        trial=None, scheduler=None, weight_max_norm=None):
    """
    Train the neural network model on the training data and validate on the validation data.
    """

    # --- NUOVA FUNZIONE: Normalizzazione/Vincolo dei Pesi ---
    def apply_weight_constraint(model, max_norm):
        with torch.no_grad():
            for name, module in model.named_modules():
                # Applica solo ai layer con pesi (es. Linear, Conv1d, Conv2d)
                if isinstance(module, (nn.Linear, nn.Conv1d, nn.Conv2d)):
                    # Vincola il parametro 'weight'
                    if hasattr(module, 'weight') and module.weight is not None:
                        # Calcola la norma L2 del tensore dei pesi
                        norm = module.weight.norm(2)
                        
                        if norm > max_norm:
                            # Se la norma è maggiore del vincolo, riscala il peso.
                            # Ciò garantisce che la norma L2 sia esattamente 'max_norm' o inferiore.
                            module.weight.data.mul_(max_norm / norm)

    # Initialize metrics tracking
    training_history = {
        'train_loss': [], 'val_loss': [],
        'train_f1': [], 'val_f1': []
    }

    # Initialize best_metric before loop
    best_metric = float('-inf') if mode == 'max' else float('inf')
    best_epoch = 0
    
    if patience > 0:
        patience_counter = 0

    if verbose > 0: # Print only if verbose
        print(f"Training {epochs} epochs...")

    # Main training loop: iterate through epochs
    for epoch in range(1, epochs + 1):

        # Forward pass, compute gradients, update weights
        train_loss, train_f1 = train_one_epoch(
            model, train_loader, criterion, optimizer, scaler, device, l1_lambda, l2_lambda
        )
        
        if weight_max_norm is not None and weight_max_norm > 0:
            apply_weight_constraint(model, weight_max_norm)

        # Evaluate model on validation data
        val_loss, val_f1 = validate_one_epoch(
            model, val_loader, criterion, device
        )

        # Store metrics
        training_history['train_loss'].append(train_loss)
        training_history['val_loss'].append(val_loss)
        training_history['train_f1'].append(train_f1)
        training_history['val_f1'].append(val_f1)

        # Write to TensorBoard
        if writer is not None:
            log_metrics_to_tensorboard(
                writer, epoch, train_loss, train_f1, val_loss, val_f1, model
            )

        # Print progress
        if verbose > 0:
            if epoch % verbose == 0 or epoch == 1:
                print(f"Epoch {epoch:3d}/{epochs} | "
                      f"Train: Loss={train_loss:.4f}, F1 Score={train_f1:.4f} | "
                      f"Val: Loss={val_loss:.4f}, F1 Score={val_f1:.4f}")

        # Get current metric for Pruning & Early Stopping
        current_metric = training_history[evaluation_metric][-1]

        # Scheduler Step
        if scheduler is not None:
            scheduler.step(current_metric)
        
        # Optuna Pruning
        if trial is not None:
            try:
                trial.report(current_metric, epoch)
            except Exception as e:
                # Gestione dell'errore (solo se Optuna è effettivamente usato)
                print(f"Error during Optuna report: {e}") 
                pass

            if trial.should_prune():
                # Pruning requested
                raise optuna.exceptions.TrialPruned()
        # End Pruning

        # Early stopping logic (omesso per brevità, resta invariato)
        if patience > 0:
            is_improvement = (current_metric > best_metric) if mode == 'max' else (current_metric < best_metric)

            if is_improvement:
                best_metric = current_metric
                best_epoch = epoch
                # Non uso la variabile `experiment_name` qui, assumo che sia definita in un contesto più ampio
                torch.save(model.state_dict(), "models/"+experiment_name+'_model.pt')
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= patience:
                    if verbose > 0:
                        print(f"Early stopping triggered after {epoch} epochs.")
                    break

    # Restore best model weights (omesso per brevità, resta invariato)
    if restore_best_weights and patience > 0 and best_epoch > 0:
        model.load_state_dict(torch.load("models/"+experiment_name+'_model.pt'))
        if verbose > 0:
            print(f"Best model restored from epoch {best_epoch} with {evaluation_metric} {best_metric:.4f}")

    # Save final model if no early stopping (omesso per brevità, resta invariato)
    if patience == 0:
        torch.save(model.state_dict(), "models/"+experiment_name+'_model.pt')
        if mode == 'max':
            best_metric = max(training_history[evaluation_metric])
        else:
            best_metric = min(training_history[evaluation_metric])
            
    if patience > 0 and best_epoch == 0:
         if mode == 'max':
             best_metric = max(training_history[evaluation_metric])
         else:
             best_metric = min(training_history[evaluation_metric])


    # Close TensorBoard writer
    if writer is not None:
        writer.close()

    return model, training_history, best_metric

In [26]:
df_train_fold.head()

,sample_index,joint_00,joint_01,joint_02,joint_03,joint_04,joint_05,joint_06,joint_07,joint_08,...,joint_25,joint_26,joint_27,joint_28,joint_29,pain_survey,merged_n_features,time_sin,time_cos,label_encoded
0,0,0.777507,0.738252,0.779512,0.804419,0.714916,0.736643,0.639301,0.733981,0.478382,...,0.000004,0.014214,0.011376,0.018978,0.020291,0.5,0.0,0.000000,1.000000,0
1,0,0.806256,0.765147,0.761153,0.838021,0.735684,0.729533,0.654604,0.760554,0.486231,...,0.000000,0.010748,0.000000,0.009473,0.010006,1.0,0.0,0.078459,0.996917,0
2,0,0.767592,0.721439,0.772834,0.777832,0.724497,0.734962,0.692340,0.787647,0.441994,...,0.000003,0.013097,0.006830,0.017065,0.016856,1.0,0.0,0.156434,0.987688,0
3,0,0.666220,0.810416,0.763971,0.785928,0.679928,0.722504,0.589127,0.793524,0.469554,...,0.000000,0.009505,0.006274,0.020264,0.017981,1.0,0.0,0.233445,0.972370,0
4,0,0.774297,0.773366,0.772162,0.767017,0.747710,0.743156,0.677764,0.725437,0.477740,...,0.000007,0.004216,0.002132,0.023389,0.018477,1.0,0.0,0.309017,0.951057,0

## Optuna

In [ ]:
import pandas as pd
import numpy as np
import os
import random # Added import for set_seed
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from sklearn.model_selection import StratifiedKFold # Replaced GroupKFold/SGKF
from sklearn.utils.class_weight import compute_class_weight
from sklearn.preprocessing import MinMaxScaler
import optuna

# NOTE: The functions 'preProcess_with_2D_PE', 'build_sequences', 'make_loader',
# 'CSHN_HybridClassifier', 'initialize_weights', 'fit', and 'device' are assumed
# to be defined elsewhere and available in the execution environment.

BATCH_SIZE = 64
EPOCHS = 200
PATIENCE = 15
N_SPLITS = 3
SEED = 42 # Assuming a global SEED variable is defined

def set_seed(seed_value):
    os.environ['PYTHONHASHSEED'] = str(seed_value)
    random.seed(seed_value)
    np.random.seed(seed_value)
    torch.manual_seed(seed_value)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed_value)
        torch.cuda.manual_seed_all(seed_value)

# --- OOF placeholders for training fold only ---
# NOTE: The length should be the number of UNIQUE samples/groups in df_train_fold,
# not the number of rows, as OOF is aggregated per sample_index.
num_classes = 3
unique_samples_in_train = df_train_labeled['sample_index'].nunique()
oof_preds_train = np.zeros(unique_samples_in_train, dtype=np.int64)
oof_probs_train = np.zeros((unique_samples_in_train, num_classes), dtype=np.float32)

# --- Stratified Group K-Fold Preparation (USING SKLEARN) ---

# 1. Create a unique label for each group based on the classes it contains.
group_level_labels_df = df_train_labeled.groupby('sample_index')['label_encoded'].agg(
    lambda x: tuple(sorted(x.unique()))
).reset_index()

# 2. Encode the unique class tuples into integers for StratifiedKFold
group_labels_encoded = pd.Categorical(group_level_labels_df['label_encoded']).codes

# 3. Extract the arrays needed for SKF split
sample_indices = group_level_labels_df['sample_index'].values # Array of unique user IDs
data_labels_for_stratification = group_labels_encoded # Array of encoded group labels

# 4. Initialize StratifiedKFold (from sklearn)
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)


# --- Optuna objective ---
def objective(trial):
    fold_scores = []

    # Trial-level hyperparameters
    seed_hp = trial.suggest_int("SEED", 0, 10000)
    set_seed(seed_hp)

    window_hp = trial.suggest_categorical("WINDOW", [20, 40, 60])
    stride_hp = trial.suggest_categorical("STRIDE", [5, 10, 15, 20, 30])
    if stride_hp >= window_hp:
        raise optuna.exceptions.TrialPruned()

    c1_filters_hp = trial.suggest_categorical("c1_filters", [32])
    c2_filters_hp = trial.suggest_categorical("c2_filters", [64])
    c3_filters_hp = trial.suggest_categorical("c3_filters", [128])

    cnn_dropout_hp = trial.suggest_float("cnn_dropout", 0.0, 0.5)

    hidden_size_hp = trial.suggest_categorical("hidden_size", [16, 32, 64, 128])
    num_layers_hp = trial.suggest_categorical("num_layers", [1, 2, 3])
    rnn_dropout_hp = trial.suggest_float("rnn_dropout", 0.1, 0.7)
    rnn_type_hp = trial.suggest_categorical("rnn_type", ["GRU"])
    bidirectional_hp = trial.suggest_categorical("bidirectional", [True, False])
    init_scheme_hp = trial.suggest_categorical("init_scheme", ["xavier_uniform", "orthogonal", "kaiming_normal"])
    lr_hp = trial.suggest_float("lr", 1e-5, 1e-3, log=True)
    weight_decay_hp = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
    l1_lambda_hp = trial.suggest_float("l1_lambda", 1e-7, 1e-4, log=True)
    weight_max_norm_hp = trial.suggest_float("weight_max_norm", 0.1, 6.0)

    # --- K-Fold CV on training fold (MODIFIED SPLIT) ---
    # We use skf.split on the group indices and labels for stratification
    for fold, (train_group_idx, val_group_idx) in enumerate(
        skf.split(
            X=sample_indices, # Split the array of unique user IDs
            y=data_labels_for_stratification # Stratify based on the encoded group labels
        )
    ):
        # 1. Map the indices back to the actual user IDs (sample_index)
        train_groups = sample_indices[train_group_idx]
        val_groups = sample_indices[val_group_idx]

        # 2. Filter the main DataFrame (df_train_labeled) based on the selected group IDs
        # This replaces the GroupKFold indexing and achieves no-leakage group splitting.
        df_train_k = df_train_labeled[df_train_labeled['sample_index'].isin(train_groups)].reset_index(drop=True)
        df_val_k   = df_train_labeled[df_train_labeled['sample_index'].isin(val_groups)].reset_index(drop=True)

        # --- Preprocess with 2D positional encoding ---
        scaler = MinMaxScaler()
        preProcess_with_2D_PE(df_train_k, scaler, fit_scaler=True)
        preProcess_with_2D_PE(df_val_k, scaler, fit_scaler=False)

        # Convert types after preprocessing
        feature_cols_fold = [c for c in df_train_k.columns if c not in ['sample_index', 'label_encoded']]
        df_train_k[feature_cols_fold] = df_train_k[feature_cols_fold].astype('float32')
        df_val_k[feature_cols_fold] = df_val_k[feature_cols_fold].astype('float32')

        # --- Build sequences (ASSUMING build_sequences RETURNS (X, y, sample_ids)) ---
        # The sample IDs are crucial for OOF aggregation
        X_train, y_train, _ = build_sequences(
            df_train_k, feature_cols_fold, 'sample_index', 'label_encoded', window_hp, stride_hp
        )
        X_val, y_val, val_sequence_sample_ids = build_sequences(
            df_val_k, feature_cols_fold, 'sample_index', 'label_encoded', window_hp, stride_hp
        )

        X_train = X_train.astype(np.float32)
        X_val = X_val.astype(np.float32)
        y_train = y_train.astype(np.int64)
        y_val = y_val.astype(np.int64)

        # --- Compute class weights ---
        labels_in_fold = np.unique(y_train)
        class_weights_present = compute_class_weight('balanced', classes=labels_in_fold, y=y_train)
        weights_tensor_np = np.zeros(num_classes, dtype=np.float32)
        for i, label in enumerate(labels_in_fold):
            weights_tensor_np[label] = class_weights_present[i]
        weights_tensor = torch.tensor(weights_tensor_np, dtype=torch.float32).to(device)

        # --- Create DataLoaders ---
        train_ds = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
        val_ds   = TensorDataset(torch.from_numpy(X_val), torch.from_numpy(y_val))
        train_loader = make_loader(train_ds, batch_size=BATCH_SIZE, shuffle=True, drop_last=False)
        val_loader   = make_loader(val_ds, batch_size=BATCH_SIZE, shuffle=False, drop_last=False)

        # --- Model ---
        cnn_params = {'c1_filters': c1_filters_hp, 'c2_filters': c2_filters_hp, 'c3_filters': c3_filters_hp, 'cnn_dropout': cnn_dropout_hp}
        rnn_params = {'hidden_size': hidden_size_hp, 'num_layers': num_layers_hp, 'rnn_dropout': rnn_dropout_hp, 'bidirectional': bidirectional_hp, 'rnn_type': rnn_type_hp}
        model = CSHN_HybridClassifier(cnn_params=cnn_params, rnn_params=rnn_params, num_raw_features=len(feature_cols_fold), num_classes=num_classes).to(device)
        initialize_weights(model, init_scheme=init_scheme_hp)

        criterion = nn.CrossEntropyLoss(weight=weights_tensor)
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr_hp, weight_decay=weight_decay_hp)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.1, patience=10, min_lr=1e-7)
        scaler_amp = torch.amp.GradScaler(enabled=(device.type=='cuda'))

        os.makedirs("models", exist_ok=True)

        # --- Train ---
        try:
            _, _, best_val_f1 = fit(
                model=model,
                train_loader=train_loader,
                val_loader=val_loader,
                epochs=EPOCHS,
                criterion=criterion,
                optimizer=optimizer,
                scaler=scaler_amp,
                device=device,
                l1_lambda=l1_lambda_hp,
                l2_lambda=0,
                patience=PATIENCE,
                evaluation_metric="val_f1",
                mode='max',
                restore_best_weights=True,
                trial=trial,
                scheduler=scheduler,
                weight_max_norm=weight_max_norm_hp,
                writer=None,
                verbose=1,
                experiment_name=f"optuna_trial_{trial.number}_fold_{fold}"
            )

            # --- OOF aggregation per sample_index ---
            model.eval()
            probs_list = []
            with torch.no_grad():
                for xb, _ in val_loader:
                    xb = xb.to(device)
                    out = model(xb)
                    probs_list.append(out.softmax(dim=1).cpu().numpy())

                probs_fold = np.concatenate(probs_list, axis=0)

                # Use the sample IDs returned by build_sequences
                current_val_sample_ids = val_sequence_sample_ids[:probs_fold.shape[0]]

                probs_fold_df = pd.DataFrame(probs_fold, columns=range(num_classes))
                probs_fold_df['sample_index'] = current_val_sample_ids

                # Aggregate probabilities by averaging across windows for each sample_index
                probs_fold_avg_df = probs_fold_df.groupby('sample_index')[list(range(num_classes))].mean()
                probs_fold_avg = probs_fold_avg_df.values

                unique_val_sample_ids = probs_fold_avg_df.index.values

                # --- OOF update logic (Robust Mapping) ---
                # We need a dictionary that maps the sample_index ID to the row index of the global OOF array.
                global_sample_index_list = df_train_labeled['sample_index'].unique()
                global_sample_index_map = {id: i for i, id in enumerate(global_sample_index_list)}

                # Get the OOF indices that correspond to the unique samples in this validation fold
                oof_indices_to_update = [global_sample_index_map[id] for id in unique_val_sample_ids]

                oof_probs_train[oof_indices_to_update] = probs_fold_avg
                oof_preds_train[oof_indices_to_update] = probs_fold_avg.argmax(axis=1)

            fold_scores.append(best_val_f1)

        except optuna.exceptions.TrialPruned:
            raise
        except Exception as e:
            print(f"Trial {trial.number} Fold {fold} failed: {e}")
            return 0.0

    return np.mean(fold_scores)

# --- Run Study (Assuming Optuna is available) ---
study = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner(n_warmup_steps=5, n_startup_trials=3))
print("Starting Optuna optimization with Stratified Group K-Fold (using sklearn)...")
study.optimize(objective, n_trials=50)

print("\n--- Optuna Tuning Complete ---")
print(f"Best trial: {study.best_trial.number}, Best mean F1 (training folds): {study.best_value:.4f}")
print("Best hyperparameters:")
for k,v in study.best_params.items():
    print(f"  {k}: {v}")

[I 2025-11-17 15:24:34,675] A new study created in memory with name: no-name-08f1c701-d9cb-477a-b7f5-04c21d9247d9

Starting Optuna optimization with Stratified Group K-Fold (using sklearn)...
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.7531, F1 Score=0.7519 | Val: Loss=1.0283, F1 Score=0.6751
Epoch   2/200 | Train: Loss=0.6705, F1 Score=0.8345 | Val: Loss=1.0337, F1 Score=0.6972
Epoch   3/200 | Train: Loss=0.5820, F1 Score=0.8575 | Val: Loss=1.0525, F1 Score=0.6751
Epoch   4/200 | Train: Loss=0.6156, F1 Score=0.8377 | Val: Loss=1.0503, F1 Score=0.6751
Epoch   5/200 | Train: Loss=0.5787, F1 Score=0.8577 | Val: Loss=1.0565, F1 Score=0.6751
Epoch   6/200 | Train: Loss=0.5401, F1 Score=0.8668 | Val: Loss=1.0505, F1 Score=0.6751
Epoch   7/200 | Train: Loss=0.6003, F1 Score=0.8430 | Val: Loss=1.0670, F1 Score=0.6751
Epoch   8/200 | Train: Loss=0.5985, F1 Score=0.8489 | Val: Loss=1.0763, F1 Score=0.6751
Epoch   9/200 | Train: Loss=0.5486, F1 Score=0.8465 | Val: Loss=1.0704, F1 Score=0.6751
Epoch  10/200 | Train: Loss=0.5790, F1 Score=0.8545 | Val: Loss=1.0610, F1 Score=0.6751
Epoch  11/200 | Train: Loss=0.5558, F1 Score=0.8639 | Val: Loss=1.0666, F1 Score=0.6751
Epoch  12/200 | Train: Loss=0.5673, F1 Score=0.8483 | Val: Loss=1.0673, F1 Score=0.6751
Epoch  13/200 | Train: Loss=0.6495, F1 Score=0.8291 | Val: Loss=1.0758, F1 Score=0.6751
Epoch  14/200 | Train: Loss=0.5423, F1 Score=0.9002 | Val: Loss=0.7877, F1 Score=0.7538
Epoch  15/200 | Train: Loss=0.5032, F1 Score=0.9119 | Val: Loss=0.6365, F1 Score=0.8659
Epoch  16/200 | Train: Loss=0.4636, F1 Score=0.9219 | Val: Loss=1.1219, F1 Score=0.5049
Epoch  17/200 | Train: Loss=0.4618, F1 Score=0.9289 | Val: Loss=0.5329, F1 Score=0.9170
Epoch  18/200 | Train: Loss=0.4494, F1 Score=0.9285 | Val: Loss=0.6260, F1 Score=0.8529
Epoch  19/200 | Train: Loss=0.4565, F1 Score=0.9273 | Val: Loss=0.5987, F1 Score=0.8658
Epoch  20/200 | Train: Loss=0.4064, F1 Score=0.9416 | Val: Loss=0.5925, F1 Score=0.8887
Epoch  21/200 | Train: Loss=0.3870, F1 Score=0.9512 | Val: Loss=0.5659, F1 Score=0.8889
Epoch  22/200 | Train: Loss=0.3818, F1 Score=0.9527 | Val: Loss=0.5162, F1 Score=0.9250
Epoch  23/200 | Train: Loss=0.3870, F1 Score=0.9504 | Val: Loss=0.5357, F1 Score=0.9037
Epoch  24/200 | Train: Loss=0.3781, F1 Score=0.9589 | Val: Loss=0.5960, F1 Score=0.8754
Epoch  25/200 | Train: Loss=0.3973, F1 Score=0.9512 | Val: Loss=0.6035, F1 Score=0.8558
Epoch  26/200 | Train: Loss=0.3923, F1 Score=0.9542 | Val: Loss=0.5342, F1 Score=0.9065
Epoch  27/200 | Train: Loss=0.3997, F1 Score=0.9477 | Val: Loss=0.6961, F1 Score=0.7993
Epoch  28/200 | Train: Loss=0.3916, F1 Score=0.9488 | Val: Loss=0.5871, F1 Score=0.8910
Epoch  29/200 | Train: Loss=0.4150, F1 Score=0.9435 | Val: Loss=0.6065, F1 Score=0.8985
Epoch  30/200 | Train: Loss=0.4020, F1 Score=0.9557 | Val: Loss=0.5518, F1 Score=0.9086
Epoch  31/200 | Train: Loss=0.3832, F1 Score=0.9595 | Val: Loss=0.6286, F1 Score=0.8516
Epoch  32/200 | Train: Loss=0.4260, F1 Score=0.9310 | Val: Loss=0.6767, F1 Score=0.7910
Epoch  33/200 | Train: Loss=0.3819, F1 Score=0.9603 | Val: Loss=0.5552, F1 Score=0.9138
Epoch  34/200 | Train: Loss=0.4010, F1 Score=0.9658 | Val: Loss=0.5213, F1 Score=0.9231
Epoch  35/200 | Train: Loss=0.3948, F1 Score=0.9739 | Val: Loss=0.5261, F1 Score=0.9199
Epoch  36/200 | Train: Loss=0.3934, F1 Score=0.9738 | Val: Loss=0.5296, F1 Score=0.9152
Epoch  37/200 | Train: Loss=0.3915, F1 Score=0.9748 | Val: Loss=0.5199, F1 Score=0.9256
Epoch  38/200 | Train: Loss=0.3891, F1 Score=0.9797 | Val: Loss=0.5274, F1 Score=0.9195
Epoch  39/200 | Train: Loss=0.3917, F1 Score=0.9770 | Val: Loss=0.5271, F1 Score=0.9202
Epoch  40/200 | Train: Loss=0.3887, F1 Score=0.9783 | Val: Loss=0.5258, F1 Score=0.9212
Epoch  41/200 | Train: Loss=0.3879, F1 Score=0.9790 | Val: Loss=0.5281, F1 Score=0.9213
Epoch  42/200 | Train: Loss=0.3870, F1 Score=0.9788 | Val: Loss=0.5208, F1 Score=0.9241
Epoch  43/200 | Train: Loss=0.3892, F1 Score=0.9789 | Val: Loss=0.5233, F1 Score=0.9244
Epoch  44/200 | Train: Loss=0.3889, F1 Score=0.9793 | Val: Loss=0.5190, F1 Score=0.9265
Epoch  45/200 | Train: Loss=0.3883, F1 Score=0.9791 | Val: Loss=0.5238, F1 Score=0.9258
Epoch  46/200 | Train: Loss=0.3883, F1 Score=0.9783 | Val: Loss=0.5282, F1 Score=0.9203
Epoch  47/200 | Train: Loss=0.3871, F1 Score=0.9805 | Val: Loss=0.5330, F1 Score=0.9175
Epoch  48/200 | Train: Loss=0.3857, F1 Score=0.9818 | Val: Loss=0.5315, F1 Score=0.9201
Epoch  49/200 | Train: Loss=0.3856, F1 Score=0.9835 | Val: Loss=0.5279, F1 Score=0.9227
Epoch  50/200 | Train: Loss=0.3867, F1 Score=0.9818 | Val: Loss=0.5259, F1 Score=0.9229
Epoch  51/200 | Train: Loss=0.3865, F1 Score=0.9835 | Val: Loss=0.5281, F1 Score=0.9215
Epoch  52/200 | Train: Loss=0.3852, F1 Score=0.9835 | Val: Loss=0.5317, F1 Score=0.9191
Epoch  53/200 | Train: Loss=0.3854, F1 Score=0.9819 | Val: Loss=0.5234, F1 Score=0.9244
Epoch  54/200 | Train: Loss=0.3877, F1 Score=0.9817 | Val: Loss=0.5351, F1 Score=0.9171
Epoch  55/200 | Train: Loss=0.3838, F1 Score=0.9835 | Val: Loss=0.5360, F1 Score=0.9190
Epoch  56/200 | Train: Loss=0.3877, F1 Score=0.9839 | Val: Loss=0.5257, F1 Score=0.9235
Epoch  57/200 | Train: Loss=0.3882, F1 Score=0.9835 | Val: Loss=0.5297, F1 Score=0.9206
Epoch  58/200 | Train: Loss=0.3874, F1 Score=0.9854 | Val: Loss=0.5260, F1 Score=0.9221
Epoch  59/200 | Train: Loss=0.3893, F1 Score=0.9839 | Val: Loss=0.5233, F1 Score=0.9244
Early stopping triggered after 59 epochs.
Best model restored from epoch 44 with val_f1 0.9265
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.8153, F1 Score=0.6588 | Val: Loss=1.0922, F1 Score=0.0369
Epoch   2/200 | Train: Loss=0.6755, F1 Score=0.8264 | Val: Loss=1.3805, F1 Score=0.0124
Epoch   3/200 | Train: Loss=0.5714, F1 Score=0.8462 | Val: Loss=1.4777, F1 Score=0.0467
Epoch   4/200 | Train: Loss=0.5303, F1 Score=0.8727 | Val: Loss=1.4870, F1 Score=0.0553
Epoch   5/200 | Train: Loss=0.5841, F1 Score=0.8573 | Val: Loss=1.5754, F1 Score=0.0369
Epoch   6/200 | Train: Loss=0.5967, F1 Score=0.8496 | Val: Loss=1.5090, F1 Score=0.0369
Epoch   7/200 | Train: Loss=0.5915, F1 Score=0.8471 | Val: Loss=1.0791, F1 Score=0.0385
Epoch   8/200 | Train: Loss=0.5689, F1 Score=0.8618 | Val: Loss=0.9456, F1 Score=0.6864
Epoch   9/200 | Train: Loss=0.5125, F1 Score=0.8787 | Val: Loss=1.0131, F1 Score=0.2452
Epoch  10/200 | Train: Loss=0.4959, F1 Score=0.8843 | Val: Loss=1.0508, F1 Score=0.6655
Epoch  11/200 | Train: Loss=0.5130, F1 Score=0.8847 | Val: Loss=0.9268, F1 Score=0.7131
Epoch  12/200 | Train: Loss=0.5418, F1 Score=0.8699 | Val: Loss=0.8851, F1 Score=0.7493
Epoch  13/200 | Train: Loss=0.5359, F1 Score=0.8752 | Val: Loss=1.1162, F1 Score=0.2545
Epoch  14/200 | Train: Loss=0.4774, F1 Score=0.8826 | Val: Loss=0.8311, F1 Score=0.7666
Epoch  15/200 | Train: Loss=0.5184, F1 Score=0.8731 | Val: Loss=0.8836, F1 Score=0.7380
Epoch  16/200 | Train: Loss=0.5494, F1 Score=0.8643 | Val: Loss=0.9203, F1 Score=0.7472
Epoch  17/200 | Train: Loss=0.5488, F1 Score=0.8551 | Val: Loss=1.0266, F1 Score=0.3853
Epoch  18/200 | Train: Loss=0.6167, F1 Score=0.8313 | Val: Loss=1.0276, F1 Score=0.6737
Epoch  19/200 | Train: Loss=0.5735, F1 Score=0.8542 | Val: Loss=1.0181, F1 Score=0.6737
Epoch  20/200 | Train: Loss=0.6589, F1 Score=0.8464 | Val: Loss=1.0406, F1 Score=0.6737
Epoch  21/200 | Train: Loss=0.6046, F1 Score=0.8568 | Val: Loss=1.0329, F1 Score=0.6737
Epoch  22/200 | Train: Loss=0.5649, F1 Score=0.8629 | Val: Loss=0.9945, F1 Score=0.6834
Epoch  23/200 | Train: Loss=0.6043, F1 Score=0.8480 | Val: Loss=1.1020, F1 Score=0.6780
Epoch  24/200 | Train: Loss=0.6298, F1 Score=0.8438 | Val: Loss=1.0598, F1 Score=0.6768
Epoch  25/200 | Train: Loss=0.6396, F1 Score=0.8532 | Val: Loss=1.0203, F1 Score=0.6784
Epoch  26/200 | Train: Loss=0.5292, F1 Score=0.9166 | Val: Loss=0.7351, F1 Score=0.7762
Epoch  27/200 | Train: Loss=0.4845, F1 Score=0.9351 | Val: Loss=0.7187, F1 Score=0.7907
Epoch  28/200 | Train: Loss=0.4644, F1 Score=0.9404 | Val: Loss=0.6162, F1 Score=0.8722
Epoch  29/200 | Train: Loss=0.4691, F1 Score=0.9432 | Val: Loss=0.6683, F1 Score=0.8228
Epoch  30/200 | Train: Loss=0.4461, F1 Score=0.9537 | Val: Loss=0.7102, F1 Score=0.7986
Epoch  31/200 | Train: Loss=0.4515, F1 Score=0.9521 | Val: Loss=0.7272, F1 Score=0.7824
Epoch  32/200 | Train: Loss=0.4480, F1 Score=0.9536 | Val: Loss=0.6263, F1 Score=0.8720
Epoch  33/200 | Train: Loss=0.4450, F1 Score=0.9593 | Val: Loss=0.6684, F1 Score=0.8249
Epoch  34/200 | Train: Loss=0.4287, F1 Score=0.9644 | Val: Loss=0.6324, F1 Score=0.8500
Epoch  35/200 | Train: Loss=0.4359, F1 Score=0.9634 | Val: Loss=0.6032, F1 Score=0.8741
Epoch  36/200 | Train: Loss=0.4367, F1 Score=0.9600 | Val: Loss=0.6442, F1 Score=0.8454
Epoch  37/200 | Train: Loss=0.4395, F1 Score=0.9566 | Val: Loss=0.6070, F1 Score=0.8766
Epoch  38/200 | Train: Loss=0.4248, F1 Score=0.9622 | Val: Loss=0.6428, F1 Score=0.8350
Epoch  39/200 | Train: Loss=0.4226, F1 Score=0.9616 | Val: Loss=0.6078, F1 Score=0.8779
Epoch  40/200 | Train: Loss=0.4165, F1 Score=0.9666 | Val: Loss=0.7393, F1 Score=0.7612
Epoch  41/200 | Train: Loss=0.4174, F1 Score=0.9669 | Val: Loss=0.6194, F1 Score=0.8691
Epoch  42/200 | Train: Loss=0.4170, F1 Score=0.9638 | Val: Loss=0.7591, F1 Score=0.7644
Epoch  43/200 | Train: Loss=0.4167, F1 Score=0.9653 | Val: Loss=0.6186, F1 Score=0.8437
Epoch  44/200 | Train: Loss=0.4111, F1 Score=0.9699 | Val: Loss=0.6453, F1 Score=0.8623
Epoch  45/200 | Train: Loss=0.4229, F1 Score=0.9665 | Val: Loss=0.6868, F1 Score=0.8198
Epoch  46/200 | Train: Loss=0.4115, F1 Score=0.9629 | Val: Loss=0.6905, F1 Score=0.8059
Epoch  47/200 | Train: Loss=0.4151, F1 Score=0.9628 | Val: Loss=0.6080, F1 Score=0.8780
Epoch  48/200 | Train: Loss=0.4147, F1 Score=0.9642 | Val: Loss=0.7513, F1 Score=0.7664
Epoch  49/200 | Train: Loss=0.4088, F1 Score=0.9498 | Val: Loss=0.6394, F1 Score=0.8503
Epoch  50/200 | Train: Loss=0.3920, F1 Score=0.9589 | Val: Loss=0.5765, F1 Score=0.8949
Epoch  51/200 | Train: Loss=0.3764, F1 Score=0.9713 | Val: Loss=0.5764, F1 Score=0.8843
Epoch  52/200 | Train: Loss=0.3853, F1 Score=0.9719 | Val: Loss=0.5845, F1 Score=0.8950
Epoch  53/200 | Train: Loss=0.3876, F1 Score=0.9680 | Val: Loss=0.6105, F1 Score=0.8717
Epoch  54/200 | Train: Loss=0.3591, F1 Score=0.9840 | Val: Loss=0.5425, F1 Score=0.9036
Epoch  55/200 | Train: Loss=0.3566, F1 Score=0.9871 | Val: Loss=0.6083, F1 Score=0.8701
Epoch  56/200 | Train: Loss=0.3659, F1 Score=0.9786 | Val: Loss=0.5834, F1 Score=0.8859
Epoch  57/200 | Train: Loss=0.3742, F1 Score=0.9782 | Val: Loss=0.6267, F1 Score=0.8530
Epoch  58/200 | Train: Loss=0.3589, F1 Score=0.9870 | Val: Loss=0.6181, F1 Score=0.8697
Epoch  59/200 | Train: Loss=0.4053, F1 Score=0.9577 | Val: Loss=0.5902, F1 Score=0.8908
Epoch  60/200 | Train: Loss=0.3717, F1 Score=0.9750 | Val: Loss=0.6444, F1 Score=0.8447
Epoch  61/200 | Train: Loss=0.3679, F1 Score=0.9774 | Val: Loss=0.5645, F1 Score=0.8858
Epoch  62/200 | Train: Loss=0.3980, F1 Score=0.9619 | Val: Loss=0.9507, F1 Score=0.6101
Epoch  63/200 | Train: Loss=0.3822, F1 Score=0.9753 | Val: Loss=0.5983, F1 Score=0.8847
Epoch  64/200 | Train: Loss=0.3689, F1 Score=0.9815 | Val: Loss=0.5700, F1 Score=0.9017
Epoch  65/200 | Train: Loss=0.3628, F1 Score=0.9824 | Val: Loss=0.5619, F1 Score=0.8972
Epoch  66/200 | Train: Loss=0.3824, F1 Score=0.9913 | Val: Loss=0.5472, F1 Score=0.9045
Epoch  67/200 | Train: Loss=0.3798, F1 Score=0.9921 | Val: Loss=0.5404, F1 Score=0.9087
Epoch  68/200 | Train: Loss=0.3798, F1 Score=0.9924 | Val: Loss=0.5497, F1 Score=0.9054
Epoch  69/200 | Train: Loss=0.3806, F1 Score=0.9927 | Val: Loss=0.5465, F1 Score=0.9070
Epoch  70/200 | Train: Loss=0.3791, F1 Score=0.9933 | Val: Loss=0.5512, F1 Score=0.9046
Epoch  71/200 | Train: Loss=0.3800, F1 Score=0.9927 | Val: Loss=0.5526, F1 Score=0.9033
Epoch  72/200 | Train: Loss=0.3787, F1 Score=0.9944 | Val: Loss=0.5585, F1 Score=0.9059
Epoch  73/200 | Train: Loss=0.3794, F1 Score=0.9943 | Val: Loss=0.5504, F1 Score=0.9075
Epoch  74/200 | Train: Loss=0.3796, F1 Score=0.9931 | Val: Loss=0.5444, F1 Score=0.9098
Epoch  75/200 | Train: Loss=0.3791, F1 Score=0.9945 | Val: Loss=0.5583, F1 Score=0.9061
Epoch  76/200 | Train: Loss=0.3777, F1 Score=0.9949 | Val: Loss=0.5563, F1 Score=0.9011
Epoch  77/200 | Train: Loss=0.3773, F1 Score=0.9953 | Val: Loss=0.5508, F1 Score=0.9036
Epoch  78/200 | Train: Loss=0.3808, F1 Score=0.9930 | Val: Loss=0.5569, F1 Score=0.9072
Epoch  79/200 | Train: Loss=0.3797, F1 Score=0.9934 | Val: Loss=0.5747, F1 Score=0.8889
Epoch  80/200 | Train: Loss=0.3780, F1 Score=0.9946 | Val: Loss=0.5540, F1 Score=0.9050
Epoch  81/200 | Train: Loss=0.3789, F1 Score=0.9943 | Val: Loss=0.5485, F1 Score=0.9058
Epoch  82/200 | Train: Loss=0.3771, F1 Score=0.9953 | Val: Loss=0.5528, F1 Score=0.9036
Epoch  83/200 | Train: Loss=0.3776, F1 Score=0.9951 | Val: Loss=0.5524, F1 Score=0.9062
Epoch  84/200 | Train: Loss=0.3781, F1 Score=0.9945 | Val: Loss=0.5501, F1 Score=0.9064
Epoch  85/200 | Train: Loss=0.3784, F1 Score=0.9940 | Val: Loss=0.5508, F1 Score=0.9052
Epoch  86/200 | Train: Loss=0.3814, F1 Score=0.9946 | Val: Loss=0.5483, F1 Score=0.9063
Epoch  87/200 | Train: Loss=0.3794, F1 Score=0.9958 | Val: Loss=0.5493, F1 Score=0.9069
Epoch  88/200 | Train: Loss=0.3804, F1 Score=0.9949 | Val: Loss=0.5487, F1 Score=0.9047
Epoch  89/200 | Train: Loss=0.3802, F1 Score=0.9955 | Val: Loss=0.5497, F1 Score=0.9050
Early stopping triggered after 89 epochs.
Best model restored from epoch 74 with val_f1 0.9098
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.7305, F1 Score=0.7609 | Val: Loss=1.0342, F1 Score=0.6737
Epoch   2/200 | Train: Loss=0.6629, F1 Score=0.8271 | Val: Loss=1.0006, F1 Score=0.6861
Epoch   3/200 | Train: Loss=0.5673, F1 Score=0.8475 | Val: Loss=1.0486, F1 Score=0.6737
Epoch   4/200 | Train: Loss=0.5224, F1 Score=0.8704 | Val: Loss=1.0571, F1 Score=0.6737
Epoch   5/200 | Train: Loss=0.5477, F1 Score=0.8556 | Val: Loss=1.0597, F1 Score=0.6737
Epoch   6/200 | Train: Loss=0.5242, F1 Score=0.8611 | Val: Loss=1.0560, F1 Score=0.6737
Epoch   7/200 | Train: Loss=0.5749, F1 Score=0.8516 | Val: Loss=1.0482, F1 Score=0.6737
Epoch   8/200 | Train: Loss=0.6243, F1 Score=0.8214 | Val: Loss=1.0212, F1 Score=0.6737
Epoch   9/200 | Train: Loss=0.5416, F1 Score=0.8651 | Val: Loss=1.0675, F1 Score=0.6737
Epoch  10/200 | Train: Loss=0.5331, F1 Score=0.8605 | Val: Loss=1.0632, F1 Score=0.6737
Epoch  11/200 | Train: Loss=0.5101, F1 Score=0.8735 | Val: Loss=1.0708, F1 Score=0.6737
Epoch  12/200 | Train: Loss=0.5484, F1 Score=0.8582 | Val: Loss=1.0822, F1 Score=0.6737
Epoch  13/200 | Train: Loss=0.4719, F1 Score=0.8801 | Val: Loss=1.0650, F1 Score=0.6737
Epoch  14/200 | Train: Loss=0.4397, F1 Score=0.9347 | Val: Loss=0.6810, F1 Score=0.7582
Epoch  15/200 | Train: Loss=0.4262, F1 Score=0.9383 | Val: Loss=0.5853, F1 Score=0.8796
Epoch  16/200 | Train: Loss=0.4086, F1 Score=0.9505 | Val: Loss=0.6376, F1 Score=0.8743
Epoch  17/200 | Train: Loss=0.4036, F1 Score=0.9536 | Val: Loss=0.6227, F1 Score=0.8782
Epoch  18/200 | Train: Loss=0.4037, F1 Score=0.9491 | Val: Loss=0.5675, F1 Score=0.9113
Epoch  19/200 | Train: Loss=0.3878, F1 Score=0.9625 | Val: Loss=0.5892, F1 Score=0.8889
Epoch  20/200 | Train: Loss=0.3827, F1 Score=0.9629 | Val: Loss=0.5973, F1 Score=0.8745
Epoch  21/200 | Train: Loss=0.3888, F1 Score=0.9612 | Val: Loss=0.5952, F1 Score=0.8671
Epoch  22/200 | Train: Loss=0.3861, F1 Score=0.9570 | Val: Loss=0.5694, F1 Score=0.8948
Epoch  23/200 | Train: Loss=0.3924, F1 Score=0.9547 | Val: Loss=0.5741, F1 Score=0.9001
Epoch  24/200 | Train: Loss=0.3828, F1 Score=0.9631 | Val: Loss=0.5622, F1 Score=0.9090
Epoch  25/200 | Train: Loss=0.3764, F1 Score=0.9667 | Val: Loss=0.6186, F1 Score=0.8798
Epoch  26/200 | Train: Loss=0.3720, F1 Score=0.9659 | Val: Loss=0.5649, F1 Score=0.9026
Epoch  27/200 | Train: Loss=0.3853, F1 Score=0.9634 | Val: Loss=0.6492, F1 Score=0.8734
Epoch  28/200 | Train: Loss=0.3739, F1 Score=0.9690 | Val: Loss=0.6408, F1 Score=0.8267
Epoch  29/200 | Train: Loss=0.3813, F1 Score=0.9639 | Val: Loss=0.5522, F1 Score=0.9088
Epoch  30/200 | Train: Loss=0.3997, F1 Score=0.9721 | Val: Loss=0.5414, F1 Score=0.8968
Epoch  31/200 | Train: Loss=0.3922, F1 Score=0.9762 | Val: Loss=0.5341, F1 Score=0.9086
Epoch  32/200 | Train: Loss=0.3887, F1 Score=0.9788 | Val: Loss=0.5264, F1 Score=0.9197
Epoch  33/200 | Train: Loss=0.3901, F1 Score=0.9800 | Val: Loss=0.5327, F1 Score=0.9111
Epoch  34/200 | Train: Loss=0.3865, F1 Score=0.9803 | Val: Loss=0.5411, F1 Score=0.9055
Epoch  35/200 | Train: Loss=0.3885, F1 Score=0.9796 | Val: Loss=0.5244, F1 Score=0.9185
Epoch  36/200 | Train: Loss=0.3846, F1 Score=0.9826 | Val: Loss=0.5286, F1 Score=0.9167
Epoch  37/200 | Train: Loss=0.3850, F1 Score=0.9844 | Val: Loss=0.5297, F1 Score=0.9199
Epoch  38/200 | Train: Loss=0.3867, F1 Score=0.9832 | Val: Loss=0.5215, F1 Score=0.9241
Epoch  39/200 | Train: Loss=0.3850, F1 Score=0.9836 | Val: Loss=0.5273, F1 Score=0.9195
Epoch  40/200 | Train: Loss=0.3835, F1 Score=0.9851 | Val: Loss=0.5235, F1 Score=0.9225
Epoch  41/200 | Train: Loss=0.3856, F1 Score=0.9833 | Val: Loss=0.5365, F1 Score=0.9144
Epoch  42/200 | Train: Loss=0.3834, F1 Score=0.9859 | Val: Loss=0.5250, F1 Score=0.9233
Epoch  43/200 | Train: Loss=0.3825, F1 Score=0.9866 | Val: Loss=0.5236, F1 Score=0.9258
Epoch  44/200 | Train: Loss=0.3814, F1 Score=0.9880 | Val: Loss=0.5307, F1 Score=0.9226
Epoch  45/200 | Train: Loss=0.3826, F1 Score=0.9863 | Val: Loss=0.5267, F1 Score=0.9234
Epoch  46/200 | Train: Loss=0.3828, F1 Score=0.9856 | Val: Loss=0.5291, F1 Score=0.9185
Epoch  47/200 | Train: Loss=0.3865, F1 Score=0.9820 | Val: Loss=0.5389, F1 Score=0.9139
Epoch  48/200 | Train: Loss=0.3830, F1 Score=0.9869 | Val: Loss=0.5299, F1 Score=0.9204
Epoch  49/200 | Train: Loss=0.3813, F1 Score=0.9880 | Val: Loss=0.5367, F1 Score=0.9187
Epoch  50/200 | Train: Loss=0.3837, F1 Score=0.9849 | Val: Loss=0.5344, F1 Score=0.9165
Epoch  51/200 | Train: Loss=0.3804, F1 Score=0.9884 | Val: Loss=0.5285, F1 Score=0.9230
Epoch  52/200 | Train: Loss=0.3823, F1 Score=0.9859 | Val: Loss=0.5218, F1 Score=0.9310
Epoch  53/200 | Train: Loss=0.3798, F1 Score=0.9895 | Val: Loss=0.5304, F1 Score=0.9240
Epoch  54/200 | Train: Loss=0.3800, F1 Score=0.9886 | Val: Loss=0.5345, F1 Score=0.9218
Epoch  55/200 | Train: Loss=0.3805, F1 Score=0.9898 | Val: Loss=0.5213, F1 Score=0.9282
Epoch  56/200 | Train: Loss=0.3805, F1 Score=0.9874 | Val: Loss=0.5282, F1 Score=0.9233
Epoch  57/200 | Train: Loss=0.3794, F1 Score=0.9897 | Val: Loss=0.5380, F1 Score=0.9158
Epoch  58/200 | Train: Loss=0.3800, F1 Score=0.9893 | Val: Loss=0.5270, F1 Score=0.9223
Epoch  59/200 | Train: Loss=0.3788, F1 Score=0.9900 | Val: Loss=0.5281, F1 Score=0.9225
Epoch  60/200 | Train: Loss=0.3789, F1 Score=0.9901 | Val: Loss=0.5264, F1 Score=0.9248
Epoch  61/200 | Train: Loss=0.3813, F1 Score=0.9898 | Val: Loss=0.5280, F1 Score=0.9249
Epoch  62/200 | Train: Loss=0.3786, F1 Score=0.9901 | Val: Loss=0.5288, F1 Score=0.9256
Epoch  63/200 | Train: Loss=0.3798, F1 Score=0.9907 | Val: Loss=0.5218, F1 Score=0.9291
Epoch  64/200 | Train: Loss=0.3823, F1 Score=0.9927 | Val: Loss=0.5284, F1 Score=0.9256
Epoch  65/200 | Train: Loss=0.3805, F1 Score=0.9923 | Val: Loss=0.5253, F1 Score=0.9282
Epoch  66/200 | Train: Loss=0.3801, F1 Score=0.9923 | Val: Loss=0.5231, F1 Score=0.9264
Epoch  67/200 | Train: Loss=0.3802, F1 Score=0.9926 | Val: Loss=0.5238, F1 Score=0.9270
Early stopping triggered after 67 epochs.
Best model restored from epoch 52 with val_f1 0.9310

[I 2025-11-17 15:35:11,160] Trial 0 finished with value: 0.9224502800789871 and parameters: {'SEED': 9938, 'WINDOW': 60, 'STRIDE': 5, 'c1_filters': 32, 'c2_filters': 64, 'c3_filters': 128, 'cnn_dropout': 0.26814738644088254, 'hidden_size': 16, 'num_layers': 3, 'rnn_dropout': 0.4098053587862246, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'xavier_uniform', 'lr': 0.0006801009335646962, 'weight_decay': 0.0003168428972529413, 'l1_lambda': 1.257438841741642e-06, 'weight_max_norm': 0.4813016928754955}. Best is trial 0 with value: 0.9224502800789871.

Training 200 epochs...
Epoch   1/200 | Train: Loss=1.6014, F1 Score=0.2706 | Val: Loss=1.1170, F1 Score=0.6751
Epoch   2/200 | Train: Loss=1.2349, F1 Score=0.5093 | Val: Loss=0.9258, F1 Score=0.6739
Epoch   3/200 | Train: Loss=1.0798, F1 Score=0.7100 | Val: Loss=0.8619, F1 Score=0.7523
Epoch   4/200 | Train: Loss=0.9946, F1 Score=0.7633 | Val: Loss=0.8010, F1 Score=0.7726
Epoch   5/200 | Train: Loss=0.9330, F1 Score=0.8012 | Val: Loss=0.7551, F1 Score=0.7897
Epoch   6/200 | Train: Loss=0.8864, F1 Score=0.8164 | Val: Loss=0.7101, F1 Score=0.8212
Epoch   7/200 | Train: Loss=0.8376, F1 Score=0.8366 | Val: Loss=0.6733, F1 Score=0.8333
Epoch   8/200 | Train: Loss=0.8070, F1 Score=0.8460 | Val: Loss=0.6684, F1 Score=0.8193
Epoch   9/200 | Train: Loss=0.7746, F1 Score=0.8427 | Val: Loss=0.6526, F1 Score=0.8262
Epoch  10/200 | Train: Loss=0.7370, F1 Score=0.8690 | Val: Loss=0.6297, F1 Score=0.8483
Epoch  11/200 | Train: Loss=0.7095, F1 Score=0.8717 | Val: Loss=0.6383, F1 Score=0.8193
Epoch  12/200 | Train: Loss=0.6908, F1 Score=0.8743 | Val: Loss=0.5943, F1 Score=0.8634
Epoch  13/200 | Train: Loss=0.6536, F1 Score=0.8780 | Val: Loss=0.5800, F1 Score=0.8695
Epoch  14/200 | Train: Loss=0.6310, F1 Score=0.8941 | Val: Loss=0.5809, F1 Score=0.8669
Epoch  15/200 | Train: Loss=0.6119, F1 Score=0.8888 | Val: Loss=0.5726, F1 Score=0.8584
Epoch  16/200 | Train: Loss=0.5921, F1 Score=0.8958 | Val: Loss=0.5928, F1 Score=0.8345
Epoch  17/200 | Train: Loss=0.5753, F1 Score=0.8964 | Val: Loss=0.5706, F1 Score=0.8688
Epoch  18/200 | Train: Loss=0.5545, F1 Score=0.8987 | Val: Loss=0.5694, F1 Score=0.8579
Epoch  19/200 | Train: Loss=0.5463, F1 Score=0.8971 | Val: Loss=0.5817, F1 Score=0.8625
Epoch  20/200 | Train: Loss=0.5224, F1 Score=0.9013 | Val: Loss=0.5671, F1 Score=0.8696
Epoch  21/200 | Train: Loss=0.4965, F1 Score=0.9112 | Val: Loss=0.6017, F1 Score=0.8372
Epoch  22/200 | Train: Loss=0.4887, F1 Score=0.9106 | Val: Loss=0.5694, F1 Score=0.8668
Epoch  23/200 | Train: Loss=0.4771, F1 Score=0.9169 | Val: Loss=0.5711, F1 Score=0.8708
Epoch  24/200 | Train: Loss=0.4558, F1 Score=0.9170 | Val: Loss=0.5640, F1 Score=0.8734
Epoch  25/200 | Train: Loss=0.4463, F1 Score=0.9230 | Val: Loss=0.5569, F1 Score=0.8797
Epoch  26/200 | Train: Loss=0.4433, F1 Score=0.9203 | Val: Loss=0.5686, F1 Score=0.8695
Epoch  27/200 | Train: Loss=0.4268, F1 Score=0.9269 | Val: Loss=0.5580, F1 Score=0.8852
Epoch  28/200 | Train: Loss=0.4062, F1 Score=0.9282 | Val: Loss=0.5533, F1 Score=0.8907
Epoch  29/200 | Train: Loss=0.4000, F1 Score=0.9333 | Val: Loss=0.5679, F1 Score=0.8905
Epoch  30/200 | Train: Loss=0.3799, F1 Score=0.9393 | Val: Loss=0.5522, F1 Score=0.8865
Epoch  31/200 | Train: Loss=0.3830, F1 Score=0.9384 | Val: Loss=0.5775, F1 Score=0.8712
Epoch  32/200 | Train: Loss=0.3695, F1 Score=0.9427 | Val: Loss=0.5773, F1 Score=0.8698
Epoch  33/200 | Train: Loss=0.3601, F1 Score=0.9458 | Val: Loss=0.5582, F1 Score=0.8821
Epoch  34/200 | Train: Loss=0.3598, F1 Score=0.9486 | Val: Loss=0.5554, F1 Score=0.8825
Epoch  35/200 | Train: Loss=0.3514, F1 Score=0.9479 | Val: Loss=0.5509, F1 Score=0.8900
Epoch  36/200 | Train: Loss=0.3515, F1 Score=0.9419 | Val: Loss=0.5883, F1 Score=0.8772
Epoch  37/200 | Train: Loss=0.3537, F1 Score=0.9418 | Val: Loss=0.5464, F1 Score=0.8974
Epoch  38/200 | Train: Loss=0.3327, F1 Score=0.9554 | Val: Loss=0.5883, F1 Score=0.8693
Epoch  39/200 | Train: Loss=0.3427, F1 Score=0.9470 | Val: Loss=0.5650, F1 Score=0.8808
Epoch  40/200 | Train: Loss=0.3308, F1 Score=0.9506 | Val: Loss=0.5599, F1 Score=0.8827
Epoch  41/200 | Train: Loss=0.3146, F1 Score=0.9578 | Val: Loss=0.5669, F1 Score=0.9028
Epoch  42/200 | Train: Loss=0.3134, F1 Score=0.9573 | Val: Loss=0.5551, F1 Score=0.8938
Epoch  43/200 | Train: Loss=0.3067, F1 Score=0.9609 | Val: Loss=0.5728, F1 Score=0.8982
Epoch  44/200 | Train: Loss=0.3015, F1 Score=0.9625 | Val: Loss=0.5874, F1 Score=0.8881
Epoch  45/200 | Train: Loss=0.3084, F1 Score=0.9588 | Val: Loss=0.5621, F1 Score=0.8870
Epoch  46/200 | Train: Loss=0.3010, F1 Score=0.9613 | Val: Loss=0.5409, F1 Score=0.9117
Epoch  47/200 | Train: Loss=0.2932, F1 Score=0.9657 | Val: Loss=0.5444, F1 Score=0.9060
Epoch  48/200 | Train: Loss=0.2864, F1 Score=0.9690 | Val: Loss=0.5587, F1 Score=0.8951
Epoch  49/200 | Train: Loss=0.2875, F1 Score=0.9675 | Val: Loss=0.5782, F1 Score=0.9000
Epoch  50/200 | Train: Loss=0.2812, F1 Score=0.9662 | Val: Loss=0.5705, F1 Score=0.9061
Epoch  51/200 | Train: Loss=0.2934, F1 Score=0.9650 | Val: Loss=0.6233, F1 Score=0.8703
Epoch  52/200 | Train: Loss=0.2802, F1 Score=0.9673 | Val: Loss=0.5599, F1 Score=0.9074
Epoch  53/200 | Train: Loss=0.2774, F1 Score=0.9710 | Val: Loss=0.5560, F1 Score=0.9083
Epoch  54/200 | Train: Loss=0.2784, F1 Score=0.9716 | Val: Loss=0.5521, F1 Score=0.9154
Epoch  55/200 | Train: Loss=0.2681, F1 Score=0.9747 | Val: Loss=0.5953, F1 Score=0.8929
Epoch  56/200 | Train: Loss=0.2657, F1 Score=0.9732 | Val: Loss=0.6320, F1 Score=0.8991
Epoch  57/200 | Train: Loss=0.2666, F1 Score=0.9751 | Val: Loss=0.5767, F1 Score=0.9058
Epoch  58/200 | Train: Loss=0.2657, F1 Score=0.9739 | Val: Loss=0.5815, F1 Score=0.9026
Epoch  59/200 | Train: Loss=0.2630, F1 Score=0.9751 | Val: Loss=0.5945, F1 Score=0.9144
Epoch  60/200 | Train: Loss=0.2595, F1 Score=0.9770 | Val: Loss=0.5818, F1 Score=0.8993
Epoch  61/200 | Train: Loss=0.2622, F1 Score=0.9742 | Val: Loss=0.6531, F1 Score=0.8932
Epoch  62/200 | Train: Loss=0.2594, F1 Score=0.9748 | Val: Loss=0.5885, F1 Score=0.8983
Epoch  63/200 | Train: Loss=0.2511, F1 Score=0.9798 | Val: Loss=0.5929, F1 Score=0.8990
Epoch  64/200 | Train: Loss=0.2560, F1 Score=0.9756 | Val: Loss=0.5641, F1 Score=0.9135
Epoch  65/200 | Train: Loss=0.2513, F1 Score=0.9789 | Val: Loss=0.6087, F1 Score=0.8998
Epoch  66/200 | Train: Loss=0.2524, F1 Score=0.9751 | Val: Loss=0.5854, F1 Score=0.9077
Epoch  67/200 | Train: Loss=0.2446, F1 Score=0.9802 | Val: Loss=0.5833, F1 Score=0.9092
Epoch  68/200 | Train: Loss=0.2418, F1 Score=0.9842 | Val: Loss=0.5802, F1 Score=0.9112
Epoch  69/200 | Train: Loss=0.2468, F1 Score=0.9810 | Val: Loss=0.5846, F1 Score=0.9081
Early stopping triggered after 69 epochs.
Best model restored from epoch 54 with val_f1 0.9154
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.4524, F1 Score=0.3903 | Val: Loss=1.0852, F1 Score=0.6737
Epoch   2/200 | Train: Loss=1.1913, F1 Score=0.6027 | Val: Loss=0.9201, F1 Score=0.7722
Epoch   3/200 | Train: Loss=1.0584, F1 Score=0.7427 | Val: Loss=0.8645, F1 Score=0.7611
Epoch   4/200 | Train: Loss=0.9902, F1 Score=0.7854 | Val: Loss=0.7966, F1 Score=0.8088
Epoch   5/200 | Train: Loss=0.9362, F1 Score=0.8040 | Val: Loss=0.7808, F1 Score=0.8329
Epoch   6/200 | Train: Loss=0.8942, F1 Score=0.8336 | Val: Loss=0.7602, F1 Score=0.8022
Epoch   7/200 | Train: Loss=0.8614, F1 Score=0.8580 | Val: Loss=0.7529, F1 Score=0.8149
Epoch   8/200 | Train: Loss=0.8441, F1 Score=0.8627 | Val: Loss=0.7230, F1 Score=0.8421
Epoch   9/200 | Train: Loss=0.8113, F1 Score=0.8696 | Val: Loss=0.7189, F1 Score=0.8426
Epoch  10/200 | Train: Loss=0.7778, F1 Score=0.8780 | Val: Loss=0.7041, F1 Score=0.8554
Epoch  11/200 | Train: Loss=0.7671, F1 Score=0.8785 | Val: Loss=0.6915, F1 Score=0.8513
Epoch  12/200 | Train: Loss=0.7435, F1 Score=0.8828 | Val: Loss=0.6627, F1 Score=0.8472
Epoch  13/200 | Train: Loss=0.7277, F1 Score=0.8894 | Val: Loss=0.6971, F1 Score=0.8564
Epoch  14/200 | Train: Loss=0.6989, F1 Score=0.9013 | Val: Loss=0.6699, F1 Score=0.8585
Epoch  15/200 | Train: Loss=0.6845, F1 Score=0.9059 | Val: Loss=0.6495, F1 Score=0.8665
Epoch  16/200 | Train: Loss=0.6635, F1 Score=0.9132 | Val: Loss=0.6422, F1 Score=0.8651
Epoch  17/200 | Train: Loss=0.6469, F1 Score=0.9134 | Val: Loss=0.6573, F1 Score=0.8692
Epoch  18/200 | Train: Loss=0.6391, F1 Score=0.9148 | Val: Loss=0.6501, F1 Score=0.8591
Epoch  19/200 | Train: Loss=0.6173, F1 Score=0.9249 | Val: Loss=0.6559, F1 Score=0.8637
Epoch  20/200 | Train: Loss=0.6143, F1 Score=0.9148 | Val: Loss=0.6393, F1 Score=0.8717
Epoch  21/200 | Train: Loss=0.5836, F1 Score=0.9304 | Val: Loss=0.6617, F1 Score=0.8776
Epoch  22/200 | Train: Loss=0.5733, F1 Score=0.9292 | Val: Loss=0.6314, F1 Score=0.8571
Epoch  23/200 | Train: Loss=0.5647, F1 Score=0.9288 | Val: Loss=0.6433, F1 Score=0.8510
Epoch  24/200 | Train: Loss=0.5445, F1 Score=0.9375 | Val: Loss=0.5876, F1 Score=0.8687
Epoch  25/200 | Train: Loss=0.5339, F1 Score=0.9380 | Val: Loss=0.6175, F1 Score=0.8798
Epoch  26/200 | Train: Loss=0.5216, F1 Score=0.9382 | Val: Loss=0.6258, F1 Score=0.8835
Epoch  27/200 | Train: Loss=0.5054, F1 Score=0.9429 | Val: Loss=0.6007, F1 Score=0.8809
Epoch  28/200 | Train: Loss=0.4910, F1 Score=0.9455 | Val: Loss=0.6144, F1 Score=0.8864
Epoch  29/200 | Train: Loss=0.4764, F1 Score=0.9466 | Val: Loss=0.5670, F1 Score=0.8786
Epoch  30/200 | Train: Loss=0.4644, F1 Score=0.9524 | Val: Loss=0.6333, F1 Score=0.8870
Epoch  31/200 | Train: Loss=0.4455, F1 Score=0.9537 | Val: Loss=0.5702, F1 Score=0.8913
Epoch  32/200 | Train: Loss=0.4373, F1 Score=0.9552 | Val: Loss=0.5754, F1 Score=0.8928
Epoch  33/200 | Train: Loss=0.4317, F1 Score=0.9531 | Val: Loss=0.5979, F1 Score=0.8945
Epoch  34/200 | Train: Loss=0.4155, F1 Score=0.9614 | Val: Loss=0.6019, F1 Score=0.8925
Epoch  35/200 | Train: Loss=0.4035, F1 Score=0.9633 | Val: Loss=0.5892, F1 Score=0.8989
Epoch  36/200 | Train: Loss=0.3904, F1 Score=0.9697 | Val: Loss=0.5896, F1 Score=0.9012
Epoch  37/200 | Train: Loss=0.3824, F1 Score=0.9664 | Val: Loss=0.5623, F1 Score=0.9011
Epoch  38/200 | Train: Loss=0.3739, F1 Score=0.9671 | Val: Loss=0.5974, F1 Score=0.8972
Epoch  39/200 | Train: Loss=0.3755, F1 Score=0.9654 | Val: Loss=0.6096, F1 Score=0.8978
Epoch  40/200 | Train: Loss=0.3556, F1 Score=0.9719 | Val: Loss=0.5942, F1 Score=0.8985
Epoch  41/200 | Train: Loss=0.3465, F1 Score=0.9725 | Val: Loss=0.5476, F1 Score=0.9045
Epoch  42/200 | Train: Loss=0.3484, F1 Score=0.9695 | Val: Loss=0.6238, F1 Score=0.9056
Epoch  43/200 | Train: Loss=0.3751, F1 Score=0.9639 | Val: Loss=0.6089, F1 Score=0.8763
Epoch  44/200 | Train: Loss=0.3441, F1 Score=0.9706 | Val: Loss=0.6035, F1 Score=0.9053
Epoch  45/200 | Train: Loss=0.3305, F1 Score=0.9765 | Val: Loss=0.5954, F1 Score=0.9010
Epoch  46/200 | Train: Loss=0.3198, F1 Score=0.9784 | Val: Loss=0.6217, F1 Score=0.9050
Epoch  47/200 | Train: Loss=0.3317, F1 Score=0.9705 | Val: Loss=0.5907, F1 Score=0.8947
Epoch  48/200 | Train: Loss=0.3312, F1 Score=0.9720 | Val: Loss=0.6666, F1 Score=0.8977
Epoch  49/200 | Train: Loss=0.3237, F1 Score=0.9733 | Val: Loss=0.6408, F1 Score=0.9067
Epoch  50/200 | Train: Loss=0.3111, F1 Score=0.9794 | Val: Loss=0.5863, F1 Score=0.9015
Epoch  51/200 | Train: Loss=0.3085, F1 Score=0.9750 | Val: Loss=0.6125, F1 Score=0.8906
Epoch  52/200 | Train: Loss=0.2908, F1 Score=0.9836 | Val: Loss=0.6171, F1 Score=0.9106
Epoch  53/200 | Train: Loss=0.2965, F1 Score=0.9813 | Val: Loss=0.6070, F1 Score=0.8886
Epoch  54/200 | Train: Loss=0.3122, F1 Score=0.9706 | Val: Loss=0.5599, F1 Score=0.9083
Epoch  55/200 | Train: Loss=0.2969, F1 Score=0.9772 | Val: Loss=0.7202, F1 Score=0.9029
Epoch  56/200 | Train: Loss=0.2865, F1 Score=0.9821 | Val: Loss=0.5865, F1 Score=0.9090
Epoch  57/200 | Train: Loss=0.2836, F1 Score=0.9819 | Val: Loss=0.5742, F1 Score=0.9108
Epoch  58/200 | Train: Loss=0.2895, F1 Score=0.9802 | Val: Loss=0.5972, F1 Score=0.8996
Epoch  59/200 | Train: Loss=0.2874, F1 Score=0.9812 | Val: Loss=0.7019, F1 Score=0.8933
Epoch  60/200 | Train: Loss=0.2889, F1 Score=0.9794 | Val: Loss=0.6587, F1 Score=0.9100
Epoch  61/200 | Train: Loss=0.2882, F1 Score=0.9819 | Val: Loss=0.6092, F1 Score=0.8836
Epoch  62/200 | Train: Loss=0.2793, F1 Score=0.9801 | Val: Loss=0.6624, F1 Score=0.8996
Epoch  63/200 | Train: Loss=0.2677, F1 Score=0.9860 | Val: Loss=0.5881, F1 Score=0.9149
Epoch  64/200 | Train: Loss=0.2720, F1 Score=0.9844 | Val: Loss=0.5964, F1 Score=0.9059
Epoch  65/200 | Train: Loss=0.2691, F1 Score=0.9834 | Val: Loss=0.7063, F1 Score=0.9082
Epoch  66/200 | Train: Loss=0.2717, F1 Score=0.9853 | Val: Loss=0.5921, F1 Score=0.9087
Epoch  67/200 | Train: Loss=0.2642, F1 Score=0.9868 | Val: Loss=0.5939, F1 Score=0.9114
Epoch  68/200 | Train: Loss=0.2553, F1 Score=0.9900 | Val: Loss=0.5954, F1 Score=0.9108
Epoch  69/200 | Train: Loss=0.2715, F1 Score=0.9821 | Val: Loss=0.6868, F1 Score=0.8903
Epoch  70/200 | Train: Loss=0.2568, F1 Score=0.9898 | Val: Loss=0.6918, F1 Score=0.9106
Epoch  71/200 | Train: Loss=0.2562, F1 Score=0.9870 | Val: Loss=0.6819, F1 Score=0.9137
Epoch  72/200 | Train: Loss=0.2531, F1 Score=0.9903 | Val: Loss=0.6256, F1 Score=0.9155
Epoch  73/200 | Train: Loss=0.2533, F1 Score=0.9907 | Val: Loss=0.6742, F1 Score=0.9150
Epoch  74/200 | Train: Loss=0.2528, F1 Score=0.9895 | Val: Loss=0.6920, F1 Score=0.9075
Epoch  75/200 | Train: Loss=0.2521, F1 Score=0.9878 | Val: Loss=0.7047, F1 Score=0.9080
Epoch  76/200 | Train: Loss=0.2555, F1 Score=0.9876 | Val: Loss=0.6156, F1 Score=0.9095
Epoch  77/200 | Train: Loss=0.2532, F1 Score=0.9861 | Val: Loss=0.6696, F1 Score=0.9041
Epoch  78/200 | Train: Loss=0.2416, F1 Score=0.9915 | Val: Loss=0.8167, F1 Score=0.8991
Epoch  79/200 | Train: Loss=0.2499, F1 Score=0.9890 | Val: Loss=0.7047, F1 Score=0.9082
Epoch  80/200 | Train: Loss=0.2430, F1 Score=0.9908 | Val: Loss=0.7128, F1 Score=0.9060
Epoch  81/200 | Train: Loss=0.2403, F1 Score=0.9917 | Val: Loss=0.6493, F1 Score=0.9019
Epoch  82/200 | Train: Loss=0.2440, F1 Score=0.9888 | Val: Loss=0.6246, F1 Score=0.9182
Epoch  83/200 | Train: Loss=0.2404, F1 Score=0.9917 | Val: Loss=0.6372, F1 Score=0.9147
Epoch  84/200 | Train: Loss=0.2415, F1 Score=0.9900 | Val: Loss=0.7164, F1 Score=0.9095
Epoch  85/200 | Train: Loss=0.2357, F1 Score=0.9927 | Val: Loss=0.6816, F1 Score=0.9104
Epoch  86/200 | Train: Loss=0.2359, F1 Score=0.9925 | Val: Loss=0.6850, F1 Score=0.9006
Epoch  87/200 | Train: Loss=0.2417, F1 Score=0.9900 | Val: Loss=0.7091, F1 Score=0.9059
Epoch  88/200 | Train: Loss=0.2455, F1 Score=0.9885 | Val: Loss=0.6049, F1 Score=0.9085
Epoch  89/200 | Train: Loss=0.2420, F1 Score=0.9861 | Val: Loss=0.7152, F1 Score=0.9115
Epoch  90/200 | Train: Loss=0.2347, F1 Score=0.9905 | Val: Loss=0.6984, F1 Score=0.9061
Epoch  91/200 | Train: Loss=0.2309, F1 Score=0.9937 | Val: Loss=0.6681, F1 Score=0.9070
Epoch  92/200 | Train: Loss=0.2683, F1 Score=0.9742 | Val: Loss=0.6693, F1 Score=0.8949
Epoch  93/200 | Train: Loss=0.2346, F1 Score=0.9917 | Val: Loss=0.6994, F1 Score=0.9123
Epoch  94/200 | Train: Loss=0.2326, F1 Score=0.9930 | Val: Loss=0.6922, F1 Score=0.9091
Epoch  95/200 | Train: Loss=0.2266, F1 Score=0.9942 | Val: Loss=0.7423, F1 Score=0.9110
Epoch  96/200 | Train: Loss=0.2296, F1 Score=0.9920 | Val: Loss=0.7411, F1 Score=0.9083
Epoch  97/200 | Train: Loss=0.2340, F1 Score=0.9920 | Val: Loss=0.7051, F1 Score=0.9132
Early stopping triggered after 97 epochs.
Best model restored from epoch 82 with val_f1 0.9182
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.5421, F1 Score=0.3630 | Val: Loss=1.2390, F1 Score=0.0137
Epoch   2/200 | Train: Loss=1.2217, F1 Score=0.5089 | Val: Loss=0.9598, F1 Score=0.6518
Epoch   3/200 | Train: Loss=1.0683, F1 Score=0.6518 | Val: Loss=0.8790, F1 Score=0.7379
Epoch   4/200 | Train: Loss=0.9939, F1 Score=0.7230 | Val: Loss=0.8332, F1 Score=0.7161
Epoch   5/200 | Train: Loss=0.9271, F1 Score=0.7593 | Val: Loss=0.7906, F1 Score=0.7753
Epoch   6/200 | Train: Loss=0.8811, F1 Score=0.7915 | Val: Loss=0.7495, F1 Score=0.7897
Epoch   7/200 | Train: Loss=0.8371, F1 Score=0.8119 | Val: Loss=0.7441, F1 Score=0.7745
Epoch   8/200 | Train: Loss=0.7862, F1 Score=0.8485 | Val: Loss=0.7593, F1 Score=0.8143
Epoch   9/200 | Train: Loss=0.7646, F1 Score=0.8507 | Val: Loss=0.7043, F1 Score=0.8055
Epoch  10/200 | Train: Loss=0.7245, F1 Score=0.8536 | Val: Loss=0.7031, F1 Score=0.8225
Epoch  11/200 | Train: Loss=0.7009, F1 Score=0.8735 | Val: Loss=0.6637, F1 Score=0.8169
Epoch  12/200 | Train: Loss=0.6752, F1 Score=0.8759 | Val: Loss=0.7125, F1 Score=0.8175
Epoch  13/200 | Train: Loss=0.6587, F1 Score=0.8743 | Val: Loss=0.7115, F1 Score=0.8235
Epoch  14/200 | Train: Loss=0.6447, F1 Score=0.8756 | Val: Loss=0.6299, F1 Score=0.8185
Epoch  15/200 | Train: Loss=0.6216, F1 Score=0.8838 | Val: Loss=0.6109, F1 Score=0.8340
Epoch  16/200 | Train: Loss=0.5980, F1 Score=0.8960 | Val: Loss=0.6638, F1 Score=0.8363
Epoch  17/200 | Train: Loss=0.5898, F1 Score=0.8923 | Val: Loss=0.7147, F1 Score=0.8387
Epoch  18/200 | Train: Loss=0.5591, F1 Score=0.9037 | Val: Loss=0.6120, F1 Score=0.8319
Epoch  19/200 | Train: Loss=0.5474, F1 Score=0.9086 | Val: Loss=0.5935, F1 Score=0.8351
Epoch  20/200 | Train: Loss=0.5311, F1 Score=0.9174 | Val: Loss=0.6224, F1 Score=0.8227
Epoch  21/200 | Train: Loss=0.5199, F1 Score=0.9141 | Val: Loss=0.6788, F1 Score=0.8433
Epoch  22/200 | Train: Loss=0.5133, F1 Score=0.9166 | Val: Loss=0.6483, F1 Score=0.8502
Epoch  23/200 | Train: Loss=0.4905, F1 Score=0.9237 | Val: Loss=0.6413, F1 Score=0.8533
Epoch  24/200 | Train: Loss=0.4784, F1 Score=0.9285 | Val: Loss=0.5986, F1 Score=0.8536
Epoch  25/200 | Train: Loss=0.4708, F1 Score=0.9254 | Val: Loss=0.5938, F1 Score=0.8515
Epoch  26/200 | Train: Loss=0.4707, F1 Score=0.9246 | Val: Loss=0.6763, F1 Score=0.8524
Epoch  27/200 | Train: Loss=0.4515, F1 Score=0.9330 | Val: Loss=0.5940, F1 Score=0.8704
Epoch  28/200 | Train: Loss=0.4332, F1 Score=0.9387 | Val: Loss=0.5968, F1 Score=0.8397
Epoch  29/200 | Train: Loss=0.4307, F1 Score=0.9370 | Val: Loss=0.6439, F1 Score=0.8571
Epoch  30/200 | Train: Loss=0.4226, F1 Score=0.9398 | Val: Loss=0.6211, F1 Score=0.8602
Epoch  31/200 | Train: Loss=0.4112, F1 Score=0.9385 | Val: Loss=0.5678, F1 Score=0.8538
Epoch  32/200 | Train: Loss=0.3997, F1 Score=0.9454 | Val: Loss=0.6484, F1 Score=0.8583
Epoch  33/200 | Train: Loss=0.4066, F1 Score=0.9442 | Val: Loss=0.6098, F1 Score=0.8456
Epoch  34/200 | Train: Loss=0.3896, F1 Score=0.9426 | Val: Loss=0.5952, F1 Score=0.8669
Epoch  35/200 | Train: Loss=0.3746, F1 Score=0.9530 | Val: Loss=0.6348, F1 Score=0.8571
Epoch  36/200 | Train: Loss=0.3685, F1 Score=0.9539 | Val: Loss=0.5700, F1 Score=0.8704
Epoch  37/200 | Train: Loss=0.3775, F1 Score=0.9477 | Val: Loss=0.6164, F1 Score=0.8441
Epoch  38/200 | Train: Loss=0.3579, F1 Score=0.9540 | Val: Loss=0.6331, F1 Score=0.8674
Epoch  39/200 | Train: Loss=0.3622, F1 Score=0.9560 | Val: Loss=0.5871, F1 Score=0.8637
Epoch  40/200 | Train: Loss=0.3492, F1 Score=0.9584 | Val: Loss=0.5906, F1 Score=0.8701
Epoch  41/200 | Train: Loss=0.3555, F1 Score=0.9537 | Val: Loss=0.5535, F1 Score=0.8676
Epoch  42/200 | Train: Loss=0.3495, F1 Score=0.9555 | Val: Loss=0.5576, F1 Score=0.8650
Epoch  43/200 | Train: Loss=0.3429, F1 Score=0.9615 | Val: Loss=0.6016, F1 Score=0.8609
Epoch  44/200 | Train: Loss=0.3515, F1 Score=0.9558 | Val: Loss=0.6375, F1 Score=0.8682
Epoch  45/200 | Train: Loss=0.3531, F1 Score=0.9563 | Val: Loss=0.5642, F1 Score=0.8713
Epoch  46/200 | Train: Loss=0.3464, F1 Score=0.9575 | Val: Loss=0.5890, F1 Score=0.8704
Epoch  47/200 | Train: Loss=0.3479, F1 Score=0.9581 | Val: Loss=0.6549, F1 Score=0.8624
Epoch  48/200 | Train: Loss=0.3453, F1 Score=0.9566 | Val: Loss=0.6628, F1 Score=0.8653
Epoch  49/200 | Train: Loss=0.3421, F1 Score=0.9625 | Val: Loss=0.6228, F1 Score=0.8726
Epoch  50/200 | Train: Loss=0.3406, F1 Score=0.9603 | Val: Loss=0.5970, F1 Score=0.8693
Epoch  51/200 | Train: Loss=0.3444, F1 Score=0.9581 | Val: Loss=0.6842, F1 Score=0.8667
Epoch  52/200 | Train: Loss=0.3399, F1 Score=0.9609 | Val: Loss=0.5933, F1 Score=0.8544
Epoch  53/200 | Train: Loss=0.3454, F1 Score=0.9583 | Val: Loss=0.6071, F1 Score=0.8574
Epoch  54/200 | Train: Loss=0.3324, F1 Score=0.9645 | Val: Loss=0.5819, F1 Score=0.8733
Epoch  55/200 | Train: Loss=0.3470, F1 Score=0.9596 | Val: Loss=0.6386, F1 Score=0.8707
Epoch  56/200 | Train: Loss=0.3402, F1 Score=0.9639 | Val: Loss=0.5863, F1 Score=0.8726
Epoch  57/200 | Train: Loss=0.3361, F1 Score=0.9614 | Val: Loss=0.6739, F1 Score=0.8765
Epoch  58/200 | Train: Loss=0.3427, F1 Score=0.9597 | Val: Loss=0.5804, F1 Score=0.8644

[I 2025-11-17 15:40:18,316] Trial 1 finished with value: 0.9033506215996918 and parameters: {'SEED': 1036, 'WINDOW': 60, 'STRIDE': 15, 'c1_filters': 32, 'c2_filters': 64, 'c3_filters': 128, 'cnn_dropout': 0.009305236420321494, 'hidden_size': 32, 'num_layers': 3, 'rnn_dropout': 0.11967645219502371, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'kaiming_normal', 'lr': 2.2892331554376754e-05, 'weight_decay': 2.4546316528685736e-06, 'l1_lambda': 3.7432311184317826e-05, 'weight_max_norm': 1.9249998391601346}. Best is trial 0 with value: 0.9224502800789871.
[I 2025-11-17 15:40:18,321] Trial 2 pruned.

Training 200 epochs...
Epoch   1/200 | Train: Loss=1.5759, F1 Score=0.5475 | Val: Loss=1.0729, F1 Score=0.1934
Epoch   2/200 | Train: Loss=1.1748, F1 Score=0.7851 | Val: Loss=0.5243, F1 Score=0.8641
Epoch   3/200 | Train: Loss=0.9260, F1 Score=0.8623 | Val: Loss=0.7078, F1 Score=0.7711
Epoch   4/200 | Train: Loss=0.7946, F1 Score=0.8872 | Val: Loss=0.6266, F1 Score=0.8326
Epoch   5/200 | Train: Loss=0.7113, F1 Score=0.9097 | Val: Loss=0.6378, F1 Score=0.8718
Epoch   6/200 | Train: Loss=0.6591, F1 Score=0.9266 | Val: Loss=0.5916, F1 Score=0.8683
Epoch   7/200 | Train: Loss=0.6186, F1 Score=0.9356 | Val: Loss=0.6522, F1 Score=0.8902
Epoch   8/200 | Train: Loss=0.5886, F1 Score=0.9448 | Val: Loss=0.6747, F1 Score=0.8967
Epoch   9/200 | Train: Loss=0.5711, F1 Score=0.9506 | Val: Loss=0.7176, F1 Score=0.8984
Epoch  10/200 | Train: Loss=0.5391, F1 Score=0.9605 | Val: Loss=0.7137, F1 Score=0.9013
Epoch  11/200 | Train: Loss=0.5368, F1 Score=0.9563 | Val: Loss=0.7400, F1 Score=0.8933
Epoch  12/200 | Train: Loss=0.5216, F1 Score=0.9607 | Val: Loss=0.6971, F1 Score=0.9150
Epoch  13/200 | Train: Loss=0.5098, F1 Score=0.9639 | Val: Loss=0.6864, F1 Score=0.9086
Epoch  14/200 | Train: Loss=0.4891, F1 Score=0.9678 | Val: Loss=0.7402, F1 Score=0.9036
Epoch  15/200 | Train: Loss=0.4851, F1 Score=0.9707 | Val: Loss=0.7039, F1 Score=0.9157
Epoch  16/200 | Train: Loss=0.4733, F1 Score=0.9720 | Val: Loss=0.6730, F1 Score=0.9230
Epoch  17/200 | Train: Loss=0.4578, F1 Score=0.9751 | Val: Loss=0.6718, F1 Score=0.9227
Epoch  18/200 | Train: Loss=0.4534, F1 Score=0.9728 | Val: Loss=0.6868, F1 Score=0.9263
Epoch  19/200 | Train: Loss=0.4411, F1 Score=0.9776 | Val: Loss=0.7513, F1 Score=0.9063
Epoch  20/200 | Train: Loss=0.4295, F1 Score=0.9786 | Val: Loss=0.7022, F1 Score=0.9265
Epoch  21/200 | Train: Loss=0.4282, F1 Score=0.9778 | Val: Loss=0.7738, F1 Score=0.8995
Epoch  22/200 | Train: Loss=0.4247, F1 Score=0.9775 | Val: Loss=0.7452, F1 Score=0.9063
Epoch  23/200 | Train: Loss=0.4165, F1 Score=0.9783 | Val: Loss=0.7214, F1 Score=0.9219
Epoch  24/200 | Train: Loss=0.4059, F1 Score=0.9816 | Val: Loss=0.7052, F1 Score=0.9317
Epoch  25/200 | Train: Loss=0.4034, F1 Score=0.9804 | Val: Loss=0.7004, F1 Score=0.9304
Epoch  26/200 | Train: Loss=0.3998, F1 Score=0.9794 | Val: Loss=0.6780, F1 Score=0.9329
Epoch  27/200 | Train: Loss=0.3865, F1 Score=0.9826 | Val: Loss=0.6968, F1 Score=0.9299
Epoch  28/200 | Train: Loss=0.3820, F1 Score=0.9827 | Val: Loss=0.6770, F1 Score=0.9315
Epoch  29/200 | Train: Loss=0.3724, F1 Score=0.9863 | Val: Loss=0.7580, F1 Score=0.9213
Epoch  30/200 | Train: Loss=0.3661, F1 Score=0.9843 | Val: Loss=0.7169, F1 Score=0.9248
Epoch  31/200 | Train: Loss=0.3611, F1 Score=0.9862 | Val: Loss=0.6763, F1 Score=0.9334
Epoch  32/200 | Train: Loss=0.3652, F1 Score=0.9821 | Val: Loss=0.7121, F1 Score=0.9254
Epoch  33/200 | Train: Loss=0.3529, F1 Score=0.9863 | Val: Loss=0.6928, F1 Score=0.9317
Epoch  34/200 | Train: Loss=0.3440, F1 Score=0.9863 | Val: Loss=0.7524, F1 Score=0.9275
Epoch  35/200 | Train: Loss=0.3358, F1 Score=0.9898 | Val: Loss=0.7466, F1 Score=0.9311
Epoch  36/200 | Train: Loss=0.3426, F1 Score=0.9841 | Val: Loss=0.8815, F1 Score=0.8878
Epoch  37/200 | Train: Loss=0.3311, F1 Score=0.9863 | Val: Loss=0.7589, F1 Score=0.9301
Epoch  38/200 | Train: Loss=0.3294, F1 Score=0.9867 | Val: Loss=0.6625, F1 Score=0.9265
Epoch  39/200 | Train: Loss=0.3325, F1 Score=0.9853 | Val: Loss=0.7258, F1 Score=0.9234
Epoch  40/200 | Train: Loss=0.3212, F1 Score=0.9867 | Val: Loss=0.7247, F1 Score=0.9326
Epoch  41/200 | Train: Loss=0.3169, F1 Score=0.9878 | Val: Loss=0.6997, F1 Score=0.9342
Epoch  42/200 | Train: Loss=0.3114, F1 Score=0.9896 | Val: Loss=0.7360, F1 Score=0.9327
Epoch  43/200 | Train: Loss=0.3088, F1 Score=0.9884 | Val: Loss=0.7240, F1 Score=0.9264
Epoch  44/200 | Train: Loss=0.3071, F1 Score=0.9885 | Val: Loss=0.8076, F1 Score=0.9235
Epoch  45/200 | Train: Loss=0.3167, F1 Score=0.9841 | Val: Loss=0.7381, F1 Score=0.9217
Epoch  46/200 | Train: Loss=0.3145, F1 Score=0.9838 | Val: Loss=0.7350, F1 Score=0.9231
Epoch  47/200 | Train: Loss=0.2934, F1 Score=0.9914 | Val: Loss=0.7215, F1 Score=0.9293
Epoch  48/200 | Train: Loss=0.2976, F1 Score=0.9881 | Val: Loss=0.7889, F1 Score=0.9197
Epoch  49/200 | Train: Loss=0.2944, F1 Score=0.9882 | Val: Loss=0.8077, F1 Score=0.9268
Epoch  50/200 | Train: Loss=0.2869, F1 Score=0.9905 | Val: Loss=0.8235, F1 Score=0.9240
Epoch  51/200 | Train: Loss=0.2888, F1 Score=0.9887 | Val: Loss=0.7783, F1 Score=0.9219
Epoch  52/200 | Train: Loss=0.2820, F1 Score=0.9908 | Val: Loss=0.7948, F1 Score=0.9204
Epoch  53/200 | Train: Loss=0.2765, F1 Score=0.9931 | Val: Loss=0.7658, F1 Score=0.9268
Epoch  54/200 | Train: Loss=0.2736, F1 Score=0.9937 | Val: Loss=0.7780, F1 Score=0.9271
Epoch  55/200 | Train: Loss=0.2732, F1 Score=0.9936 | Val: Loss=0.7708, F1 Score=0.9279
Epoch  56/200 | Train: Loss=0.2717, F1 Score=0.9940 | Val: Loss=0.7523, F1 Score=0.9295
Early stopping triggered after 56 epochs.
Best model restored from epoch 41 with val_f1 0.9342
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.5435, F1 Score=0.5974 | Val: Loss=1.2513, F1 Score=0.0124
Epoch   2/200 | Train: Loss=1.1223, F1 Score=0.8190 | Val: Loss=0.6107, F1 Score=0.8353
Epoch   3/200 | Train: Loss=0.8825, F1 Score=0.8800 | Val: Loss=0.6890, F1 Score=0.7568
Epoch   4/200 | Train: Loss=0.7663, F1 Score=0.9060 | Val: Loss=0.6413, F1 Score=0.8632
Epoch   5/200 | Train: Loss=0.6897, F1 Score=0.9208 | Val: Loss=0.6720, F1 Score=0.8898
Epoch   6/200 | Train: Loss=0.6400, F1 Score=0.9314 | Val: Loss=0.6687, F1 Score=0.8987
Epoch   7/200 | Train: Loss=0.5992, F1 Score=0.9484 | Val: Loss=0.7555, F1 Score=0.8687
Epoch   8/200 | Train: Loss=0.5786, F1 Score=0.9521 | Val: Loss=0.7725, F1 Score=0.8719
Epoch   9/200 | Train: Loss=0.5505, F1 Score=0.9572 | Val: Loss=0.8701, F1 Score=0.9002
Epoch  10/200 | Train: Loss=0.5336, F1 Score=0.9644 | Val: Loss=0.8164, F1 Score=0.8842
Epoch  11/200 | Train: Loss=0.5155, F1 Score=0.9654 | Val: Loss=0.8287, F1 Score=0.9062
Epoch  12/200 | Train: Loss=0.5121, F1 Score=0.9685 | Val: Loss=0.7748, F1 Score=0.8953
Epoch  13/200 | Train: Loss=0.4977, F1 Score=0.9692 | Val: Loss=0.8907, F1 Score=0.8789
Epoch  14/200 | Train: Loss=0.4787, F1 Score=0.9731 | Val: Loss=0.9393, F1 Score=0.9033
Epoch  15/200 | Train: Loss=0.4716, F1 Score=0.9719 | Val: Loss=0.8716, F1 Score=0.9031
Epoch  16/200 | Train: Loss=0.4672, F1 Score=0.9748 | Val: Loss=0.8665, F1 Score=0.9013
Epoch  17/200 | Train: Loss=0.4437, F1 Score=0.9795 | Val: Loss=0.8590, F1 Score=0.9070
Epoch  18/200 | Train: Loss=0.4355, F1 Score=0.9820 | Val: Loss=0.9526, F1 Score=0.8968
Epoch  19/200 | Train: Loss=0.4287, F1 Score=0.9832 | Val: Loss=0.9096, F1 Score=0.9101
Epoch  20/200 | Train: Loss=0.4174, F1 Score=0.9835 | Val: Loss=0.9133, F1 Score=0.8992
Epoch  21/200 | Train: Loss=0.4164, F1 Score=0.9811 | Val: Loss=0.8708, F1 Score=0.9082
Epoch  22/200 | Train: Loss=0.4032, F1 Score=0.9844 | Val: Loss=0.8501, F1 Score=0.9027
Epoch  23/200 | Train: Loss=0.4005, F1 Score=0.9842 | Val: Loss=0.8989, F1 Score=0.9030
Epoch  24/200 | Train: Loss=0.4000, F1 Score=0.9814 | Val: Loss=0.9102, F1 Score=0.9048
Epoch  25/200 | Train: Loss=0.3923, F1 Score=0.9824 | Val: Loss=0.8578, F1 Score=0.9088
Epoch  26/200 | Train: Loss=0.3881, F1 Score=0.9814 | Val: Loss=0.8337, F1 Score=0.8995
Epoch  27/200 | Train: Loss=0.3667, F1 Score=0.9883 | Val: Loss=0.9189, F1 Score=0.9107
Epoch  28/200 | Train: Loss=0.3680, F1 Score=0.9871 | Val: Loss=0.8869, F1 Score=0.8994
Epoch  29/200 | Train: Loss=0.3668, F1 Score=0.9836 | Val: Loss=0.9263, F1 Score=0.9113
Epoch  30/200 | Train: Loss=0.3529, F1 Score=0.9884 | Val: Loss=0.9018, F1 Score=0.9101
Epoch  31/200 | Train: Loss=0.3505, F1 Score=0.9863 | Val: Loss=0.8716, F1 Score=0.9148
Epoch  32/200 | Train: Loss=0.3495, F1 Score=0.9862 | Val: Loss=0.9132, F1 Score=0.9010
Epoch  33/200 | Train: Loss=0.3421, F1 Score=0.9880 | Val: Loss=0.9102, F1 Score=0.9137
Epoch  34/200 | Train: Loss=0.3279, F1 Score=0.9907 | Val: Loss=0.9210, F1 Score=0.9151
Epoch  35/200 | Train: Loss=0.3379, F1 Score=0.9900 | Val: Loss=0.9705, F1 Score=0.8742
Epoch  36/200 | Train: Loss=0.3210, F1 Score=0.9911 | Val: Loss=0.9946, F1 Score=0.9086
Epoch  37/200 | Train: Loss=0.3294, F1 Score=0.9874 | Val: Loss=0.8788, F1 Score=0.9081
Epoch  38/200 | Train: Loss=0.3130, F1 Score=0.9909 | Val: Loss=0.8566, F1 Score=0.9124
Epoch  39/200 | Train: Loss=0.3103, F1 Score=0.9921 | Val: Loss=0.9631, F1 Score=0.9063
Epoch  40/200 | Train: Loss=0.3069, F1 Score=0.9925 | Val: Loss=0.9128, F1 Score=0.8995
Epoch  41/200 | Train: Loss=0.3208, F1 Score=0.9871 | Val: Loss=0.9443, F1 Score=0.9101
Epoch  42/200 | Train: Loss=0.2969, F1 Score=0.9919 | Val: Loss=0.9423, F1 Score=0.9145
Epoch  43/200 | Train: Loss=0.2988, F1 Score=0.9905 | Val: Loss=0.9149, F1 Score=0.9127
Epoch  44/200 | Train: Loss=0.2907, F1 Score=0.9929 | Val: Loss=0.8945, F1 Score=0.9133
Epoch  45/200 | Train: Loss=0.2879, F1 Score=0.9936 | Val: Loss=0.9446, F1 Score=0.9152
Epoch  46/200 | Train: Loss=0.2858, F1 Score=0.9952 | Val: Loss=0.8646, F1 Score=0.9116
Epoch  47/200 | Train: Loss=0.2838, F1 Score=0.9936 | Val: Loss=0.8769, F1 Score=0.9117
Epoch  48/200 | Train: Loss=0.2841, F1 Score=0.9944 | Val: Loss=0.8957, F1 Score=0.9109
Epoch  49/200 | Train: Loss=0.2810, F1 Score=0.9946 | Val: Loss=0.8950, F1 Score=0.9135
Epoch  50/200 | Train: Loss=0.2812, F1 Score=0.9950 | Val: Loss=0.8960, F1 Score=0.9104
Epoch  51/200 | Train: Loss=0.2782, F1 Score=0.9963 | Val: Loss=0.8936, F1 Score=0.9124
Epoch  52/200 | Train: Loss=0.2788, F1 Score=0.9955 | Val: Loss=0.8988, F1 Score=0.9114
Epoch  53/200 | Train: Loss=0.2785, F1 Score=0.9966 | Val: Loss=0.8987, F1 Score=0.9107
Epoch  54/200 | Train: Loss=0.2770, F1 Score=0.9954 | Val: Loss=0.9082, F1 Score=0.9122
Epoch  55/200 | Train: Loss=0.2782, F1 Score=0.9962 | Val: Loss=0.9334, F1 Score=0.9122
Epoch  56/200 | Train: Loss=0.2778, F1 Score=0.9961 | Val: Loss=0.9259, F1 Score=0.9125
Epoch  57/200 | Train: Loss=0.2747, F1 Score=0.9967 | Val: Loss=0.9109, F1 Score=0.9132
Epoch  58/200 | Train: Loss=0.2747, F1 Score=0.9967 | Val: Loss=0.9009, F1 Score=0.9113
Epoch  59/200 | Train: Loss=0.2763, F1 Score=0.9967 | Val: Loss=0.8793, F1 Score=0.9125
Epoch  60/200 | Train: Loss=0.2762, F1 Score=0.9963 | Val: Loss=0.9015, F1 Score=0.9130
Early stopping triggered after 60 epochs.
Best model restored from epoch 45 with val_f1 0.9152
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.5045, F1 Score=0.5716 | Val: Loss=0.9944, F1 Score=0.6737
Epoch   2/200 | Train: Loss=1.0950, F1 Score=0.8283 | Val: Loss=0.5930, F1 Score=0.8484
Epoch   3/200 | Train: Loss=0.9252, F1 Score=0.8756 | Val: Loss=0.5866, F1 Score=0.8423
Epoch   4/200 | Train: Loss=0.8201, F1 Score=0.8974 | Val: Loss=0.5483, F1 Score=0.8708
Epoch   5/200 | Train: Loss=0.7451, F1 Score=0.9148 | Val: Loss=0.6254, F1 Score=0.8554
Epoch   6/200 | Train: Loss=0.6862, F1 Score=0.9262 | Val: Loss=0.6059, F1 Score=0.8814
Epoch   7/200 | Train: Loss=0.6327, F1 Score=0.9395 | Val: Loss=0.6672, F1 Score=0.8629
Epoch   8/200 | Train: Loss=0.6050, F1 Score=0.9452 | Val: Loss=0.6182, F1 Score=0.8786
Epoch   9/200 | Train: Loss=0.5786, F1 Score=0.9482 | Val: Loss=0.6950, F1 Score=0.8726
Epoch  10/200 | Train: Loss=0.5621, F1 Score=0.9527 | Val: Loss=0.6789, F1 Score=0.8771
Epoch  11/200 | Train: Loss=0.5377, F1 Score=0.9579 | Val: Loss=0.7463, F1 Score=0.8866
Epoch  12/200 | Train: Loss=0.5306, F1 Score=0.9586 | Val: Loss=0.6591, F1 Score=0.8825
Epoch  13/200 | Train: Loss=0.5159, F1 Score=0.9585 | Val: Loss=0.7605, F1 Score=0.8747
Epoch  14/200 | Train: Loss=0.4967, F1 Score=0.9660 | Val: Loss=0.6956, F1 Score=0.8783
Epoch  15/200 | Train: Loss=0.4955, F1 Score=0.9660 | Val: Loss=0.7637, F1 Score=0.8858
Epoch  16/200 | Train: Loss=0.4808, F1 Score=0.9676 | Val: Loss=0.8313, F1 Score=0.8869
Epoch  17/200 | Train: Loss=0.4800, F1 Score=0.9669 | Val: Loss=0.7792, F1 Score=0.8954
Epoch  18/200 | Train: Loss=0.4602, F1 Score=0.9701 | Val: Loss=0.8605, F1 Score=0.8923
Epoch  19/200 | Train: Loss=0.4485, F1 Score=0.9755 | Val: Loss=0.8807, F1 Score=0.8984
Epoch  20/200 | Train: Loss=0.4537, F1 Score=0.9692 | Val: Loss=0.7780, F1 Score=0.8916
Epoch  21/200 | Train: Loss=0.4299, F1 Score=0.9772 | Val: Loss=0.8228, F1 Score=0.8989
Epoch  22/200 | Train: Loss=0.4251, F1 Score=0.9774 | Val: Loss=0.8530, F1 Score=0.8936
Epoch  23/200 | Train: Loss=0.4201, F1 Score=0.9765 | Val: Loss=0.8786, F1 Score=0.8809
Epoch  24/200 | Train: Loss=0.4104, F1 Score=0.9802 | Val: Loss=0.9209, F1 Score=0.8737
Epoch  25/200 | Train: Loss=0.4012, F1 Score=0.9824 | Val: Loss=0.8860, F1 Score=0.8982
Epoch  26/200 | Train: Loss=0.4010, F1 Score=0.9806 | Val: Loss=0.8063, F1 Score=0.8959
Epoch  27/200 | Train: Loss=0.3879, F1 Score=0.9826 | Val: Loss=0.7922, F1 Score=0.9045
Epoch  28/200 | Train: Loss=0.3892, F1 Score=0.9832 | Val: Loss=0.9652, F1 Score=0.8908
Epoch  29/200 | Train: Loss=0.3732, F1 Score=0.9845 | Val: Loss=0.8536, F1 Score=0.8811
Epoch  30/200 | Train: Loss=0.3701, F1 Score=0.9840 | Val: Loss=0.8975, F1 Score=0.9042
Epoch  31/200 | Train: Loss=0.3722, F1 Score=0.9834 | Val: Loss=1.0447, F1 Score=0.8805
Epoch  32/200 | Train: Loss=0.3687, F1 Score=0.9801 | Val: Loss=0.9197, F1 Score=0.8967
Epoch  33/200 | Train: Loss=0.3537, F1 Score=0.9848 | Val: Loss=0.8946, F1 Score=0.9001
Epoch  34/200 | Train: Loss=0.3585, F1 Score=0.9840 | Val: Loss=0.9551, F1 Score=0.8912
Epoch  35/200 | Train: Loss=0.3489, F1 Score=0.9868 | Val: Loss=0.9210, F1 Score=0.8802
Epoch  36/200 | Train: Loss=0.3484, F1 Score=0.9844 | Val: Loss=0.8504, F1 Score=0.8972
Epoch  37/200 | Train: Loss=0.3381, F1 Score=0.9873 | Val: Loss=0.8976, F1 Score=0.8999
Epoch  38/200 | Train: Loss=0.3311, F1 Score=0.9881 | Val: Loss=0.8326, F1 Score=0.9112
Epoch  39/200 | Train: Loss=0.3317, F1 Score=0.9873 | Val: Loss=0.9863, F1 Score=0.8890
Epoch  40/200 | Train: Loss=0.3257, F1 Score=0.9864 | Val: Loss=0.9286, F1 Score=0.8965
Epoch  41/200 | Train: Loss=0.3179, F1 Score=0.9898 | Val: Loss=0.8585, F1 Score=0.9102
Epoch  42/200 | Train: Loss=0.3169, F1 Score=0.9884 | Val: Loss=0.9353, F1 Score=0.8885
Epoch  43/200 | Train: Loss=0.3123, F1 Score=0.9882 | Val: Loss=0.9309, F1 Score=0.8956
Epoch  44/200 | Train: Loss=0.3122, F1 Score=0.9881 | Val: Loss=0.9966, F1 Score=0.8959
Epoch  45/200 | Train: Loss=0.3044, F1 Score=0.9890 | Val: Loss=1.0005, F1 Score=0.8929
Epoch  46/200 | Train: Loss=0.2986, F1 Score=0.9921 | Val: Loss=1.0062, F1 Score=0.9014
Epoch  47/200 | Train: Loss=0.2992, F1 Score=0.9901 | Val: Loss=0.9496, F1 Score=0.9069
Epoch  48/200 | Train: Loss=0.2929, F1 Score=0.9904 | Val: Loss=0.9814, F1 Score=0.9056
Epoch  49/200 | Train: Loss=0.3083, F1 Score=0.9867 | Val: Loss=1.0966, F1 Score=0.8722
Epoch  50/200 | Train: Loss=0.2940, F1 Score=0.9890 | Val: Loss=0.9707, F1 Score=0.8962
Epoch  51/200 | Train: Loss=0.2842, F1 Score=0.9935 | Val: Loss=0.9654, F1 Score=0.8960
Epoch  52/200 | Train: Loss=0.2833, F1 Score=0.9947 | Val: Loss=0.9399, F1 Score=0.8998
Epoch  53/200 | Train: Loss=0.2798, F1 Score=0.9952 | Val: Loss=0.9458, F1 Score=0.8992
Early stopping triggered after 53 epochs.
Best model restored from epoch 38 with val_f1 0.9112

[I 2025-11-17 15:48:28,671] Trial 3 finished with value: 0.9202062528891056 and parameters: {'SEED': 3840, 'WINDOW': 40, 'STRIDE': 5, 'c1_filters': 32, 'c2_filters': 64, 'c3_filters': 128, 'cnn_dropout': 0.44849297337560773, 'hidden_size': 128, 'num_layers': 3, 'rnn_dropout': 0.1816365044570294, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'xavier_uniform', 'lr': 3.849453199518574e-05, 'weight_decay': 5.332960638567651e-06, 'l1_lambda': 3.033506916171516e-05, 'weight_max_norm': 2.6680866430670824}. Best is trial 0 with value: 0.9224502800789871.

Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1113, F1 Score=0.4468 | Val: Loss=1.0568, F1 Score=0.6751
Epoch   2/200 | Train: Loss=1.0232, F1 Score=0.5172 | Val: Loss=0.9897, F1 Score=0.5976
Epoch   3/200 | Train: Loss=0.9282, F1 Score=0.5861 | Val: Loss=0.9332, F1 Score=0.6189
Epoch   4/200 | Train: Loss=0.8561, F1 Score=0.6446 | Val: Loss=0.8624, F1 Score=0.7044

[I 2025-11-17 15:48:46,178] Trial 4 pruned.

Epoch   5/200 | Train: Loss=0.7819, F1 Score=0.6852 | Val: Loss=0.8129, F1 Score=0.7297
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.5649, F1 Score=0.4961 | Val: Loss=1.1221, F1 Score=0.0136
Epoch   2/200 | Train: Loss=1.1535, F1 Score=0.7157 | Val: Loss=0.6877, F1 Score=0.8036
Epoch   3/200 | Train: Loss=0.9627, F1 Score=0.8182 | Val: Loss=0.6087, F1 Score=0.8241
Epoch   4/200 | Train: Loss=0.8511, F1 Score=0.8533 | Val: Loss=0.6079, F1 Score=0.8039
Epoch   5/200 | Train: Loss=0.7679, F1 Score=0.8689 | Val: Loss=0.5311, F1 Score=0.8634
Epoch   6/200 | Train: Loss=0.7077, F1 Score=0.8904 | Val: Loss=0.4847, F1 Score=0.8771
Epoch   7/200 | Train: Loss=0.6463, F1 Score=0.9092 | Val: Loss=0.4963, F1 Score=0.8784
Epoch   8/200 | Train: Loss=0.5962, F1 Score=0.9208 | Val: Loss=0.4596, F1 Score=0.8855
Epoch   9/200 | Train: Loss=0.5571, F1 Score=0.9254 | Val: Loss=0.4157, F1 Score=0.9027
Epoch  10/200 | Train: Loss=0.5144, F1 Score=0.9338 | Val: Loss=0.4086, F1 Score=0.9034
Epoch  11/200 | Train: Loss=0.4945, F1 Score=0.9332 | Val: Loss=0.4234, F1 Score=0.8934
Epoch  12/200 | Train: Loss=0.4648, F1 Score=0.9413 | Val: Loss=0.4113, F1 Score=0.8936
Epoch  13/200 | Train: Loss=0.4409, F1 Score=0.9465 | Val: Loss=0.4316, F1 Score=0.8898
Epoch  14/200 | Train: Loss=0.4262, F1 Score=0.9484 | Val: Loss=0.4639, F1 Score=0.8721
Epoch  15/200 | Train: Loss=0.4140, F1 Score=0.9491 | Val: Loss=0.3938, F1 Score=0.9002
Epoch  16/200 | Train: Loss=0.3944, F1 Score=0.9551 | Val: Loss=0.3810, F1 Score=0.9201
Epoch  17/200 | Train: Loss=0.3940, F1 Score=0.9518 | Val: Loss=0.4839, F1 Score=0.8818
Epoch  18/200 | Train: Loss=0.3795, F1 Score=0.9559 | Val: Loss=0.3823, F1 Score=0.9187
Epoch  19/200 | Train: Loss=0.3607, F1 Score=0.9641 | Val: Loss=0.3929, F1 Score=0.9220
Epoch  20/200 | Train: Loss=0.3584, F1 Score=0.9635 | Val: Loss=0.4235, F1 Score=0.9099
Epoch  21/200 | Train: Loss=0.3505, F1 Score=0.9654 | Val: Loss=0.3776, F1 Score=0.9213
Epoch  22/200 | Train: Loss=0.3391, F1 Score=0.9701 | Val: Loss=0.4032, F1 Score=0.9193
Epoch  23/200 | Train: Loss=0.3346, F1 Score=0.9716 | Val: Loss=0.3780, F1 Score=0.9232
Epoch  24/200 | Train: Loss=0.3372, F1 Score=0.9688 | Val: Loss=0.4341, F1 Score=0.9158
Epoch  25/200 | Train: Loss=0.3246, F1 Score=0.9733 | Val: Loss=0.5309, F1 Score=0.8429
Epoch  26/200 | Train: Loss=0.3185, F1 Score=0.9738 | Val: Loss=0.4279, F1 Score=0.9227
Epoch  27/200 | Train: Loss=0.3142, F1 Score=0.9771 | Val: Loss=0.4532, F1 Score=0.9120
Epoch  28/200 | Train: Loss=0.3116, F1 Score=0.9766 | Val: Loss=0.4296, F1 Score=0.9123
Epoch  29/200 | Train: Loss=0.3128, F1 Score=0.9750 | Val: Loss=0.4128, F1 Score=0.9197
Epoch  30/200 | Train: Loss=0.3013, F1 Score=0.9815 | Val: Loss=0.4955, F1 Score=0.8898
Epoch  31/200 | Train: Loss=0.2967, F1 Score=0.9817 | Val: Loss=0.4041, F1 Score=0.9227
Epoch  32/200 | Train: Loss=0.2932, F1 Score=0.9837 | Val: Loss=0.4626, F1 Score=0.9137
Epoch  33/200 | Train: Loss=0.2932, F1 Score=0.9825 | Val: Loss=0.4454, F1 Score=0.9253
Epoch  34/200 | Train: Loss=0.2858, F1 Score=0.9859 | Val: Loss=0.4661, F1 Score=0.9118
Epoch  35/200 | Train: Loss=0.2959, F1 Score=0.9772 | Val: Loss=0.4786, F1 Score=0.9083
Epoch  36/200 | Train: Loss=0.2794, F1 Score=0.9865 | Val: Loss=0.4082, F1 Score=0.9253

[I 2025-11-17 15:51:07,937] Trial 5 pruned.

Epoch  37/200 | Train: Loss=0.2837, F1 Score=0.9844 | Val: Loss=0.4253, F1 Score=0.9171
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.9912, F1 Score=0.7572 | Val: Loss=1.5565, F1 Score=0.6929
Epoch   2/200 | Train: Loss=0.6286, F1 Score=0.8604 | Val: Loss=0.6112, F1 Score=0.8819
Epoch   3/200 | Train: Loss=0.4874, F1 Score=0.9028 | Val: Loss=0.8922, F1 Score=0.7830
Epoch   4/200 | Train: Loss=0.4265, F1 Score=0.9255 | Val: Loss=0.6136, F1 Score=0.8715
Epoch   5/200 | Train: Loss=0.4182, F1 Score=0.9307 | Val: Loss=0.6324, F1 Score=0.8917
Epoch   6/200 | Train: Loss=0.3641, F1 Score=0.9432 | Val: Loss=0.6857, F1 Score=0.9039
Epoch   7/200 | Train: Loss=0.3473, F1 Score=0.9486 | Val: Loss=0.9002, F1 Score=0.8740
Epoch   8/200 | Train: Loss=0.3338, F1 Score=0.9520 | Val: Loss=0.8370, F1 Score=0.8715
Epoch   9/200 | Train: Loss=0.3171, F1 Score=0.9552 | Val: Loss=0.6483, F1 Score=0.8919
Epoch  10/200 | Train: Loss=0.3111, F1 Score=0.9636 | Val: Loss=0.8554, F1 Score=0.9087
Epoch  11/200 | Train: Loss=0.3212, F1 Score=0.9531 | Val: Loss=0.8347, F1 Score=0.8474
Epoch  12/200 | Train: Loss=0.2902, F1 Score=0.9645 | Val: Loss=0.6500, F1 Score=0.9265
Epoch  13/200 | Train: Loss=0.2757, F1 Score=0.9706 | Val: Loss=0.8603, F1 Score=0.9280
Epoch  14/200 | Train: Loss=0.2697, F1 Score=0.9728 | Val: Loss=0.7266, F1 Score=0.9214
Epoch  15/200 | Train: Loss=0.2775, F1 Score=0.9660 | Val: Loss=0.7483, F1 Score=0.9011
Epoch  16/200 | Train: Loss=0.2832, F1 Score=0.9634 | Val: Loss=0.9213, F1 Score=0.9147
Epoch  17/200 | Train: Loss=0.3069, F1 Score=0.9598 | Val: Loss=0.6561, F1 Score=0.9127
Epoch  18/200 | Train: Loss=0.2609, F1 Score=0.9762 | Val: Loss=0.5678, F1 Score=0.9101
Epoch  19/200 | Train: Loss=0.2600, F1 Score=0.9694 | Val: Loss=0.6545, F1 Score=0.9118
Epoch  20/200 | Train: Loss=0.2348, F1 Score=0.9816 | Val: Loss=0.9691, F1 Score=0.8654
Epoch  21/200 | Train: Loss=0.2322, F1 Score=0.9802 | Val: Loss=0.5841, F1 Score=0.9316
Epoch  22/200 | Train: Loss=0.2398, F1 Score=0.9733 | Val: Loss=0.7019, F1 Score=0.9340
Epoch  23/200 | Train: Loss=0.2178, F1 Score=0.9837 | Val: Loss=0.8135, F1 Score=0.9193
Epoch  24/200 | Train: Loss=0.2185, F1 Score=0.9825 | Val: Loss=0.7886, F1 Score=0.9350
Epoch  25/200 | Train: Loss=0.2108, F1 Score=0.9856 | Val: Loss=0.9190, F1 Score=0.8864
Epoch  26/200 | Train: Loss=0.2141, F1 Score=0.9799 | Val: Loss=0.8057, F1 Score=0.9314
Epoch  27/200 | Train: Loss=0.2148, F1 Score=0.9770 | Val: Loss=0.8133, F1 Score=0.9310
Epoch  28/200 | Train: Loss=0.1955, F1 Score=0.9852 | Val: Loss=0.9456, F1 Score=0.8712
Epoch  29/200 | Train: Loss=0.2170, F1 Score=0.9717 | Val: Loss=0.9634, F1 Score=0.8646
Epoch  30/200 | Train: Loss=0.1974, F1 Score=0.9808 | Val: Loss=0.8897, F1 Score=0.9225
Epoch  31/200 | Train: Loss=0.2247, F1 Score=0.9723 | Val: Loss=0.8418, F1 Score=0.8728
Epoch  32/200 | Train: Loss=0.2312, F1 Score=0.9749 | Val: Loss=0.8030, F1 Score=0.9156
Epoch  33/200 | Train: Loss=0.2286, F1 Score=0.9655 | Val: Loss=0.8970, F1 Score=0.9288
Epoch  34/200 | Train: Loss=0.2134, F1 Score=0.9745 | Val: Loss=0.7810, F1 Score=0.9311
Epoch  35/200 | Train: Loss=0.1920, F1 Score=0.9773 | Val: Loss=0.7472, F1 Score=0.9289
Epoch  36/200 | Train: Loss=0.1708, F1 Score=0.9875 | Val: Loss=0.7355, F1 Score=0.9361
Epoch  37/200 | Train: Loss=0.1655, F1 Score=0.9907 | Val: Loss=0.7603, F1 Score=0.9365
Epoch  38/200 | Train: Loss=0.1619, F1 Score=0.9932 | Val: Loss=0.7907, F1 Score=0.9357
Epoch  39/200 | Train: Loss=0.1630, F1 Score=0.9924 | Val: Loss=0.7553, F1 Score=0.9360
Epoch  40/200 | Train: Loss=0.1599, F1 Score=0.9934 | Val: Loss=0.7662, F1 Score=0.9391
Epoch  41/200 | Train: Loss=0.1589, F1 Score=0.9933 | Val: Loss=0.7778, F1 Score=0.9361
Epoch  42/200 | Train: Loss=0.1597, F1 Score=0.9914 | Val: Loss=0.7870, F1 Score=0.9393
Epoch  43/200 | Train: Loss=0.1560, F1 Score=0.9953 | Val: Loss=0.7803, F1 Score=0.9393
Epoch  44/200 | Train: Loss=0.1592, F1 Score=0.9916 | Val: Loss=0.7892, F1 Score=0.9369
Epoch  45/200 | Train: Loss=0.1541, F1 Score=0.9938 | Val: Loss=0.8207, F1 Score=0.9387
Epoch  46/200 | Train: Loss=0.1543, F1 Score=0.9943 | Val: Loss=0.8066, F1 Score=0.9353
Epoch  47/200 | Train: Loss=0.1547, F1 Score=0.9939 | Val: Loss=0.7762, F1 Score=0.9391
Epoch  48/200 | Train: Loss=0.1542, F1 Score=0.9938 | Val: Loss=0.7809, F1 Score=0.9351
Epoch  49/200 | Train: Loss=0.1526, F1 Score=0.9933 | Val: Loss=0.7929, F1 Score=0.9349
Epoch  50/200 | Train: Loss=0.1521, F1 Score=0.9940 | Val: Loss=0.8246, F1 Score=0.9384
Epoch  51/200 | Train: Loss=0.1514, F1 Score=0.9945 | Val: Loss=0.8046, F1 Score=0.9363
Epoch  52/200 | Train: Loss=0.1533, F1 Score=0.9936 | Val: Loss=0.8383, F1 Score=0.9381
Epoch  53/200 | Train: Loss=0.1487, F1 Score=0.9950 | Val: Loss=0.8589, F1 Score=0.9357
Epoch  54/200 | Train: Loss=0.1503, F1 Score=0.9945 | Val: Loss=0.8378, F1 Score=0.9382
Epoch  55/200 | Train: Loss=0.1483, F1 Score=0.9943 | Val: Loss=0.8284, F1 Score=0.9358
Epoch  56/200 | Train: Loss=0.1471, F1 Score=0.9953 | Val: Loss=0.8495, F1 Score=0.9372
Epoch  57/200 | Train: Loss=0.1491, F1 Score=0.9945 | Val: Loss=0.8270, F1 Score=0.9370
Early stopping triggered after 57 epochs.
Best model restored from epoch 42 with val_f1 0.9393
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.9612, F1 Score=0.7763 | Val: Loss=0.9286, F1 Score=0.7509
Epoch   2/200 | Train: Loss=0.6297, F1 Score=0.8733 | Val: Loss=0.6986, F1 Score=0.8276
Epoch   3/200 | Train: Loss=0.4597, F1 Score=0.9199 | Val: Loss=1.0102, F1 Score=0.8542
Epoch   4/200 | Train: Loss=0.3952, F1 Score=0.9432 | Val: Loss=1.0658, F1 Score=0.8172
Epoch   5/200 | Train: Loss=0.3698, F1 Score=0.9526 | Val: Loss=1.1482, F1 Score=0.7715
Epoch   6/200 | Train: Loss=0.3577, F1 Score=0.9541 | Val: Loss=0.8076, F1 Score=0.8405
Epoch   7/200 | Train: Loss=0.3224, F1 Score=0.9638 | Val: Loss=0.9369, F1 Score=0.8733
Epoch   8/200 | Train: Loss=0.3333, F1 Score=0.9564 | Val: Loss=0.9001, F1 Score=0.8384
Epoch   9/200 | Train: Loss=0.3218, F1 Score=0.9644 | Val: Loss=1.2664, F1 Score=0.7689
Epoch  10/200 | Train: Loss=0.3229, F1 Score=0.9594 | Val: Loss=0.8548, F1 Score=0.8478
Epoch  11/200 | Train: Loss=0.2906, F1 Score=0.9721 | Val: Loss=1.0124, F1 Score=0.8744
Epoch  12/200 | Train: Loss=0.2617, F1 Score=0.9820 | Val: Loss=0.8950, F1 Score=0.8803
Epoch  13/200 | Train: Loss=0.2493, F1 Score=0.9883 | Val: Loss=0.8738, F1 Score=0.8971
Epoch  14/200 | Train: Loss=0.2347, F1 Score=0.9912 | Val: Loss=1.1069, F1 Score=0.8962
Epoch  15/200 | Train: Loss=0.2926, F1 Score=0.9680 | Val: Loss=1.1288, F1 Score=0.7898
Epoch  16/200 | Train: Loss=0.3071, F1 Score=0.9614 | Val: Loss=0.8628, F1 Score=0.8494
Epoch  17/200 | Train: Loss=0.2453, F1 Score=0.9807 | Val: Loss=0.9057, F1 Score=0.8808
Epoch  18/200 | Train: Loss=0.2609, F1 Score=0.9787 | Val: Loss=0.8960, F1 Score=0.8766
Epoch  19/200 | Train: Loss=0.2281, F1 Score=0.9864 | Val: Loss=0.8814, F1 Score=0.8781
Epoch  20/200 | Train: Loss=0.2289, F1 Score=0.9824 | Val: Loss=1.0446, F1 Score=0.8986
Epoch  21/200 | Train: Loss=0.2502, F1 Score=0.9779 | Val: Loss=0.9878, F1 Score=0.8835
Epoch  22/200 | Train: Loss=0.2302, F1 Score=0.9814 | Val: Loss=0.8080, F1 Score=0.8880
Epoch  23/200 | Train: Loss=0.2389, F1 Score=0.9734 | Val: Loss=0.8799, F1 Score=0.8976
Epoch  24/200 | Train: Loss=0.1988, F1 Score=0.9898 | Val: Loss=0.8682, F1 Score=0.8953
Epoch  25/200 | Train: Loss=0.1913, F1 Score=0.9914 | Val: Loss=0.8867, F1 Score=0.8929
Epoch  26/200 | Train: Loss=0.2071, F1 Score=0.9828 | Val: Loss=1.0320, F1 Score=0.8948
Epoch  27/200 | Train: Loss=0.2220, F1 Score=0.9818 | Val: Loss=0.7719, F1 Score=0.8978
Epoch  28/200 | Train: Loss=0.1907, F1 Score=0.9870 | Val: Loss=0.9340, F1 Score=0.9109
Epoch  29/200 | Train: Loss=0.1954, F1 Score=0.9841 | Val: Loss=1.0091, F1 Score=0.8847
Epoch  30/200 | Train: Loss=0.1960, F1 Score=0.9840 | Val: Loss=1.0140, F1 Score=0.8885
Epoch  31/200 | Train: Loss=0.1743, F1 Score=0.9910 | Val: Loss=0.8834, F1 Score=0.8898
Epoch  32/200 | Train: Loss=0.1772, F1 Score=0.9888 | Val: Loss=1.0623, F1 Score=0.8928
Epoch  33/200 | Train: Loss=0.1759, F1 Score=0.9884 | Val: Loss=1.3615, F1 Score=0.7877
Epoch  34/200 | Train: Loss=0.2136, F1 Score=0.9765 | Val: Loss=1.0615, F1 Score=0.8868
Epoch  35/200 | Train: Loss=0.2109, F1 Score=0.9774 | Val: Loss=1.0241, F1 Score=0.9015
Epoch  36/200 | Train: Loss=0.2015, F1 Score=0.9781 | Val: Loss=1.2679, F1 Score=0.7633
Epoch  37/200 | Train: Loss=0.1808, F1 Score=0.9793 | Val: Loss=0.8687, F1 Score=0.9018
Epoch  38/200 | Train: Loss=0.1580, F1 Score=0.9900 | Val: Loss=0.9156, F1 Score=0.9049
Epoch  39/200 | Train: Loss=0.1462, F1 Score=0.9941 | Val: Loss=1.0491, F1 Score=0.9056
Epoch  40/200 | Train: Loss=0.1416, F1 Score=0.9958 | Val: Loss=1.0326, F1 Score=0.9083
Epoch  41/200 | Train: Loss=0.1407, F1 Score=0.9965 | Val: Loss=0.9623, F1 Score=0.9075
Epoch  42/200 | Train: Loss=0.1388, F1 Score=0.9962 | Val: Loss=0.9691, F1 Score=0.9077
Epoch  43/200 | Train: Loss=0.1374, F1 Score=0.9962 | Val: Loss=1.0148, F1 Score=0.9072
Early stopping triggered after 43 epochs.
Best model restored from epoch 28 with val_f1 0.9109
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.9725, F1 Score=0.7532 | Val: Loss=1.0621, F1 Score=0.6973
Epoch   2/200 | Train: Loss=0.6643, F1 Score=0.8661 | Val: Loss=0.8159, F1 Score=0.8378
Epoch   3/200 | Train: Loss=0.4839, F1 Score=0.9142 | Val: Loss=0.6989, F1 Score=0.8374
Epoch   4/200 | Train: Loss=0.4019, F1 Score=0.9335 | Val: Loss=0.9509, F1 Score=0.8867
Epoch   5/200 | Train: Loss=0.3735, F1 Score=0.9441 | Val: Loss=1.2225, F1 Score=0.7871
Epoch   6/200 | Train: Loss=0.3536, F1 Score=0.9499 | Val: Loss=0.7939, F1 Score=0.8689
Epoch   7/200 | Train: Loss=0.3360, F1 Score=0.9540 | Val: Loss=1.2524, F1 Score=0.8131
Epoch   8/200 | Train: Loss=0.3460, F1 Score=0.9566 | Val: Loss=1.0248, F1 Score=0.8605
Epoch   9/200 | Train: Loss=0.3116, F1 Score=0.9581 | Val: Loss=0.9698, F1 Score=0.8987
Epoch  10/200 | Train: Loss=0.3170, F1 Score=0.9606 | Val: Loss=0.8410, F1 Score=0.8682
Epoch  11/200 | Train: Loss=0.3079, F1 Score=0.9637 | Val: Loss=0.8402, F1 Score=0.8756
Epoch  12/200 | Train: Loss=0.2946, F1 Score=0.9631 | Val: Loss=0.8123, F1 Score=0.8902
Epoch  13/200 | Train: Loss=0.2713, F1 Score=0.9717 | Val: Loss=0.8950, F1 Score=0.8878
Epoch  14/200 | Train: Loss=0.2678, F1 Score=0.9725 | Val: Loss=0.7922, F1 Score=0.8846
Epoch  15/200 | Train: Loss=0.2741, F1 Score=0.9683 | Val: Loss=1.1187, F1 Score=0.8809
Epoch  16/200 | Train: Loss=0.2834, F1 Score=0.9653 | Val: Loss=0.8225, F1 Score=0.9038
Epoch  17/200 | Train: Loss=0.2527, F1 Score=0.9769 | Val: Loss=1.0224, F1 Score=0.8928
Epoch  18/200 | Train: Loss=0.2556, F1 Score=0.9745 | Val: Loss=0.8719, F1 Score=0.8794
Epoch  19/200 | Train: Loss=0.2237, F1 Score=0.9826 | Val: Loss=1.1999, F1 Score=0.9134
Epoch  20/200 | Train: Loss=0.2229, F1 Score=0.9842 | Val: Loss=0.7469, F1 Score=0.9147
Epoch  21/200 | Train: Loss=0.2234, F1 Score=0.9840 | Val: Loss=0.9471, F1 Score=0.8989
Epoch  22/200 | Train: Loss=0.2585, F1 Score=0.9725 | Val: Loss=0.7571, F1 Score=0.9117
Epoch  23/200 | Train: Loss=0.2375, F1 Score=0.9805 | Val: Loss=1.0552, F1 Score=0.7797
Epoch  24/200 | Train: Loss=0.2547, F1 Score=0.9691 | Val: Loss=0.7563, F1 Score=0.8946
Epoch  25/200 | Train: Loss=0.1998, F1 Score=0.9867 | Val: Loss=0.9220, F1 Score=0.9069
Epoch  26/200 | Train: Loss=0.2168, F1 Score=0.9813 | Val: Loss=0.6839, F1 Score=0.9115
Epoch  27/200 | Train: Loss=0.2060, F1 Score=0.9816 | Val: Loss=0.8914, F1 Score=0.9130
Epoch  28/200 | Train: Loss=0.2121, F1 Score=0.9783 | Val: Loss=0.9432, F1 Score=0.9179
Epoch  29/200 | Train: Loss=0.2000, F1 Score=0.9838 | Val: Loss=0.8887, F1 Score=0.9106
Epoch  30/200 | Train: Loss=0.1925, F1 Score=0.9842 | Val: Loss=0.8831, F1 Score=0.9120
Epoch  31/200 | Train: Loss=0.1790, F1 Score=0.9891 | Val: Loss=0.8682, F1 Score=0.9069
Epoch  32/200 | Train: Loss=0.1634, F1 Score=0.9936 | Val: Loss=0.8883, F1 Score=0.9088
Epoch  33/200 | Train: Loss=0.1650, F1 Score=0.9923 | Val: Loss=1.0990, F1 Score=0.9086
Epoch  34/200 | Train: Loss=0.2077, F1 Score=0.9793 | Val: Loss=0.8285, F1 Score=0.8123
Epoch  35/200 | Train: Loss=0.1936, F1 Score=0.9781 | Val: Loss=0.7752, F1 Score=0.9181
Epoch  36/200 | Train: Loss=0.1813, F1 Score=0.9814 | Val: Loss=0.8325, F1 Score=0.8685
Epoch  37/200 | Train: Loss=0.1735, F1 Score=0.9836 | Val: Loss=1.0179, F1 Score=0.9210
Epoch  38/200 | Train: Loss=0.1589, F1 Score=0.9890 | Val: Loss=0.8638, F1 Score=0.8943
Epoch  39/200 | Train: Loss=0.1670, F1 Score=0.9847 | Val: Loss=1.0710, F1 Score=0.8683
Epoch  40/200 | Train: Loss=0.1507, F1 Score=0.9901 | Val: Loss=0.9323, F1 Score=0.9188
Epoch  41/200 | Train: Loss=0.1470, F1 Score=0.9914 | Val: Loss=1.0204, F1 Score=0.9069
Epoch  42/200 | Train: Loss=0.1522, F1 Score=0.9858 | Val: Loss=1.2021, F1 Score=0.9134
Epoch  43/200 | Train: Loss=0.1769, F1 Score=0.9789 | Val: Loss=1.0138, F1 Score=0.9153
Epoch  44/200 | Train: Loss=0.1382, F1 Score=0.9934 | Val: Loss=1.0048, F1 Score=0.8998
Epoch  45/200 | Train: Loss=0.1381, F1 Score=0.9908 | Val: Loss=1.2441, F1 Score=0.8902
Epoch  46/200 | Train: Loss=0.2166, F1 Score=0.9649 | Val: Loss=0.9479, F1 Score=0.9199
Epoch  47/200 | Train: Loss=0.1699, F1 Score=0.9801 | Val: Loss=1.0611, F1 Score=0.8866
Epoch  48/200 | Train: Loss=0.1472, F1 Score=0.9864 | Val: Loss=0.8340, F1 Score=0.9166
Epoch  49/200 | Train: Loss=0.1401, F1 Score=0.9848 | Val: Loss=0.9752, F1 Score=0.9060
Epoch  50/200 | Train: Loss=0.1279, F1 Score=0.9938 | Val: Loss=0.9955, F1 Score=0.9106
Epoch  51/200 | Train: Loss=0.1248, F1 Score=0.9959 | Val: Loss=1.0183, F1 Score=0.9134
Epoch  52/200 | Train: Loss=0.1241, F1 Score=0.9955 | Val: Loss=1.0579, F1 Score=0.9124
Early stopping triggered after 52 epochs.
Best model restored from epoch 37 with val_f1 0.9210

[I 2025-11-17 15:55:14,910] Trial 6 finished with value: 0.9237374292834479 and parameters: {'SEED': 2163, 'WINDOW': 40, 'STRIDE': 10, 'c1_filters': 32, 'c2_filters': 64, 'c3_filters': 128, 'cnn_dropout': 0.3334893561616289, 'hidden_size': 128, 'num_layers': 1, 'rnn_dropout': 0.2085534262702733, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.0007626032933332757, 'weight_decay': 6.081581496383507e-06, 'l1_lambda': 1.1924705740299222e-05, 'weight_max_norm': 5.154230717920252}. Best is trial 6 with value: 0.9237374292834479.

Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1611, F1 Score=0.5037 | Val: Loss=1.2662, F1 Score=0.0345
Epoch   2/200 | Train: Loss=1.0038, F1 Score=0.6161 | Val: Loss=0.9478, F1 Score=0.6313
Epoch   3/200 | Train: Loss=0.8037, F1 Score=0.7394 | Val: Loss=0.7722, F1 Score=0.7809
Epoch   4/200 | Train: Loss=0.6939, F1 Score=0.7718 | Val: Loss=0.7454, F1 Score=0.7723

[I 2025-11-17 15:55:20,213] Trial 7 pruned.

Epoch   5/200 | Train: Loss=0.6133, F1 Score=0.8007 | Val: Loss=0.7865, F1 Score=0.7397
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0350, F1 Score=0.6026 | Val: Loss=1.0767, F1 Score=0.6877
Epoch   2/200 | Train: Loss=0.8228, F1 Score=0.7419 | Val: Loss=0.8028, F1 Score=0.7757
Epoch   3/200 | Train: Loss=0.6636, F1 Score=0.8160 | Val: Loss=0.7752, F1 Score=0.8287
Epoch   4/200 | Train: Loss=0.5520, F1 Score=0.8411 | Val: Loss=0.7758, F1 Score=0.8073
Epoch   5/200 | Train: Loss=0.4798, F1 Score=0.8620 | Val: Loss=0.7812, F1 Score=0.8702
Epoch   6/200 | Train: Loss=0.4092, F1 Score=0.8761 | Val: Loss=0.7134, F1 Score=0.7950
Epoch   7/200 | Train: Loss=0.3776, F1 Score=0.8686 | Val: Loss=1.1420, F1 Score=0.6344
Epoch   8/200 | Train: Loss=0.3801, F1 Score=0.8711 | Val: Loss=1.0120, F1 Score=0.8403
Epoch   9/200 | Train: Loss=0.2967, F1 Score=0.8987 | Val: Loss=0.7278, F1 Score=0.8119
Epoch  10/200 | Train: Loss=0.2509, F1 Score=0.9084 | Val: Loss=0.7293, F1 Score=0.8817
Epoch  11/200 | Train: Loss=0.2364, F1 Score=0.9151 | Val: Loss=0.7154, F1 Score=0.8635

[I 2025-11-17 15:55:30,773] Trial 8 pruned.

Epoch  12/200 | Train: Loss=0.2629, F1 Score=0.8899 | Val: Loss=1.0173, F1 Score=0.6820
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0702, F1 Score=0.6334 | Val: Loss=1.1349, F1 Score=0.0345
Epoch   2/200 | Train: Loss=0.7303, F1 Score=0.7976 | Val: Loss=0.8703, F1 Score=0.6433
Epoch   3/200 | Train: Loss=0.4921, F1 Score=0.8665 | Val: Loss=0.5980, F1 Score=0.8482
Epoch   4/200 | Train: Loss=0.3832, F1 Score=0.8902 | Val: Loss=0.5808, F1 Score=0.8395
Epoch   5/200 | Train: Loss=0.3015, F1 Score=0.9136 | Val: Loss=0.4969, F1 Score=0.8664
Epoch   6/200 | Train: Loss=0.2444, F1 Score=0.9247 | Val: Loss=0.5141, F1 Score=0.8509
Epoch   7/200 | Train: Loss=0.2097, F1 Score=0.9348 | Val: Loss=0.4986, F1 Score=0.8542
Epoch   8/200 | Train: Loss=0.1834, F1 Score=0.9381 | Val: Loss=0.3973, F1 Score=0.9137
Epoch   9/200 | Train: Loss=0.1607, F1 Score=0.9466 | Val: Loss=0.4529, F1 Score=0.8898
Epoch  10/200 | Train: Loss=0.1416, F1 Score=0.9551 | Val: Loss=0.3870, F1 Score=0.9113
Epoch  11/200 | Train: Loss=0.1319, F1 Score=0.9576 | Val: Loss=0.4325, F1 Score=0.8956
Epoch  12/200 | Train: Loss=0.1239, F1 Score=0.9605 | Val: Loss=0.3803, F1 Score=0.9251
Epoch  13/200 | Train: Loss=0.1081, F1 Score=0.9677 | Val: Loss=0.4172, F1 Score=0.9068
Epoch  14/200 | Train: Loss=0.1060, F1 Score=0.9683 | Val: Loss=0.4057, F1 Score=0.8914
Epoch  15/200 | Train: Loss=0.0906, F1 Score=0.9740 | Val: Loss=0.4600, F1 Score=0.8777
Epoch  16/200 | Train: Loss=0.0907, F1 Score=0.9722 | Val: Loss=0.3774, F1 Score=0.9263
Epoch  17/200 | Train: Loss=0.0925, F1 Score=0.9709 | Val: Loss=0.3961, F1 Score=0.8984
Epoch  18/200 | Train: Loss=0.0872, F1 Score=0.9736 | Val: Loss=0.4595, F1 Score=0.9076
Epoch  19/200 | Train: Loss=0.0891, F1 Score=0.9712 | Val: Loss=0.3846, F1 Score=0.9164
Epoch  20/200 | Train: Loss=0.0699, F1 Score=0.9801 | Val: Loss=0.3761, F1 Score=0.9296
Epoch  21/200 | Train: Loss=0.0824, F1 Score=0.9747 | Val: Loss=0.4339, F1 Score=0.9095
Epoch  22/200 | Train: Loss=0.0693, F1 Score=0.9800 | Val: Loss=0.4296, F1 Score=0.9179
Epoch  23/200 | Train: Loss=0.0662, F1 Score=0.9790 | Val: Loss=0.3822, F1 Score=0.9287
Epoch  24/200 | Train: Loss=0.0645, F1 Score=0.9795 | Val: Loss=0.4202, F1 Score=0.9127
Epoch  25/200 | Train: Loss=0.0669, F1 Score=0.9803 | Val: Loss=0.4631, F1 Score=0.8884
Epoch  26/200 | Train: Loss=0.0629, F1 Score=0.9806 | Val: Loss=0.4216, F1 Score=0.9215
Epoch  27/200 | Train: Loss=0.0699, F1 Score=0.9776 | Val: Loss=0.4506, F1 Score=0.9220
Epoch  28/200 | Train: Loss=0.0611, F1 Score=0.9815 | Val: Loss=0.4506, F1 Score=0.9189
Epoch  29/200 | Train: Loss=0.0464, F1 Score=0.9891 | Val: Loss=0.4323, F1 Score=0.9230
Epoch  30/200 | Train: Loss=0.0604, F1 Score=0.9806 | Val: Loss=0.3964, F1 Score=0.9285
Epoch  31/200 | Train: Loss=0.0465, F1 Score=0.9885 | Val: Loss=0.4303, F1 Score=0.9254
Epoch  32/200 | Train: Loss=0.0455, F1 Score=0.9872 | Val: Loss=0.4213, F1 Score=0.9261
Epoch  33/200 | Train: Loss=0.0409, F1 Score=0.9910 | Val: Loss=0.4162, F1 Score=0.9273
Epoch  34/200 | Train: Loss=0.0383, F1 Score=0.9924 | Val: Loss=0.4105, F1 Score=0.9296
Epoch  35/200 | Train: Loss=0.0424, F1 Score=0.9893 | Val: Loss=0.4298, F1 Score=0.9276
Early stopping triggered after 35 epochs.
Best model restored from epoch 20 with val_f1 0.9296
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0643, F1 Score=0.4331 | Val: Loss=1.0854, F1 Score=0.6737
Epoch   2/200 | Train: Loss=0.6554, F1 Score=0.7935 | Val: Loss=0.5762, F1 Score=0.8442
Epoch   3/200 | Train: Loss=0.3898, F1 Score=0.8949 | Val: Loss=0.5707, F1 Score=0.8403
Epoch   4/200 | Train: Loss=0.2929, F1 Score=0.9271 | Val: Loss=0.4894, F1 Score=0.8872
Epoch   5/200 | Train: Loss=0.2461, F1 Score=0.9334 | Val: Loss=0.5680, F1 Score=0.8253
Epoch   6/200 | Train: Loss=0.1987, F1 Score=0.9488 | Val: Loss=0.5272, F1 Score=0.8557
Epoch   7/200 | Train: Loss=0.1684, F1 Score=0.9568 | Val: Loss=0.6255, F1 Score=0.8080
Epoch   8/200 | Train: Loss=0.1438, F1 Score=0.9608 | Val: Loss=0.4887, F1 Score=0.8803
Epoch   9/200 | Train: Loss=0.1414, F1 Score=0.9603 | Val: Loss=0.4924, F1 Score=0.8882
Epoch  10/200 | Train: Loss=0.1223, F1 Score=0.9640 | Val: Loss=0.5191, F1 Score=0.8742
Epoch  11/200 | Train: Loss=0.1080, F1 Score=0.9698 | Val: Loss=0.4963, F1 Score=0.9048
Epoch  12/200 | Train: Loss=0.0980, F1 Score=0.9726 | Val: Loss=0.5109, F1 Score=0.8926
Epoch  13/200 | Train: Loss=0.0946, F1 Score=0.9722 | Val: Loss=0.4836, F1 Score=0.8903
Epoch  14/200 | Train: Loss=0.0870, F1 Score=0.9744 | Val: Loss=0.5282, F1 Score=0.8889
Epoch  15/200 | Train: Loss=0.0771, F1 Score=0.9797 | Val: Loss=0.4942, F1 Score=0.8991
Epoch  16/200 | Train: Loss=0.0759, F1 Score=0.9780 | Val: Loss=0.4982, F1 Score=0.9089
Epoch  17/200 | Train: Loss=0.0859, F1 Score=0.9729 | Val: Loss=0.4721, F1 Score=0.9077
Epoch  18/200 | Train: Loss=0.0677, F1 Score=0.9806 | Val: Loss=0.5473, F1 Score=0.8912
Epoch  19/200 | Train: Loss=0.0717, F1 Score=0.9791 | Val: Loss=0.5043, F1 Score=0.9098
Epoch  20/200 | Train: Loss=0.0703, F1 Score=0.9805 | Val: Loss=0.5171, F1 Score=0.9139
Epoch  21/200 | Train: Loss=0.0622, F1 Score=0.9822 | Val: Loss=0.5493, F1 Score=0.8883
Epoch  22/200 | Train: Loss=0.0619, F1 Score=0.9823 | Val: Loss=0.5199, F1 Score=0.8948
Epoch  23/200 | Train: Loss=0.0678, F1 Score=0.9825 | Val: Loss=0.5091, F1 Score=0.9065
Epoch  24/200 | Train: Loss=0.0577, F1 Score=0.9840 | Val: Loss=0.5311, F1 Score=0.9088
Epoch  25/200 | Train: Loss=0.0537, F1 Score=0.9851 | Val: Loss=0.5646, F1 Score=0.8984
Epoch  26/200 | Train: Loss=0.0519, F1 Score=0.9851 | Val: Loss=0.5416, F1 Score=0.9105
Epoch  27/200 | Train: Loss=0.0482, F1 Score=0.9874 | Val: Loss=0.5360, F1 Score=0.9066
Epoch  28/200 | Train: Loss=0.0513, F1 Score=0.9853 | Val: Loss=0.5729, F1 Score=0.9073
Epoch  29/200 | Train: Loss=0.0434, F1 Score=0.9888 | Val: Loss=0.5708, F1 Score=0.8886
Epoch  30/200 | Train: Loss=0.0470, F1 Score=0.9847 | Val: Loss=0.5747, F1 Score=0.8941
Epoch  31/200 | Train: Loss=0.0501, F1 Score=0.9839 | Val: Loss=0.5634, F1 Score=0.9130
Epoch  32/200 | Train: Loss=0.0396, F1 Score=0.9910 | Val: Loss=0.5601, F1 Score=0.9088
Epoch  33/200 | Train: Loss=0.0375, F1 Score=0.9933 | Val: Loss=0.5674, F1 Score=0.9118
Epoch  34/200 | Train: Loss=0.0352, F1 Score=0.9935 | Val: Loss=0.5566, F1 Score=0.9084
Epoch  35/200 | Train: Loss=0.0354, F1 Score=0.9936 | Val: Loss=0.5434, F1 Score=0.9101
Early stopping triggered after 35 epochs.
Best model restored from epoch 20 with val_f1 0.9139
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0659, F1 Score=0.5724 | Val: Loss=1.0375, F1 Score=0.6737
Epoch   2/200 | Train: Loss=0.6655, F1 Score=0.8053 | Val: Loss=0.6411, F1 Score=0.7975
Epoch   3/200 | Train: Loss=0.4396, F1 Score=0.8793 | Val: Loss=0.5558, F1 Score=0.8253
Epoch   4/200 | Train: Loss=0.3436, F1 Score=0.9058 | Val: Loss=0.5056, F1 Score=0.8679
Epoch   5/200 | Train: Loss=0.2723, F1 Score=0.9211 | Val: Loss=0.4673, F1 Score=0.8671
Epoch   6/200 | Train: Loss=0.2268, F1 Score=0.9326 | Val: Loss=0.4511, F1 Score=0.8703
Epoch   7/200 | Train: Loss=0.1974, F1 Score=0.9408 | Val: Loss=0.5004, F1 Score=0.8586
Epoch   8/200 | Train: Loss=0.1735, F1 Score=0.9460 | Val: Loss=0.3914, F1 Score=0.8816
Epoch   9/200 | Train: Loss=0.1552, F1 Score=0.9476 | Val: Loss=0.4270, F1 Score=0.8687
Epoch  10/200 | Train: Loss=0.1437, F1 Score=0.9527 | Val: Loss=0.4041, F1 Score=0.8958
Epoch  11/200 | Train: Loss=0.1265, F1 Score=0.9567 | Val: Loss=0.4031, F1 Score=0.9044
Epoch  12/200 | Train: Loss=0.1185, F1 Score=0.9608 | Val: Loss=0.4039, F1 Score=0.8926
Epoch  13/200 | Train: Loss=0.1080, F1 Score=0.9646 | Val: Loss=0.4052, F1 Score=0.8974
Epoch  14/200 | Train: Loss=0.0991, F1 Score=0.9682 | Val: Loss=0.4026, F1 Score=0.8749
Epoch  15/200 | Train: Loss=0.0970, F1 Score=0.9665 | Val: Loss=0.4456, F1 Score=0.9021
Epoch  16/200 | Train: Loss=0.0932, F1 Score=0.9700 | Val: Loss=0.3741, F1 Score=0.9177
Epoch  17/200 | Train: Loss=0.0799, F1 Score=0.9726 | Val: Loss=0.4356, F1 Score=0.8993
Epoch  18/200 | Train: Loss=0.0810, F1 Score=0.9722 | Val: Loss=0.5023, F1 Score=0.8767
Epoch  19/200 | Train: Loss=0.0755, F1 Score=0.9746 | Val: Loss=0.3947, F1 Score=0.9261
Epoch  20/200 | Train: Loss=0.0825, F1 Score=0.9727 | Val: Loss=0.4925, F1 Score=0.8729
Epoch  21/200 | Train: Loss=0.0855, F1 Score=0.9706 | Val: Loss=0.4281, F1 Score=0.8901
Epoch  22/200 | Train: Loss=0.0661, F1 Score=0.9762 | Val: Loss=0.4034, F1 Score=0.9001
Epoch  23/200 | Train: Loss=0.0624, F1 Score=0.9799 | Val: Loss=0.4559, F1 Score=0.8963
Epoch  24/200 | Train: Loss=0.0616, F1 Score=0.9804 | Val: Loss=0.3984, F1 Score=0.8865
Epoch  25/200 | Train: Loss=0.0667, F1 Score=0.9792 | Val: Loss=0.3587, F1 Score=0.9121
Epoch  26/200 | Train: Loss=0.0688, F1 Score=0.9765 | Val: Loss=0.3936, F1 Score=0.9014
Epoch  27/200 | Train: Loss=0.0636, F1 Score=0.9806 | Val: Loss=0.4217, F1 Score=0.8998
Epoch  28/200 | Train: Loss=0.0538, F1 Score=0.9829 | Val: Loss=0.4193, F1 Score=0.9134
Epoch  29/200 | Train: Loss=0.0495, F1 Score=0.9859 | Val: Loss=0.3956, F1 Score=0.9263
Epoch  30/200 | Train: Loss=0.0461, F1 Score=0.9890 | Val: Loss=0.4662, F1 Score=0.9144
Epoch  31/200 | Train: Loss=0.0546, F1 Score=0.9804 | Val: Loss=0.5309, F1 Score=0.8773
Epoch  32/200 | Train: Loss=0.0586, F1 Score=0.9821 | Val: Loss=0.4258, F1 Score=0.8961
Epoch  33/200 | Train: Loss=0.0465, F1 Score=0.9870 | Val: Loss=0.4479, F1 Score=0.9177
Epoch  34/200 | Train: Loss=0.0487, F1 Score=0.9858 | Val: Loss=0.4353, F1 Score=0.9047
Epoch  35/200 | Train: Loss=0.0412, F1 Score=0.9885 | Val: Loss=0.4643, F1 Score=0.9155
Epoch  36/200 | Train: Loss=0.0475, F1 Score=0.9863 | Val: Loss=0.4242, F1 Score=0.9220
Epoch  37/200 | Train: Loss=0.0389, F1 Score=0.9905 | Val: Loss=0.4804, F1 Score=0.8953
Epoch  38/200 | Train: Loss=0.0440, F1 Score=0.9896 | Val: Loss=0.5444, F1 Score=0.8726
Epoch  39/200 | Train: Loss=0.0776, F1 Score=0.9737 | Val: Loss=0.4512, F1 Score=0.9254
Epoch  40/200 | Train: Loss=0.0440, F1 Score=0.9894 | Val: Loss=0.4624, F1 Score=0.9107
Epoch  41/200 | Train: Loss=0.0358, F1 Score=0.9925 | Val: Loss=0.4257, F1 Score=0.9165
Epoch  42/200 | Train: Loss=0.0333, F1 Score=0.9941 | Val: Loss=0.4350, F1 Score=0.9118
Epoch  43/200 | Train: Loss=0.0338, F1 Score=0.9934 | Val: Loss=0.4388, F1 Score=0.9125
Epoch  44/200 | Train: Loss=0.0309, F1 Score=0.9951 | Val: Loss=0.4418, F1 Score=0.9157
Early stopping triggered after 44 epochs.
Best model restored from epoch 29 with val_f1 0.9263

[I 2025-11-17 16:00:09,768] Trial 9 finished with value: 0.9232867345908543 and parameters: {'SEED': 8267, 'WINDOW': 40, 'STRIDE': 5, 'c1_filters': 32, 'c2_filters': 64, 'c3_filters': 128, 'cnn_dropout': 0.3639771981976235, 'hidden_size': 32, 'num_layers': 1, 'rnn_dropout': 0.6738530057833251, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 4.472055773267313e-05, 'weight_decay': 0.0004596001972722854, 'l1_lambda': 2.796270617139279e-06, 'weight_max_norm': 1.144192766321675}. Best is trial 6 with value: 0.9237374292834479.

Training 200 epochs...
Epoch   1/200 | Train: Loss=1.4319, F1 Score=0.6523 | Val: Loss=1.2833, F1 Score=0.0182
Epoch   2/200 | Train: Loss=1.0845, F1 Score=0.8073 | Val: Loss=0.6397, F1 Score=0.7685
Epoch   3/200 | Train: Loss=0.8787, F1 Score=0.8632 | Val: Loss=0.6216, F1 Score=0.8203
Epoch   4/200 | Train: Loss=0.7560, F1 Score=0.8989 | Val: Loss=0.6127, F1 Score=0.8468
Epoch   5/200 | Train: Loss=0.7073, F1 Score=0.9179 | Val: Loss=0.5541, F1 Score=0.8881
Epoch   6/200 | Train: Loss=0.6653, F1 Score=0.9285 | Val: Loss=0.5916, F1 Score=0.8981
Epoch   7/200 | Train: Loss=0.6572, F1 Score=0.9335 | Val: Loss=0.6115, F1 Score=0.9187
Epoch   8/200 | Train: Loss=0.6189, F1 Score=0.9515 | Val: Loss=0.7531, F1 Score=0.8947
Epoch   9/200 | Train: Loss=0.6088, F1 Score=0.9473 | Val: Loss=0.7668, F1 Score=0.8819
Epoch  10/200 | Train: Loss=0.6038, F1 Score=0.9538 | Val: Loss=0.6915, F1 Score=0.8913
Epoch  11/200 | Train: Loss=0.5800, F1 Score=0.9573 | Val: Loss=0.6727, F1 Score=0.8869
Epoch  12/200 | Train: Loss=0.5980, F1 Score=0.9493 | Val: Loss=0.7607, F1 Score=0.9255
Epoch  13/200 | Train: Loss=0.5497, F1 Score=0.9707 | Val: Loss=0.7175, F1 Score=0.9099
Epoch  14/200 | Train: Loss=0.5721, F1 Score=0.9566 | Val: Loss=0.7823, F1 Score=0.9113
Epoch  15/200 | Train: Loss=0.5631, F1 Score=0.9669 | Val: Loss=0.6819, F1 Score=0.8728
Epoch  16/200 | Train: Loss=0.5560, F1 Score=0.9625 | Val: Loss=0.8331, F1 Score=0.9037
Epoch  17/200 | Train: Loss=0.5264, F1 Score=0.9732 | Val: Loss=0.7853, F1 Score=0.9091
Epoch  18/200 | Train: Loss=0.5282, F1 Score=0.9698 | Val: Loss=0.7588, F1 Score=0.9118
Epoch  19/200 | Train: Loss=0.5143, F1 Score=0.9745 | Val: Loss=0.8136, F1 Score=0.9244
Epoch  20/200 | Train: Loss=0.5315, F1 Score=0.9694 | Val: Loss=0.9547, F1 Score=0.9037
Epoch  21/200 | Train: Loss=0.5093, F1 Score=0.9772 | Val: Loss=0.7417, F1 Score=0.9300
Epoch  22/200 | Train: Loss=0.5003, F1 Score=0.9782 | Val: Loss=0.8496, F1 Score=0.9154
Epoch  23/200 | Train: Loss=0.4971, F1 Score=0.9782 | Val: Loss=0.9222, F1 Score=0.8967
Epoch  24/200 | Train: Loss=0.5031, F1 Score=0.9747 | Val: Loss=0.8531, F1 Score=0.9090
Epoch  25/200 | Train: Loss=0.4858, F1 Score=0.9796 | Val: Loss=0.7823, F1 Score=0.9116
Epoch  26/200 | Train: Loss=0.4739, F1 Score=0.9818 | Val: Loss=0.7950, F1 Score=0.9320
Epoch  27/200 | Train: Loss=0.4875, F1 Score=0.9746 | Val: Loss=0.8584, F1 Score=0.9245
Epoch  28/200 | Train: Loss=0.4806, F1 Score=0.9779 | Val: Loss=0.9495, F1 Score=0.9164
Epoch  29/200 | Train: Loss=0.4768, F1 Score=0.9765 | Val: Loss=0.8556, F1 Score=0.9155
Epoch  30/200 | Train: Loss=0.4629, F1 Score=0.9829 | Val: Loss=0.8306, F1 Score=0.9351
Epoch  31/200 | Train: Loss=0.4631, F1 Score=0.9821 | Val: Loss=0.8706, F1 Score=0.9191
Epoch  32/200 | Train: Loss=0.4528, F1 Score=0.9842 | Val: Loss=0.7733, F1 Score=0.9281
Epoch  33/200 | Train: Loss=0.4383, F1 Score=0.9882 | Val: Loss=0.7776, F1 Score=0.9281
Epoch  34/200 | Train: Loss=0.5092, F1 Score=0.9621 | Val: Loss=0.8684, F1 Score=0.9269
Epoch  35/200 | Train: Loss=0.4639, F1 Score=0.9787 | Val: Loss=0.7146, F1 Score=0.9316
Epoch  36/200 | Train: Loss=0.4357, F1 Score=0.9829 | Val: Loss=0.7395, F1 Score=0.9362
Epoch  37/200 | Train: Loss=0.4258, F1 Score=0.9857 | Val: Loss=0.7065, F1 Score=0.9345
Epoch  38/200 | Train: Loss=0.4373, F1 Score=0.9814 | Val: Loss=0.8492, F1 Score=0.9374
Epoch  39/200 | Train: Loss=0.4299, F1 Score=0.9829 | Val: Loss=0.7203, F1 Score=0.9372
Epoch  40/200 | Train: Loss=0.4486, F1 Score=0.9750 | Val: Loss=0.7460, F1 Score=0.9373
Epoch  41/200 | Train: Loss=0.4175, F1 Score=0.9850 | Val: Loss=0.7365, F1 Score=0.9334
Epoch  42/200 | Train: Loss=0.4406, F1 Score=0.9795 | Val: Loss=0.7095, F1 Score=0.9286
Epoch  43/200 | Train: Loss=0.4103, F1 Score=0.9842 | Val: Loss=0.9181, F1 Score=0.9208
Epoch  44/200 | Train: Loss=0.4278, F1 Score=0.9732 | Val: Loss=0.7454, F1 Score=0.9311
Epoch  45/200 | Train: Loss=0.4081, F1 Score=0.9847 | Val: Loss=0.6882, F1 Score=0.9365
Epoch  46/200 | Train: Loss=0.3920, F1 Score=0.9886 | Val: Loss=0.7462, F1 Score=0.9426
Epoch  47/200 | Train: Loss=0.3844, F1 Score=0.9909 | Val: Loss=0.7841, F1 Score=0.9297
Epoch  48/200 | Train: Loss=0.3885, F1 Score=0.9881 | Val: Loss=0.8009, F1 Score=0.9334
Epoch  49/200 | Train: Loss=0.3842, F1 Score=0.9881 | Val: Loss=0.9987, F1 Score=0.9193
Epoch  50/200 | Train: Loss=0.3791, F1 Score=0.9857 | Val: Loss=0.8334, F1 Score=0.9439
Epoch  51/200 | Train: Loss=0.3729, F1 Score=0.9885 | Val: Loss=0.6961, F1 Score=0.9399
Epoch  52/200 | Train: Loss=0.3939, F1 Score=0.9819 | Val: Loss=0.8625, F1 Score=0.9058
Epoch  53/200 | Train: Loss=0.3849, F1 Score=0.9833 | Val: Loss=0.8592, F1 Score=0.9329
Epoch  54/200 | Train: Loss=0.3926, F1 Score=0.9817 | Val: Loss=0.7142, F1 Score=0.9339
Epoch  55/200 | Train: Loss=0.3636, F1 Score=0.9886 | Val: Loss=0.7690, F1 Score=0.9325
Epoch  56/200 | Train: Loss=0.3585, F1 Score=0.9882 | Val: Loss=0.8156, F1 Score=0.9354
Epoch  57/200 | Train: Loss=0.3531, F1 Score=0.9906 | Val: Loss=0.8212, F1 Score=0.9432
Epoch  58/200 | Train: Loss=0.3740, F1 Score=0.9823 | Val: Loss=0.8203, F1 Score=0.9209
Epoch  59/200 | Train: Loss=0.3695, F1 Score=0.9801 | Val: Loss=0.8454, F1 Score=0.9366
Epoch  60/200 | Train: Loss=0.3750, F1 Score=0.9779 | Val: Loss=0.7165, F1 Score=0.9257
Epoch  61/200 | Train: Loss=0.3660, F1 Score=0.9758 | Val: Loss=0.6874, F1 Score=0.9370
Epoch  62/200 | Train: Loss=0.3419, F1 Score=0.9901 | Val: Loss=0.7700, F1 Score=0.9383
Epoch  63/200 | Train: Loss=0.3354, F1 Score=0.9915 | Val: Loss=0.7424, F1 Score=0.9361
Epoch  64/200 | Train: Loss=0.3354, F1 Score=0.9931 | Val: Loss=0.7662, F1 Score=0.9367
Epoch  65/200 | Train: Loss=0.3342, F1 Score=0.9927 | Val: Loss=0.7832, F1 Score=0.9344
Early stopping triggered after 65 epochs.
Best model restored from epoch 50 with val_f1 0.9439
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.3684, F1 Score=0.7111 | Val: Loss=1.3171, F1 Score=0.6574
Epoch   2/200 | Train: Loss=1.0613, F1 Score=0.8255 | Val: Loss=0.5942, F1 Score=0.8469
Epoch   3/200 | Train: Loss=0.8823, F1 Score=0.8743 | Val: Loss=0.6654, F1 Score=0.8024
Epoch   4/200 | Train: Loss=0.7733, F1 Score=0.9145 | Val: Loss=0.6216, F1 Score=0.8275
Epoch   5/200 | Train: Loss=0.7158, F1 Score=0.9238 | Val: Loss=0.5648, F1 Score=0.8767
Epoch   6/200 | Train: Loss=0.6620, F1 Score=0.9460 | Val: Loss=0.6546, F1 Score=0.8967
Epoch   7/200 | Train: Loss=0.6568, F1 Score=0.9396 | Val: Loss=0.5737, F1 Score=0.8606
Epoch   8/200 | Train: Loss=0.6271, F1 Score=0.9451 | Val: Loss=0.6313, F1 Score=0.8947
Epoch   9/200 | Train: Loss=0.6057, F1 Score=0.9538 | Val: Loss=0.6521, F1 Score=0.9063
Epoch  10/200 | Train: Loss=0.5856, F1 Score=0.9615 | Val: Loss=0.6698, F1 Score=0.8978
Epoch  11/200 | Train: Loss=0.5706, F1 Score=0.9687 | Val: Loss=0.6122, F1 Score=0.9025
Epoch  12/200 | Train: Loss=0.5612, F1 Score=0.9667 | Val: Loss=0.6759, F1 Score=0.9160
Epoch  13/200 | Train: Loss=0.5496, F1 Score=0.9728 | Val: Loss=0.6892, F1 Score=0.9006
Epoch  14/200 | Train: Loss=0.5346, F1 Score=0.9754 | Val: Loss=0.7776, F1 Score=0.9004
Epoch  15/200 | Train: Loss=0.5473, F1 Score=0.9675 | Val: Loss=0.6717, F1 Score=0.8838
Epoch  16/200 | Train: Loss=0.5363, F1 Score=0.9740 | Val: Loss=0.6611, F1 Score=0.9074
Epoch  17/200 | Train: Loss=0.5228, F1 Score=0.9775 | Val: Loss=0.7383, F1 Score=0.9100
Epoch  18/200 | Train: Loss=0.5375, F1 Score=0.9771 | Val: Loss=0.7479, F1 Score=0.8868
Epoch  19/200 | Train: Loss=0.5172, F1 Score=0.9735 | Val: Loss=0.6864, F1 Score=0.8897
Epoch  20/200 | Train: Loss=0.5047, F1 Score=0.9769 | Val: Loss=0.7587, F1 Score=0.8992
Epoch  21/200 | Train: Loss=0.4928, F1 Score=0.9835 | Val: Loss=0.6892, F1 Score=0.9183
Epoch  22/200 | Train: Loss=0.4800, F1 Score=0.9855 | Val: Loss=0.7333, F1 Score=0.9120
Epoch  23/200 | Train: Loss=0.4754, F1 Score=0.9862 | Val: Loss=0.7263, F1 Score=0.9166
Epoch  24/200 | Train: Loss=0.4712, F1 Score=0.9841 | Val: Loss=0.7608, F1 Score=0.9111
Epoch  25/200 | Train: Loss=0.4797, F1 Score=0.9811 | Val: Loss=0.8632, F1 Score=0.9119
Epoch  26/200 | Train: Loss=0.4695, F1 Score=0.9816 | Val: Loss=0.7791, F1 Score=0.9032
Epoch  27/200 | Train: Loss=0.4563, F1 Score=0.9895 | Val: Loss=0.7852, F1 Score=0.9108
Epoch  28/200 | Train: Loss=0.4685, F1 Score=0.9830 | Val: Loss=0.8087, F1 Score=0.9022
Epoch  29/200 | Train: Loss=0.4760, F1 Score=0.9787 | Val: Loss=0.6847, F1 Score=0.9056
Epoch  30/200 | Train: Loss=0.4475, F1 Score=0.9854 | Val: Loss=0.7440, F1 Score=0.8997
Epoch  31/200 | Train: Loss=0.4356, F1 Score=0.9877 | Val: Loss=0.9247, F1 Score=0.8799
Epoch  32/200 | Train: Loss=0.4375, F1 Score=0.9836 | Val: Loss=0.7079, F1 Score=0.9109
Epoch  33/200 | Train: Loss=0.4193, F1 Score=0.9918 | Val: Loss=0.7804, F1 Score=0.9086
Epoch  34/200 | Train: Loss=0.4175, F1 Score=0.9927 | Val: Loss=0.7664, F1 Score=0.9151
Epoch  35/200 | Train: Loss=0.4169, F1 Score=0.9930 | Val: Loss=0.7330, F1 Score=0.9169
Epoch  36/200 | Train: Loss=0.4107, F1 Score=0.9943 | Val: Loss=0.7614, F1 Score=0.9193
Epoch  37/200 | Train: Loss=0.4100, F1 Score=0.9952 | Val: Loss=0.7192, F1 Score=0.9176
Epoch  38/200 | Train: Loss=0.4094, F1 Score=0.9949 | Val: Loss=0.7714, F1 Score=0.9166
Epoch  39/200 | Train: Loss=0.4115, F1 Score=0.9926 | Val: Loss=0.7269, F1 Score=0.9208
Epoch  40/200 | Train: Loss=0.4062, F1 Score=0.9951 | Val: Loss=0.7664, F1 Score=0.9211
Epoch  41/200 | Train: Loss=0.4060, F1 Score=0.9955 | Val: Loss=0.7880, F1 Score=0.9209
Epoch  42/200 | Train: Loss=0.4060, F1 Score=0.9955 | Val: Loss=0.7710, F1 Score=0.9208
Epoch  43/200 | Train: Loss=0.4035, F1 Score=0.9961 | Val: Loss=0.7737, F1 Score=0.9195
Epoch  44/200 | Train: Loss=0.4057, F1 Score=0.9946 | Val: Loss=0.7737, F1 Score=0.9188
Epoch  45/200 | Train: Loss=0.4037, F1 Score=0.9958 | Val: Loss=0.7885, F1 Score=0.9173
Epoch  46/200 | Train: Loss=0.4012, F1 Score=0.9962 | Val: Loss=0.8319, F1 Score=0.9189
Epoch  47/200 | Train: Loss=0.4025, F1 Score=0.9964 | Val: Loss=0.7717, F1 Score=0.9173
Epoch  48/200 | Train: Loss=0.3987, F1 Score=0.9958 | Val: Loss=0.8384, F1 Score=0.9140
Epoch  49/200 | Train: Loss=0.4006, F1 Score=0.9955 | Val: Loss=0.7721, F1 Score=0.9186
Epoch  50/200 | Train: Loss=0.3992, F1 Score=0.9942 | Val: Loss=0.8181, F1 Score=0.9166
Epoch  51/200 | Train: Loss=0.3973, F1 Score=0.9960 | Val: Loss=0.8194, F1 Score=0.9194
Epoch  52/200 | Train: Loss=0.3957, F1 Score=0.9971 | Val: Loss=0.8037, F1 Score=0.9200
Epoch  53/200 | Train: Loss=0.3949, F1 Score=0.9962 | Val: Loss=0.8236, F1 Score=0.9193
Epoch  54/200 | Train: Loss=0.3942, F1 Score=0.9965 | Val: Loss=0.8297, F1 Score=0.9190
Epoch  55/200 | Train: Loss=0.3957, F1 Score=0.9962 | Val: Loss=0.8092, F1 Score=0.9200
Early stopping triggered after 55 epochs.
Best model restored from epoch 40 with val_f1 0.9211
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.3700, F1 Score=0.7203 | Val: Loss=1.1748, F1 Score=0.2488
Epoch   2/200 | Train: Loss=1.0651, F1 Score=0.8228 | Val: Loss=0.6490, F1 Score=0.8329
Epoch   3/200 | Train: Loss=0.8895, F1 Score=0.8842 | Val: Loss=0.6669, F1 Score=0.8679
Epoch   4/200 | Train: Loss=0.7835, F1 Score=0.9015 | Val: Loss=0.6535, F1 Score=0.8887
Epoch   5/200 | Train: Loss=0.7191, F1 Score=0.9213 | Val: Loss=0.7050, F1 Score=0.8832
Epoch   6/200 | Train: Loss=0.6767, F1 Score=0.9254 | Val: Loss=0.7844, F1 Score=0.8842
Epoch   7/200 | Train: Loss=0.6442, F1 Score=0.9376 | Val: Loss=0.8042, F1 Score=0.8525
Epoch   8/200 | Train: Loss=0.6437, F1 Score=0.9383 | Val: Loss=0.8026, F1 Score=0.8805
Epoch   9/200 | Train: Loss=0.6081, F1 Score=0.9492 | Val: Loss=0.8247, F1 Score=0.8751
Epoch  10/200 | Train: Loss=0.6053, F1 Score=0.9529 | Val: Loss=0.9005, F1 Score=0.8650
Epoch  11/200 | Train: Loss=0.6177, F1 Score=0.9481 | Val: Loss=0.8775, F1 Score=0.8913
Epoch  12/200 | Train: Loss=0.5761, F1 Score=0.9590 | Val: Loss=0.7648, F1 Score=0.8807
Epoch  13/200 | Train: Loss=0.5582, F1 Score=0.9623 | Val: Loss=0.8225, F1 Score=0.8952
Epoch  14/200 | Train: Loss=0.5447, F1 Score=0.9694 | Val: Loss=0.9402, F1 Score=0.8786
Epoch  15/200 | Train: Loss=0.5389, F1 Score=0.9668 | Val: Loss=0.8254, F1 Score=0.8930
Epoch  16/200 | Train: Loss=0.5450, F1 Score=0.9700 | Val: Loss=0.9718, F1 Score=0.8929
Epoch  17/200 | Train: Loss=0.5296, F1 Score=0.9738 | Val: Loss=0.9345, F1 Score=0.8889
Epoch  18/200 | Train: Loss=0.5114, F1 Score=0.9748 | Val: Loss=0.8523, F1 Score=0.8863
Epoch  19/200 | Train: Loss=0.5381, F1 Score=0.9619 | Val: Loss=1.0479, F1 Score=0.8824
Epoch  20/200 | Train: Loss=0.5177, F1 Score=0.9699 | Val: Loss=0.7267, F1 Score=0.8895
Epoch  21/200 | Train: Loss=0.5073, F1 Score=0.9717 | Val: Loss=0.9026, F1 Score=0.9042
Epoch  22/200 | Train: Loss=0.5033, F1 Score=0.9732 | Val: Loss=0.9725, F1 Score=0.8900
Epoch  23/200 | Train: Loss=0.4809, F1 Score=0.9815 | Val: Loss=0.8229, F1 Score=0.8972
Epoch  24/200 | Train: Loss=0.4794, F1 Score=0.9800 | Val: Loss=0.8474, F1 Score=0.8995
Epoch  25/200 | Train: Loss=0.4686, F1 Score=0.9822 | Val: Loss=1.1172, F1 Score=0.8812
Epoch  26/200 | Train: Loss=0.4662, F1 Score=0.9830 | Val: Loss=0.9494, F1 Score=0.8954
Epoch  27/200 | Train: Loss=0.4529, F1 Score=0.9875 | Val: Loss=1.0848, F1 Score=0.8938
Epoch  28/200 | Train: Loss=0.4715, F1 Score=0.9735 | Val: Loss=0.9889, F1 Score=0.8775
Epoch  29/200 | Train: Loss=0.4687, F1 Score=0.9756 | Val: Loss=1.0492, F1 Score=0.8846
Epoch  30/200 | Train: Loss=0.4557, F1 Score=0.9814 | Val: Loss=1.0976, F1 Score=0.8869
Epoch  31/200 | Train: Loss=0.4462, F1 Score=0.9815 | Val: Loss=0.9892, F1 Score=0.8996
Epoch  32/200 | Train: Loss=0.4357, F1 Score=0.9831 | Val: Loss=1.0275, F1 Score=0.8971
Epoch  33/200 | Train: Loss=0.4258, F1 Score=0.9852 | Val: Loss=0.9686, F1 Score=0.8991
Epoch  34/200 | Train: Loss=0.4190, F1 Score=0.9897 | Val: Loss=0.9925, F1 Score=0.9012
Epoch  35/200 | Train: Loss=0.4137, F1 Score=0.9928 | Val: Loss=0.9860, F1 Score=0.8984
Epoch  36/200 | Train: Loss=0.4123, F1 Score=0.9925 | Val: Loss=0.9742, F1 Score=0.9034
Early stopping triggered after 36 epochs.
Best model restored from epoch 21 with val_f1 0.9042

[I 2025-11-17 16:05:45,654] Trial 10 finished with value: 0.9230837873566425 and parameters: {'SEED': 6128, 'WINDOW': 20, 'STRIDE': 10, 'c1_filters': 32, 'c2_filters': 64, 'c3_filters': 128, 'cnn_dropout': 0.10916701066140932, 'hidden_size': 128, 'num_layers': 2, 'rnn_dropout': 0.42755142451544814, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.00024846770273918975, 'weight_decay': 2.011758234099584e-05, 'l1_lambda': 1.1540252835242405e-05, 'weight_max_norm': 5.729567206562534}. Best is trial 6 with value: 0.9237374292834479.

Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0113, F1 Score=0.6433 | Val: Loss=1.0060, F1 Score=0.7401
Epoch   2/200 | Train: Loss=0.7523, F1 Score=0.7886 | Val: Loss=0.6559, F1 Score=0.8147
Epoch   3/200 | Train: Loss=0.5515, F1 Score=0.8427 | Val: Loss=0.6292, F1 Score=0.8126
Epoch   4/200 | Train: Loss=0.4503, F1 Score=0.8560 | Val: Loss=0.5896, F1 Score=0.8326
Epoch   5/200 | Train: Loss=0.3931, F1 Score=0.8706 | Val: Loss=0.6064, F1 Score=0.8705
Epoch   6/200 | Train: Loss=0.3326, F1 Score=0.8847 | Val: Loss=0.4820, F1 Score=0.8861
Epoch   7/200 | Train: Loss=0.2750, F1 Score=0.8999 | Val: Loss=0.6333, F1 Score=0.8080
Epoch   8/200 | Train: Loss=0.2271, F1 Score=0.9164 | Val: Loss=0.5674, F1 Score=0.8901
Epoch   9/200 | Train: Loss=0.2026, F1 Score=0.9250 | Val: Loss=0.7084, F1 Score=0.8776

[I 2025-11-17 16:06:01,421] Trial 11 pruned.

Epoch  10/200 | Train: Loss=0.1862, F1 Score=0.9220 | Val: Loss=0.6337, F1 Score=0.8648
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.8861, F1 Score=0.7124 | Val: Loss=1.0767, F1 Score=0.6751
Epoch   2/200 | Train: Loss=0.6907, F1 Score=0.8092 | Val: Loss=1.0173, F1 Score=0.6948
Epoch   3/200 | Train: Loss=0.5823, F1 Score=0.8321 | Val: Loss=1.1221, F1 Score=0.0136
Epoch   4/200 | Train: Loss=0.5446, F1 Score=0.8391 | Val: Loss=1.1114, F1 Score=0.1946

[I 2025-11-17 16:06:10,647] Trial 12 pruned.

Epoch   5/200 | Train: Loss=0.4911, F1 Score=0.8515 | Val: Loss=1.0056, F1 Score=0.7060
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1698, F1 Score=0.3879 | Val: Loss=1.0894, F1 Score=0.6772
Epoch   2/200 | Train: Loss=1.0580, F1 Score=0.5396 | Val: Loss=0.9636, F1 Score=0.6812
Epoch   3/200 | Train: Loss=0.9239, F1 Score=0.6519 | Val: Loss=0.8745, F1 Score=0.7309
Epoch   4/200 | Train: Loss=0.8616, F1 Score=0.7186 | Val: Loss=0.8006, F1 Score=0.7770

[I 2025-11-17 16:06:17,361] Trial 13 pruned.

Epoch   5/200 | Train: Loss=0.7914, F1 Score=0.7642 | Val: Loss=0.7523, F1 Score=0.7745
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0943, F1 Score=0.6485 | Val: Loss=1.0996, F1 Score=0.6751
Epoch   2/200 | Train: Loss=0.7627, F1 Score=0.7816 | Val: Loss=0.7478, F1 Score=0.6942
Epoch   3/200 | Train: Loss=0.5197, F1 Score=0.8582 | Val: Loss=0.6553, F1 Score=0.7870
Epoch   4/200 | Train: Loss=0.4329, F1 Score=0.8657 | Val: Loss=0.7852, F1 Score=0.6829

[I 2025-11-17 16:06:23,874] Trial 14 pruned.

Epoch   5/200 | Train: Loss=0.3637, F1 Score=0.8861 | Val: Loss=0.7759, F1 Score=0.8686
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0462, F1 Score=0.4891 | Val: Loss=0.9348, F1 Score=0.7714
Epoch   2/200 | Train: Loss=0.8392, F1 Score=0.7585 | Val: Loss=0.7432, F1 Score=0.7985
Epoch   3/200 | Train: Loss=0.6741, F1 Score=0.8266 | Val: Loss=0.6454, F1 Score=0.8226
Epoch   4/200 | Train: Loss=0.5840, F1 Score=0.8489 | Val: Loss=0.6030, F1 Score=0.8217

[I 2025-11-17 16:06:33,086] Trial 15 pruned.

Epoch   5/200 | Train: Loss=0.5103, F1 Score=0.8601 | Val: Loss=0.5602, F1 Score=0.8375
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1536, F1 Score=0.3636 | Val: Loss=1.1152, F1 Score=0.1921
Epoch   2/200 | Train: Loss=1.0235, F1 Score=0.5401 | Val: Loss=0.9317, F1 Score=0.6445
Epoch   3/200 | Train: Loss=0.8988, F1 Score=0.6629 | Val: Loss=0.7971, F1 Score=0.7427
Epoch   4/200 | Train: Loss=0.8012, F1 Score=0.7366 | Val: Loss=0.6980, F1 Score=0.7955

[I 2025-11-17 16:06:47,891] Trial 16 pruned.

Epoch   5/200 | Train: Loss=0.7251, F1 Score=0.7794 | Val: Loss=0.6664, F1 Score=0.7940
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.2032, F1 Score=0.6923 | Val: Loss=1.2357, F1 Score=0.6751
Epoch   2/200 | Train: Loss=0.7587, F1 Score=0.8154 | Val: Loss=0.6563, F1 Score=0.8310
Epoch   3/200 | Train: Loss=0.5655, F1 Score=0.8647 | Val: Loss=1.5695, F1 Score=0.4087
Epoch   4/200 | Train: Loss=0.4771, F1 Score=0.8903 | Val: Loss=0.9489, F1 Score=0.8511
Epoch   5/200 | Train: Loss=0.3921, F1 Score=0.9148 | Val: Loss=0.6513, F1 Score=0.8940
Epoch   6/200 | Train: Loss=0.4045, F1 Score=0.9145 | Val: Loss=0.7271, F1 Score=0.8858
Epoch   7/200 | Train: Loss=0.3373, F1 Score=0.9275 | Val: Loss=0.7004, F1 Score=0.9042
Epoch   8/200 | Train: Loss=0.3318, F1 Score=0.9269 | Val: Loss=1.1911, F1 Score=0.6530
Epoch   9/200 | Train: Loss=0.3261, F1 Score=0.9365 | Val: Loss=0.5870, F1 Score=0.9043
Epoch  10/200 | Train: Loss=0.3380, F1 Score=0.9207 | Val: Loss=0.6757, F1 Score=0.8727
Epoch  11/200 | Train: Loss=0.3152, F1 Score=0.9359 | Val: Loss=0.8715, F1 Score=0.7766

[I 2025-11-17 16:07:08,225] Trial 17 pruned.

Epoch  12/200 | Train: Loss=0.2940, F1 Score=0.9389 | Val: Loss=0.9090, F1 Score=0.8504
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1619, F1 Score=0.4510 | Val: Loss=1.0968, F1 Score=0.6751
Epoch   2/200 | Train: Loss=0.8962, F1 Score=0.6774 | Val: Loss=1.0576, F1 Score=0.5643
Epoch   3/200 | Train: Loss=0.6243, F1 Score=0.8290 | Val: Loss=0.6590, F1 Score=0.8406
Epoch   4/200 | Train: Loss=0.5063, F1 Score=0.8458 | Val: Loss=0.6197, F1 Score=0.8476

[I 2025-11-17 16:07:13,844] Trial 18 pruned.

Epoch   5/200 | Train: Loss=0.4199, F1 Score=0.8707 | Val: Loss=0.9409, F1 Score=0.5443
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0887, F1 Score=0.6781 | Val: Loss=1.0516, F1 Score=0.7610
Epoch   2/200 | Train: Loss=0.7772, F1 Score=0.7975 | Val: Loss=0.5448, F1 Score=0.8613
Epoch   3/200 | Train: Loss=0.5776, F1 Score=0.8454 | Val: Loss=0.7233, F1 Score=0.6999
Epoch   4/200 | Train: Loss=0.4745, F1 Score=0.8612 | Val: Loss=0.6272, F1 Score=0.7497

[I 2025-11-17 16:07:21,163] Trial 19 pruned.

Epoch   5/200 | Train: Loss=0.3775, F1 Score=0.8881 | Val: Loss=0.5702, F1 Score=0.7823
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0797, F1 Score=0.6577 | Val: Loss=1.1186, F1 Score=0.7267
Epoch   2/200 | Train: Loss=0.7604, F1 Score=0.8068 | Val: Loss=0.8984, F1 Score=0.7530
Epoch   3/200 | Train: Loss=0.5639, F1 Score=0.8480 | Val: Loss=0.8958, F1 Score=0.8045
Epoch   4/200 | Train: Loss=0.4674, F1 Score=0.8802 | Val: Loss=0.6721, F1 Score=0.8717
Epoch   5/200 | Train: Loss=0.3936, F1 Score=0.9034 | Val: Loss=0.8346, F1 Score=0.7737
Epoch   6/200 | Train: Loss=0.3981, F1 Score=0.8995 | Val: Loss=0.7042, F1 Score=0.8464
Epoch   7/200 | Train: Loss=0.3583, F1 Score=0.9193 | Val: Loss=1.4514, F1 Score=0.5578

[I 2025-11-17 16:07:32,069] Trial 20 pruned.

Epoch   8/200 | Train: Loss=0.3427, F1 Score=0.9180 | Val: Loss=0.8019, F1 Score=0.8430
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.3762, F1 Score=0.6822 | Val: Loss=1.6466, F1 Score=0.6819
Epoch   2/200 | Train: Loss=1.0556, F1 Score=0.8206 | Val: Loss=0.5592, F1 Score=0.7825
Epoch   3/200 | Train: Loss=0.8708, F1 Score=0.8675 | Val: Loss=0.4913, F1 Score=0.8774
Epoch   4/200 | Train: Loss=0.7744, F1 Score=0.9017 | Val: Loss=0.4614, F1 Score=0.8793
Epoch   5/200 | Train: Loss=0.7023, F1 Score=0.9201 | Val: Loss=0.4956, F1 Score=0.8890
Epoch   6/200 | Train: Loss=0.6787, F1 Score=0.9279 | Val: Loss=0.5050, F1 Score=0.8842
Epoch   7/200 | Train: Loss=0.6507, F1 Score=0.9341 | Val: Loss=0.5125, F1 Score=0.9055
Epoch   8/200 | Train: Loss=0.6138, F1 Score=0.9465 | Val: Loss=0.5501, F1 Score=0.9177
Epoch   9/200 | Train: Loss=0.6180, F1 Score=0.9389 | Val: Loss=0.5273, F1 Score=0.9160
Epoch  10/200 | Train: Loss=0.5946, F1 Score=0.9504 | Val: Loss=0.5640, F1 Score=0.9137
Epoch  11/200 | Train: Loss=0.5811, F1 Score=0.9517 | Val: Loss=0.6078, F1 Score=0.9150

[I 2025-11-17 16:07:58,663] Trial 21 pruned.

Epoch  12/200 | Train: Loss=0.5699, F1 Score=0.9589 | Val: Loss=0.6046, F1 Score=0.9087
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0356, F1 Score=0.7224 | Val: Loss=1.4689, F1 Score=0.0392
Epoch   2/200 | Train: Loss=0.7125, F1 Score=0.8310 | Val: Loss=0.7195, F1 Score=0.8085
Epoch   3/200 | Train: Loss=0.5226, F1 Score=0.8878 | Val: Loss=0.7963, F1 Score=0.7798
Epoch   4/200 | Train: Loss=0.4541, F1 Score=0.9071 | Val: Loss=0.7175, F1 Score=0.8611
Epoch   5/200 | Train: Loss=0.3814, F1 Score=0.9298 | Val: Loss=0.6012, F1 Score=0.9150
Epoch   6/200 | Train: Loss=0.4104, F1 Score=0.9176 | Val: Loss=0.8310, F1 Score=0.9070
Epoch   7/200 | Train: Loss=0.3460, F1 Score=0.9402 | Val: Loss=0.6885, F1 Score=0.9096
Epoch   8/200 | Train: Loss=0.3565, F1 Score=0.9360 | Val: Loss=0.5920, F1 Score=0.8970
Epoch   9/200 | Train: Loss=0.3321, F1 Score=0.9459 | Val: Loss=0.7701, F1 Score=0.8399
Epoch  10/200 | Train: Loss=0.3170, F1 Score=0.9523 | Val: Loss=0.8296, F1 Score=0.8854
Epoch  11/200 | Train: Loss=0.3345, F1 Score=0.9420 | Val: Loss=0.6341, F1 Score=0.9028

[I 2025-11-17 16:08:25,363] Trial 22 pruned.

Epoch  12/200 | Train: Loss=0.3155, F1 Score=0.9541 | Val: Loss=0.8115, F1 Score=0.8910
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.8000, F1 Score=0.6269 | Val: Loss=1.2489, F1 Score=0.0698
Epoch   2/200 | Train: Loss=1.4509, F1 Score=0.7985 | Val: Loss=0.7018, F1 Score=0.7299
Epoch   3/200 | Train: Loss=1.2718, F1 Score=0.8439 | Val: Loss=0.6322, F1 Score=0.8370
Epoch   4/200 | Train: Loss=1.1612, F1 Score=0.8595 | Val: Loss=0.6447, F1 Score=0.8750
Epoch   5/200 | Train: Loss=1.1090, F1 Score=0.8824 | Val: Loss=0.6807, F1 Score=0.8688
Epoch   6/200 | Train: Loss=1.0378, F1 Score=0.9066 | Val: Loss=0.7038, F1 Score=0.8719
Epoch   7/200 | Train: Loss=1.0086, F1 Score=0.9086 | Val: Loss=0.7023, F1 Score=0.8736

[I 2025-11-17 16:08:43,519] Trial 23 pruned.

Epoch   8/200 | Train: Loss=0.9558, F1 Score=0.9208 | Val: Loss=0.7826, F1 Score=0.8679
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0062, F1 Score=0.6017 | Val: Loss=1.3092, F1 Score=0.0172
Epoch   2/200 | Train: Loss=0.6873, F1 Score=0.7782 | Val: Loss=0.7289, F1 Score=0.7415
Epoch   3/200 | Train: Loss=0.4606, F1 Score=0.8423 | Val: Loss=0.8154, F1 Score=0.7802
Epoch   4/200 | Train: Loss=0.3595, F1 Score=0.8823 | Val: Loss=0.6043, F1 Score=0.8676

[I 2025-11-17 16:08:55,383] Trial 24 pruned.

Epoch   5/200 | Train: Loss=0.2940, F1 Score=0.8980 | Val: Loss=0.6870, F1 Score=0.8462
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.3206, F1 Score=0.5402 | Val: Loss=0.9843, F1 Score=0.6746
Epoch   2/200 | Train: Loss=1.1270, F1 Score=0.6744 | Val: Loss=0.7985, F1 Score=0.7699
Epoch   3/200 | Train: Loss=0.9814, F1 Score=0.7657 | Val: Loss=0.6908, F1 Score=0.8125
Epoch   4/200 | Train: Loss=0.8978, F1 Score=0.7997 | Val: Loss=0.6386, F1 Score=0.8154

[I 2025-11-17 16:09:12,034] Trial 25 pruned.

Epoch   5/200 | Train: Loss=0.8185, F1 Score=0.8206 | Val: Loss=0.5836, F1 Score=0.8289
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1623, F1 Score=0.7894 | Val: Loss=1.0981, F1 Score=0.7173
Epoch   2/200 | Train: Loss=0.7449, F1 Score=0.8649 | Val: Loss=1.0568, F1 Score=0.5992
Epoch   3/200 | Train: Loss=0.5492, F1 Score=0.8897 | Val: Loss=0.7447, F1 Score=0.7923
Epoch   4/200 | Train: Loss=0.4408, F1 Score=0.9069 | Val: Loss=0.8659, F1 Score=0.7910
Epoch   5/200 | Train: Loss=0.3976, F1 Score=0.9203 | Val: Loss=0.8584, F1 Score=0.8903
Epoch   6/200 | Train: Loss=0.3589, F1 Score=0.9243 | Val: Loss=0.9865, F1 Score=0.9039
Epoch   7/200 | Train: Loss=0.3291, F1 Score=0.9336 | Val: Loss=0.6507, F1 Score=0.8768
Epoch   8/200 | Train: Loss=0.3135, F1 Score=0.9330 | Val: Loss=0.6303, F1 Score=0.9154
Epoch   9/200 | Train: Loss=0.2739, F1 Score=0.9405 | Val: Loss=0.6737, F1 Score=0.9214
Epoch  10/200 | Train: Loss=0.2505, F1 Score=0.9530 | Val: Loss=1.0285, F1 Score=0.8378
Epoch  11/200 | Train: Loss=0.2689, F1 Score=0.9388 | Val: Loss=0.9199, F1 Score=0.8617
Epoch  12/200 | Train: Loss=0.2293, F1 Score=0.9503 | Val: Loss=1.1534, F1 Score=0.7322
Epoch  13/200 | Train: Loss=0.2498, F1 Score=0.9391 | Val: Loss=1.0380, F1 Score=0.8531
Epoch  14/200 | Train: Loss=0.2166, F1 Score=0.9572 | Val: Loss=0.9655, F1 Score=0.7699
Epoch  15/200 | Train: Loss=0.1958, F1 Score=0.9551 | Val: Loss=0.8155, F1 Score=0.8883
Epoch  16/200 | Train: Loss=0.1882, F1 Score=0.9626 | Val: Loss=0.7646, F1 Score=0.9180
Epoch  17/200 | Train: Loss=0.1870, F1 Score=0.9575 | Val: Loss=1.4199, F1 Score=0.7519
Epoch  18/200 | Train: Loss=0.1675, F1 Score=0.9615 | Val: Loss=1.0027, F1 Score=0.9154
Epoch  19/200 | Train: Loss=0.2113, F1 Score=0.9508 | Val: Loss=0.7646, F1 Score=0.9134
Epoch  20/200 | Train: Loss=0.1998, F1 Score=0.9514 | Val: Loss=0.8730, F1 Score=0.9074
Epoch  21/200 | Train: Loss=0.1336, F1 Score=0.9744 | Val: Loss=0.6290, F1 Score=0.9216
Epoch  22/200 | Train: Loss=0.1151, F1 Score=0.9847 | Val: Loss=0.6603, F1 Score=0.9163
Epoch  23/200 | Train: Loss=0.1140, F1 Score=0.9819 | Val: Loss=0.6704, F1 Score=0.9225
Epoch  24/200 | Train: Loss=0.1083, F1 Score=0.9854 | Val: Loss=0.6886, F1 Score=0.9261
Epoch  25/200 | Train: Loss=0.1077, F1 Score=0.9841 | Val: Loss=0.7024, F1 Score=0.9241

[I 2025-11-17 16:10:02,903] Trial 26 pruned.

Epoch  26/200 | Train: Loss=0.1026, F1 Score=0.9874 | Val: Loss=0.7122, F1 Score=0.9221
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0749, F1 Score=0.5902 | Val: Loss=1.0886, F1 Score=0.0756
Epoch   2/200 | Train: Loss=0.7629, F1 Score=0.7913 | Val: Loss=0.6681, F1 Score=0.8037
Epoch   3/200 | Train: Loss=0.5738, F1 Score=0.8448 | Val: Loss=0.6035, F1 Score=0.8179
Epoch   4/200 | Train: Loss=0.4663, F1 Score=0.8698 | Val: Loss=0.5384, F1 Score=0.8677

[I 2025-11-17 16:10:11,434] Trial 27 pruned.

Epoch   5/200 | Train: Loss=0.3982, F1 Score=0.8845 | Val: Loss=0.6040, F1 Score=0.8362
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.3418, F1 Score=0.5079 | Val: Loss=1.1781, F1 Score=0.0151
Epoch   2/200 | Train: Loss=1.0866, F1 Score=0.6907 | Val: Loss=0.6435, F1 Score=0.7806
Epoch   3/200 | Train: Loss=0.8702, F1 Score=0.7938 | Val: Loss=0.5832, F1 Score=0.7897
Epoch   4/200 | Train: Loss=0.7195, F1 Score=0.8352 | Val: Loss=0.4566, F1 Score=0.8792
Epoch   5/200 | Train: Loss=0.6365, F1 Score=0.8663 | Val: Loss=0.4787, F1 Score=0.8577
Epoch   6/200 | Train: Loss=0.5751, F1 Score=0.8867 | Val: Loss=0.4674, F1 Score=0.8784
Epoch   7/200 | Train: Loss=0.5114, F1 Score=0.9012 | Val: Loss=0.4765, F1 Score=0.8931
Epoch   8/200 | Train: Loss=0.4763, F1 Score=0.9106 | Val: Loss=0.5544, F1 Score=0.8644
Epoch   9/200 | Train: Loss=0.4354, F1 Score=0.9225 | Val: Loss=0.4641, F1 Score=0.9111
Epoch  10/200 | Train: Loss=0.4151, F1 Score=0.9272 | Val: Loss=0.5008, F1 Score=0.9019
Epoch  11/200 | Train: Loss=0.3951, F1 Score=0.9316 | Val: Loss=0.5377, F1 Score=0.9084

[I 2025-11-17 16:10:52,742] Trial 28 pruned.

Epoch  12/200 | Train: Loss=0.3728, F1 Score=0.9385 | Val: Loss=0.5158, F1 Score=0.9062
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.5921, F1 Score=0.8024 | Val: Loss=1.0257, F1 Score=0.5755
Epoch   2/200 | Train: Loss=0.3193, F1 Score=0.8817 | Val: Loss=0.7402, F1 Score=0.8275
Epoch   3/200 | Train: Loss=0.2200, F1 Score=0.9116 | Val: Loss=0.4780, F1 Score=0.9206
Epoch   4/200 | Train: Loss=0.1824, F1 Score=0.9221 | Val: Loss=0.5651, F1 Score=0.8598
Epoch   5/200 | Train: Loss=0.1692, F1 Score=0.9288 | Val: Loss=0.4946, F1 Score=0.8745
Epoch   6/200 | Train: Loss=0.1472, F1 Score=0.9386 | Val: Loss=0.5758, F1 Score=0.8761
Epoch   7/200 | Train: Loss=0.1434, F1 Score=0.9400 | Val: Loss=0.6059, F1 Score=0.8676
Epoch   8/200 | Train: Loss=0.1272, F1 Score=0.9430 | Val: Loss=0.6479, F1 Score=0.8776
Epoch   9/200 | Train: Loss=0.1086, F1 Score=0.9514 | Val: Loss=0.6648, F1 Score=0.9159
Epoch  10/200 | Train: Loss=0.1098, F1 Score=0.9576 | Val: Loss=0.5767, F1 Score=0.8914
Epoch  11/200 | Train: Loss=0.0931, F1 Score=0.9588 | Val: Loss=0.6615, F1 Score=0.8853
Epoch  12/200 | Train: Loss=0.1166, F1 Score=0.9558 | Val: Loss=0.6476, F1 Score=0.9062
Epoch  13/200 | Train: Loss=0.0980, F1 Score=0.9590 | Val: Loss=0.7282, F1 Score=0.8713
Epoch  14/200 | Train: Loss=0.1058, F1 Score=0.9591 | Val: Loss=0.8448, F1 Score=0.8607
Epoch  15/200 | Train: Loss=0.0948, F1 Score=0.9647 | Val: Loss=0.4962, F1 Score=0.9180
Epoch  16/200 | Train: Loss=0.0549, F1 Score=0.9733 | Val: Loss=0.5012, F1 Score=0.9245
Epoch  17/200 | Train: Loss=0.0511, F1 Score=0.9765 | Val: Loss=0.5451, F1 Score=0.9290
Epoch  18/200 | Train: Loss=0.0476, F1 Score=0.9815 | Val: Loss=0.5747, F1 Score=0.9232
Epoch  19/200 | Train: Loss=0.0416, F1 Score=0.9820 | Val: Loss=0.5598, F1 Score=0.9359
Epoch  20/200 | Train: Loss=0.0429, F1 Score=0.9853 | Val: Loss=0.5929, F1 Score=0.9314
Epoch  21/200 | Train: Loss=0.0404, F1 Score=0.9845 | Val: Loss=0.5897, F1 Score=0.9358
Epoch  22/200 | Train: Loss=0.0368, F1 Score=0.9873 | Val: Loss=0.6494, F1 Score=0.9291
Epoch  23/200 | Train: Loss=0.0398, F1 Score=0.9851 | Val: Loss=0.6309, F1 Score=0.9280
Epoch  24/200 | Train: Loss=0.0373, F1 Score=0.9859 | Val: Loss=0.6287, F1 Score=0.9384
Epoch  25/200 | Train: Loss=0.0362, F1 Score=0.9878 | Val: Loss=0.6514, F1 Score=0.9334
Epoch  26/200 | Train: Loss=0.0338, F1 Score=0.9876 | Val: Loss=0.6594, F1 Score=0.9354
Epoch  27/200 | Train: Loss=0.0348, F1 Score=0.9883 | Val: Loss=0.6523, F1 Score=0.9357
Epoch  28/200 | Train: Loss=0.0322, F1 Score=0.9887 | Val: Loss=0.6853, F1 Score=0.9334
Epoch  29/200 | Train: Loss=0.0294, F1 Score=0.9906 | Val: Loss=0.6906, F1 Score=0.9336
Epoch  30/200 | Train: Loss=0.0299, F1 Score=0.9907 | Val: Loss=0.6831, F1 Score=0.9339
Epoch  31/200 | Train: Loss=0.0317, F1 Score=0.9892 | Val: Loss=0.7064, F1 Score=0.9329
Epoch  32/200 | Train: Loss=0.0304, F1 Score=0.9905 | Val: Loss=0.7210, F1 Score=0.9292
Epoch  33/200 | Train: Loss=0.0288, F1 Score=0.9909 | Val: Loss=0.7068, F1 Score=0.9356
Epoch  34/200 | Train: Loss=0.0291, F1 Score=0.9914 | Val: Loss=0.6920, F1 Score=0.9378
Epoch  35/200 | Train: Loss=0.0262, F1 Score=0.9921 | Val: Loss=0.6795, F1 Score=0.9403
Epoch  36/200 | Train: Loss=0.0310, F1 Score=0.9911 | Val: Loss=0.6611, F1 Score=0.9373
Epoch  37/200 | Train: Loss=0.0290, F1 Score=0.9899 | Val: Loss=0.6717, F1 Score=0.9388
Epoch  38/200 | Train: Loss=0.0328, F1 Score=0.9903 | Val: Loss=0.7111, F1 Score=0.9358
Epoch  39/200 | Train: Loss=0.0264, F1 Score=0.9929 | Val: Loss=0.7028, F1 Score=0.9359
Epoch  40/200 | Train: Loss=0.0306, F1 Score=0.9897 | Val: Loss=0.7058, F1 Score=0.9325
Epoch  41/200 | Train: Loss=0.0266, F1 Score=0.9917 | Val: Loss=0.7441, F1 Score=0.9300
Epoch  42/200 | Train: Loss=0.0264, F1 Score=0.9923 | Val: Loss=0.7106, F1 Score=0.9354
Epoch  43/200 | Train: Loss=0.0270, F1 Score=0.9927 | Val: Loss=0.6704, F1 Score=0.9357
Epoch  44/200 | Train: Loss=0.0282, F1 Score=0.9917 | Val: Loss=0.7172, F1 Score=0.9339
Epoch  45/200 | Train: Loss=0.0223, F1 Score=0.9931 | Val: Loss=0.6970, F1 Score=0.9356
Epoch  46/200 | Train: Loss=0.0246, F1 Score=0.9930 | Val: Loss=0.7395, F1 Score=0.9322
Epoch  47/200 | Train: Loss=0.0238, F1 Score=0.9929 | Val: Loss=0.7365, F1 Score=0.9361
Epoch  48/200 | Train: Loss=0.0228, F1 Score=0.9934 | Val: Loss=0.7124, F1 Score=0.9362
Epoch  49/200 | Train: Loss=0.0241, F1 Score=0.9918 | Val: Loss=0.6955, F1 Score=0.9371
Epoch  50/200 | Train: Loss=0.0230, F1 Score=0.9932 | Val: Loss=0.7051, F1 Score=0.9373
Early stopping triggered after 50 epochs.
Best model restored from epoch 35 with val_f1 0.9403
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.5854, F1 Score=0.8135 | Val: Loss=1.2353, F1 Score=0.3412
Epoch   2/200 | Train: Loss=0.2929, F1 Score=0.8975 | Val: Loss=0.6953, F1 Score=0.8400
Epoch   3/200 | Train: Loss=0.2100, F1 Score=0.9330 | Val: Loss=0.9394, F1 Score=0.8310
Epoch   4/200 | Train: Loss=0.1863, F1 Score=0.9341 | Val: Loss=0.9795, F1 Score=0.7295
Epoch   5/200 | Train: Loss=0.1339, F1 Score=0.9533 | Val: Loss=0.5950, F1 Score=0.9004
Epoch   6/200 | Train: Loss=0.1157, F1 Score=0.9570 | Val: Loss=0.8185, F1 Score=0.8894
Epoch   7/200 | Train: Loss=0.1170, F1 Score=0.9568 | Val: Loss=0.8189, F1 Score=0.8226
Epoch   8/200 | Train: Loss=0.1002, F1 Score=0.9625 | Val: Loss=0.7095, F1 Score=0.9003
Epoch   9/200 | Train: Loss=0.0944, F1 Score=0.9708 | Val: Loss=0.8130, F1 Score=0.8029
Epoch  10/200 | Train: Loss=0.1016, F1 Score=0.9639 | Val: Loss=0.7698, F1 Score=0.8920
Epoch  11/200 | Train: Loss=0.0743, F1 Score=0.9719 | Val: Loss=0.9302, F1 Score=0.8481
Epoch  12/200 | Train: Loss=0.0844, F1 Score=0.9729 | Val: Loss=0.9654, F1 Score=0.8142
Epoch  13/200 | Train: Loss=0.0955, F1 Score=0.9655 | Val: Loss=0.8018, F1 Score=0.8923
Epoch  14/200 | Train: Loss=0.0738, F1 Score=0.9719 | Val: Loss=0.8562, F1 Score=0.8643
Epoch  15/200 | Train: Loss=0.0819, F1 Score=0.9731 | Val: Loss=0.7186, F1 Score=0.8984
Epoch  16/200 | Train: Loss=0.0937, F1 Score=0.9686 | Val: Loss=1.0885, F1 Score=0.8042
Epoch  17/200 | Train: Loss=0.0578, F1 Score=0.9784 | Val: Loss=0.6598, F1 Score=0.9158
Epoch  18/200 | Train: Loss=0.0426, F1 Score=0.9859 | Val: Loss=0.6490, F1 Score=0.9157
Epoch  19/200 | Train: Loss=0.0315, F1 Score=0.9898 | Val: Loss=0.6580, F1 Score=0.9180
Epoch  20/200 | Train: Loss=0.0303, F1 Score=0.9915 | Val: Loss=0.6754, F1 Score=0.9179

## Predict Public tests

In [ ]:
df_train_fold.head()

In [ ]:
def create_test_tta_windows(
    df,
    feature_cols,
    seq_length,
    stride,
    num_tta=3,
    noise_std=0.003
):
    """
    Create test windows + TTA augmentations.
    Compatible with build_sequences_with_ids output format.
    """

    all_sequences = []
    all_sample_ids = []

    for sample_id, group in df.groupby("sample_index"):
        X = group[feature_cols].values.astype(np.float32)
        total_steps = len(X)

        # standard slide across the sequence
        offsets = list(range(0, total_steps - seq_length + 1, stride))

        for offset in offsets:
            base_win = X[offset:offset + seq_length]

            # TTA 1 — original unchanged window
            all_sequences.append(base_win)
            all_sample_ids.append(sample_id)

            # TTA 2 — noisy versions
            for _ in range(num_tta):
                noise = np.random.normal(0, noise_std, base_win.shape).astype(np.float32)
                noisy_win = base_win + noise
                all_sequences.append(noisy_win)
                all_sample_ids.append(sample_id)

    return np.array(all_sequences, dtype=np.float32), np.array(all_sample_ids)


def collect_probabilities(model, data_loader, device, num_classes):
    model.eval()
    probs = []
    with torch.no_grad():
        for batch in data_loader:
            if isinstance(batch, (tuple, list)):
                inputs = batch[0]
            else:
                inputs = batch
            inputs = inputs.to(device)
            with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
                logits = model(inputs)
            probs.append(logits.softmax(dim=1).cpu().numpy())
    if not probs:
        return np.zeros((0, num_classes), dtype=np.float32)
    return np.concatenate(probs, axis=0)


def aggregate_probabilities(sample_ids, probs, num_classes):
    prob_cols = [f'prob_{i}' for i in range(num_classes)]
    df_probs = pd.DataFrame(probs, columns=prob_cols)
    df_probs['sample_index'] = sample_ids
    return df_probs.groupby('sample_index')[prob_cols].mean()


# --- Prepare final datasets ---
df_train_final = df_train_fold.copy()
df_val_final = df_val_fold.copy()
df_test_final = df_public_test.copy()

scaler_final = MinMaxScaler()
preProcess_with_2D_PE(df_train_final, scaler_final, fit_scaler=True)
preProcess_with_2D_PE(df_val_final, scaler_final, fit_scaler=False)
preProcess_with_2D_PE(df_test_final, scaler_final, fit_scaler=False)

final_feature_cols = [col for col in feature_cols if col in df_train_final.columns]
if not final_feature_cols:
    raise ValueError("No feature columns available for final training.")

df_train_final[final_feature_cols] = df_train_final[final_feature_cols].astype(np.float32)
df_val_final[final_feature_cols] = df_val_final[final_feature_cols].astype(np.float32)
df_test_final[final_feature_cols] = df_test_final[final_feature_cols].astype(np.float32)
df_train_final['label_encoded'] = df_train_final['label_encoded'].astype(np.int64)
df_val_final['label_encoded'] = df_val_final['label_encoded'].astype(np.int64)

window_final = study.best_params['WINDOW']
stride_final = study.best_params['STRIDE']


X_train_final, y_train_final, _ = build_sequences_with_ids(
    df_train_final, final_feature_cols, 'sample_index', window_final, stride_final, label_col='label_encoded'
)
X_val_final, y_val_final, val_sample_ids = build_sequences_with_ids(
    df_val_final, final_feature_cols, 'sample_index', window_final, stride_final, label_col='label_encoded'
)

X_test_final, test_sample_ids = create_test_tta_windows(
    df_test_final,
    final_feature_cols,
    window_final,
    stride_final,
    num_tta=3,
    noise_std=0.004
)


y_train_final = y_train_final.astype(np.int64)
y_val_final = y_val_final.astype(np.int64)

num_classes = 3
labels_in_train = np.unique(y_train_final)

class_weights_present = compute_class_weight('balanced', classes=labels_in_train, y=y_train_final)
weights_array = np.ones(num_classes, dtype=np.float32)
for label, weight in zip(labels_in_train, class_weights_present):
    weights_array[int(label)] = weight
weights_tensor = torch.tensor(weights_array, dtype=torch.float32, device=device)

train_ds_final = TensorDataset(torch.from_numpy(X_train_final), torch.from_numpy(y_train_final))
val_ds_final = TensorDataset(torch.from_numpy(X_val_final), torch.from_numpy(y_val_final))
test_ds_final = TensorDataset(torch.from_numpy(X_test_final))

train_loader_final = make_loader(train_ds_final, batch_size=BATCH_SIZE, shuffle=True, drop_last=False)
val_loader_final = make_loader(val_ds_final, batch_size=BATCH_SIZE, shuffle=False, drop_last=False)
test_loader_final = make_loader(test_ds_final, batch_size=BATCH_SIZE, shuffle=False, drop_last=False)

cnn_params = {
    'c1_filters': study.best_params['c1_filters'],
    'c2_filters': study.best_params['c2_filters'],
    'c3_filters': study.best_params['c3_filters'],
    'cnn_dropout': study.best_params['cnn_dropout']
}
rnn_params = {
    'hidden_size': study.best_params['hidden_size'],
    'num_layers': study.best_params['num_layers'],
    'rnn_dropout': study.best_params['rnn_dropout'],
    'bidirectional': study.best_params['bidirectional'],
    'rnn_type': study.best_params['rnn_type']
}

model_final = CSHN_HybridClassifier(
    cnn_params=cnn_params,
    rnn_params=rnn_params,
    num_raw_features=len(final_feature_cols),
    num_classes=num_classes
).to(device)
initialize_weights(model_final, init_scheme=study.best_params['init_scheme'])

criterion_final = nn.CrossEntropyLoss(weight=weights_tensor)
optimizer_final = torch.optim.AdamW(model_final.parameters(), lr=study.best_params['lr'], weight_decay=study.best_params['weight_decay'])
scheduler_final = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer_final, mode='max', factor=0.1, patience=10, min_lr=1e-7)
scaler_amp_final = torch.amp.GradScaler(enabled=(device.type == 'cuda'))

os.makedirs("models", exist_ok=True)
os.makedirs("submissions", exist_ok=True)

model_final, history_final, best_val_f1 = fit(
    model=model_final,
    train_loader=train_loader_final,
    val_loader=val_loader_final,
    epochs=EPOCHS,
    criterion=criterion_final,
    optimizer=optimizer_final,
    scaler=scaler_amp_final,
    device=device,
    l1_lambda=study.best_params['l1_lambda'],
    l2_lambda=0,
    patience=PATIENCE,
    evaluation_metric="val_f1",
    mode='max',
    restore_best_weights=True,
    scheduler=scheduler_final,
    weight_max_norm=study.best_params['weight_max_norm']
)
print(f"Best validation F1 (window level): {best_val_f1:.4f}")

val_probs = collect_probabilities(model_final, val_loader_final, device, num_classes)
if val_probs.shape[0] != len(val_sample_ids):
    raise ValueError("Mismatch between validation probabilities and sample indices.")
val_probs_agg = aggregate_probabilities(val_sample_ids, val_probs, num_classes)
val_sample_targets = df_val_final.groupby('sample_index')['label_encoded'].first().loc[val_probs_agg.index].values
val_preds = val_probs_agg.values.argmax(axis=1)
val_accuracy = accuracy_score(val_sample_targets, val_preds)
val_f1_macro = f1_score(val_sample_targets, val_preds, average='macro')
print(f"Validation (per sample) - Accuracy: {val_accuracy:.4f}, Macro F1: {val_f1_macro:.4f}")

trial_number = study.best_trial.number
model_path = f"models/optuna_trial_{trial_number}_final_model.pt"
torch.save({
    "model_state_dict": model_final.state_dict(),
    "hyperparameters": study.best_params,
    "feature_cols": final_feature_cols,
    "scaler": scaler_final,
    "window": window_final,
    "stride": stride_final,
}, model_path)
print("Saved model:", model_path)

test_probs = collect_probabilities(model_final, test_loader_final, device, num_classes)
if test_probs.shape[0] != len(test_sample_ids):
    raise ValueError("Mismatch between test probabilities and sample indices.")
test_probs_agg = aggregate_probabilities(test_sample_ids, test_probs, num_classes)
test_preds = test_probs_agg.values.argmax(axis=1)
inverse_label_map = {v: k for k, v in label_map.items()}

test_sample_index_values = test_probs_agg.index.to_numpy()
if np.issubdtype(test_sample_index_values.dtype, np.number):
    test_sample_index_values = test_sample_index_values.astype(int)

submission_df = pd.DataFrame({
    "sample_index": test_sample_index_values,
    "label": [inverse_label_map[int(label)] for label in test_preds]
}).sort_values("sample_index").reset_index(drop=True)

submission_path = f"submissions/optuna_trial_{trial_number}_submission.csv"
submission_df.to_csv(submission_path, index=False)
print("Saved submission:", submission_path)

print(submission_df.head())

In [ ]:
submission_df.head(50)