In [69]:
# Set seed for reproducibility
SEED = 16

# Import necessary libraries
import os

# Set environment variables before importing modules
os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['MPLCONFIGDIR'] = os.getcwd() + '/configs/'

# Suppress warnings
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=Warning)

# Import necessary modules
import logging
import random
import numpy as np

# Set seeds for random number generators in NumPy and Python
np.random.seed(SEED)
random.seed(SEED)

# Import PyTorch
import torch
torch.manual_seed(SEED)
from torch import nn
# from torchsummary import summary
from torch.utils.tensorboard import SummaryWriter
from torch.utils.data import TensorDataset, DataLoader
logs_dir = "tensorboard"
!pkill -f tensorboard
%load_ext tensorboard
!mkdir -p models

if torch.cuda.is_available():
    device = torch.device("cuda")
    torch.cuda.manual_seed_all(SEED)
    torch.backends.cudnn.benchmark = True
else:
    device = torch.device("cpu")

print(f"PyTorch version: {torch.__version__}")
print(f"Device: {device}")

# Import other libraries
import copy
import shutil
from itertools import product
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import optuna


# Configure plot display settings
sns.set(font_scale=1.4)
sns.set_style('white')
plt.rc('font', size=14)
%matplotlib inline

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
PyTorch version: 2.6.0+cu124
Device: cuda

In [15]:
# Uninstall any existing conflicting versions
!pip uninstall tensorboard -y
!pip uninstall tensorflow -y
!pip uninstall tensorflow-estimator -y

Found existing installation: tensorboard 2.20.0
Uninstalling tensorboard-2.20.0:
  Successfully uninstalled tensorboard-2.20.0
Found existing installation: tensorflow 2.20.0
Uninstalling tensorflow-2.20.0:
  Successfully uninstalled tensorflow-2.20.0
WARNING: Skipping tensorflow-estimator as it is not installed.

In [17]:
# Reinstall a recent, known good version of tensorboard and the necessary TensorFlow packages
!pip install tensorboard tensorflow

Collecting tensorboard
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow
  Using cached tensorflow-2.20.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (1.74.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (3.8.2)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorboard) (25.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from tensorboard) (11.3.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (6.33.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (75.2.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (3.1.3)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.5)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.12.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.10.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.10.0->tensorflow) (0.16.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (2025.3.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (2022.3.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (2.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Requirement already satisfied: onemkl-license==2025.3.0 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.12.0->tensorboard) (2025.3.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.12.0->tensorboard) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.12.0->tensorboard) (2022.3.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.12.0->tensorboard) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.12.0->tensorboard) (2024.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.19.2)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.12.0->tensorboard) (2024.2.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)
Using cached tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
Using cached tensorflow-2.20.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (620.6 MB)
Installing collected packages: tensorboard, tensorflow
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.1.2 requires gymnasium>=1.0.0, but you have gymnasium 0.29.0 which is incompatible.
tf-keras 2.18.0 requires tensorflow<2.19,>=2.18, but you have tensorflow 2.20.0 which is incompatible.
tensorflow-decision-forests 1.11.0 requires tensorflow==2.18.0, but you have tensorflow 2.20.0 which is incompatible.
tensorflow-text 2.18.1 requires tensorflow<2.19,>=2.18.0, but you have tensorflow 2.20.0 which is incompatible.
Successfully installed tensorboard-2.20.0 tensorflow-2.20.0

In [70]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/the-pirate-pain-dataset/sample_submission.csv
/kaggle/input/the-pirate-pain-dataset/pirate_pain_test.csv
/kaggle/input/the-pirate-pain-dataset/pirate_pain_train_labels.csv
/kaggle/input/the-pirate-pain-dataset/pirate_pain_train.csv

## ⏳ **Data Loading**

## 🔎 **Exploration and Data Analysis**

In [71]:
# Load the dataset from a CSV file
df_train = pd.read_csv("/kaggle/input/the-pirate-pain-dataset/pirate_pain_train.csv")
df_public_test = pd.read_csv("/kaggle/input/the-pirate-pain-dataset/pirate_pain_test.csv")
df_labels = pd.read_csv("/kaggle/input/the-pirate-pain-dataset/pirate_pain_train_labels.csv")

# Print the shape of the DataFrame
# print(f"DataFrame sh/kaggle/input/the-pirate-pain-dataset/sample_submission.csv

## 🔄 **Data Preprocessing**

In [72]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_labels['label_encoded'] = label_encoder.fit_transform(df_labels['label'])
# This gives: ['high_pain', 'low_pain', 'no_pain']
label_map = {'no_pain': 0, 'low_pain': 1, 'high_pain': 2}
df_labels['label_encoded'] = df_labels['label'].map(label_map)

In [73]:
from sklearn.preprocessing import MinMaxScaler
# Convert static cols
def preProcess(df):
    # Changed from .min(axis=1) to .median(axis=1)
    df["pain_survey"] = np.floor(df[["pain_survey_1", "pain_survey_2", "pain_survey_3", "pain_survey_4"]].median(axis=1)).astype(int) 
    df.drop(columns=['pain_survey_1', 'pain_survey_2', 'pain_survey_3', 'pain_survey_4'], inplace=True)
    
    df['merged_n_features'] = np.where(
        (df['n_legs'] == 'two') & (df['n_hands'] == 'two') & (df['n_eyes'] == 'two'),
        0, 
        1  
    )
    
    # Calculate the count of rows where n_legs, n_hands, or n_eyes are not 'two'
    explicit_different_count = df[
        (df['n_legs'] != 'two') | (df['n_hands'] != 'two') | (df['n_eyes'] != 'two')
    ].shape[0]
    
    df.drop(columns=['n_legs', 'n_hands', 'n_eyes', "joint_30"], inplace=True)
    
    columns_to_scale = [col for col in df.columns if col not in ['time', 'sample_index']]

    scaler = MinMaxScaler()
    df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

preProcess(df_train)
preProcess(df_public_test)

df_train.head()

,sample_index,time,joint_00,joint_01,joint_02,joint_03,joint_04,joint_05,joint_06,joint_07,...,joint_22,joint_23,joint_24,joint_25,joint_26,joint_27,joint_28,joint_29,pain_survey,merged_n_features
0,0,0,0.777507,0.738252,0.779512,0.804419,0.714916,0.736643,0.639301,0.733981,...,1.374706e-06,0.000015,3.162813e-04,0.000004,0.014214,0.011376,0.018978,0.020291,0.5,0.0
1,0,1,0.806256,0.765147,0.761153,0.838021,0.735684,0.729533,0.654605,0.760554,...,4.026521e-07,0.000022,9.828599e-07,0.000000,0.010748,0.000000,0.009473,0.010006,1.0,0.0
2,0,2,0.767592,0.721439,0.772834,0.777832,0.724497,0.734962,0.692340,0.787647,...,1.440847e-08,0.000005,6.626013e-05,0.000003,0.013097,0.006830,0.017065,0.016856,1.0,0.0
3,0,3,0.666220,0.810416,0.763971,0.785928,0.679928,0.722504,0.589127,0.793524,...,3.065580e-07,0.000007,1.199337e-06,0.000000,0.009505,0.006274,0.020264,0.017981,1.0,0.0
4,0,4,0.774297,0.773366,0.772162,0.767017,0.747710,0.743156,0.677764,0.725437,...,1.723863e-08,0.000006,1.307199e-06,0.000007,0.004216,0.002132,0.023389,0.018477,1.0,0.0

In [77]:
from sklearn.preprocessing import MinMaxScaler
# Scaling
scale_cols = [f'joint_{i:02d}' for i in range(30)] + ['pain_survey', 'merged_n_features']

scaler = MinMaxScaler()

# FIT the scaler ONLY on the training data
df_train[scale_cols] = scaler.fit_transform(df_train[scale_cols])

# TRANSFORM the test data with the same scaler
df_public_test[scale_cols] = scaler.transform(df_public_test[scale_cols])

In [78]:
from sklearn.model_selection import train_test_split
# STRATIFICATION
user_labels = df_labels.copy()

train_users, val_users = train_test_split(
    user_labels['sample_index'],
    test_size=0.2,  # 20% validation
    stratify=user_labels['label'], # This is the key for imbalance
    random_state=SEED
)

df_train_full = df_train.copy()

# Filter the full dataframe to get rows for train/val users
df_train_fold = df_train_full[df_train_full['sample_index'].isin(train_users)]
df_val_fold   = df_train_full[df_train_full['sample_index'].isin(val_users)]

# Merge labels back in
df_train_fold = df_train_fold.merge(user_labels[['sample_index', 'label', 'label_encoded']], on='sample_index', how='left')
df_val_fold   = df_val_fold.merge(user_labels[['sample_index', 'label', 'label_encoded']], on='sample_index', how='left')

# Check class distribution
print("--- Training Set Class Distribution ---")
print(df_train_fold['label'].value_counts(normalize=True))
print("\n--- Validation Set Class Distribution ---")
print(df_val_fold['label'].value_counts(normalize=True))

df_train_fold = df_train_fold.drop(columns=['label'])
df_val_fold = df_val_fold.drop(columns=['label'])
print(df_train_fold.head())

# X_train_final = df_train_fold.drop(columns=['label', 'label_encoded'])
# y_train_final = df_train_fold[['sample_index', 'label_encoded']]

# X_val_final = df_val_fold.drop(columns=['label', 'label_encoded'])
# y_val_final = df_val_fold[['sample_index', 'label_encoded']]

--- Training Set Class Distribution ---
label
no_pain      0.772727
low_pain     0.142045
high_pain    0.085227
Name: proportion, dtype: float64

--- Validation Set Class Distribution ---
label
no_pain      0.774436
low_pain     0.142857
high_pain    0.082707
Name: proportion, dtype: float64
   sample_index  time  joint_00  joint_01  joint_02  joint_03  joint_04  \
0             0     0  0.777507  0.738252  0.779512  0.804419  0.714916
1             0     1  0.806256  0.765147  0.761153  0.838021  0.735684
2             0     2  0.767592  0.721439  0.772834  0.777832  0.724497
3             0     3  0.666220  0.810416  0.763971  0.785928  0.679928
4             0     4  0.774297  0.773366  0.772162  0.767017  0.747710

   joint_05  joint_06  joint_07  ...  joint_23      joint_24  joint_25  \
0  0.736643  0.639301  0.733981  ...  0.000015  3.162813e-04  0.000004
1  0.729533  0.654605  0.760554  ...  0.000022  9.828599e-07  0.000000
2  0.734962  0.692340  0.787647  ...  0.000005  6.626013e-05  0.000003
3  0.722504  0.589127  0.793524  ...  0.000007  1.199337e-06  0.000000
4  0.743156  0.677764  0.725437  ...  0.000006  1.307199e-06  0.000007

   joint_26  joint_27  joint_28  joint_29  pain_survey  merged_n_features  \
0  0.014214  0.011376  0.018978  0.020291          0.5                0.0
1  0.010748  0.000000  0.009473  0.010006          1.0                0.0
2  0.013097  0.006830  0.017065  0.016856          1.0                0.0
3  0.009505  0.006274  0.020264  0.017981          1.0                0.0
4  0.004216  0.002132  0.023389  0.018477          1.0                0.0

   label_encoded
0              0
1              0
2              0
3              0
4              0

[5 rows x 35 columns]

In [79]:
# Convert all feature columns (X) to float32
# This includes the scaled dynamic cols and the static/numeric pirate features
df_train_fold = df_train_fold.astype('float32')
df_val_fold   = df_val_fold.astype('float32')

# Convert the target label column (y) to int64
# PyTorch's CrossEntropyLoss expects class labels as LongTensors (int64)
df_train_fold['label_encoded']  = df_train_fold['label_encoded'].astype('int64')
df_val_fold['label_encoded']   = df_val_fold['label_encoded'].astype('int64')


# --- Verify the changes ---
print("--- df_train_fold (Features) dtypes ---")
# .info() will show all columns are now float32
print(df_train_fold.info())

--- df_train_fold (Features) dtypes ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84480 entries, 0 to 84479
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sample_index       84480 non-null  float32
 1   time               84480 non-null  float32
 2   joint_00           84480 non-null  float32
 3   joint_01           84480 non-null  float32
 4   joint_02           84480 non-null  float32
 5   joint_03           84480 non-null  float32
 6   joint_04           84480 non-null  float32
 7   joint_05           84480 non-null  float32
 8   joint_06           84480 non-null  float32
 9   joint_07           84480 non-null  float32
 10  joint_08           84480 non-null  float32
 11  joint_09           84480 non-null  float32
 12  joint_10           84480 non-null  float32
 13  joint_11           84480 non-null  float32
 14  joint_12           84480 non-null  float32
 15  joint_13           84480 non-null  float32
 16  joint_14           84480 non-null  float32
 17  joint_15           84480 non-null  float32
 18  joint_16           84480 non-null  float32
 19  joint_17           84480 non-null  float32
 20  joint_18           84480 non-null  float32
 21  joint_19           84480 non-null  float32
 22  joint_20           84480 non-null  float32
 23  joint_21           84480 non-null  float32
 24  joint_22           84480 non-null  float32
 25  joint_23           84480 non-null  float32
 26  joint_24           84480 non-null  float32
 27  joint_25           84480 non-null  float32
 28  joint_26           84480 non-null  float32
 29  joint_27           84480 non-null  float32
 30  joint_28           84480 non-null  float32
 31  joint_29           84480 non-null  float32
 32  pain_survey        84480 non-null  float32
 33  merged_n_features  84480 non-null  float32
 34  label_encoded      84480 non-null  int64
dtypes: float32(34), int64(1)
memory usage: 11.6 MB
None

In [80]:
df_train_fold.head(-10)

,sample_index,time,joint_00,joint_01,joint_02,joint_03,joint_04,joint_05,joint_06,joint_07,...,joint_23,joint_24,joint_25,joint_26,joint_27,joint_28,joint_29,pain_survey,merged_n_features,label_encoded
0,0.0,0.0,0.777507,0.738252,0.779512,0.804419,0.714916,0.736643,0.639301,0.733981,...,1.458410e-05,3.162813e-04,0.000004,0.014214,0.011376,0.018978,0.020291,0.5,0.0,0
1,0.0,1.0,0.806256,0.765147,0.761153,0.838021,0.735684,0.729533,0.654604,0.760554,...,2.195013e-05,9.828599e-07,0.000000,0.010748,0.000000,0.009473,0.010006,1.0,0.0,0
2,0.0,2.0,0.767592,0.721439,0.772834,0.777832,0.724497,0.734962,0.692340,0.787647,...,5.272918e-06,6.626013e-05,0.000003,0.013097,0.006830,0.017065,0.016856,1.0,0.0,0
3,0.0,3.0,0.666220,0.810416,0.763971,0.785928,0.679928,0.722504,0.589127,0.793524,...,6.737126e-06,1.199337e-06,0.000000,0.009505,0.006274,0.020264,0.017981,1.0,0.0,0
4,0.0,4.0,0.774297,0.773366,0.772162,0.767017,0.747710,0.743156,0.677764,0.725437,...,5.661887e-06,1.307199e-06,0.000007,0.004216,0.002132,0.023389,0.018477,1.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84465,660.0,145.0,0.747113,0.633353,0.556208,0.526835,0.058241,0.129760,0.648898,0.600525,...,3.068689e-06,6.187494e-06,0.000002,0.057496,0.008263,0.121502,0.054748,1.0,0.0,0
84466,660.0,146.0,0.766650,0.730096,0.596908,0.583812,0.098994,0.119217,0.706742,0.624951,...,1.851797e-06,6.117617e-06,0.000001,0.042580,0.019101,0.195717,0.102979,1.0,0.0,0
84467,660.0,147.0,0.746536,0.704494,0.650648,0.585991,0.064944,0.182338,0.678559,0.596394,...,5.101990e-06,6.046634e-06,0.000001,0.036764,0.012704,0.125387,0.075700,1.0,0.0,0
84468,660.0,148.0,0.719192,0.599540,0.572594,0.605968,0.097262,0.170702,0.676817,0.604818,...,1.269752e-07,5.974558e-06,0.000008,0.015018,0.008760,0.137120,0.082437,1.0,0.0,0
84469,660.0,149.0,0.680471,0.659945,0.589452,0.596914,0.108154,0.159792,0.659558,0.559143,...,1.104031e-07,1.136757e-05,0.000001,0.012745,0.011485,0.067033,0.106066,0.5,0.0,0

## Prepare data for training

In [81]:
def make_loader(ds, batch_size, shuffle, drop_last):
    # Determine optimal number of worker processes for data loading
    cpu_cores = os.cpu_count() or 2
    num_workers = max(2, min(4, cpu_cores))

    # Create DataLoader with performance optimizations
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
        pin_memory=True,  # Faster GPU transfer
        pin_memory_device="cuda" if torch.cuda.is_available() else "",
        prefetch_factor=4,  # Load 4 batches ahead
    )

In [82]:
feature_cols = [col for col in df_train.columns if col not in ["sample_index", "time"]]

In [83]:
WINDOW = 40
STRIDE = 10

BATCH_SIZE = 64
num_features = len(feature_cols)

In [84]:
import numpy as np

def build_sequences(df, feature_cols, id_col='sample_index', label_col='label_encoded', window=200, stride=200):
    """
    Builds sequences from a time-series dataframe.
    
    Args:
        df (pd.DataFrame): The input DataFrame (e.g., df_train_fold) containing
                           features, IDs, and labels.
        feature_cols (list): A list of column names to be used as features.
        id_col (str): The name of the column for unique sample IDs.
        label_col (str): The name of the column for the labels.
        window (int): The size of each sequence (window).
        stride (int): The step size between sequences.
    """
    # Sanity check
    # assert window % stride == 0
    
    num_features = len(feature_cols)
    dataset = []
    labels = []

    # Iterate over unique sample IDs
    for sample_id in df[id_col].unique():
        
        # Get the dataframe for the current sample
        temp_df = df[df[id_col] == sample_id]

        # Extract feature data for the current ID
        temp_features = temp_df[feature_cols].values

        # Retrieve the single label for the current ID
        # (Assumes all rows for one ID have the same label)
        label = temp_df[label_col].values[0]

        # Calculate padding length to ensure full windows
        # This logic correctly handles cases where length is already a multiple
        padding_len = (window - len(temp_features) % window) % window
        
        if padding_len > 0:
            # Create zero padding and concatenate with the data
            padding = np.zeros((padding_len, num_features), dtype='float32')
            temp_features = np.concatenate((temp_features, padding))

        # Build feature windows and associate them with labels
        idx = 0
        while idx + window <= len(temp_features):
            dataset.append(temp_features[idx:idx + window])
            labels.append(label)
            idx += stride

    # Convert lists to numpy arrays for further processing
    dataset = np.array(dataset)
    labels = np.array(labels)

    return dataset, labels

In [85]:
# Generate sequences and labels for the training set
X_train, y_train = build_sequences(
    df_train_fold, 
    feature_cols=feature_cols, 
    id_col='sample_index',
    label_col='label_encoded',
    window=WINDOW, 
    stride=STRIDE
)

# Generate sequences and labels for the validation set
X_val, y_val = build_sequences(
    df_val_fold, 
    feature_cols=feature_cols,
    id_col='sample_index',
    label_col='label_encoded',
    window=WINDOW, 
    stride=STRIDE
)

# Print the shapes of the generated datasets and their labels
X_train.shape, y_train.shape, X_val.shape, y_val.shape

((6864, 40, 32), (6864,), (1729, 40, 32), (1729,))

In [86]:
# Define the input shape based on the training data
input_shape = X_train.shape[1:]

num_classes = 3

In [87]:
# Convert numpy arrays to PyTorch datasets (pairs features with labels)
train_ds = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
val_ds   = TensorDataset(torch.from_numpy(X_val), torch.from_numpy(y_val))

In [88]:
def make_loader(ds, batch_size, shuffle, drop_last):
    # Determine optimal number of worker processes for data loading
    cpu_cores = os.cpu_count() or 2
    num_workers = max(2, min(4, cpu_cores))

    # Create DataLoader with performance optimizations
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
        pin_memory=True,  # Faster GPU transfer
        pin_memory_device="cuda" if torch.cuda.is_available() else "",
        prefetch_factor=4,  # Load 4 batches ahead
    )

In [89]:
# Create data loaders with different settings for each phase
train_loader = make_loader(train_ds, batch_size=BATCH_SIZE, shuffle=True, drop_last=False)
val_loader   = make_loader(val_ds, batch_size=BATCH_SIZE, shuffle=False, drop_last=False)

In [91]:
import math
import torch
from torch.optim import Optimizer

class Ranger(Optimizer):
    def __init__(self, params, lr=1e-3, alpha=0.5, k=6, betas=(0.95, 0.999), eps=1e-5, weight_decay=0):
        """
        Ranger = RAdam + Lookahead
        Args:
            params: model parameters
            lr: learning rate
            alpha: lookahead step size (0.5 is default)
            k: lookahead steps before sync (6 is default)
            betas: RAdam betas
            eps: numerical stability
            weight_decay: L2 regularization
        """
        defaults = dict(lr=lr, alpha=alpha, k=k, betas=betas, eps=eps, weight_decay=weight_decay)
        super(Ranger, self).__init__(params, defaults)
        self._step = 0

        for group in self.param_groups:
            group["slow_params"] = [p.clone().detach() for p in group["params"] if p.requires_grad]

    def step(self, closure=None):
        loss = None
        if closure is not None:
            loss = closure()

        for group in self.param_groups:
            for p, sp in zip(group["params"], group["slow_params"]):
                if p.grad is None:
                    continue

                grad = p.grad.data
                if grad.is_sparse:
                    raise RuntimeError("Ranger does not support sparse gradients")

                state = self.state[p]

                # State initialization
                if len(state) == 0:
                    state["step"] = 0
                    state["exp_avg"] = torch.zeros_like(p.data)
                    state["exp_avg_sq"] = torch.zeros_like(p.data)

                exp_avg, exp_avg_sq = state["exp_avg"], state["exp_avg_sq"]
                beta1, beta2 = group["betas"]

                state["step"] += 1
                self._step += 1

                # Apply weight decay
                if group["weight_decay"] != 0:
                    grad = grad.add(p.data, alpha=group["weight_decay"])

                # Update exponential moving averages
                exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
                exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1 - beta2)

                # Compute rectified term (RAdam)
                bias_correction1 = 1 - beta1 ** state["step"]
                bias_correction2 = 1 - beta2 ** state["step"]
                n_sma_max = 2 / (1 - beta2) - 1
                n_sma = n_sma_max - 2 * state["step"] * (beta2 ** state["step"]) / bias_correction2

                if n_sma >= 5:
                    step_size = group["lr"] * math.sqrt(
                        ((1 - beta2 ** state["step"]) * (n_sma - 4) / (n_sma_max - 4)) *
                        ((n_sma - 2) / n_sma) * (n_sma_max / (n_sma_max - 2))
                    ) / bias_correction1
                    denom = exp_avg_sq.sqrt().add_(group["eps"])
                    p.data.addcdiv_(exp_avg, denom, value=-step_size)
                else:
                    step_size = group["lr"] / bias_correction1
                    p.data.add_(exp_avg, alpha=-step_size)

                # Lookahead updates
                if self._step % group["k"] == 0:
                    sp.add_(p.data - sp, alpha=group["alpha"])
                    p.data.copy_(sp)

        return loss

## 🛠️ **Model Building**

In [92]:
def recurrent_summary(model, input_size):
    """
    Custom summary function that emulates torchinfo's output while correctly
    counting parameters for RNN/GRU/LSTM layers.

    This function is designed for models whose direct children are
    nn.Linear, nn.RNN, nn.GRU, or nn.LSTM layers.

    Args:
        model (nn.Module): The model to analyze.
        input_size (tuple): Shape of the input tensor (e.g., (seq_len, features)).
    """

    # Dictionary to store output shapes captured by forward hooks
    output_shapes = {}
    # List to track hook handles for later removal
    hooks = []

    def get_hook(name):
        """Factory function to create a forward hook for a specific module."""
        def hook(module, input, output):
            # Handle RNN layer outputs (returns a tuple)
            if isinstance(output, tuple):
                # output[0]: all hidden states with shape (batch, seq_len, hidden*directions)
                shape1 = list(output[0].shape)
                shape1[0] = -1  # Replace batch dimension with -1

                # output[1]: final hidden state h_n (or tuple (h_n, c_n) for LSTM)
                if isinstance(output[1], tuple):  # LSTM case: (h_n, c_n)
                    shape2 = list(output[1][0].shape)  # Extract h_n only
                else:  # RNN/GRU case: h_n only
                    shape2 = list(output[1].shape)

                # Replace batch dimension (middle position) with -1
                shape2[1] = -1

                output_shapes[name] = f"[{shape1}, {shape2}]"

            # Handle standard layer outputs (e.g., Linear)
            else:
                shape = list(output.shape)
                shape[0] = -1  # Replace batch dimension with -1
                output_shapes[name] = f"{shape}"
        return hook

    # 1. Determine the device where model parameters reside
    try:
        device = next(model.parameters()).device
    except StopIteration:
        device = torch.device("cpu")  # Fallback for models without parameters

    # 2. Create a dummy input tensor with batch_size=1
    dummy_input = torch.randn(1, *input_size).to(device)

    # 3. Register forward hooks on target layers
    # Iterate through direct children of the model (e.g., self.rnn, self.classifier)
    for name, module in model.named_children():
        if isinstance(module, (nn.Linear, nn.RNN, nn.GRU, nn.LSTM)):
            # Register the hook and store its handle for cleanup
            hook_handle = module.register_forward_hook(get_hook(name))
            hooks.append(hook_handle)

    # 4. Execute a dummy forward pass in evaluation mode
    model.eval()
    with torch.no_grad():
        try:
            model(dummy_input)
        except Exception as e:
            print(f"Error during dummy forward pass: {e}")
            # Clean up hooks even if an error occurs
            for h in hooks:
                h.remove()
            return

    # 5. Remove all registered hooks
    for h in hooks:
        h.remove()

    # --- 6. Print the summary table ---

    print("-" * 79)
    # Column headers
    print(f"{'Layer (type)':<25} {'Output Shape':<28} {'Param #':<18}")
    print("=" * 79)

    total_params = 0
    total_trainable_params = 0

    # Iterate through modules again to collect and display parameter information
    for name, module in model.named_children():
        if name in output_shapes:
            # Count total and trainable parameters for this module
            module_params = sum(p.numel() for p in module.parameters())
            trainable_params = sum(p.numel() for p in module.parameters() if p.requires_grad)

            total_params += module_params
            total_trainable_params += trainable_params

            # Format strings for display
            layer_name = f"{name} ({type(module).__name__})"
            output_shape_str = str(output_shapes[name])
            params_str = f"{trainable_params:,}"

            print(f"{layer_name:<25} {output_shape_str:<28} {params_str:<15}")

    print("=" * 79)
    print(f"Total params: {total_params:,}")
    print(f"Trainable params: {total_trainable_params:,}")
    print(f"Non-trainable params: {total_params - total_trainable_params:,}")
    print("-" * 79)

In [93]:
class RecurrentClassifier(nn.Module):
    """
    Generic RNN classifier (RNN, LSTM, GRU).
    Uses the last hidden state for classification.
    """
    def __init__(
            self,
            input_size,
            hidden_size,
            num_layers,
            num_classes,
            rnn_type='GRU',        # 'RNN', 'LSTM', or 'GRU'
            bidirectional=False,
            dropout_rate=0.2
            ):
        super().__init__()

        self.rnn_type = rnn_type
        self.num_layers = num_layers
        self.hidden_size = hidden_size
        self.bidirectional = bidirectional

        # Map string name to PyTorch RNN class
        rnn_map = {
            'RNN': nn.RNN,
            'LSTM': nn.LSTM,
            'GRU': nn.GRU
        }

        if rnn_type not in rnn_map:
            raise ValueError("rnn_type must be 'RNN', 'LSTM', or 'GRU'")

        rnn_module = rnn_map[rnn_type]

        # Dropout is only applied between layers (if num_layers > 1)
        dropout_val = dropout_rate if num_layers > 1 else 0

        # Create the recurrent layer
        self.rnn = rnn_module(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,       # Input shape: (batch, seq_len, features)
            bidirectional=bidirectional,
            dropout=dropout_val
        )

        # Calculate input size for the final classifier
        if self.bidirectional:
            classifier_input_size = hidden_size * 2 # Concat fwd + bwd
        else:
            classifier_input_size = hidden_size

        # Final classification layer
        self.classifier = nn.Linear(classifier_input_size, num_classes)

    def forward(self, x):
        """
        x shape: (batch_size, seq_length, input_size)
        """

        # rnn_out shape: (batch_size, seq_len, hidden_size * num_directions)
        rnn_out, hidden = self.rnn(x)

        # LSTM returns (h_n, c_n), we only need h_n
        if self.rnn_type == 'LSTM':
            hidden = hidden[0]

        # hidden shape: (num_layers * num_directions, batch_size, hidden_size)

        if self.bidirectional:
            # Reshape to (num_layers, 2, batch_size, hidden_size)
            hidden = hidden.view(self.num_layers, 2, -1, self.hidden_size)

            # Concat last fwd (hidden[-1, 0, ...]) and bwd (hidden[-1, 1, ...])
            # Final shape: (batch_size, hidden_size * 2)
            hidden_to_classify = torch.cat([hidden[-1, 0, :, :], hidden[-1, 1, :, :]], dim=1)
        else:
            # Take the last layer's hidden state
            # Final shape: (batch_size, hidden_size)
            hidden_to_classify = hidden[-1]

        # Get logits
        logits = self.classifier(hidden_to_classify)
        return logits

In [94]:
def initialize_weights(model, init_scheme='xavier_uniform'):
    """Initializes weights using the specified scheme."""
    for name, param in model.named_parameters():
        if 'weight_ih' in name or 'weight_hh' in name:
            # Recurrent weights
            if init_scheme == 'xavier_uniform':
                torch.nn.init.xavier_uniform_(param.data)
            elif init_scheme == 'orthogonal':
                # Often preferred for RNNs to maintain gradient scale
                torch.nn.init.orthogonal_(param.data)
        elif 'weight' in name:
            # Linear or Convolutional weights (e.g., in the final layer)
            if init_scheme == 'xavier_uniform':
                torch.nn.init.xavier_uniform_(param.data)
            elif init_scheme == 'kaiming_normal':
                 # Good for ReLU/Leaky ReLU (common in surrounding layers)
                torch.nn.init.kaiming_normal_(param.data, mode='fan_in', nonlinearity='relu')
        elif 'bias' in name:
            # Set biases to zero, which is common
            torch.nn.init.constant_(param.data, 0)
            
            # Optional: initialize forget gate bias to a positive value (e.g., 1.0 or 2.0)
            if 'bias_hh' in name and 'LSTM' in name: 
                 n = param.shape[0]
                 start, end = n // 4, n // 2
                 param.data[start:end].fill_(1.0) # For LSTM forget gate bias

In [95]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class FocalLoss(nn.Module):
    """
    Focal Loss for multi-class classification.
    Reference: https://arxiv.org/abs/1708.02002 (Lin et al. 2017)

    Args:
        alpha (float or list): Weighting factor for classes (balances class imbalance)
        gamma (float): Focusing parameter to reduce the loss for well-classified examples
        reduction (str): 'none' | 'mean' | 'sum'
    """
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        super(FocalLoss, self).__init__()
        if isinstance(alpha, (float, int)):
            self.alpha = torch.tensor([alpha])
        else:
            self.alpha = torch.tensor(alpha) if alpha is not None else None
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        """
        Args:
            inputs: Predictions (logits), shape [batch_size, num_classes]
            targets: Ground truth labels, shape [batch_size]
        """
        # Compute log-probabilities
        log_probs = F.log_softmax(inputs, dim=1)
        probs = torch.exp(log_probs)

        # Select log-probability of the correct class
        log_probs_true = log_probs.gather(1, targets.unsqueeze(1)).squeeze(1)
        probs_true = probs.gather(1, targets.unsqueeze(1)).squeeze(1)

        # Compute focal weight
        focal_weight = (1 - probs_true) ** self.gamma

        # Apply alpha (class weight)
        if self.alpha is not None:
            if self.alpha.device != inputs.device:
                self.alpha = self.alpha.to(inputs.device)
            alpha_factor = self.alpha[targets]
            focal_weight = alpha_factor * focal_weight

        # Compute final loss
        loss = -focal_weight * log_probs_true

        if self.reduction == 'mean':
            return loss.mean()
        elif self.reduction == 'sum':
            return loss.sum()
        else:
            return loss

## 🧮 **Network and Training Hyperparameters**

In [96]:
from sklearn.utils.class_weight import compute_class_weight

# --- Calculate Class Weights ---
labels = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=labels,
    y=y_train
)

weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)

print(f"Original label counts: {np.bincount(y_train)}")
print(f"Calculated weights: {weights_tensor}")

Original label counts: [5304  975  585]
Calculated weights: tensor([0.4314, 2.3467, 3.9111], device='cuda:0')

In [56]:
# # Training configuration
# RNN_TYPE = 'GRU'
# BIDIRECTIONAL = True

# LEARNING_RATE = 1e-4
# EPOCHS = 100
# PATIENCE = 30

# # Architecture
# HIDDEN_LAYERS = 2        # Hidden layers
# HIDDEN_SIZE = 128        # Neurons per layer

# # Regularisation
# DROPOUT_RATE = 0.4         # Dropout probability
# L1_LAMBDA = 0            # L1 penalty
# L2_LAMBDA = 1e-4            # L2 penalty

# # Set up loss function and optimizer
# criterion = nn.CrossEntropyLoss(weight=weights_tensor, label_smoothing=0.1)

In [101]:
# Assuming necessary imports (torch, optuna, FocalLoss, RecurrentClassifier, initialize_weights, 
# build_sequences, make_loader, TensorDataset, etc.) and global variables (BATCH_SIZE, 
# df_train_fold, df_val_fold, feature_cols, weights_tensor, input_shape, num_classes, device)
# are defined elsewhere in your Kaggle notebook.

# --- 1. Define Global Training Constants ---
EPOCHS = 200
PATIENCE = 15 # Used as the maximum patience for Early Stopping, 
              # but now we will tune a separate patience for the LR scheduler.

# --- 2. Define the Optuna Objective Function ---
def objective(trial):
    
    # --- 1. Tune Window and Stride (Data Generation) ---
    # Expanded range for better exploration
    window_hp = trial.suggest_categorical("WINDOW", [20, 40])
    stride_hp = trial.suggest_categorical("STRIDE", [10, 15, 20, 30])

    # Prune if stride is larger than the window
    if stride_hp >= window_hp:
        raise optuna.exceptions.TrialPruned()

    # --- 2. Build Dynamic Datasets and Loaders ---
    # Generate sequences for this trial
    X_train, y_train = build_sequences(
        df_train_fold, 
        feature_cols=feature_cols, 
        id_col='sample_index',
        label_col='label_encoded',
        window=window_hp, 
        stride=stride_hp
    )
    X_val, y_val = build_sequences(
        df_val_fold, 
        feature_cols=feature_cols,
        id_col='sample_index',
        label_col='label_encoded',
        window=window_hp, 
        stride=stride_hp
    )

    # Create TensorDatasets for this trial
    train_ds = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
    val_ds   = TensorDataset(torch.from_numpy(X_val), torch.from_numpy(y_val))

    # Create DataLoaders for this trial
    train_loader = make_loader(train_ds, batch_size=BATCH_SIZE, shuffle=True, drop_last=False)
    val_loader   = make_loader(val_ds, batch_size=BATCH_SIZE, shuffle=False, drop_last=False)
    
    # --- 3. Suggest Other Hyperparameters ---
    
    hidden_size_hp = trial.suggest_categorical("hidden_size", [32, 64, 128]) # Reduced range
    num_layers_hp = trial.suggest_int("num_layers", 1, 3)
    dropout_hp = trial.suggest_float("dropout_rate", 0.1, 0.7) # Increased max
    rnn_type_hp = trial.suggest_categorical("rnn_type", ["GRU"])
    bidirectional_hp = trial.suggest_categorical("bidirectional", [True, False])
    
    # Initialization (SYNTAX FIX: Removed the extra closing parenthesis)
    init_scheme_hp = trial.suggest_categorical(
        "init_scheme", 
        ["xavier_uniform", "orthogonal", "kaiming_normal"]
    )
    
    # Optimization Parameters (L2)
    lr_hp = trial.suggest_float("lr", 1e-5, 1e-3, log=True)
    weight_decay_hp = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
    
    # NEW L1 Regularization (For sparsity/simplification)
    l1_lambda_hp = trial.suggest_float("l1_lambda", 1e-7, 1e-4, log=True)
    
    # Focal Loss Parameters (gamma=0.0 now includes CrossEntropy)
    focal_gamma_hp = trial.suggest_float("focal_gamma", 0.0, 5.0, step=0.5)
    
    # Scheduler Parameters
    scheduler_patience_hp = trial.suggest_int("scheduler_patience", 3, 10, step=1)
    scheduler_factor_hp = trial.suggest_categorical("scheduler_factor", [0.1, 0.2, 0.5])
    
    # --- 4. Create Model, Criterion, Optimizer, and Scheduler ---
    
    # Criterion: Using FocalLoss
    criterion = nn.CrossEntropyLoss(weight=weights_tensor)
    
    # Model Definition
    model = RecurrentClassifier(
        input_size=input_shape[-1], 
        hidden_size=hidden_size_hp,
        num_layers=num_layers_hp,
        num_classes=num_classes,
        dropout_rate=dropout_hp,
        bidirectional=bidirectional_hp,
        rnn_type=rnn_type_hp
    ).to(device)

    # --- APPLY INITIALIZATION (NEW) ---
    initialize_weights(model, init_scheme=init_scheme_hp) 

    optimizer = torch.optim.AdamW(
        model.parameters(), 
        lr=lr_hp, 
        weight_decay=weight_decay_hp 
    )
    
    # Scheduler Definition (ReduceLROnPlateau)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, 
        mode='max',
        factor=scheduler_factor_hp, 
        patience=scheduler_patience_hp, 
        verbose=False,
        threshold=1e-4,
        min_lr=1e-7
    )

    scaler = torch.amp.GradScaler(enabled=(device.type == 'cuda'))
    weight_max_norm_hp = trial.suggest_float("weight_max_norm", low=0.1, high=6.0, log=False)
    # --- 5. Run Training ---
    try:
        _, _, best_val_f1 = fit(
            model=model,
            train_loader=train_loader, 
            val_loader=val_loader,     
            epochs=EPOCHS,
            criterion=criterion,
            optimizer=optimizer,
            scaler=scaler,
            device=device,
            l1_lambda=l1_lambda_hp, # <-- PASSED THE TUNED L1 PARAMETER
            l2_lambda=0,            # L2 still handled by optimizer
            patience=PATIENCE,
            evaluation_metric="val_f1",
            mode='max',
            restore_best_weights=True,
            writer=None,
            verbose=1,
            experiment_name=f"optuna_trial_{trial.number}",
            trial=trial,
            scheduler=scheduler,
            weight_max_norm = weight_max_norm_hp
        )
        
        return best_val_f1

    except optuna.exceptions.TrialPruned:
        return 0.0 
    except Exception as e:
        print(f"Trial {trial.number} failed with exception: {e}")
        return 0.0 

# --- 6. Create and Run the Optuna Study ---
print("--- Starting Optuna Hyperparameter Tuning ---")

study = optuna.create_study(
    direction="maximize", 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=5, n_startup_trials=3)
)

study.optimize(objective, n_trials=50) 

print("\n--- Tuning Complete ---")
print(f"Best trial number: {study.best_trial.number}")
print(f"Best validation F1-score: {study.best_value:.4f}")
print("Best hyperparameters found:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

[I 2025-11-11 18:10:42,454] A new study created in memory with name: no-name-c53587af-d312-4612-a90a-a0ced4ea6c97

--- Starting Optuna Hyperparameter Tuning ---
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0623, F1 Score=0.5395 | Val: Loss=0.9702, F1 Score=0.7004
Epoch   2/200 | Train: Loss=0.9431, F1 Score=0.6549 | Val: Loss=0.8782, F1 Score=0.7680
Epoch   3/200 | Train: Loss=0.8805, F1 Score=0.6725 | Val: Loss=0.9064, F1 Score=0.5692
Epoch   4/200 | Train: Loss=0.7388, F1 Score=0.7660 | Val: Loss=0.7867, F1 Score=0.6723
Epoch   5/200 | Train: Loss=0.6812, F1 Score=0.7988 | Val: Loss=0.7588, F1 Score=0.8145
Epoch   6/200 | Train: Loss=0.6269, F1 Score=0.8270 | Val: Loss=0.7725, F1 Score=0.8586
Epoch   7/200 | Train: Loss=0.5755, F1 Score=0.8460 | Val: Loss=0.6446, F1 Score=0.8667
Epoch   8/200 | Train: Loss=0.5258, F1 Score=0.8554 | Val: Loss=0.6570, F1 Score=0.8619
Epoch   9/200 | Train: Loss=0.5153, F1 Score=0.8473 | Val: Loss=0.5524, F1 Score=0.8064
Epoch  10/200 | Train: Loss=0.4948, F1 Score=0.8495 | Val: Loss=0.6285, F1 Score=0.8700
Epoch  11/200 | Train: Loss=0.4790, F1 Score=0.8590 | Val: Loss=0.5653, F1 Score=0.8187
Epoch  12/200 | Train: Loss=0.4834, F1 Score=0.8603 | Val: Loss=0.5580, F1 Score=0.8218
Epoch  13/200 | Train: Loss=0.4449, F1 Score=0.8617 | Val: Loss=0.6221, F1 Score=0.8674
Epoch  14/200 | Train: Loss=0.4444, F1 Score=0.8535 | Val: Loss=0.5183, F1 Score=0.8593
Epoch  15/200 | Train: Loss=0.4357, F1 Score=0.8561 | Val: Loss=0.5383, F1 Score=0.8142
Epoch  16/200 | Train: Loss=0.3850, F1 Score=0.8877 | Val: Loss=0.5501, F1 Score=0.8126
Epoch  17/200 | Train: Loss=0.3478, F1 Score=0.8866 | Val: Loss=0.5948, F1 Score=0.8601
Epoch  18/200 | Train: Loss=0.3485, F1 Score=0.8896 | Val: Loss=0.5101, F1 Score=0.8502
Epoch  19/200 | Train: Loss=0.3277, F1 Score=0.8924 | Val: Loss=0.5779, F1 Score=0.8638
Epoch  20/200 | Train: Loss=0.3222, F1 Score=0.9012 | Val: Loss=0.5236, F1 Score=0.8577
Epoch  21/200 | Train: Loss=0.2989, F1 Score=0.9019 | Val: Loss=0.5573, F1 Score=0.8155
Epoch  22/200 | Train: Loss=0.2762, F1 Score=0.9085 | Val: Loss=0.4885, F1 Score=0.8711
Epoch  23/200 | Train: Loss=0.2840, F1 Score=0.9069 | Val: Loss=0.5167, F1 Score=0.8561
Epoch  24/200 | Train: Loss=0.2793, F1 Score=0.9093 | Val: Loss=0.4876, F1 Score=0.8568
Epoch  25/200 | Train: Loss=0.2686, F1 Score=0.9128 | Val: Loss=0.5198, F1 Score=0.8672
Epoch  26/200 | Train: Loss=0.2683, F1 Score=0.9098 | Val: Loss=0.5543, F1 Score=0.8451
Epoch  27/200 | Train: Loss=0.2529, F1 Score=0.9176 | Val: Loss=0.6049, F1 Score=0.8443
Epoch  28/200 | Train: Loss=0.2595, F1 Score=0.9216 | Val: Loss=0.5231, F1 Score=0.8721
Epoch  29/200 | Train: Loss=0.2354, F1 Score=0.9176 | Val: Loss=0.4608, F1 Score=0.8763
Epoch  30/200 | Train: Loss=0.2329, F1 Score=0.9192 | Val: Loss=0.4926, F1 Score=0.8706
Epoch  31/200 | Train: Loss=0.2371, F1 Score=0.9196 | Val: Loss=0.5369, F1 Score=0.8712
Epoch  32/200 | Train: Loss=0.2419, F1 Score=0.9180 | Val: Loss=0.4400, F1 Score=0.8728
Epoch  33/200 | Train: Loss=0.2285, F1 Score=0.9204 | Val: Loss=0.4742, F1 Score=0.8791
Epoch  34/200 | Train: Loss=0.2232, F1 Score=0.9185 | Val: Loss=0.5358, F1 Score=0.8718
Epoch  35/200 | Train: Loss=0.2227, F1 Score=0.9236 | Val: Loss=0.4707, F1 Score=0.8826
Epoch  36/200 | Train: Loss=0.2223, F1 Score=0.9240 | Val: Loss=0.4956, F1 Score=0.8716
Epoch  37/200 | Train: Loss=0.2188, F1 Score=0.9237 | Val: Loss=0.4684, F1 Score=0.8774
Epoch  38/200 | Train: Loss=0.2154, F1 Score=0.9258 | Val: Loss=0.4783, F1 Score=0.8700
Epoch  39/200 | Train: Loss=0.2270, F1 Score=0.9228 | Val: Loss=0.4923, F1 Score=0.8804
Epoch  40/200 | Train: Loss=0.2173, F1 Score=0.9251 | Val: Loss=0.4697, F1 Score=0.8857
Epoch  41/200 | Train: Loss=0.2178, F1 Score=0.9213 | Val: Loss=0.4865, F1 Score=0.8785
Epoch  42/200 | Train: Loss=0.2124, F1 Score=0.9264 | Val: Loss=0.5183, F1 Score=0.8781
Epoch  43/200 | Train: Loss=0.2103, F1 Score=0.9253 | Val: Loss=0.4477, F1 Score=0.8884
Epoch  44/200 | Train: Loss=0.2049, F1 Score=0.9259 | Val: Loss=0.4817, F1 Score=0.8707
Epoch  45/200 | Train: Loss=0.2057, F1 Score=0.9251 | Val: Loss=0.4657, F1 Score=0.8814
Epoch  46/200 | Train: Loss=0.2018, F1 Score=0.9286 | Val: Loss=0.4912, F1 Score=0.8714
Epoch  47/200 | Train: Loss=0.2110, F1 Score=0.9252 | Val: Loss=0.6102, F1 Score=0.8694
Epoch  48/200 | Train: Loss=0.2074, F1 Score=0.9264 | Val: Loss=0.4306, F1 Score=0.8756
Epoch  49/200 | Train: Loss=0.1959, F1 Score=0.9286 | Val: Loss=0.4694, F1 Score=0.8725
Epoch  50/200 | Train: Loss=0.1940, F1 Score=0.9299 | Val: Loss=0.4371, F1 Score=0.8787
Epoch  51/200 | Train: Loss=0.1922, F1 Score=0.9255 | Val: Loss=0.4383, F1 Score=0.8921
Epoch  52/200 | Train: Loss=0.1948, F1 Score=0.9332 | Val: Loss=0.4697, F1 Score=0.8791
Epoch  53/200 | Train: Loss=0.1923, F1 Score=0.9262 | Val: Loss=0.4703, F1 Score=0.8823
Epoch  54/200 | Train: Loss=0.1880, F1 Score=0.9288 | Val: Loss=0.4623, F1 Score=0.8831
Epoch  55/200 | Train: Loss=0.1884, F1 Score=0.9302 | Val: Loss=0.4666, F1 Score=0.8872
Epoch  56/200 | Train: Loss=0.1857, F1 Score=0.9286 | Val: Loss=0.4272, F1 Score=0.8827
Epoch  57/200 | Train: Loss=0.1863, F1 Score=0.9312 | Val: Loss=0.4221, F1 Score=0.8808
Epoch  58/200 | Train: Loss=0.1851, F1 Score=0.9277 | Val: Loss=0.4466, F1 Score=0.8871
Epoch  59/200 | Train: Loss=0.1870, F1 Score=0.9306 | Val: Loss=0.4453, F1 Score=0.8855
Epoch  60/200 | Train: Loss=0.1788, F1 Score=0.9320 | Val: Loss=0.4421, F1 Score=0.8733
Epoch  61/200 | Train: Loss=0.1852, F1 Score=0.9278 | Val: Loss=0.4434, F1 Score=0.8864
Epoch  62/200 | Train: Loss=0.1825, F1 Score=0.9316 | Val: Loss=0.4500, F1 Score=0.8850
Epoch  63/200 | Train: Loss=0.1804, F1 Score=0.9304 | Val: Loss=0.4425, F1 Score=0.8877
Epoch  64/200 | Train: Loss=0.1811, F1 Score=0.9301 | Val: Loss=0.4441, F1 Score=0.8862
Epoch  65/200 | Train: Loss=0.1820, F1 Score=0.9314 | Val: Loss=0.4490, F1 Score=0.8843

[I 2025-11-11 18:11:57,913] Trial 0 finished with value: 0.8921109555660751 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.13573375074615965, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.0006544276067279963, 'weight_decay': 1.1731213437457893e-06, 'l1_lambda': 5.396709736523594e-07, 'focal_gamma': 0.5, 'scheduler_patience': 4, 'scheduler_factor': 0.5, 'weight_max_norm': 5.616934331600047}. Best is trial 0 with value: 0.8921109555660751.

Epoch  66/200 | Train: Loss=0.1787, F1 Score=0.9320 | Val: Loss=0.4457, F1 Score=0.8780
Early stopping triggered after 66 epochs.
Best model restored from epoch 51 with val_f1 0.8921
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.2406, F1 Score=0.6208 | Val: Loss=1.0796, F1 Score=0.6859
Epoch   2/200 | Train: Loss=1.2257, F1 Score=0.6176 | Val: Loss=1.0758, F1 Score=0.7743
Epoch   3/200 | Train: Loss=1.2097, F1 Score=0.6622 | Val: Loss=1.0582, F1 Score=0.7808
Epoch   4/200 | Train: Loss=1.1881, F1 Score=0.6871 | Val: Loss=1.0429, F1 Score=0.6762
Epoch   5/200 | Train: Loss=1.1522, F1 Score=0.6734 | Val: Loss=1.0021, F1 Score=0.6681
Epoch   6/200 | Train: Loss=1.0963, F1 Score=0.6800 | Val: Loss=0.9345, F1 Score=0.6955
Epoch   7/200 | Train: Loss=1.0589, F1 Score=0.6721 | Val: Loss=0.9163, F1 Score=0.6986
Epoch   8/200 | Train: Loss=1.0356, F1 Score=0.6790 | Val: Loss=0.9625, F1 Score=0.6318
Epoch   9/200 | Train: Loss=1.0133, F1 Score=0.6827 | Val: Loss=0.9168, F1 Score=0.6771
Epoch  10/200 | Train: Loss=0.9932, F1 Score=0.6862 | Val: Loss=0.9376, F1 Score=0.6647
Epoch  11/200 | Train: Loss=0.9805, F1 Score=0.6874 | Val: Loss=0.9037, F1 Score=0.6965
Epoch  12/200 | Train: Loss=0.9553, F1 Score=0.6946 | Val: Loss=0.9203, F1 Score=0.6615
Epoch  13/200 | Train: Loss=0.9387, F1 Score=0.6853 | Val: Loss=0.9101, F1 Score=0.6661
Epoch  14/200 | Train: Loss=0.9223, F1 Score=0.6881 | Val: Loss=0.8708, F1 Score=0.7013
Epoch  15/200 | Train: Loss=0.9114, F1 Score=0.6857 | Val: Loss=0.8721, F1 Score=0.6983
Epoch  16/200 | Train: Loss=0.9045, F1 Score=0.6970 | Val: Loss=0.8748, F1 Score=0.6922
Epoch  17/200 | Train: Loss=0.9047, F1 Score=0.6880 | Val: Loss=0.8659, F1 Score=0.7054

[I 2025-11-11 18:12:34,546] Trial 1 finished with value: 0.7808408483390261 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 32, 'num_layers': 3, 'dropout_rate': 0.387892677372777, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 7.252627958721836e-05, 'weight_decay': 5.9207657352008226e-05, 'l1_lambda': 3.674561284571719e-05, 'focal_gamma': 0.5, 'scheduler_patience': 10, 'scheduler_factor': 0.1, 'weight_max_norm': 2.694457539247971}. Best is trial 0 with value: 0.8921109555660751.

Epoch  18/200 | Train: Loss=0.9050, F1 Score=0.6950 | Val: Loss=0.8724, F1 Score=0.6960
Early stopping triggered after 18 epochs.
Best model restored from epoch 3 with val_f1 0.7808
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0977, F1 Score=0.6559 | Val: Loss=1.0803, F1 Score=0.6312
Epoch   2/200 | Train: Loss=1.0949, F1 Score=0.6503 | Val: Loss=1.0828, F1 Score=0.6387
Epoch   3/200 | Train: Loss=1.0924, F1 Score=0.6504 | Val: Loss=1.0835, F1 Score=0.6526
Epoch   4/200 | Train: Loss=1.0903, F1 Score=0.6678 | Val: Loss=1.0823, F1 Score=0.6685
Epoch   5/200 | Train: Loss=1.0884, F1 Score=0.6740 | Val: Loss=1.0801, F1 Score=0.6822
Epoch   6/200 | Train: Loss=1.0863, F1 Score=0.6848 | Val: Loss=1.0785, F1 Score=0.6847
Epoch   7/200 | Train: Loss=1.0840, F1 Score=0.6884 | Val: Loss=1.0767, F1 Score=0.6890
Epoch   8/200 | Train: Loss=1.0817, F1 Score=0.6949 | Val: Loss=1.0751, F1 Score=0.6779
Epoch   9/200 | Train: Loss=1.0795, F1 Score=0.6883 | Val: Loss=1.0734, F1 Score=0.6754
Epoch  10/200 | Train: Loss=1.0763, F1 Score=0.6527 | Val: Loss=1.0710, F1 Score=0.6848
Epoch  11/200 | Train: Loss=1.0729, F1 Score=0.7034 | Val: Loss=1.0675, F1 Score=0.6915
Epoch  12/200 | Train: Loss=1.0696, F1 Score=0.7000 | Val: Loss=1.0668, F1 Score=0.6431
Epoch  13/200 | Train: Loss=1.0645, F1 Score=0.6436 | Val: Loss=1.0642, F1 Score=0.6047
Epoch  14/200 | Train: Loss=1.0591, F1 Score=0.6567 | Val: Loss=1.0580, F1 Score=0.6414
Epoch  15/200 | Train: Loss=1.0498, F1 Score=0.6277 | Val: Loss=1.0495, F1 Score=0.6521
Epoch  16/200 | Train: Loss=1.0352, F1 Score=0.6655 | Val: Loss=1.0381, F1 Score=0.6499
Epoch  17/200 | Train: Loss=1.0122, F1 Score=0.6510 | Val: Loss=1.0293, F1 Score=0.6206
Epoch  18/200 | Train: Loss=0.9844, F1 Score=0.6230 | Val: Loss=1.0049, F1 Score=0.6688
Epoch  19/200 | Train: Loss=0.9722, F1 Score=0.6281 | Val: Loss=1.0083, F1 Score=0.6388
Epoch  20/200 | Train: Loss=0.9663, F1 Score=0.6077 | Val: Loss=1.0089, F1 Score=0.6326
Epoch  21/200 | Train: Loss=0.9611, F1 Score=0.6233 | Val: Loss=1.0077, F1 Score=0.6333
Epoch  22/200 | Train: Loss=0.9581, F1 Score=0.6152 | Val: Loss=0.9966, F1 Score=0.6522
Epoch  23/200 | Train: Loss=0.9537, F1 Score=0.6186 | Val: Loss=0.9898, F1 Score=0.6636
Epoch  24/200 | Train: Loss=0.9492, F1 Score=0.6255 | Val: Loss=0.9878, F1 Score=0.6666
Epoch  25/200 | Train: Loss=0.9458, F1 Score=0.6197 | Val: Loss=0.9939, F1 Score=0.6515

[I 2025-11-11 18:13:06,650] Trial 2 finished with value: 0.6914620606626701 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 32, 'num_layers': 1, 'dropout_rate': 0.5923960820757741, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 5.1390477468736194e-05, 'weight_decay': 3.551390163748875e-05, 'l1_lambda': 5.794653680751825e-07, 'focal_gamma': 1.0, 'scheduler_patience': 6, 'scheduler_factor': 0.5, 'weight_max_norm': 1.700287033134566}. Best is trial 0 with value: 0.8921109555660751.

Epoch  26/200 | Train: Loss=0.9423, F1 Score=0.6156 | Val: Loss=0.9855, F1 Score=0.6674
Early stopping triggered after 26 epochs.
Best model restored from epoch 11 with val_f1 0.6915
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.4379, F1 Score=0.5758 | Val: Loss=1.0907, F1 Score=0.4692
Epoch   2/200 | Train: Loss=1.3866, F1 Score=0.5928 | Val: Loss=1.0611, F1 Score=0.6328
Epoch   3/200 | Train: Loss=1.3235, F1 Score=0.6368 | Val: Loss=1.0212, F1 Score=0.5783
Epoch   4/200 | Train: Loss=1.2333, F1 Score=0.6578 | Val: Loss=0.9185, F1 Score=0.7040
Epoch   5/200 | Train: Loss=1.1694, F1 Score=0.6544 | Val: Loss=0.9159, F1 Score=0.6914
Epoch   6/200 | Train: Loss=1.1222, F1 Score=0.6439 | Val: Loss=0.8736, F1 Score=0.7454
Epoch   7/200 | Train: Loss=1.0745, F1 Score=0.6605 | Val: Loss=0.8616, F1 Score=0.7113
Epoch   8/200 | Train: Loss=1.0372, F1 Score=0.6473 | Val: Loss=0.8707, F1 Score=0.6823
Epoch   9/200 | Train: Loss=1.0091, F1 Score=0.6594 | Val: Loss=0.8611, F1 Score=0.6896
Epoch  10/200 | Train: Loss=0.9832, F1 Score=0.6674 | Val: Loss=0.8205, F1 Score=0.7273
Epoch  11/200 | Train: Loss=0.9591, F1 Score=0.6687 | Val: Loss=0.8465, F1 Score=0.6567
Epoch  12/200 | Train: Loss=0.9384, F1 Score=0.6594 | Val: Loss=0.8433, F1 Score=0.6998
Epoch  13/200 | Train: Loss=0.9278, F1 Score=0.6664 | Val: Loss=0.8385, F1 Score=0.6968
Epoch  14/200 | Train: Loss=0.9247, F1 Score=0.6686 | Val: Loss=0.8400, F1 Score=0.6625
Epoch  15/200 | Train: Loss=0.9139, F1 Score=0.6697 | Val: Loss=0.8220, F1 Score=0.6884
Epoch  16/200 | Train: Loss=0.9116, F1 Score=0.6767 | Val: Loss=0.8300, F1 Score=0.6770
Epoch  17/200 | Train: Loss=0.9052, F1 Score=0.6705 | Val: Loss=0.8225, F1 Score=0.6976
Epoch  18/200 | Train: Loss=0.9022, F1 Score=0.6750 | Val: Loss=0.8270, F1 Score=0.7165

[I 2025-11-11 18:13:36,205] Trial 3 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.3583480727305013, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'kaiming_normal', 'lr': 9.796562200498227e-05, 'weight_decay': 1.0314698903628836e-06, 'l1_lambda': 8.551654247956156e-05, 'focal_gamma': 4.0, 'scheduler_patience': 4, 'scheduler_factor': 0.5, 'weight_max_norm': 5.8512762986363045}. Best is trial 0 with value: 0.8921109555660751.

Epoch  19/200 | Train: Loss=0.8966, F1 Score=0.6850 | Val: Loss=0.8139, F1 Score=0.7077
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1378, F1 Score=0.5643 | Val: Loss=1.0777, F1 Score=0.2570
Epoch   2/200 | Train: Loss=1.1118, F1 Score=0.5275 | Val: Loss=1.0517, F1 Score=0.4116
Epoch   3/200 | Train: Loss=1.0845, F1 Score=0.5452 | Val: Loss=1.0267, F1 Score=0.6633
Epoch   4/200 | Train: Loss=1.0475, F1 Score=0.6077 | Val: Loss=1.0111, F1 Score=0.4293
Epoch   5/200 | Train: Loss=1.0140, F1 Score=0.5993 | Val: Loss=0.9694, F1 Score=0.7850
Epoch   6/200 | Train: Loss=0.9878, F1 Score=0.6394 | Val: Loss=0.9552, F1 Score=0.7605
Epoch   7/200 | Train: Loss=0.9774, F1 Score=0.6497 | Val: Loss=0.9384, F1 Score=0.4903
Epoch   8/200 | Train: Loss=0.9438, F1 Score=0.6128 | Val: Loss=0.8965, F1 Score=0.7460
Epoch   9/200 | Train: Loss=0.9491, F1 Score=0.6560 | Val: Loss=0.8920, F1 Score=0.6528
Epoch  10/200 | Train: Loss=0.9225, F1 Score=0.6291 | Val: Loss=0.8707, F1 Score=0.7658
Epoch  11/200 | Train: Loss=0.9198, F1 Score=0.6645 | Val: Loss=0.8695, F1 Score=0.7363
Epoch  12/200 | Train: Loss=0.8854, F1 Score=0.7061 | Val: Loss=0.8567, F1 Score=0.6783
Epoch  13/200 | Train: Loss=0.8851, F1 Score=0.6637 | Val: Loss=0.8535, F1 Score=0.6917
Epoch  14/200 | Train: Loss=0.8797, F1 Score=0.6828 | Val: Loss=0.8525, F1 Score=0.7115
Epoch  15/200 | Train: Loss=0.8878, F1 Score=0.6655 | Val: Loss=0.8494, F1 Score=0.6992
Epoch  16/200 | Train: Loss=0.8765, F1 Score=0.6876 | Val: Loss=0.8473, F1 Score=0.7101
Epoch  17/200 | Train: Loss=0.8808, F1 Score=0.6834 | Val: Loss=0.8467, F1 Score=0.7028
Epoch  18/200 | Train: Loss=0.8788, F1 Score=0.6840 | Val: Loss=0.8467, F1 Score=0.7002
Epoch  19/200 | Train: Loss=0.8831, F1 Score=0.6786 | Val: Loss=0.8469, F1 Score=0.6989

[I 2025-11-11 18:13:57,175] Trial 4 finished with value: 0.7850445523188785 and parameters: {'WINDOW': 40, 'STRIDE': 30, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.5785003464045118, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 9.410300795800557e-05, 'weight_decay': 0.00022582028555133863, 'l1_lambda': 1.2196197619386113e-06, 'focal_gamma': 5.0, 'scheduler_patience': 5, 'scheduler_factor': 0.1, 'weight_max_norm': 4.474130281597721}. Best is trial 0 with value: 0.8921109555660751.

Epoch  20/200 | Train: Loss=0.8714, F1 Score=0.6774 | Val: Loss=0.8466, F1 Score=0.6985
Early stopping triggered after 20 epochs.
Best model restored from epoch 5 with val_f1 0.7850
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0950, F1 Score=0.4876 | Val: Loss=1.0702, F1 Score=0.5840
Epoch   2/200 | Train: Loss=1.0513, F1 Score=0.6627 | Val: Loss=0.9776, F1 Score=0.7026
Epoch   3/200 | Train: Loss=0.9668, F1 Score=0.6718 | Val: Loss=0.9360, F1 Score=0.7491
Epoch   4/200 | Train: Loss=0.9300, F1 Score=0.6995 | Val: Loss=0.9746, F1 Score=0.4219
Epoch   5/200 | Train: Loss=0.9018, F1 Score=0.6669 | Val: Loss=0.8606, F1 Score=0.7650
Epoch   6/200 | Train: Loss=0.8668, F1 Score=0.6763 | Val: Loss=0.8960, F1 Score=0.7856
Epoch   7/200 | Train: Loss=0.8591, F1 Score=0.6343 | Val: Loss=0.8754, F1 Score=0.7924
Epoch   8/200 | Train: Loss=0.8238, F1 Score=0.6849 | Val: Loss=0.8585, F1 Score=0.6347
Epoch   9/200 | Train: Loss=0.7736, F1 Score=0.7293 | Val: Loss=0.7694, F1 Score=0.7012
Epoch  10/200 | Train: Loss=0.6578, F1 Score=0.7993 | Val: Loss=0.6695, F1 Score=0.8226
Epoch  11/200 | Train: Loss=0.5892, F1 Score=0.8190 | Val: Loss=0.6356, F1 Score=0.8241
Epoch  12/200 | Train: Loss=0.5755, F1 Score=0.8317 | Val: Loss=0.6703, F1 Score=0.7624
Epoch  13/200 | Train: Loss=0.5543, F1 Score=0.8255 | Val: Loss=0.6331, F1 Score=0.8727
Epoch  14/200 | Train: Loss=0.5553, F1 Score=0.8161 | Val: Loss=0.6585, F1 Score=0.8669
Epoch  15/200 | Train: Loss=0.5522, F1 Score=0.8324 | Val: Loss=0.6273, F1 Score=0.8555
Epoch  16/200 | Train: Loss=0.5171, F1 Score=0.8417 | Val: Loss=0.6167, F1 Score=0.7742
Epoch  17/200 | Train: Loss=0.4826, F1 Score=0.8570 | Val: Loss=0.6307, F1 Score=0.8040
Epoch  18/200 | Train: Loss=0.4729, F1 Score=0.8595 | Val: Loss=0.6321, F1 Score=0.8771
Epoch  19/200 | Train: Loss=0.4685, F1 Score=0.8604 | Val: Loss=0.7523, F1 Score=0.8684
Epoch  20/200 | Train: Loss=0.4869, F1 Score=0.8600 | Val: Loss=0.7096, F1 Score=0.7469
Epoch  21/200 | Train: Loss=0.4928, F1 Score=0.8489 | Val: Loss=0.6063, F1 Score=0.8790
Epoch  22/200 | Train: Loss=0.4735, F1 Score=0.8622 | Val: Loss=0.5524, F1 Score=0.8785
Epoch  23/200 | Train: Loss=0.4368, F1 Score=0.8687 | Val: Loss=0.7025, F1 Score=0.8655
Epoch  24/200 | Train: Loss=0.4215, F1 Score=0.8798 | Val: Loss=0.5782, F1 Score=0.8339
Epoch  25/200 | Train: Loss=0.4552, F1 Score=0.8504 | Val: Loss=0.6246, F1 Score=0.8874
Epoch  26/200 | Train: Loss=0.4229, F1 Score=0.8915 | Val: Loss=0.5750, F1 Score=0.8506
Epoch  27/200 | Train: Loss=0.4401, F1 Score=0.8597 | Val: Loss=0.7488, F1 Score=0.8088
Epoch  28/200 | Train: Loss=0.4445, F1 Score=0.8663 | Val: Loss=0.6987, F1 Score=0.8163
Epoch  29/200 | Train: Loss=0.4128, F1 Score=0.8759 | Val: Loss=0.6608, F1 Score=0.8318
Epoch  30/200 | Train: Loss=0.4248, F1 Score=0.8592 | Val: Loss=0.5902, F1 Score=0.8974
Epoch  31/200 | Train: Loss=0.4142, F1 Score=0.8662 | Val: Loss=0.7618, F1 Score=0.8632
Epoch  32/200 | Train: Loss=0.4176, F1 Score=0.8721 | Val: Loss=0.6376, F1 Score=0.8850
Epoch  33/200 | Train: Loss=0.4236, F1 Score=0.8675 | Val: Loss=0.5591, F1 Score=0.8908
Epoch  34/200 | Train: Loss=0.3805, F1 Score=0.8893 | Val: Loss=0.6128, F1 Score=0.8492
Epoch  35/200 | Train: Loss=0.3678, F1 Score=0.8919 | Val: Loss=0.6837, F1 Score=0.8490
Epoch  36/200 | Train: Loss=0.4163, F1 Score=0.8650 | Val: Loss=0.6150, F1 Score=0.8339
Epoch  37/200 | Train: Loss=0.3790, F1 Score=0.8903 | Val: Loss=0.5642, F1 Score=0.8396
Epoch  38/200 | Train: Loss=0.3981, F1 Score=0.8903 | Val: Loss=0.5494, F1 Score=0.8898
Epoch  39/200 | Train: Loss=0.3638, F1 Score=0.8885 | Val: Loss=0.6780, F1 Score=0.8596
Epoch  40/200 | Train: Loss=0.3499, F1 Score=0.8952 | Val: Loss=0.5276, F1 Score=0.8600
Epoch  41/200 | Train: Loss=0.3417, F1 Score=0.8969 | Val: Loss=0.5313, F1 Score=0.8662
Epoch  42/200 | Train: Loss=0.3296, F1 Score=0.8985 | Val: Loss=0.5973, F1 Score=0.8307
Epoch  43/200 | Train: Loss=0.3299, F1 Score=0.8982 | Val: Loss=0.5840, F1 Score=0.8516
Epoch  44/200 | Train: Loss=0.3205, F1 Score=0.8911 | Val: Loss=0.6030, F1 Score=0.8516

[I 2025-11-11 18:14:34,432] Trial 5 finished with value: 0.8973708605674166 and parameters: {'WINDOW': 40, 'STRIDE': 30, 'hidden_size': 32, 'num_layers': 3, 'dropout_rate': 0.15609070681632656, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'kaiming_normal', 'lr': 0.0009344313542330503, 'weight_decay': 0.0002081953117596135, 'l1_lambda': 2.583109206985774e-07, 'focal_gamma': 0.5, 'scheduler_patience': 8, 'scheduler_factor': 0.5, 'weight_max_norm': 3.427342238526061}. Best is trial 5 with value: 0.8973708605674166.

Epoch  45/200 | Train: Loss=0.3226, F1 Score=0.9033 | Val: Loss=0.6311, F1 Score=0.8266
Early stopping triggered after 45 epochs.
Best model restored from epoch 30 with val_f1 0.8974
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0973, F1 Score=0.6242 | Val: Loss=1.0916, F1 Score=0.2239
Epoch   2/200 | Train: Loss=1.0859, F1 Score=0.5315 | Val: Loss=1.0760, F1 Score=0.5883
Epoch   3/200 | Train: Loss=1.0703, F1 Score=0.6524 | Val: Loss=1.0683, F1 Score=0.3609
Epoch   4/200 | Train: Loss=1.0229, F1 Score=0.6777 | Val: Loss=1.0483, F1 Score=0.7452
Epoch   5/200 | Train: Loss=1.0012, F1 Score=0.6631 | Val: Loss=0.9908, F1 Score=0.6047

[I 2025-11-11 18:14:40,366] Trial 6 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 20, 'hidden_size': 32, 'num_layers': 1, 'dropout_rate': 0.495884044905205, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0005250405305310213, 'weight_decay': 4.145421793575816e-05, 'l1_lambda': 4.1318454125918664e-07, 'focal_gamma': 0.0, 'scheduler_patience': 3, 'scheduler_factor': 0.2, 'weight_max_norm': 5.208690195985856}. Best is trial 5 with value: 0.8973708605674166.

Epoch   6/200 | Train: Loss=0.9498, F1 Score=0.7028 | Val: Loss=0.9678, F1 Score=0.6517
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1260, F1 Score=0.5305 | Val: Loss=1.0552, F1 Score=0.5664
Epoch   2/200 | Train: Loss=1.0560, F1 Score=0.6289 | Val: Loss=0.9872, F1 Score=0.7060
Epoch   3/200 | Train: Loss=0.9817, F1 Score=0.6387 | Val: Loss=0.9342, F1 Score=0.6751
Epoch   4/200 | Train: Loss=0.9527, F1 Score=0.6666 | Val: Loss=0.9511, F1 Score=0.6459
Epoch   5/200 | Train: Loss=0.9163, F1 Score=0.6196 | Val: Loss=0.9553, F1 Score=0.4361
Epoch   6/200 | Train: Loss=0.8778, F1 Score=0.6810 | Val: Loss=0.8598, F1 Score=0.7838
Epoch   7/200 | Train: Loss=0.7996, F1 Score=0.7372 | Val: Loss=0.8518, F1 Score=0.8132
Epoch   8/200 | Train: Loss=0.7778, F1 Score=0.7413 | Val: Loss=0.8742, F1 Score=0.8334
Epoch   9/200 | Train: Loss=0.6864, F1 Score=0.7713 | Val: Loss=0.6311, F1 Score=0.8408
Epoch  10/200 | Train: Loss=0.6718, F1 Score=0.7708 | Val: Loss=0.6177, F1 Score=0.8020
Epoch  11/200 | Train: Loss=0.6174, F1 Score=0.8182 | Val: Loss=0.6516, F1 Score=0.8529
Epoch  12/200 | Train: Loss=0.5986, F1 Score=0.8240 | Val: Loss=0.7604, F1 Score=0.7650
Epoch  13/200 | Train: Loss=0.5617, F1 Score=0.8315 | Val: Loss=0.6491, F1 Score=0.8206
Epoch  14/200 | Train: Loss=0.5599, F1 Score=0.8333 | Val: Loss=0.6739, F1 Score=0.8465
Epoch  15/200 | Train: Loss=0.4905, F1 Score=0.8588 | Val: Loss=0.6338, F1 Score=0.8804
Epoch  16/200 | Train: Loss=0.5229, F1 Score=0.8470 | Val: Loss=0.6398, F1 Score=0.8966
Epoch  17/200 | Train: Loss=0.5092, F1 Score=0.8621 | Val: Loss=0.4974, F1 Score=0.8857
Epoch  18/200 | Train: Loss=0.4504, F1 Score=0.8796 | Val: Loss=0.6918, F1 Score=0.7677
Epoch  19/200 | Train: Loss=0.4551, F1 Score=0.8505 | Val: Loss=0.5203, F1 Score=0.9078
Epoch  20/200 | Train: Loss=0.4394, F1 Score=0.8672 | Val: Loss=0.5779, F1 Score=0.8651
Epoch  21/200 | Train: Loss=0.4012, F1 Score=0.8915 | Val: Loss=0.4735, F1 Score=0.9121
Epoch  22/200 | Train: Loss=0.4013, F1 Score=0.8795 | Val: Loss=0.5625, F1 Score=0.8536
Epoch  23/200 | Train: Loss=0.4382, F1 Score=0.8544 | Val: Loss=0.6916, F1 Score=0.8286
Epoch  24/200 | Train: Loss=0.4190, F1 Score=0.8712 | Val: Loss=0.5375, F1 Score=0.8821
Epoch  25/200 | Train: Loss=0.3587, F1 Score=0.9049 | Val: Loss=0.5188, F1 Score=0.8836
Epoch  26/200 | Train: Loss=0.3859, F1 Score=0.8828 | Val: Loss=0.4491, F1 Score=0.9083
Epoch  27/200 | Train: Loss=0.3632, F1 Score=0.8888 | Val: Loss=0.5258, F1 Score=0.9131
Epoch  28/200 | Train: Loss=0.3075, F1 Score=0.9152 | Val: Loss=0.4725, F1 Score=0.8932
Epoch  29/200 | Train: Loss=0.3175, F1 Score=0.9053 | Val: Loss=0.6004, F1 Score=0.8850
Epoch  30/200 | Train: Loss=0.3020, F1 Score=0.9130 | Val: Loss=0.4791, F1 Score=0.8661
Epoch  31/200 | Train: Loss=0.3026, F1 Score=0.9140 | Val: Loss=0.6767, F1 Score=0.8660
Epoch  32/200 | Train: Loss=0.2907, F1 Score=0.9114 | Val: Loss=0.4472, F1 Score=0.8847
Epoch  33/200 | Train: Loss=0.3003, F1 Score=0.9088 | Val: Loss=0.4665, F1 Score=0.9133
Epoch  34/200 | Train: Loss=0.3071, F1 Score=0.9040 | Val: Loss=0.5096, F1 Score=0.8951
Epoch  35/200 | Train: Loss=0.3179, F1 Score=0.8983 | Val: Loss=0.4681, F1 Score=0.9025
Epoch  36/200 | Train: Loss=0.2586, F1 Score=0.9182 | Val: Loss=0.4458, F1 Score=0.9174
Epoch  37/200 | Train: Loss=0.2270, F1 Score=0.9308 | Val: Loss=0.4903, F1 Score=0.9034
Epoch  38/200 | Train: Loss=0.2247, F1 Score=0.9356 | Val: Loss=0.4588, F1 Score=0.8761
Epoch  39/200 | Train: Loss=0.2274, F1 Score=0.9239 | Val: Loss=0.4044, F1 Score=0.9289
Epoch  40/200 | Train: Loss=0.2160, F1 Score=0.9272 | Val: Loss=0.5716, F1 Score=0.8660
Epoch  41/200 | Train: Loss=0.2118, F1 Score=0.9269 | Val: Loss=0.4013, F1 Score=0.8813
Epoch  42/200 | Train: Loss=0.2297, F1 Score=0.9340 | Val: Loss=0.5547, F1 Score=0.8795
Epoch  43/200 | Train: Loss=0.2820, F1 Score=0.9189 | Val: Loss=0.5067, F1 Score=0.8033
Epoch  44/200 | Train: Loss=0.2718, F1 Score=0.8994 | Val: Loss=0.5015, F1 Score=0.9036
Epoch  45/200 | Train: Loss=0.2090, F1 Score=0.9295 | Val: Loss=0.3713, F1 Score=0.8972
Epoch  46/200 | Train: Loss=0.1912, F1 Score=0.9356 | Val: Loss=0.3679, F1 Score=0.8887
Epoch  47/200 | Train: Loss=0.1603, F1 Score=0.9357 | Val: Loss=0.4081, F1 Score=0.9059
Epoch  48/200 | Train: Loss=0.2354, F1 Score=0.9167 | Val: Loss=0.4479, F1 Score=0.8899
Epoch  49/200 | Train: Loss=0.1646, F1 Score=0.9317 | Val: Loss=0.4106, F1 Score=0.8990
Epoch  50/200 | Train: Loss=0.1436, F1 Score=0.9437 | Val: Loss=0.3836, F1 Score=0.8788
Epoch  51/200 | Train: Loss=0.1360, F1 Score=0.9457 | Val: Loss=0.3779, F1 Score=0.9000
Epoch  52/200 | Train: Loss=0.1330, F1 Score=0.9501 | Val: Loss=0.3723, F1 Score=0.8932
Epoch  53/200 | Train: Loss=0.1245, F1 Score=0.9536 | Val: Loss=0.3827, F1 Score=0.8965

[I 2025-11-11 18:15:35,922] Trial 7 finished with value: 0.9289077176984794 and parameters: {'WINDOW': 40, 'STRIDE': 30, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.5275740556306774, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.0006541772891371, 'weight_decay': 1.6138440383337687e-05, 'l1_lambda': 2.62703326114608e-06, 'focal_gamma': 3.0, 'scheduler_patience': 8, 'scheduler_factor': 0.2, 'weight_max_norm': 3.57042476566107}. Best is trial 7 with value: 0.9289077176984794.

Epoch  54/200 | Train: Loss=0.1247, F1 Score=0.9513 | Val: Loss=0.3937, F1 Score=0.8988
Early stopping triggered after 54 epochs.
Best model restored from epoch 39 with val_f1 0.9289
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.2153, F1 Score=0.5602 | Val: Loss=1.0624, F1 Score=0.5759
Epoch   2/200 | Train: Loss=1.1081, F1 Score=0.6752 | Val: Loss=0.9941, F1 Score=0.6371
Epoch   3/200 | Train: Loss=1.0139, F1 Score=0.6425 | Val: Loss=0.9152, F1 Score=0.6929
Epoch   4/200 | Train: Loss=0.9607, F1 Score=0.6675 | Val: Loss=0.8857, F1 Score=0.5796
Epoch   5/200 | Train: Loss=0.8742, F1 Score=0.6925 | Val: Loss=0.8752, F1 Score=0.6563
Epoch   6/200 | Train: Loss=0.8003, F1 Score=0.7402 | Val: Loss=0.6476, F1 Score=0.8731
Epoch   7/200 | Train: Loss=0.6996, F1 Score=0.8217 | Val: Loss=0.6449, F1 Score=0.8620
Epoch   8/200 | Train: Loss=0.6692, F1 Score=0.8400 | Val: Loss=0.8241, F1 Score=0.6500
Epoch   9/200 | Train: Loss=0.6182, F1 Score=0.8298 | Val: Loss=0.6028, F1 Score=0.8940
Epoch  10/200 | Train: Loss=0.5905, F1 Score=0.8539 | Val: Loss=0.6278, F1 Score=0.8503
Epoch  11/200 | Train: Loss=0.5555, F1 Score=0.8770 | Val: Loss=0.5422, F1 Score=0.8525
Epoch  12/200 | Train: Loss=0.5718, F1 Score=0.8517 | Val: Loss=0.5906, F1 Score=0.8382
Epoch  13/200 | Train: Loss=0.5275, F1 Score=0.8772 | Val: Loss=0.5099, F1 Score=0.9028
Epoch  14/200 | Train: Loss=0.5240, F1 Score=0.8786 | Val: Loss=0.5343, F1 Score=0.8859
Epoch  15/200 | Train: Loss=0.5139, F1 Score=0.8792 | Val: Loss=0.6249, F1 Score=0.8155
Epoch  16/200 | Train: Loss=0.5336, F1 Score=0.8566 | Val: Loss=0.6126, F1 Score=0.8198
Epoch  17/200 | Train: Loss=0.4903, F1 Score=0.8874 | Val: Loss=0.5321, F1 Score=0.8159
Epoch  18/200 | Train: Loss=0.4682, F1 Score=0.9007 | Val: Loss=0.5079, F1 Score=0.8997
Epoch  19/200 | Train: Loss=0.4455, F1 Score=0.9154 | Val: Loss=0.5183, F1 Score=0.8845
Epoch  20/200 | Train: Loss=0.4432, F1 Score=0.9156 | Val: Loss=0.5149, F1 Score=0.8957
Epoch  21/200 | Train: Loss=0.4373, F1 Score=0.9209 | Val: Loss=0.5192, F1 Score=0.8856
Epoch  22/200 | Train: Loss=0.4425, F1 Score=0.9166 | Val: Loss=0.5182, F1 Score=0.8874
Epoch  23/200 | Train: Loss=0.4374, F1 Score=0.9160 | Val: Loss=0.5175, F1 Score=0.8897
Epoch  24/200 | Train: Loss=0.4389, F1 Score=0.9182 | Val: Loss=0.5168, F1 Score=0.8900
Epoch  25/200 | Train: Loss=0.4373, F1 Score=0.9164 | Val: Loss=0.5176, F1 Score=0.8931
Epoch  26/200 | Train: Loss=0.4403, F1 Score=0.9178 | Val: Loss=0.5178, F1 Score=0.8937
Epoch  27/200 | Train: Loss=0.4393, F1 Score=0.9179 | Val: Loss=0.5178, F1 Score=0.8937

[I 2025-11-11 18:16:21,976] Trial 8 finished with value: 0.9027582311027208 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.27091012217979427, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.0006308104295511815, 'weight_decay': 0.0008772591501726385, 'l1_lambda': 1.7526737081254093e-05, 'focal_gamma': 4.0, 'scheduler_patience': 3, 'scheduler_factor': 0.1, 'weight_max_norm': 0.368495533167163}. Best is trial 7 with value: 0.9289077176984794.

Epoch  28/200 | Train: Loss=0.4357, F1 Score=0.9173 | Val: Loss=0.5178, F1 Score=0.8937
Early stopping triggered after 28 epochs.
Best model restored from epoch 13 with val_f1 0.9028
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0980, F1 Score=0.5154 | Val: Loss=1.0762, F1 Score=0.2767
Epoch   2/200 | Train: Loss=1.0704, F1 Score=0.5541 | Val: Loss=1.0499, F1 Score=0.7518
Epoch   3/200 | Train: Loss=1.0397, F1 Score=0.6171 | Val: Loss=1.0306, F1 Score=0.6190
Epoch   4/200 | Train: Loss=0.9881, F1 Score=0.6312 | Val: Loss=0.9618, F1 Score=0.7035
Epoch   5/200 | Train: Loss=0.9385, F1 Score=0.6696 | Val: Loss=0.9070, F1 Score=0.7066

[I 2025-11-11 18:16:27,246] Trial 9 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 20, 'hidden_size': 32, 'num_layers': 1, 'dropout_rate': 0.40886862494296217, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'kaiming_normal', 'lr': 0.0007731017234812488, 'weight_decay': 4.761184106981158e-05, 'l1_lambda': 2.3587821331079846e-07, 'focal_gamma': 4.0, 'scheduler_patience': 6, 'scheduler_factor': 0.2, 'weight_max_norm': 4.103635429758458}. Best is trial 7 with value: 0.9289077176984794.
[I 2025-11-11 18:16:27,251] Trial 10 pruned.

Epoch   6/200 | Train: Loss=0.9219, F1 Score=0.6779 | Val: Loss=0.9318, F1 Score=0.6183
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1790, F1 Score=0.6705 | Val: Loss=1.0954, F1 Score=0.6706
Epoch   2/200 | Train: Loss=1.1663, F1 Score=0.6454 | Val: Loss=1.0951, F1 Score=0.6696
Epoch   3/200 | Train: Loss=1.1662, F1 Score=0.6563 | Val: Loss=1.0945, F1 Score=0.6714
Epoch   4/200 | Train: Loss=1.1654, F1 Score=0.6574 | Val: Loss=1.0935, F1 Score=0.6762

[I 2025-11-11 18:16:34,614] Trial 11 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.26012408394519015, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 1.1967677146008508e-05, 'weight_decay': 6.60281079347458e-06, 'l1_lambda': 9.960159524569733e-06, 'focal_gamma': 3.0, 'scheduler_patience': 8, 'scheduler_factor': 0.2, 'weight_max_norm': 0.5003087489426984}. Best is trial 7 with value: 0.9289077176984794.

Epoch   5/200 | Train: Loss=1.1648, F1 Score=0.6614 | Val: Loss=1.0929, F1 Score=0.6834
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1108, F1 Score=0.5451 | Val: Loss=1.0866, F1 Score=0.6990
Epoch   2/200 | Train: Loss=1.1205, F1 Score=0.7295 | Val: Loss=1.0603, F1 Score=0.7830
Epoch   3/200 | Train: Loss=1.0739, F1 Score=0.6906 | Val: Loss=1.0185, F1 Score=0.6464
Epoch   4/200 | Train: Loss=1.0080, F1 Score=0.6444 | Val: Loss=0.9476, F1 Score=0.7466
Epoch   5/200 | Train: Loss=0.9797, F1 Score=0.6705 | Val: Loss=0.9698, F1 Score=0.6827
Epoch   6/200 | Train: Loss=0.9461, F1 Score=0.6554 | Val: Loss=0.9416, F1 Score=0.6815
Epoch   7/200 | Train: Loss=0.8984, F1 Score=0.7007 | Val: Loss=0.8994, F1 Score=0.7152
Epoch   8/200 | Train: Loss=0.8547, F1 Score=0.7231 | Val: Loss=0.8563, F1 Score=0.8365
Epoch   9/200 | Train: Loss=0.8146, F1 Score=0.7431 | Val: Loss=0.8662, F1 Score=0.7366
Epoch  10/200 | Train: Loss=0.7598, F1 Score=0.7584 | Val: Loss=0.8287, F1 Score=0.8000
Epoch  11/200 | Train: Loss=0.7129, F1 Score=0.7997 | Val: Loss=0.7672, F1 Score=0.8607
Epoch  12/200 | Train: Loss=0.6486, F1 Score=0.8381 | Val: Loss=0.7421, F1 Score=0.8611
Epoch  13/200 | Train: Loss=0.6466, F1 Score=0.8291 | Val: Loss=0.6725, F1 Score=0.8840
Epoch  14/200 | Train: Loss=0.6141, F1 Score=0.8593 | Val: Loss=0.6646, F1 Score=0.8804
Epoch  15/200 | Train: Loss=0.5950, F1 Score=0.8586 | Val: Loss=0.6576, F1 Score=0.8857
Epoch  16/200 | Train: Loss=0.6260, F1 Score=0.8506 | Val: Loss=0.6565, F1 Score=0.8950
Epoch  17/200 | Train: Loss=0.5919, F1 Score=0.8667 | Val: Loss=0.6957, F1 Score=0.8747
Epoch  18/200 | Train: Loss=0.5805, F1 Score=0.8651 | Val: Loss=0.6720, F1 Score=0.8477
Epoch  19/200 | Train: Loss=0.5562, F1 Score=0.8671 | Val: Loss=0.6356, F1 Score=0.9026
Epoch  20/200 | Train: Loss=0.5437, F1 Score=0.8788 | Val: Loss=0.6364, F1 Score=0.8853
Epoch  21/200 | Train: Loss=0.5613, F1 Score=0.8828 | Val: Loss=0.6151, F1 Score=0.9039
Epoch  22/200 | Train: Loss=0.5332, F1 Score=0.8850 | Val: Loss=0.6368, F1 Score=0.8963
Epoch  23/200 | Train: Loss=0.5210, F1 Score=0.8851 | Val: Loss=0.6834, F1 Score=0.7976
Epoch  24/200 | Train: Loss=0.5230, F1 Score=0.8801 | Val: Loss=0.6219, F1 Score=0.8932
Epoch  25/200 | Train: Loss=0.5187, F1 Score=0.8743 | Val: Loss=0.6131, F1 Score=0.8818
Epoch  26/200 | Train: Loss=0.5000, F1 Score=0.8905 | Val: Loss=0.6501, F1 Score=0.8355
Epoch  27/200 | Train: Loss=0.4915, F1 Score=0.8875 | Val: Loss=0.6001, F1 Score=0.8847
Epoch  28/200 | Train: Loss=0.4983, F1 Score=0.8971 | Val: Loss=0.5976, F1 Score=0.8807
Epoch  29/200 | Train: Loss=0.4848, F1 Score=0.8886 | Val: Loss=0.5954, F1 Score=0.8719
Epoch  30/200 | Train: Loss=0.4634, F1 Score=0.8996 | Val: Loss=0.6206, F1 Score=0.8751
Epoch  31/200 | Train: Loss=0.5168, F1 Score=0.9094 | Val: Loss=0.6334, F1 Score=0.8525
Epoch  32/200 | Train: Loss=0.4999, F1 Score=0.9081 | Val: Loss=0.6168, F1 Score=0.8686
Epoch  33/200 | Train: Loss=0.4987, F1 Score=0.9126 | Val: Loss=0.5889, F1 Score=0.8856
Epoch  34/200 | Train: Loss=0.4990, F1 Score=0.9137 | Val: Loss=0.6080, F1 Score=0.8745
Epoch  35/200 | Train: Loss=0.4934, F1 Score=0.9085 | Val: Loss=0.6034, F1 Score=0.8824

[I 2025-11-11 18:17:24,871] Trial 12 finished with value: 0.9038949012473823 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.6802181955485522, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 0.0002733836576288721, 'weight_decay': 0.0007634392265038722, 'l1_lambda': 5.550804789117151e-06, 'focal_gamma': 2.0, 'scheduler_patience': 8, 'scheduler_factor': 0.1, 'weight_max_norm': 0.2624028343534026}. Best is trial 7 with value: 0.9289077176984794.

Epoch  36/200 | Train: Loss=0.4948, F1 Score=0.9107 | Val: Loss=0.6008, F1 Score=0.8807
Early stopping triggered after 36 epochs.
Best model restored from epoch 21 with val_f1 0.9039
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1173, F1 Score=0.4935 | Val: Loss=1.0481, F1 Score=0.7441
Epoch   2/200 | Train: Loss=1.0729, F1 Score=0.5539 | Val: Loss=0.9985, F1 Score=0.7455
Epoch   3/200 | Train: Loss=1.0218, F1 Score=0.6218 | Val: Loss=0.9417, F1 Score=0.7154
Epoch   4/200 | Train: Loss=0.9631, F1 Score=0.6350 | Val: Loss=0.9561, F1 Score=0.6479
Epoch   5/200 | Train: Loss=0.9261, F1 Score=0.6568 | Val: Loss=0.8780, F1 Score=0.7459
Epoch   6/200 | Train: Loss=0.8882, F1 Score=0.6690 | Val: Loss=0.9238, F1 Score=0.5986
Epoch   7/200 | Train: Loss=0.8410, F1 Score=0.6668 | Val: Loss=0.8968, F1 Score=0.6277
Epoch   8/200 | Train: Loss=0.8025, F1 Score=0.7124 | Val: Loss=0.7972, F1 Score=0.6782
Epoch   9/200 | Train: Loss=0.7071, F1 Score=0.7722 | Val: Loss=0.6645, F1 Score=0.7684
Epoch  10/200 | Train: Loss=0.6157, F1 Score=0.8159 | Val: Loss=0.5750, F1 Score=0.8851
Epoch  11/200 | Train: Loss=0.5922, F1 Score=0.8262 | Val: Loss=0.5828, F1 Score=0.8809
Epoch  12/200 | Train: Loss=0.5397, F1 Score=0.8442 | Val: Loss=0.5831, F1 Score=0.8688
Epoch  13/200 | Train: Loss=0.5066, F1 Score=0.8502 | Val: Loss=0.5932, F1 Score=0.8434
Epoch  14/200 | Train: Loss=0.4968, F1 Score=0.8576 | Val: Loss=0.6158, F1 Score=0.8745
Epoch  15/200 | Train: Loss=0.4613, F1 Score=0.8741 | Val: Loss=0.5938, F1 Score=0.8493
Epoch  16/200 | Train: Loss=0.4612, F1 Score=0.8663 | Val: Loss=0.5955, F1 Score=0.8970
Epoch  17/200 | Train: Loss=0.4625, F1 Score=0.8699 | Val: Loss=0.5621, F1 Score=0.8590
Epoch  18/200 | Train: Loss=0.4258, F1 Score=0.8923 | Val: Loss=0.5917, F1 Score=0.8685
Epoch  19/200 | Train: Loss=0.4203, F1 Score=0.8831 | Val: Loss=0.5810, F1 Score=0.8791
Epoch  20/200 | Train: Loss=0.4126, F1 Score=0.8909 | Val: Loss=0.5304, F1 Score=0.8589
Epoch  21/200 | Train: Loss=0.3869, F1 Score=0.8893 | Val: Loss=0.5588, F1 Score=0.8964
Epoch  22/200 | Train: Loss=0.3873, F1 Score=0.8929 | Val: Loss=0.5007, F1 Score=0.8880
Epoch  23/200 | Train: Loss=0.3744, F1 Score=0.8971 | Val: Loss=0.5444, F1 Score=0.8427
Epoch  24/200 | Train: Loss=0.3764, F1 Score=0.8947 | Val: Loss=0.5015, F1 Score=0.8651
Epoch  25/200 | Train: Loss=0.3569, F1 Score=0.8978 | Val: Loss=0.4843, F1 Score=0.8860
Epoch  26/200 | Train: Loss=0.3246, F1 Score=0.9138 | Val: Loss=0.4695, F1 Score=0.8622
Epoch  27/200 | Train: Loss=0.3186, F1 Score=0.9132 | Val: Loss=0.4870, F1 Score=0.8797
Epoch  28/200 | Train: Loss=0.3279, F1 Score=0.9127 | Val: Loss=0.4720, F1 Score=0.8675
Epoch  29/200 | Train: Loss=0.3125, F1 Score=0.9157 | Val: Loss=0.4765, F1 Score=0.8711
Epoch  30/200 | Train: Loss=0.3132, F1 Score=0.9128 | Val: Loss=0.4941, F1 Score=0.8581

[I 2025-11-11 18:18:08,079] Trial 13 finished with value: 0.8969964682609475 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.6980190186233859, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 0.00026754332873123247, 'weight_decay': 7.274180466215137e-06, 'l1_lambda': 3.328713713513749e-06, 'focal_gamma': 2.0, 'scheduler_patience': 8, 'scheduler_factor': 0.2, 'weight_max_norm': 1.921579443688785}. Best is trial 7 with value: 0.9289077176984794.

Epoch  31/200 | Train: Loss=0.3091, F1 Score=0.9174 | Val: Loss=0.5041, F1 Score=0.8745
Early stopping triggered after 31 epochs.
Best model restored from epoch 16 with val_f1 0.8970
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1302, F1 Score=0.5085 | Val: Loss=1.0782, F1 Score=0.2892
Epoch   2/200 | Train: Loss=1.1083, F1 Score=0.5028 | Val: Loss=1.0464, F1 Score=0.6923
Epoch   3/200 | Train: Loss=1.0832, F1 Score=0.5675 | Val: Loss=1.0380, F1 Score=0.4869
Epoch   4/200 | Train: Loss=1.0547, F1 Score=0.6043 | Val: Loss=1.0189, F1 Score=0.4157
Epoch   5/200 | Train: Loss=1.0325, F1 Score=0.6128 | Val: Loss=0.9800, F1 Score=0.7069

[I 2025-11-11 18:18:13,992] Trial 14 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 30, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.6880712883487193, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 0.0002485851741274715, 'weight_decay': 9.410218356409568e-06, 'l1_lambda': 3.655850627012026e-06, 'focal_gamma': 2.0, 'scheduler_patience': 10, 'scheduler_factor': 0.1, 'weight_max_norm': 2.7881741103866444}. Best is trial 7 with value: 0.9289077176984794.

Epoch   6/200 | Train: Loss=0.9996, F1 Score=0.6314 | Val: Loss=0.9627, F1 Score=0.5829
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1449, F1 Score=0.4384 | Val: Loss=1.0718, F1 Score=0.4305
Epoch   2/200 | Train: Loss=1.1167, F1 Score=0.6174 | Val: Loss=1.0389, F1 Score=0.7009
Epoch   3/200 | Train: Loss=1.0735, F1 Score=0.6523 | Val: Loss=0.9831, F1 Score=0.7108
Epoch   4/200 | Train: Loss=1.0080, F1 Score=0.6377 | Val: Loss=0.9270, F1 Score=0.6916
Epoch   5/200 | Train: Loss=0.9592, F1 Score=0.6576 | Val: Loss=0.9006, F1 Score=0.6944
Epoch   6/200 | Train: Loss=0.8934, F1 Score=0.6736 | Val: Loss=0.9407, F1 Score=0.5010
Epoch   7/200 | Train: Loss=0.8557, F1 Score=0.6789 | Val: Loss=0.9080, F1 Score=0.7161
Epoch   8/200 | Train: Loss=0.8140, F1 Score=0.7233 | Val: Loss=0.8824, F1 Score=0.6000
Epoch   9/200 | Train: Loss=0.7347, F1 Score=0.7645 | Val: Loss=0.7076, F1 Score=0.7949
Epoch  10/200 | Train: Loss=0.6686, F1 Score=0.8018 | Val: Loss=0.6662, F1 Score=0.8561
Epoch  11/200 | Train: Loss=0.6289, F1 Score=0.8217 | Val: Loss=0.6336, F1 Score=0.8074
Epoch  12/200 | Train: Loss=0.5750, F1 Score=0.8492 | Val: Loss=0.6349, F1 Score=0.8136
Epoch  13/200 | Train: Loss=0.5728, F1 Score=0.8290 | Val: Loss=0.6276, F1 Score=0.8395
Epoch  14/200 | Train: Loss=0.5289, F1 Score=0.8493 | Val: Loss=0.5840, F1 Score=0.8549
Epoch  15/200 | Train: Loss=0.5139, F1 Score=0.8481 | Val: Loss=0.5544, F1 Score=0.8600
Epoch  16/200 | Train: Loss=0.5229, F1 Score=0.8514 | Val: Loss=0.6660, F1 Score=0.8010
Epoch  17/200 | Train: Loss=0.4817, F1 Score=0.8619 | Val: Loss=0.6011, F1 Score=0.8675
Epoch  18/200 | Train: Loss=0.4781, F1 Score=0.8541 | Val: Loss=0.5577, F1 Score=0.8683

[I 2025-11-11 18:18:40,467] Trial 15 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.5793755507966316, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 0.0002371462573652324, 'weight_decay': 0.0007828960735590047, 'l1_lambda': 6.736876006848477e-06, 'focal_gamma': 3.0, 'scheduler_patience': 9, 'scheduler_factor': 0.2, 'weight_max_norm': 1.289238318843743}. Best is trial 7 with value: 0.9289077176984794.

Epoch  19/200 | Train: Loss=0.4558, F1 Score=0.8713 | Val: Loss=0.5930, F1 Score=0.8569
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1008, F1 Score=0.5067 | Val: Loss=1.0530, F1 Score=0.5747
Epoch   2/200 | Train: Loss=1.0559, F1 Score=0.5975 | Val: Loss=1.0053, F1 Score=0.7771
Epoch   3/200 | Train: Loss=1.0033, F1 Score=0.6249 | Val: Loss=0.9634, F1 Score=0.5588
Epoch   4/200 | Train: Loss=0.9488, F1 Score=0.6210 | Val: Loss=0.8989, F1 Score=0.7845
Epoch   5/200 | Train: Loss=0.9183, F1 Score=0.6812 | Val: Loss=0.8851, F1 Score=0.7878
Epoch   6/200 | Train: Loss=0.8798, F1 Score=0.6811 | Val: Loss=0.8421, F1 Score=0.7701
Epoch   7/200 | Train: Loss=0.8527, F1 Score=0.6947 | Val: Loss=0.8072, F1 Score=0.7759
Epoch   8/200 | Train: Loss=0.8163, F1 Score=0.7130 | Val: Loss=0.7907, F1 Score=0.7040
Epoch   9/200 | Train: Loss=0.7626, F1 Score=0.7398 | Val: Loss=0.8495, F1 Score=0.7910

[I 2025-11-11 18:18:50,063] Trial 16 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 30, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.518343341073207, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 0.0003158574870339037, 'weight_decay': 0.00018354911318928087, 'l1_lambda': 1.547087316035634e-06, 'focal_gamma': 2.0, 'scheduler_patience': 7, 'scheduler_factor': 0.1, 'weight_max_norm': 3.6436939828050225}. Best is trial 7 with value: 0.9289077176984794.
[I 2025-11-11 18:18:50,067] Trial 17 pruned.

Epoch  10/200 | Train: Loss=0.7504, F1 Score=0.7351 | Val: Loss=0.7083, F1 Score=0.7971
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0997, F1 Score=0.5043 | Val: Loss=1.0655, F1 Score=0.4664
Epoch   2/200 | Train: Loss=1.0607, F1 Score=0.5605 | Val: Loss=1.0144, F1 Score=0.5834
Epoch   3/200 | Train: Loss=1.0232, F1 Score=0.5714 | Val: Loss=1.0055, F1 Score=0.5185
Epoch   4/200 | Train: Loss=0.9713, F1 Score=0.6196 | Val: Loss=0.9666, F1 Score=0.6394

[I 2025-11-11 18:18:57,634] Trial 18 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.6334158843876434, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 0.00016253569928226298, 'weight_decay': 1.8273783504290052e-05, 'l1_lambda': 1.3737242895680351e-06, 'focal_gamma': 3.0, 'scheduler_patience': 7, 'scheduler_factor': 0.2, 'weight_max_norm': 2.4749325816753096}. Best is trial 7 with value: 0.9289077176984794.

Epoch   5/200 | Train: Loss=0.9551, F1 Score=0.6313 | Val: Loss=0.9245, F1 Score=0.6865
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.8754, F1 Score=0.4985 | Val: Loss=1.0886, F1 Score=0.6934
Epoch   2/200 | Train: Loss=1.8620, F1 Score=0.5207 | Val: Loss=1.0820, F1 Score=0.5610
Epoch   3/200 | Train: Loss=1.8449, F1 Score=0.5812 | Val: Loss=1.0733, F1 Score=0.6251
Epoch   4/200 | Train: Loss=1.8295, F1 Score=0.5451 | Val: Loss=1.0654, F1 Score=0.6894
Epoch   5/200 | Train: Loss=1.8160, F1 Score=0.6155 | Val: Loss=1.0576, F1 Score=0.6644

[I 2025-11-11 18:19:04,416] Trial 19 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 30, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.4893926009009242, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 2.5769203237765417e-05, 'weight_decay': 0.00013064898260389105, 'l1_lambda': 2.12287880617888e-05, 'focal_gamma': 1.5, 'scheduler_patience': 9, 'scheduler_factor': 0.1, 'weight_max_norm': 4.615421452561872}. Best is trial 7 with value: 0.9289077176984794.
[I 2025-11-11 18:19:04,420] Trial 20 pruned.

Epoch   6/200 | Train: Loss=1.8013, F1 Score=0.5685 | Val: Loss=1.0545, F1 Score=0.4834
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1894, F1 Score=0.5758 | Val: Loss=1.0874, F1 Score=0.3677
Epoch   2/200 | Train: Loss=1.1127, F1 Score=0.6075 | Val: Loss=1.0045, F1 Score=0.6478
Epoch   3/200 | Train: Loss=1.0451, F1 Score=0.6771 | Val: Loss=0.9199, F1 Score=0.7868
Epoch   4/200 | Train: Loss=0.9901, F1 Score=0.6638 | Val: Loss=0.9005, F1 Score=0.8101
Epoch   5/200 | Train: Loss=0.9303, F1 Score=0.6662 | Val: Loss=0.8657, F1 Score=0.7579
Epoch   6/200 | Train: Loss=0.8737, F1 Score=0.7268 | Val: Loss=0.8178, F1 Score=0.7697
Epoch   7/200 | Train: Loss=0.7912, F1 Score=0.7629 | Val: Loss=0.7314, F1 Score=0.8791
Epoch   8/200 | Train: Loss=0.6828, F1 Score=0.8338 | Val: Loss=0.6832, F1 Score=0.8758
Epoch   9/200 | Train: Loss=0.6469, F1 Score=0.8363 | Val: Loss=0.6840, F1 Score=0.8434
Epoch  10/200 | Train: Loss=0.6180, F1 Score=0.8522 | Val: Loss=0.6295, F1 Score=0.8453
Epoch  11/200 | Train: Loss=0.6046, F1 Score=0.8449 | Val: Loss=0.6387, F1 Score=0.8073
Epoch  12/200 | Train: Loss=0.5826, F1 Score=0.8609 | Val: Loss=0.6094, F1 Score=0.8850
Epoch  13/200 | Train: Loss=0.5493, F1 Score=0.8709 | Val: Loss=0.7312, F1 Score=0.8321
Epoch  14/200 | Train: Loss=0.5396, F1 Score=0.8649 | Val: Loss=0.6119, F1 Score=0.8525
Epoch  15/200 | Train: Loss=0.5265, F1 Score=0.8722 | Val: Loss=0.5703, F1 Score=0.8703
Epoch  16/200 | Train: Loss=0.5295, F1 Score=0.8730 | Val: Loss=0.6441, F1 Score=0.8594
Epoch  17/200 | Train: Loss=0.5266, F1 Score=0.8848 | Val: Loss=0.5715, F1 Score=0.8727
Epoch  18/200 | Train: Loss=0.5154, F1 Score=0.8823 | Val: Loss=0.5490, F1 Score=0.8816
Epoch  19/200 | Train: Loss=0.5245, F1 Score=0.8809 | Val: Loss=0.5958, F1 Score=0.8666
Epoch  20/200 | Train: Loss=0.5519, F1 Score=0.8727 | Val: Loss=0.5774, F1 Score=0.8935
Epoch  21/200 | Train: Loss=0.4835, F1 Score=0.8934 | Val: Loss=0.6026, F1 Score=0.8401
Epoch  22/200 | Train: Loss=0.4761, F1 Score=0.8933 | Val: Loss=0.5988, F1 Score=0.8718
Epoch  23/200 | Train: Loss=0.4528, F1 Score=0.8992 | Val: Loss=0.6177, F1 Score=0.8717
Epoch  24/200 | Train: Loss=0.4533, F1 Score=0.9024 | Val: Loss=0.6356, F1 Score=0.8724
Epoch  25/200 | Train: Loss=0.4630, F1 Score=0.8991 | Val: Loss=0.5842, F1 Score=0.8750
Epoch  26/200 | Train: Loss=0.4666, F1 Score=0.8964 | Val: Loss=0.5344, F1 Score=0.8927
Epoch  27/200 | Train: Loss=0.4573, F1 Score=0.8898 | Val: Loss=0.5900, F1 Score=0.8702
Epoch  28/200 | Train: Loss=0.4333, F1 Score=0.9075 | Val: Loss=0.6212, F1 Score=0.8776
Epoch  29/200 | Train: Loss=0.4253, F1 Score=0.9050 | Val: Loss=0.6132, F1 Score=0.8748
Epoch  30/200 | Train: Loss=0.4518, F1 Score=0.8990 | Val: Loss=0.6273, F1 Score=0.8697
Epoch  31/200 | Train: Loss=0.4503, F1 Score=0.9212 | Val: Loss=0.5551, F1 Score=0.8767
Epoch  32/200 | Train: Loss=0.4271, F1 Score=0.9185 | Val: Loss=0.5535, F1 Score=0.8816
Epoch  33/200 | Train: Loss=0.4226, F1 Score=0.9150 | Val: Loss=0.5630, F1 Score=0.8760
Epoch  34/200 | Train: Loss=0.4175, F1 Score=0.9180 | Val: Loss=0.5733, F1 Score=0.8837
Epoch  35/200 | Train: Loss=0.4174, F1 Score=0.9140 | Val: Loss=0.5575, F1 Score=0.8938
Epoch  36/200 | Train: Loss=0.4140, F1 Score=0.9199 | Val: Loss=0.6064, F1 Score=0.8583
Epoch  37/200 | Train: Loss=0.4138, F1 Score=0.9177 | Val: Loss=0.5718, F1 Score=0.8798
Epoch  38/200 | Train: Loss=0.4087, F1 Score=0.9190 | Val: Loss=0.5878, F1 Score=0.8838
Epoch  39/200 | Train: Loss=0.4059, F1 Score=0.9198 | Val: Loss=0.5887, F1 Score=0.8835
Epoch  40/200 | Train: Loss=0.4109, F1 Score=0.9229 | Val: Loss=0.5552, F1 Score=0.8952
Epoch  41/200 | Train: Loss=0.4135, F1 Score=0.9184 | Val: Loss=0.5784, F1 Score=0.8845
Epoch  42/200 | Train: Loss=0.4034, F1 Score=0.9194 | Val: Loss=0.5589, F1 Score=0.8890
Epoch  43/200 | Train: Loss=0.4053, F1 Score=0.9213 | Val: Loss=0.5898, F1 Score=0.8820
Epoch  44/200 | Train: Loss=0.4088, F1 Score=0.9182 | Val: Loss=0.5922, F1 Score=0.8773
Epoch  45/200 | Train: Loss=0.4009, F1 Score=0.9229 | Val: Loss=0.5643, F1 Score=0.8834
Epoch  46/200 | Train: Loss=0.3980, F1 Score=0.9206 | Val: Loss=0.5999, F1 Score=0.8773
Epoch  47/200 | Train: Loss=0.4010, F1 Score=0.9199 | Val: Loss=0.5733, F1 Score=0.8840
Epoch  48/200 | Train: Loss=0.3994, F1 Score=0.9230 | Val: Loss=0.5710, F1 Score=0.8853
Epoch  49/200 | Train: Loss=0.3991, F1 Score=0.9197 | Val: Loss=0.5985, F1 Score=0.8795
Epoch  50/200 | Train: Loss=0.3939, F1 Score=0.9235 | Val: Loss=0.5926, F1 Score=0.8816

[I 2025-11-11 18:20:26,881] Trial 21 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.3030470429083013, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.00044544923028273916, 'weight_decay': 0.0009479744352493346, 'l1_lambda': 1.1731401335303297e-05, 'focal_gamma': 4.0, 'scheduler_patience': 9, 'scheduler_factor': 0.1, 'weight_max_norm': 0.3490814337795811}. Best is trial 7 with value: 0.9289077176984794.

Epoch  51/200 | Train: Loss=0.4063, F1 Score=0.9192 | Val: Loss=0.5888, F1 Score=0.8845
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1039, F1 Score=0.5259 | Val: Loss=1.0344, F1 Score=0.5916
Epoch   2/200 | Train: Loss=1.0187, F1 Score=0.6514 | Val: Loss=0.9895, F1 Score=0.4910
Epoch   3/200 | Train: Loss=0.9418, F1 Score=0.6227 | Val: Loss=0.8374, F1 Score=0.7842
Epoch   4/200 | Train: Loss=0.9105, F1 Score=0.6624 | Val: Loss=0.8883, F1 Score=0.5945
Epoch   5/200 | Train: Loss=0.8160, F1 Score=0.7243 | Val: Loss=0.6863, F1 Score=0.8225
Epoch   6/200 | Train: Loss=0.7051, F1 Score=0.7874 | Val: Loss=0.6014, F1 Score=0.8293
Epoch   7/200 | Train: Loss=0.6671, F1 Score=0.7882 | Val: Loss=0.6094, F1 Score=0.8555
Epoch   8/200 | Train: Loss=0.6234, F1 Score=0.8150 | Val: Loss=0.5824, F1 Score=0.8120
Epoch   9/200 | Train: Loss=0.5980, F1 Score=0.8254 | Val: Loss=0.5374, F1 Score=0.8414
Epoch  10/200 | Train: Loss=0.5382, F1 Score=0.8380 | Val: Loss=0.5836, F1 Score=0.8647
Epoch  11/200 | Train: Loss=0.5676, F1 Score=0.8257 | Val: Loss=0.5732, F1 Score=0.7483
Epoch  12/200 | Train: Loss=0.4972, F1 Score=0.8470 | Val: Loss=0.4561, F1 Score=0.8283
Epoch  13/200 | Train: Loss=0.4545, F1 Score=0.8589 | Val: Loss=0.4666, F1 Score=0.8053
Epoch  14/200 | Train: Loss=0.4705, F1 Score=0.8456 | Val: Loss=0.4185, F1 Score=0.8528
Epoch  15/200 | Train: Loss=0.4191, F1 Score=0.8697 | Val: Loss=0.4076, F1 Score=0.8816
Epoch  16/200 | Train: Loss=0.3769, F1 Score=0.8644 | Val: Loss=0.4788, F1 Score=0.8445
Epoch  17/200 | Train: Loss=0.4537, F1 Score=0.8516 | Val: Loss=0.3810, F1 Score=0.8957
Epoch  18/200 | Train: Loss=0.3435, F1 Score=0.9002 | Val: Loss=0.3628, F1 Score=0.8636
Epoch  19/200 | Train: Loss=0.3375, F1 Score=0.8869 | Val: Loss=0.3332, F1 Score=0.9221
Epoch  20/200 | Train: Loss=0.3289, F1 Score=0.8992 | Val: Loss=0.3918, F1 Score=0.8091
Epoch  21/200 | Train: Loss=0.3074, F1 Score=0.9020 | Val: Loss=0.3746, F1 Score=0.8608
Epoch  22/200 | Train: Loss=0.3009, F1 Score=0.8977 | Val: Loss=0.3047, F1 Score=0.8940
Epoch  23/200 | Train: Loss=0.2548, F1 Score=0.9214 | Val: Loss=0.3213, F1 Score=0.8625
Epoch  24/200 | Train: Loss=0.2808, F1 Score=0.9070 | Val: Loss=0.3354, F1 Score=0.9054
Epoch  25/200 | Train: Loss=0.3291, F1 Score=0.8929 | Val: Loss=0.2718, F1 Score=0.8943
Epoch  26/200 | Train: Loss=0.2391, F1 Score=0.9206 | Val: Loss=0.2394, F1 Score=0.9044
Epoch  27/200 | Train: Loss=0.2556, F1 Score=0.9140 | Val: Loss=0.3440, F1 Score=0.8577
Epoch  28/200 | Train: Loss=0.2129, F1 Score=0.9297 | Val: Loss=0.2659, F1 Score=0.8900
Epoch  29/200 | Train: Loss=0.2006, F1 Score=0.9347 | Val: Loss=0.2687, F1 Score=0.8865
Epoch  30/200 | Train: Loss=0.1944, F1 Score=0.9374 | Val: Loss=0.2731, F1 Score=0.8803
Epoch  31/200 | Train: Loss=0.1878, F1 Score=0.9369 | Val: Loss=0.2741, F1 Score=0.8818
Epoch  32/200 | Train: Loss=0.1877, F1 Score=0.9337 | Val: Loss=0.2601, F1 Score=0.8902
Epoch  33/200 | Train: Loss=0.1851, F1 Score=0.9387 | Val: Loss=0.2674, F1 Score=0.8916

[I 2025-11-11 18:21:21,893] Trial 22 finished with value: 0.9220596167383627 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.19907523001258187, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.0004557146174242735, 'weight_decay': 0.00047503524452452103, 'l1_lambda': 5.533984798885019e-06, 'focal_gamma': 5.0, 'scheduler_patience': 7, 'scheduler_factor': 0.1, 'weight_max_norm': 1.187827619214362}. Best is trial 7 with value: 0.9289077176984794.

Epoch  34/200 | Train: Loss=0.1841, F1 Score=0.9388 | Val: Loss=0.2612, F1 Score=0.8907
Early stopping triggered after 34 epochs.
Best model restored from epoch 19 with val_f1 0.9221
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1449, F1 Score=0.6185 | Val: Loss=1.0912, F1 Score=0.2959
Epoch   2/200 | Train: Loss=1.1249, F1 Score=0.6226 | Val: Loss=1.0534, F1 Score=0.4206
Epoch   3/200 | Train: Loss=1.0479, F1 Score=0.6628 | Val: Loss=0.9319, F1 Score=0.7571
Epoch   4/200 | Train: Loss=0.9868, F1 Score=0.6696 | Val: Loss=0.9088, F1 Score=0.7170
Epoch   5/200 | Train: Loss=0.9504, F1 Score=0.6742 | Val: Loss=0.9398, F1 Score=0.6558
Epoch   6/200 | Train: Loss=0.9209, F1 Score=0.6820 | Val: Loss=0.8660, F1 Score=0.6970
Epoch   7/200 | Train: Loss=0.8882, F1 Score=0.6838 | Val: Loss=0.8540, F1 Score=0.7080
Epoch   8/200 | Train: Loss=0.8575, F1 Score=0.6739 | Val: Loss=0.8630, F1 Score=0.7260

[I 2025-11-11 18:21:36,816] Trial 23 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.1889183950472207, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.00016097955067770418, 'weight_decay': 0.00042204877570526023, 'l1_lambda': 5.542877680154616e-06, 'focal_gamma': 5.0, 'scheduler_patience': 7, 'scheduler_factor': 0.1, 'weight_max_norm': 1.063608889835593}. Best is trial 7 with value: 0.9289077176984794.

Epoch   9/200 | Train: Loss=0.8347, F1 Score=0.7017 | Val: Loss=0.8798, F1 Score=0.6271
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0876, F1 Score=0.5179 | Val: Loss=1.0546, F1 Score=0.7570
Epoch   2/200 | Train: Loss=1.0277, F1 Score=0.6572 | Val: Loss=1.0391, F1 Score=0.3740
Epoch   3/200 | Train: Loss=0.9523, F1 Score=0.6352 | Val: Loss=0.9646, F1 Score=0.5960
Epoch   4/200 | Train: Loss=0.8954, F1 Score=0.6392 | Val: Loss=0.9397, F1 Score=0.6327
Epoch   5/200 | Train: Loss=0.8182, F1 Score=0.6793 | Val: Loss=0.8347, F1 Score=0.6967
Epoch   6/200 | Train: Loss=0.7188, F1 Score=0.7582 | Val: Loss=0.6904, F1 Score=0.8213
Epoch   7/200 | Train: Loss=0.6295, F1 Score=0.7996 | Val: Loss=0.6762, F1 Score=0.7923
Epoch   8/200 | Train: Loss=0.5618, F1 Score=0.8403 | Val: Loss=0.6829, F1 Score=0.7867
Epoch   9/200 | Train: Loss=0.5316, F1 Score=0.8400 | Val: Loss=0.6046, F1 Score=0.8690
Epoch  10/200 | Train: Loss=0.5330, F1 Score=0.8435 | Val: Loss=0.6047, F1 Score=0.8887
Epoch  11/200 | Train: Loss=0.5193, F1 Score=0.8441 | Val: Loss=0.5684, F1 Score=0.8684
Epoch  12/200 | Train: Loss=0.4569, F1 Score=0.8688 | Val: Loss=0.7642, F1 Score=0.7338
Epoch  13/200 | Train: Loss=0.4605, F1 Score=0.8608 | Val: Loss=0.5751, F1 Score=0.8797
Epoch  14/200 | Train: Loss=0.4211, F1 Score=0.8749 | Val: Loss=0.5810, F1 Score=0.8187
Epoch  15/200 | Train: Loss=0.4299, F1 Score=0.8839 | Val: Loss=0.5883, F1 Score=0.8548
Epoch  16/200 | Train: Loss=0.4513, F1 Score=0.8611 | Val: Loss=0.5321, F1 Score=0.8646
Epoch  17/200 | Train: Loss=0.3946, F1 Score=0.8845 | Val: Loss=0.4950, F1 Score=0.9018
Epoch  18/200 | Train: Loss=0.3808, F1 Score=0.8941 | Val: Loss=0.4284, F1 Score=0.8896
Epoch  19/200 | Train: Loss=0.3821, F1 Score=0.8984 | Val: Loss=0.4450, F1 Score=0.8866
Epoch  20/200 | Train: Loss=0.3661, F1 Score=0.8974 | Val: Loss=0.4976, F1 Score=0.8623
Epoch  21/200 | Train: Loss=0.3549, F1 Score=0.8949 | Val: Loss=0.5643, F1 Score=0.8749
Epoch  22/200 | Train: Loss=0.3503, F1 Score=0.8950 | Val: Loss=0.4899, F1 Score=0.8645
Epoch  23/200 | Train: Loss=0.3275, F1 Score=0.9057 | Val: Loss=0.5146, F1 Score=0.8592
Epoch  24/200 | Train: Loss=0.3336, F1 Score=0.9035 | Val: Loss=0.4411, F1 Score=0.8707
Epoch  25/200 | Train: Loss=0.3393, F1 Score=0.8963 | Val: Loss=0.4873, F1 Score=0.8343
Epoch  26/200 | Train: Loss=0.3182, F1 Score=0.8979 | Val: Loss=0.4416, F1 Score=0.8865
Epoch  27/200 | Train: Loss=0.2804, F1 Score=0.9160 | Val: Loss=0.4461, F1 Score=0.8710
Epoch  28/200 | Train: Loss=0.2668, F1 Score=0.9173 | Val: Loss=0.4271, F1 Score=0.8805
Epoch  29/200 | Train: Loss=0.2561, F1 Score=0.9178 | Val: Loss=0.4517, F1 Score=0.8681
Epoch  30/200 | Train: Loss=0.2575, F1 Score=0.9220 | Val: Loss=0.4261, F1 Score=0.8768
Epoch  31/200 | Train: Loss=0.2535, F1 Score=0.9210 | Val: Loss=0.4537, F1 Score=0.8738

[I 2025-11-11 18:22:21,581] Trial 24 finished with value: 0.9018414408935861 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.4552646737933421, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.00045970988049309525, 'weight_decay': 0.0003979381215590131, 'l1_lambda': 1.7379061954775795e-06, 'focal_gamma': 2.5, 'scheduler_patience': 8, 'scheduler_factor': 0.1, 'weight_max_norm': 1.0384316802654452}. Best is trial 7 with value: 0.9289077176984794.

Epoch  32/200 | Train: Loss=0.2511, F1 Score=0.9201 | Val: Loss=0.4548, F1 Score=0.8654
Early stopping triggered after 32 epochs.
Best model restored from epoch 17 with val_f1 0.9018
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0990, F1 Score=0.5419 | Val: Loss=1.0977, F1 Score=0.7413
Epoch   2/200 | Train: Loss=1.0981, F1 Score=0.4574 | Val: Loss=1.0962, F1 Score=0.7084
Epoch   3/200 | Train: Loss=1.0970, F1 Score=0.6433 | Val: Loss=1.0942, F1 Score=0.6869
Epoch   4/200 | Train: Loss=1.0965, F1 Score=0.6832 | Val: Loss=1.0925, F1 Score=0.6802
Epoch   5/200 | Train: Loss=1.0939, F1 Score=0.6997 | Val: Loss=1.0877, F1 Score=0.6823
Epoch   6/200 | Train: Loss=1.0789, F1 Score=0.7026 | Val: Loss=1.0544, F1 Score=0.7001

[I 2025-11-11 18:22:30,695] Trial 25 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.6315363273755867, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'kaiming_normal', 'lr': 0.00015299880309353558, 'weight_decay': 8.531644687086415e-05, 'l1_lambda': 1.1819428776529075e-07, 'focal_gamma': 4.5, 'scheduler_patience': 6, 'scheduler_factor': 0.1, 'weight_max_norm': 0.13212593053552418}. Best is trial 7 with value: 0.9289077176984794.

Epoch   7/200 | Train: Loss=1.0287, F1 Score=0.6495 | Val: Loss=1.0275, F1 Score=0.6782
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0871, F1 Score=0.5964 | Val: Loss=1.0534, F1 Score=0.3925
Epoch   2/200 | Train: Loss=0.9779, F1 Score=0.6312 | Val: Loss=0.8543, F1 Score=0.7645
Epoch   3/200 | Train: Loss=0.8943, F1 Score=0.6622 | Val: Loss=0.8873, F1 Score=0.6104
Epoch   4/200 | Train: Loss=0.8417, F1 Score=0.7089 | Val: Loss=0.7471, F1 Score=0.7866
Epoch   5/200 | Train: Loss=0.7193, F1 Score=0.7871 | Val: Loss=0.6530, F1 Score=0.8215
Epoch   6/200 | Train: Loss=0.6331, F1 Score=0.8160 | Val: Loss=0.5592, F1 Score=0.8667
Epoch   7/200 | Train: Loss=0.5692, F1 Score=0.8370 | Val: Loss=0.6409, F1 Score=0.8083
Epoch   8/200 | Train: Loss=0.5430, F1 Score=0.8426 | Val: Loss=0.4905, F1 Score=0.8570
Epoch   9/200 | Train: Loss=0.5172, F1 Score=0.8597 | Val: Loss=0.6346, F1 Score=0.8269
Epoch  10/200 | Train: Loss=0.4530, F1 Score=0.8724 | Val: Loss=0.4468, F1 Score=0.8756
Epoch  11/200 | Train: Loss=0.4510, F1 Score=0.8707 | Val: Loss=0.4309, F1 Score=0.8901
Epoch  12/200 | Train: Loss=0.4079, F1 Score=0.8778 | Val: Loss=0.3696, F1 Score=0.9083
Epoch  13/200 | Train: Loss=0.3753, F1 Score=0.8794 | Val: Loss=0.4552, F1 Score=0.8119
Epoch  14/200 | Train: Loss=0.3691, F1 Score=0.8756 | Val: Loss=0.3078, F1 Score=0.9115
Epoch  15/200 | Train: Loss=0.3183, F1 Score=0.8945 | Val: Loss=0.4038, F1 Score=0.8180
Epoch  16/200 | Train: Loss=0.3057, F1 Score=0.8903 | Val: Loss=0.2976, F1 Score=0.9346
Epoch  17/200 | Train: Loss=0.3131, F1 Score=0.8935 | Val: Loss=0.3881, F1 Score=0.8728
Epoch  18/200 | Train: Loss=0.2639, F1 Score=0.9082 | Val: Loss=0.3078, F1 Score=0.9025
Epoch  19/200 | Train: Loss=0.2578, F1 Score=0.9129 | Val: Loss=0.3422, F1 Score=0.8906
Epoch  20/200 | Train: Loss=0.2367, F1 Score=0.9166 | Val: Loss=0.3109, F1 Score=0.9085
Epoch  21/200 | Train: Loss=0.2142, F1 Score=0.9248 | Val: Loss=0.2943, F1 Score=0.9079
Epoch  22/200 | Train: Loss=0.2155, F1 Score=0.9272 | Val: Loss=0.3456, F1 Score=0.8975
Epoch  23/200 | Train: Loss=0.2415, F1 Score=0.9127 | Val: Loss=0.5599, F1 Score=0.8161
Epoch  24/200 | Train: Loss=0.2066, F1 Score=0.9214 | Val: Loss=0.3638, F1 Score=0.9076
Epoch  25/200 | Train: Loss=0.1748, F1 Score=0.9339 | Val: Loss=0.3268, F1 Score=0.9137
Epoch  26/200 | Train: Loss=0.1621, F1 Score=0.9346 | Val: Loss=0.3328, F1 Score=0.8925
Epoch  27/200 | Train: Loss=0.1586, F1 Score=0.9347 | Val: Loss=0.3129, F1 Score=0.9171
Epoch  28/200 | Train: Loss=0.1589, F1 Score=0.9377 | Val: Loss=0.3127, F1 Score=0.8991
Epoch  29/200 | Train: Loss=0.1478, F1 Score=0.9425 | Val: Loss=0.3231, F1 Score=0.9010
Epoch  30/200 | Train: Loss=0.1503, F1 Score=0.9382 | Val: Loss=0.3424, F1 Score=0.8995

[I 2025-11-11 18:23:23,935] Trial 26 finished with value: 0.9346398721646666 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.5398212462846596, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00039606659384819283, 'weight_decay': 1.8817337191334556e-05, 'l1_lambda': 2.2891312791982454e-06, 'focal_gamma': 3.5, 'scheduler_patience': 7, 'scheduler_factor': 0.2, 'weight_max_norm': 2.15292750525708}. Best is trial 26 with value: 0.9346398721646666.

Epoch  31/200 | Train: Loss=0.1526, F1 Score=0.9372 | Val: Loss=0.3221, F1 Score=0.9059
Early stopping triggered after 31 epochs.
Best model restored from epoch 16 with val_f1 0.9346
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0729, F1 Score=0.5827 | Val: Loss=0.8634, F1 Score=0.7334
Epoch   2/200 | Train: Loss=0.9247, F1 Score=0.6589 | Val: Loss=1.0529, F1 Score=0.3472
Epoch   3/200 | Train: Loss=0.7424, F1 Score=0.7692 | Val: Loss=0.4642, F1 Score=0.8903
Epoch   4/200 | Train: Loss=0.5879, F1 Score=0.8408 | Val: Loss=0.5461, F1 Score=0.8800
Epoch   5/200 | Train: Loss=0.5520, F1 Score=0.8450 | Val: Loss=0.5569, F1 Score=0.8729
Epoch   6/200 | Train: Loss=0.4957, F1 Score=0.8610 | Val: Loss=0.7131, F1 Score=0.7169
Epoch   7/200 | Train: Loss=0.4533, F1 Score=0.8703 | Val: Loss=0.4173, F1 Score=0.8903
Epoch   8/200 | Train: Loss=0.4229, F1 Score=0.8858 | Val: Loss=0.5531, F1 Score=0.8117
Epoch   9/200 | Train: Loss=0.3446, F1 Score=0.9080 | Val: Loss=0.4227, F1 Score=0.9002
Epoch  10/200 | Train: Loss=0.3638, F1 Score=0.8962 | Val: Loss=0.5385, F1 Score=0.8042
Epoch  11/200 | Train: Loss=0.3356, F1 Score=0.9039 | Val: Loss=0.6064, F1 Score=0.8557
Epoch  12/200 | Train: Loss=0.3356, F1 Score=0.9028 | Val: Loss=0.3795, F1 Score=0.9138
Epoch  13/200 | Train: Loss=0.2731, F1 Score=0.9184 | Val: Loss=0.3369, F1 Score=0.8792
Epoch  14/200 | Train: Loss=0.2291, F1 Score=0.9350 | Val: Loss=0.4007, F1 Score=0.8910
Epoch  15/200 | Train: Loss=0.2218, F1 Score=0.9314 | Val: Loss=0.4054, F1 Score=0.8702
Epoch  16/200 | Train: Loss=0.2279, F1 Score=0.9260 | Val: Loss=0.4247, F1 Score=0.8943
Epoch  17/200 | Train: Loss=0.2247, F1 Score=0.9317 | Val: Loss=0.3048, F1 Score=0.9147
Epoch  18/200 | Train: Loss=0.1874, F1 Score=0.9423 | Val: Loss=0.3263, F1 Score=0.9159
Epoch  19/200 | Train: Loss=0.2166, F1 Score=0.9330 | Val: Loss=0.3837, F1 Score=0.9133
Epoch  20/200 | Train: Loss=0.1879, F1 Score=0.9398 | Val: Loss=0.5662, F1 Score=0.8394
Epoch  21/200 | Train: Loss=0.2158, F1 Score=0.9323 | Val: Loss=0.3992, F1 Score=0.9079
Epoch  22/200 | Train: Loss=0.1621, F1 Score=0.9534 | Val: Loss=0.3364, F1 Score=0.9089
Epoch  23/200 | Train: Loss=0.1717, F1 Score=0.9456 | Val: Loss=0.4324, F1 Score=0.9222
Epoch  24/200 | Train: Loss=0.1475, F1 Score=0.9544 | Val: Loss=0.3490, F1 Score=0.8941
Epoch  25/200 | Train: Loss=0.2673, F1 Score=0.9227 | Val: Loss=0.4138, F1 Score=0.8937
Epoch  26/200 | Train: Loss=0.1844, F1 Score=0.9472 | Val: Loss=0.2704, F1 Score=0.9116
Epoch  27/200 | Train: Loss=0.1685, F1 Score=0.9528 | Val: Loss=0.3946, F1 Score=0.8841
Epoch  28/200 | Train: Loss=0.1830, F1 Score=0.9517 | Val: Loss=0.3813, F1 Score=0.9322
Epoch  29/200 | Train: Loss=0.1287, F1 Score=0.9626 | Val: Loss=0.2495, F1 Score=0.9432
Epoch  30/200 | Train: Loss=0.1562, F1 Score=0.9534 | Val: Loss=0.4701, F1 Score=0.8699
Epoch  31/200 | Train: Loss=0.1503, F1 Score=0.9558 | Val: Loss=0.3059, F1 Score=0.9094
Epoch  32/200 | Train: Loss=0.1204, F1 Score=0.9692 | Val: Loss=0.3048, F1 Score=0.9273
Epoch  33/200 | Train: Loss=0.2035, F1 Score=0.9425 | Val: Loss=0.5812, F1 Score=0.9083
Epoch  34/200 | Train: Loss=0.1665, F1 Score=0.9560 | Val: Loss=0.3554, F1 Score=0.9306
Epoch  35/200 | Train: Loss=0.1725, F1 Score=0.9567 | Val: Loss=0.9051, F1 Score=0.7706
Epoch  36/200 | Train: Loss=0.1725, F1 Score=0.9623 | Val: Loss=0.2885, F1 Score=0.9156
Epoch  37/200 | Train: Loss=0.0989, F1 Score=0.9812 | Val: Loss=0.2727, F1 Score=0.9168
Epoch  38/200 | Train: Loss=0.0941, F1 Score=0.9831 | Val: Loss=0.2707, F1 Score=0.9330
Epoch  39/200 | Train: Loss=0.0902, F1 Score=0.9829 | Val: Loss=0.2643, F1 Score=0.9446
Epoch  40/200 | Train: Loss=0.0866, F1 Score=0.9876 | Val: Loss=0.2726, F1 Score=0.9351
Epoch  41/200 | Train: Loss=0.0838, F1 Score=0.9864 | Val: Loss=0.2706, F1 Score=0.9336
Epoch  42/200 | Train: Loss=0.0824, F1 Score=0.9880 | Val: Loss=0.2747, F1 Score=0.9342
Epoch  43/200 | Train: Loss=0.0781, F1 Score=0.9898 | Val: Loss=0.2671, F1 Score=0.9416
Epoch  44/200 | Train: Loss=0.0853, F1 Score=0.9865 | Val: Loss=0.2873, F1 Score=0.9289
Epoch  45/200 | Train: Loss=0.0840, F1 Score=0.9845 | Val: Loss=0.2639, F1 Score=0.9440
Epoch  46/200 | Train: Loss=0.0756, F1 Score=0.9905 | Val: Loss=0.2633, F1 Score=0.9444
Epoch  47/200 | Train: Loss=0.0739, F1 Score=0.9922 | Val: Loss=0.2693, F1 Score=0.9429
Epoch  48/200 | Train: Loss=0.0739, F1 Score=0.9914 | Val: Loss=0.2665, F1 Score=0.9483
Epoch  49/200 | Train: Loss=0.0735, F1 Score=0.9925 | Val: Loss=0.2687, F1 Score=0.9456
Epoch  50/200 | Train: Loss=0.0716, F1 Score=0.9924 | Val: Loss=0.2693, F1 Score=0.9444
Epoch  51/200 | Train: Loss=0.0750, F1 Score=0.9912 | Val: Loss=0.2832, F1 Score=0.9381
Epoch  52/200 | Train: Loss=0.0722, F1 Score=0.9924 | Val: Loss=0.2780, F1 Score=0.9462
Epoch  53/200 | Train: Loss=0.0713, F1 Score=0.9925 | Val: Loss=0.2749, F1 Score=0.9499
Epoch  54/200 | Train: Loss=0.0716, F1 Score=0.9936 | Val: Loss=0.2797, F1 Score=0.9424
Epoch  55/200 | Train: Loss=0.0718, F1 Score=0.9931 | Val: Loss=0.2776, F1 Score=0.9460
Epoch  56/200 | Train: Loss=0.0703, F1 Score=0.9937 | Val: Loss=0.2746, F1 Score=0.9407
Epoch  57/200 | Train: Loss=0.0703, F1 Score=0.9934 | Val: Loss=0.2778, F1 Score=0.9456
Epoch  58/200 | Train: Loss=0.0699, F1 Score=0.9935 | Val: Loss=0.2836, F1 Score=0.9384
Epoch  59/200 | Train: Loss=0.0686, F1 Score=0.9945 | Val: Loss=0.2832, F1 Score=0.9390
Epoch  60/200 | Train: Loss=0.0687, F1 Score=0.9938 | Val: Loss=0.2813, F1 Score=0.9466
Epoch  61/200 | Train: Loss=0.0677, F1 Score=0.9957 | Val: Loss=0.2824, F1 Score=0.9434
Epoch  62/200 | Train: Loss=0.0678, F1 Score=0.9951 | Val: Loss=0.2820, F1 Score=0.9466
Epoch  63/200 | Train: Loss=0.0670, F1 Score=0.9951 | Val: Loss=0.2814, F1 Score=0.9477
Epoch  64/200 | Train: Loss=0.0676, F1 Score=0.9948 | Val: Loss=0.2830, F1 Score=0.9477
Epoch  65/200 | Train: Loss=0.0679, F1 Score=0.9948 | Val: Loss=0.2851, F1 Score=0.9450
Epoch  66/200 | Train: Loss=0.0674, F1 Score=0.9938 | Val: Loss=0.2847, F1 Score=0.9450
Epoch  67/200 | Train: Loss=0.0676, F1 Score=0.9942 | Val: Loss=0.2843, F1 Score=0.9455

[I 2025-11-11 18:25:41,940] Trial 27 finished with value: 0.9499284386309793 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.5377302226330053, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0009785537478176932, 'weight_decay': 1.7897780974039973e-05, 'l1_lambda': 2.571348226648045e-06, 'focal_gamma': 3.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 2.166420382127338}. Best is trial 27 with value: 0.9499284386309793.

Epoch  68/200 | Train: Loss=0.0676, F1 Score=0.9957 | Val: Loss=0.2845, F1 Score=0.9455
Early stopping triggered after 68 epochs.
Best model restored from epoch 53 with val_f1 0.9499
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0359, F1 Score=0.5724 | Val: Loss=0.8736, F1 Score=0.7127
Epoch   2/200 | Train: Loss=0.8994, F1 Score=0.6648 | Val: Loss=0.8098, F1 Score=0.7636
Epoch   3/200 | Train: Loss=0.7717, F1 Score=0.7328 | Val: Loss=0.6192, F1 Score=0.8722
Epoch   4/200 | Train: Loss=0.6344, F1 Score=0.7964 | Val: Loss=0.6051, F1 Score=0.8154
Epoch   5/200 | Train: Loss=0.5481, F1 Score=0.8341 | Val: Loss=0.6470, F1 Score=0.7313
Epoch   6/200 | Train: Loss=0.4658, F1 Score=0.8625 | Val: Loss=0.5336, F1 Score=0.7678
Epoch   7/200 | Train: Loss=0.4199, F1 Score=0.8716 | Val: Loss=0.4527, F1 Score=0.8787
Epoch   8/200 | Train: Loss=0.3831, F1 Score=0.8836 | Val: Loss=0.4451, F1 Score=0.8154
Epoch   9/200 | Train: Loss=0.3778, F1 Score=0.8844 | Val: Loss=0.4604, F1 Score=0.8819
Epoch  10/200 | Train: Loss=0.3229, F1 Score=0.8988 | Val: Loss=0.3602, F1 Score=0.8884
Epoch  11/200 | Train: Loss=0.2686, F1 Score=0.9164 | Val: Loss=0.3841, F1 Score=0.8515
Epoch  12/200 | Train: Loss=0.3682, F1 Score=0.8861 | Val: Loss=0.3353, F1 Score=0.8861
Epoch  13/200 | Train: Loss=0.2565, F1 Score=0.9227 | Val: Loss=0.2842, F1 Score=0.8895
Epoch  14/200 | Train: Loss=0.2210, F1 Score=0.9292 | Val: Loss=0.2876, F1 Score=0.9093
Epoch  15/200 | Train: Loss=0.2388, F1 Score=0.9251 | Val: Loss=0.6026, F1 Score=0.8896
Epoch  16/200 | Train: Loss=0.1887, F1 Score=0.9368 | Val: Loss=0.3158, F1 Score=0.8817
Epoch  17/200 | Train: Loss=0.1839, F1 Score=0.9380 | Val: Loss=0.4153, F1 Score=0.8964
Epoch  18/200 | Train: Loss=0.1593, F1 Score=0.9436 | Val: Loss=0.3293, F1 Score=0.8972
Epoch  19/200 | Train: Loss=0.1512, F1 Score=0.9459 | Val: Loss=0.3312, F1 Score=0.9004
Epoch  20/200 | Train: Loss=0.1857, F1 Score=0.9332 | Val: Loss=0.3629, F1 Score=0.8880
Epoch  21/200 | Train: Loss=0.1149, F1 Score=0.9602 | Val: Loss=0.2459, F1 Score=0.9174
Epoch  22/200 | Train: Loss=0.1058, F1 Score=0.9644 | Val: Loss=0.2175, F1 Score=0.9231
Epoch  23/200 | Train: Loss=0.0994, F1 Score=0.9661 | Val: Loss=0.2070, F1 Score=0.9261
Epoch  24/200 | Train: Loss=0.0976, F1 Score=0.9666 | Val: Loss=0.2189, F1 Score=0.9325
Epoch  25/200 | Train: Loss=0.0914, F1 Score=0.9729 | Val: Loss=0.2288, F1 Score=0.9252
Epoch  26/200 | Train: Loss=0.0910, F1 Score=0.9716 | Val: Loss=0.2274, F1 Score=0.9320
Epoch  27/200 | Train: Loss=0.0916, F1 Score=0.9718 | Val: Loss=0.2219, F1 Score=0.9345
Epoch  28/200 | Train: Loss=0.0879, F1 Score=0.9732 | Val: Loss=0.2118, F1 Score=0.9308
Epoch  29/200 | Train: Loss=0.0861, F1 Score=0.9723 | Val: Loss=0.2724, F1 Score=0.9420
Epoch  30/200 | Train: Loss=0.0837, F1 Score=0.9764 | Val: Loss=0.2234, F1 Score=0.9255
Epoch  31/200 | Train: Loss=0.0809, F1 Score=0.9772 | Val: Loss=0.2109, F1 Score=0.9386
Epoch  32/200 | Train: Loss=0.1095, F1 Score=0.9671 | Val: Loss=0.2813, F1 Score=0.9188
Epoch  33/200 | Train: Loss=0.0941, F1 Score=0.9662 | Val: Loss=0.2365, F1 Score=0.9210
Epoch  34/200 | Train: Loss=0.0814, F1 Score=0.9759 | Val: Loss=0.2300, F1 Score=0.9286
Epoch  35/200 | Train: Loss=0.0807, F1 Score=0.9750 | Val: Loss=0.2594, F1 Score=0.9318
Epoch  36/200 | Train: Loss=0.0670, F1 Score=0.9830 | Val: Loss=0.2300, F1 Score=0.9369
Epoch  37/200 | Train: Loss=0.0677, F1 Score=0.9838 | Val: Loss=0.2221, F1 Score=0.9364
Epoch  38/200 | Train: Loss=0.0632, F1 Score=0.9878 | Val: Loss=0.2208, F1 Score=0.9395
Epoch  39/200 | Train: Loss=0.0659, F1 Score=0.9834 | Val: Loss=0.2182, F1 Score=0.9401
Epoch  40/200 | Train: Loss=0.0670, F1 Score=0.9841 | Val: Loss=0.2540, F1 Score=0.9197
Epoch  41/200 | Train: Loss=0.0654, F1 Score=0.9832 | Val: Loss=0.2331, F1 Score=0.9352
Epoch  42/200 | Train: Loss=0.0626, F1 Score=0.9861 | Val: Loss=0.2243, F1 Score=0.9379
Epoch  43/200 | Train: Loss=0.0618, F1 Score=0.9865 | Val: Loss=0.2237, F1 Score=0.9389

[I 2025-11-11 18:26:57,832] Trial 28 finished with value: 0.9420182273164759 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.5387662597635959, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0008349406272181838, 'weight_decay': 1.7233570711222844e-05, 'l1_lambda': 2.2818911897517564e-06, 'focal_gamma': 3.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 2.239147087866114}. Best is trial 27 with value: 0.9499284386309793.

Epoch  44/200 | Train: Loss=0.0609, F1 Score=0.9865 | Val: Loss=0.2309, F1 Score=0.9373
Early stopping triggered after 44 epochs.
Best model restored from epoch 29 with val_f1 0.9420
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0222, F1 Score=0.6113 | Val: Loss=0.8721, F1 Score=0.7121
Epoch   2/200 | Train: Loss=0.8743, F1 Score=0.6838 | Val: Loss=0.7516, F1 Score=0.7661
Epoch   3/200 | Train: Loss=0.7963, F1 Score=0.7259 | Val: Loss=0.7934, F1 Score=0.7430
Epoch   4/200 | Train: Loss=0.7029, F1 Score=0.7725 | Val: Loss=0.8742, F1 Score=0.6155
Epoch   5/200 | Train: Loss=0.6306, F1 Score=0.7996 | Val: Loss=0.5710, F1 Score=0.8213
Epoch   6/200 | Train: Loss=0.5825, F1 Score=0.8199 | Val: Loss=0.5378, F1 Score=0.8397
Epoch   7/200 | Train: Loss=0.5236, F1 Score=0.8443 | Val: Loss=0.4839, F1 Score=0.8895
Epoch   8/200 | Train: Loss=0.4958, F1 Score=0.8494 | Val: Loss=0.4906, F1 Score=0.8582
Epoch   9/200 | Train: Loss=0.4164, F1 Score=0.8855 | Val: Loss=0.4703, F1 Score=0.8810
Epoch  10/200 | Train: Loss=0.4090, F1 Score=0.8829 | Val: Loss=0.4439, F1 Score=0.8827
Epoch  11/200 | Train: Loss=0.3580, F1 Score=0.8957 | Val: Loss=0.3471, F1 Score=0.9203
Epoch  12/200 | Train: Loss=0.3245, F1 Score=0.9051 | Val: Loss=0.3011, F1 Score=0.9274
Epoch  13/200 | Train: Loss=0.3456, F1 Score=0.8813 | Val: Loss=0.4056, F1 Score=0.8360
Epoch  14/200 | Train: Loss=0.3249, F1 Score=0.9020 | Val: Loss=0.4647, F1 Score=0.8222
Epoch  15/200 | Train: Loss=0.2422, F1 Score=0.9170 | Val: Loss=0.4114, F1 Score=0.8033
Epoch  16/200 | Train: Loss=0.2593, F1 Score=0.9114 | Val: Loss=0.3185, F1 Score=0.8834
Epoch  17/200 | Train: Loss=0.2691, F1 Score=0.9162 | Val: Loss=0.2694, F1 Score=0.8980
Epoch  18/200 | Train: Loss=0.2346, F1 Score=0.9203 | Val: Loss=0.2690, F1 Score=0.9230
Epoch  19/200 | Train: Loss=0.1419, F1 Score=0.9436 | Val: Loss=0.2493, F1 Score=0.9211
Epoch  20/200 | Train: Loss=0.1269, F1 Score=0.9472 | Val: Loss=0.2531, F1 Score=0.9060
Epoch  21/200 | Train: Loss=0.1189, F1 Score=0.9469 | Val: Loss=0.2505, F1 Score=0.9329
Epoch  22/200 | Train: Loss=0.1174, F1 Score=0.9472 | Val: Loss=0.2902, F1 Score=0.9038
Epoch  23/200 | Train: Loss=0.1095, F1 Score=0.9467 | Val: Loss=0.2751, F1 Score=0.9093
Epoch  24/200 | Train: Loss=0.1163, F1 Score=0.9476 | Val: Loss=0.2839, F1 Score=0.8951
Epoch  25/200 | Train: Loss=0.1186, F1 Score=0.9494 | Val: Loss=0.3301, F1 Score=0.8994
Epoch  26/200 | Train: Loss=0.1016, F1 Score=0.9542 | Val: Loss=0.2936, F1 Score=0.9208
Epoch  27/200 | Train: Loss=0.1012, F1 Score=0.9531 | Val: Loss=0.3116, F1 Score=0.9165
Epoch  28/200 | Train: Loss=0.0896, F1 Score=0.9585 | Val: Loss=0.2966, F1 Score=0.9233
Epoch  29/200 | Train: Loss=0.0818, F1 Score=0.9626 | Val: Loss=0.2910, F1 Score=0.9280
Epoch  30/200 | Train: Loss=0.0814, F1 Score=0.9621 | Val: Loss=0.2916, F1 Score=0.9229
Epoch  31/200 | Train: Loss=0.0817, F1 Score=0.9622 | Val: Loss=0.2920, F1 Score=0.9235
Epoch  32/200 | Train: Loss=0.0829, F1 Score=0.9627 | Val: Loss=0.2933, F1 Score=0.9315
Epoch  33/200 | Train: Loss=0.0795, F1 Score=0.9635 | Val: Loss=0.2873, F1 Score=0.9256
Epoch  34/200 | Train: Loss=0.0751, F1 Score=0.9652 | Val: Loss=0.2851, F1 Score=0.9298
Epoch  35/200 | Train: Loss=0.0755, F1 Score=0.9642 | Val: Loss=0.2816, F1 Score=0.9291

[I 2025-11-11 18:27:46,773] Trial 29 finished with value: 0.9329190846672359 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.4474921192924508, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0009638231638010894, 'weight_decay': 2.808214224004909e-06, 'l1_lambda': 8.622004395645264e-07, 'focal_gamma': 3.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 2.159540647196542}. Best is trial 27 with value: 0.9499284386309793.

Epoch  36/200 | Train: Loss=0.0736, F1 Score=0.9685 | Val: Loss=0.2845, F1 Score=0.9285
Early stopping triggered after 36 epochs.
Best model restored from epoch 21 with val_f1 0.9329
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0851, F1 Score=0.5676 | Val: Loss=1.0216, F1 Score=0.4150
Epoch   2/200 | Train: Loss=0.9742, F1 Score=0.6268 | Val: Loss=0.8602, F1 Score=0.7326
Epoch   3/200 | Train: Loss=0.8885, F1 Score=0.6765 | Val: Loss=0.7898, F1 Score=0.7167
Epoch   4/200 | Train: Loss=0.8092, F1 Score=0.7047 | Val: Loss=0.6785, F1 Score=0.8120
Epoch   5/200 | Train: Loss=0.7029, F1 Score=0.7605 | Val: Loss=0.5358, F1 Score=0.8836
Epoch   6/200 | Train: Loss=0.6097, F1 Score=0.7961 | Val: Loss=0.6387, F1 Score=0.8048
Epoch   7/200 | Train: Loss=0.5968, F1 Score=0.8016 | Val: Loss=0.5694, F1 Score=0.8549
Epoch   8/200 | Train: Loss=0.5346, F1 Score=0.8286 | Val: Loss=0.7802, F1 Score=0.8678
Epoch   9/200 | Train: Loss=0.5304, F1 Score=0.8342 | Val: Loss=0.4868, F1 Score=0.8960
Epoch  10/200 | Train: Loss=0.5011, F1 Score=0.8489 | Val: Loss=0.4621, F1 Score=0.8933
Epoch  11/200 | Train: Loss=0.4689, F1 Score=0.8562 | Val: Loss=0.5726, F1 Score=0.8813
Epoch  12/200 | Train: Loss=0.4405, F1 Score=0.8663 | Val: Loss=0.4147, F1 Score=0.8880
Epoch  13/200 | Train: Loss=0.4050, F1 Score=0.8737 | Val: Loss=0.5206, F1 Score=0.8750
Epoch  14/200 | Train: Loss=0.3940, F1 Score=0.8792 | Val: Loss=0.4494, F1 Score=0.8517
Epoch  15/200 | Train: Loss=0.3662, F1 Score=0.8889 | Val: Loss=0.3919, F1 Score=0.8933
Epoch  16/200 | Train: Loss=0.2790, F1 Score=0.9200 | Val: Loss=0.3698, F1 Score=0.8970
Epoch  17/200 | Train: Loss=0.2650, F1 Score=0.9273 | Val: Loss=0.3369, F1 Score=0.9014
Epoch  18/200 | Train: Loss=0.2577, F1 Score=0.9244 | Val: Loss=0.3411, F1 Score=0.9057
Epoch  19/200 | Train: Loss=0.2444, F1 Score=0.9285 | Val: Loss=0.3217, F1 Score=0.8975
Epoch  20/200 | Train: Loss=0.2406, F1 Score=0.9237 | Val: Loss=0.3446, F1 Score=0.9128
Epoch  21/200 | Train: Loss=0.2371, F1 Score=0.9280 | Val: Loss=0.3803, F1 Score=0.8803
Epoch  22/200 | Train: Loss=0.2326, F1 Score=0.9268 | Val: Loss=0.2916, F1 Score=0.9006
Epoch  23/200 | Train: Loss=0.2248, F1 Score=0.9288 | Val: Loss=0.3435, F1 Score=0.8783
Epoch  24/200 | Train: Loss=0.2216, F1 Score=0.9284 | Val: Loss=0.3279, F1 Score=0.8834
Epoch  25/200 | Train: Loss=0.2134, F1 Score=0.9306 | Val: Loss=0.3370, F1 Score=0.8986
Epoch  26/200 | Train: Loss=0.2150, F1 Score=0.9300 | Val: Loss=0.3440, F1 Score=0.8874
Epoch  27/200 | Train: Loss=0.1981, F1 Score=0.9344 | Val: Loss=0.3231, F1 Score=0.8963
Epoch  28/200 | Train: Loss=0.1959, F1 Score=0.9354 | Val: Loss=0.3189, F1 Score=0.9024
Epoch  29/200 | Train: Loss=0.1934, F1 Score=0.9367 | Val: Loss=0.3346, F1 Score=0.8889
Epoch  30/200 | Train: Loss=0.1966, F1 Score=0.9333 | Val: Loss=0.3130, F1 Score=0.8963
Epoch  31/200 | Train: Loss=0.1907, F1 Score=0.9347 | Val: Loss=0.3365, F1 Score=0.8928
Epoch  32/200 | Train: Loss=0.1913, F1 Score=0.9343 | Val: Loss=0.3180, F1 Score=0.9051
Epoch  33/200 | Train: Loss=0.1899, F1 Score=0.9378 | Val: Loss=0.3238, F1 Score=0.8961
Epoch  34/200 | Train: Loss=0.1888, F1 Score=0.9355 | Val: Loss=0.3274, F1 Score=0.8947

[I 2025-11-11 18:28:47,015] Trial 30 finished with value: 0.9127792847004507 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.5534005222386185, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00036763399135277637, 'weight_decay': 2.171667719169477e-05, 'l1_lambda': 2.6496500638367635e-06, 'focal_gamma': 3.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 3.1152142581153472}. Best is trial 27 with value: 0.9499284386309793.

Epoch  35/200 | Train: Loss=0.1903, F1 Score=0.9365 | Val: Loss=0.3283, F1 Score=0.8956
Early stopping triggered after 35 epochs.
Best model restored from epoch 20 with val_f1 0.9128
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0177, F1 Score=0.5839 | Val: Loss=1.0221, F1 Score=0.4087
Epoch   2/200 | Train: Loss=0.9110, F1 Score=0.6560 | Val: Loss=0.8876, F1 Score=0.5171
Epoch   3/200 | Train: Loss=0.8404, F1 Score=0.6722 | Val: Loss=0.7297, F1 Score=0.7767
Epoch   4/200 | Train: Loss=0.6617, F1 Score=0.7943 | Val: Loss=0.6894, F1 Score=0.7475
Epoch   5/200 | Train: Loss=0.5559, F1 Score=0.8336 | Val: Loss=0.5732, F1 Score=0.7995
Epoch   6/200 | Train: Loss=0.4929, F1 Score=0.8538 | Val: Loss=0.4911, F1 Score=0.9103
Epoch   7/200 | Train: Loss=0.4780, F1 Score=0.8469 | Val: Loss=0.4736, F1 Score=0.8724
Epoch   8/200 | Train: Loss=0.4415, F1 Score=0.8699 | Val: Loss=0.5182, F1 Score=0.8503
Epoch   9/200 | Train: Loss=0.4391, F1 Score=0.8583 | Val: Loss=0.5092, F1 Score=0.9000
Epoch  10/200 | Train: Loss=0.3678, F1 Score=0.8795 | Val: Loss=0.5211, F1 Score=0.7881
Epoch  11/200 | Train: Loss=0.3447, F1 Score=0.8981 | Val: Loss=0.3686, F1 Score=0.9150
Epoch  12/200 | Train: Loss=0.3279, F1 Score=0.8993 | Val: Loss=0.5571, F1 Score=0.8235
Epoch  13/200 | Train: Loss=0.3184, F1 Score=0.9027 | Val: Loss=0.3748, F1 Score=0.8719
Epoch  14/200 | Train: Loss=0.3665, F1 Score=0.8971 | Val: Loss=0.4995, F1 Score=0.8351
Epoch  15/200 | Train: Loss=0.2958, F1 Score=0.9094 | Val: Loss=0.4512, F1 Score=0.8443
Epoch  16/200 | Train: Loss=0.2556, F1 Score=0.9064 | Val: Loss=0.4597, F1 Score=0.9255
Epoch  17/200 | Train: Loss=0.2259, F1 Score=0.9163 | Val: Loss=0.3271, F1 Score=0.9226
Epoch  18/200 | Train: Loss=0.2643, F1 Score=0.9144 | Val: Loss=0.3965, F1 Score=0.8604
Epoch  19/200 | Train: Loss=0.2394, F1 Score=0.9102 | Val: Loss=0.3604, F1 Score=0.9258
Epoch  20/200 | Train: Loss=0.1890, F1 Score=0.9298 | Val: Loss=0.4281, F1 Score=0.8688
Epoch  21/200 | Train: Loss=0.2243, F1 Score=0.9121 | Val: Loss=0.2298, F1 Score=0.9061
Epoch  22/200 | Train: Loss=0.2272, F1 Score=0.9177 | Val: Loss=0.2696, F1 Score=0.9268
Epoch  23/200 | Train: Loss=0.1880, F1 Score=0.9337 | Val: Loss=0.3243, F1 Score=0.9003
Epoch  24/200 | Train: Loss=0.1927, F1 Score=0.9160 | Val: Loss=0.3765, F1 Score=0.9166
Epoch  25/200 | Train: Loss=0.1547, F1 Score=0.9371 | Val: Loss=0.3117, F1 Score=0.9134
Epoch  26/200 | Train: Loss=0.1439, F1 Score=0.9404 | Val: Loss=0.6231, F1 Score=0.8410
Epoch  27/200 | Train: Loss=0.2559, F1 Score=0.9160 | Val: Loss=0.3987, F1 Score=0.8654
Epoch  28/200 | Train: Loss=0.1796, F1 Score=0.9326 | Val: Loss=0.3345, F1 Score=0.8988
Epoch  29/200 | Train: Loss=0.1190, F1 Score=0.9503 | Val: Loss=0.3002, F1 Score=0.8904
Epoch  30/200 | Train: Loss=0.1130, F1 Score=0.9511 | Val: Loss=0.2648, F1 Score=0.9162
Epoch  31/200 | Train: Loss=0.0987, F1 Score=0.9558 | Val: Loss=0.2833, F1 Score=0.9185
Epoch  32/200 | Train: Loss=0.0883, F1 Score=0.9567 | Val: Loss=0.2607, F1 Score=0.9188
Epoch  33/200 | Train: Loss=0.0886, F1 Score=0.9607 | Val: Loss=0.2916, F1 Score=0.9075
Epoch  34/200 | Train: Loss=0.0836, F1 Score=0.9588 | Val: Loss=0.2922, F1 Score=0.9230
Epoch  35/200 | Train: Loss=0.0721, F1 Score=0.9637 | Val: Loss=0.2911, F1 Score=0.9250
Epoch  36/200 | Train: Loss=0.0726, F1 Score=0.9632 | Val: Loss=0.2859, F1 Score=0.9263
Epoch  37/200 | Train: Loss=0.0712, F1 Score=0.9655 | Val: Loss=0.2808, F1 Score=0.9300
Epoch  38/200 | Train: Loss=0.0715, F1 Score=0.9644 | Val: Loss=0.2848, F1 Score=0.9293
Epoch  39/200 | Train: Loss=0.0693, F1 Score=0.9651 | Val: Loss=0.2789, F1 Score=0.9266
Epoch  40/200 | Train: Loss=0.0660, F1 Score=0.9663 | Val: Loss=0.2861, F1 Score=0.9293
Epoch  41/200 | Train: Loss=0.0677, F1 Score=0.9670 | Val: Loss=0.2828, F1 Score=0.9293
Epoch  42/200 | Train: Loss=0.0679, F1 Score=0.9651 | Val: Loss=0.2878, F1 Score=0.9279
Epoch  43/200 | Train: Loss=0.0651, F1 Score=0.9670 | Val: Loss=0.3157, F1 Score=0.9255
Epoch  44/200 | Train: Loss=0.0666, F1 Score=0.9661 | Val: Loss=0.3028, F1 Score=0.9270
Epoch  45/200 | Train: Loss=0.0645, F1 Score=0.9641 | Val: Loss=0.2953, F1 Score=0.9255
Epoch  46/200 | Train: Loss=0.0665, F1 Score=0.9655 | Val: Loss=0.2989, F1 Score=0.9266
Epoch  47/200 | Train: Loss=0.0641, F1 Score=0.9657 | Val: Loss=0.2960, F1 Score=0.9281
Epoch  48/200 | Train: Loss=0.0667, F1 Score=0.9663 | Val: Loss=0.2920, F1 Score=0.9278
Epoch  49/200 | Train: Loss=0.0641, F1 Score=0.9675 | Val: Loss=0.2971, F1 Score=0.9282
Epoch  50/200 | Train: Loss=0.0646, F1 Score=0.9661 | Val: Loss=0.2957, F1 Score=0.9282
Epoch  51/200 | Train: Loss=0.0654, F1 Score=0.9659 | Val: Loss=0.2954, F1 Score=0.9287

[I 2025-11-11 18:29:56,816] Trial 31 finished with value: 0.9300308693912567 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.4389780300443881, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0009711056848397234, 'weight_decay': 2.3137502259060232e-06, 'l1_lambda': 1.0032878717092892e-06, 'focal_gamma': 3.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 2.0975243970706723}. Best is trial 27 with value: 0.9499284386309793.

Epoch  52/200 | Train: Loss=0.0659, F1 Score=0.9664 | Val: Loss=0.2934, F1 Score=0.9283
Early stopping triggered after 52 epochs.
Best model restored from epoch 37 with val_f1 0.9300
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0444, F1 Score=0.5567 | Val: Loss=0.9781, F1 Score=0.6571
Epoch   2/200 | Train: Loss=0.9309, F1 Score=0.6559 | Val: Loss=0.8875, F1 Score=0.6906
Epoch   3/200 | Train: Loss=0.8507, F1 Score=0.6802 | Val: Loss=0.7976, F1 Score=0.7228
Epoch   4/200 | Train: Loss=0.6869, F1 Score=0.7771 | Val: Loss=0.6065, F1 Score=0.8667
Epoch   5/200 | Train: Loss=0.5572, F1 Score=0.8315 | Val: Loss=0.5657, F1 Score=0.8392
Epoch   6/200 | Train: Loss=0.5024, F1 Score=0.8467 | Val: Loss=0.5542, F1 Score=0.8981
Epoch   7/200 | Train: Loss=0.4552, F1 Score=0.8616 | Val: Loss=0.6239, F1 Score=0.8019
Epoch   8/200 | Train: Loss=0.4467, F1 Score=0.8610 | Val: Loss=0.4235, F1 Score=0.9046
Epoch   9/200 | Train: Loss=0.3786, F1 Score=0.8819 | Val: Loss=0.5815, F1 Score=0.8782
Epoch  10/200 | Train: Loss=0.3956, F1 Score=0.8786 | Val: Loss=0.4701, F1 Score=0.9127
Epoch  11/200 | Train: Loss=0.3347, F1 Score=0.8994 | Val: Loss=0.5056, F1 Score=0.9130
Epoch  12/200 | Train: Loss=0.3175, F1 Score=0.8923 | Val: Loss=0.3971, F1 Score=0.8994
Epoch  13/200 | Train: Loss=0.2985, F1 Score=0.8990 | Val: Loss=0.4144, F1 Score=0.8710
Epoch  14/200 | Train: Loss=0.2843, F1 Score=0.8994 | Val: Loss=0.3378, F1 Score=0.9069
Epoch  15/200 | Train: Loss=0.2917, F1 Score=0.9086 | Val: Loss=0.5638, F1 Score=0.7433
Epoch  16/200 | Train: Loss=0.2355, F1 Score=0.9083 | Val: Loss=0.4765, F1 Score=0.8954
Epoch  17/200 | Train: Loss=0.1661, F1 Score=0.9373 | Val: Loss=0.2791, F1 Score=0.9171
Epoch  18/200 | Train: Loss=0.1316, F1 Score=0.9452 | Val: Loss=0.2822, F1 Score=0.8953
Epoch  19/200 | Train: Loss=0.1258, F1 Score=0.9451 | Val: Loss=0.3428, F1 Score=0.8721
Epoch  20/200 | Train: Loss=0.1228, F1 Score=0.9462 | Val: Loss=0.2867, F1 Score=0.8864
Epoch  21/200 | Train: Loss=0.1214, F1 Score=0.9457 | Val: Loss=0.3037, F1 Score=0.8807
Epoch  22/200 | Train: Loss=0.1158, F1 Score=0.9456 | Val: Loss=0.2749, F1 Score=0.9065
Epoch  23/200 | Train: Loss=0.1044, F1 Score=0.9504 | Val: Loss=0.2794, F1 Score=0.9057
Epoch  24/200 | Train: Loss=0.0972, F1 Score=0.9515 | Val: Loss=0.2750, F1 Score=0.9257
Epoch  25/200 | Train: Loss=0.0987, F1 Score=0.9553 | Val: Loss=0.2813, F1 Score=0.9051
Epoch  26/200 | Train: Loss=0.0924, F1 Score=0.9525 | Val: Loss=0.2762, F1 Score=0.9076
Epoch  27/200 | Train: Loss=0.0945, F1 Score=0.9526 | Val: Loss=0.2813, F1 Score=0.9132
Epoch  28/200 | Train: Loss=0.0915, F1 Score=0.9557 | Val: Loss=0.2837, F1 Score=0.9038
Epoch  29/200 | Train: Loss=0.0951, F1 Score=0.9547 | Val: Loss=0.2864, F1 Score=0.9094
Epoch  30/200 | Train: Loss=0.0910, F1 Score=0.9544 | Val: Loss=0.2847, F1 Score=0.9125
Epoch  31/200 | Train: Loss=0.0909, F1 Score=0.9535 | Val: Loss=0.2849, F1 Score=0.9129
Epoch  32/200 | Train: Loss=0.0915, F1 Score=0.9560 | Val: Loss=0.2830, F1 Score=0.9084
Epoch  33/200 | Train: Loss=0.0888, F1 Score=0.9545 | Val: Loss=0.2835, F1 Score=0.9122
Epoch  34/200 | Train: Loss=0.0890, F1 Score=0.9564 | Val: Loss=0.2837, F1 Score=0.9095
Epoch  35/200 | Train: Loss=0.0879, F1 Score=0.9552 | Val: Loss=0.2830, F1 Score=0.9100
Epoch  36/200 | Train: Loss=0.0909, F1 Score=0.9553 | Val: Loss=0.2827, F1 Score=0.9106
Epoch  37/200 | Train: Loss=0.0915, F1 Score=0.9551 | Val: Loss=0.2826, F1 Score=0.9101
Epoch  38/200 | Train: Loss=0.0881, F1 Score=0.9569 | Val: Loss=0.2830, F1 Score=0.9101

[I 2025-11-11 18:30:49,020] Trial 32 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.456647382112561, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0009357341492706358, 'weight_decay': 3.6273443079355766e-06, 'l1_lambda': 8.252511890579853e-07, 'focal_gamma': 3.5, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 2.2572705864802187}. Best is trial 27 with value: 0.9499284386309793.

Epoch  39/200 | Train: Loss=0.0874, F1 Score=0.9560 | Val: Loss=0.2833, F1 Score=0.9111
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0597, F1 Score=0.5789 | Val: Loss=1.0183, F1 Score=0.4609
Epoch   2/200 | Train: Loss=0.9156, F1 Score=0.6366 | Val: Loss=1.0330, F1 Score=0.4339
Epoch   3/200 | Train: Loss=0.8311, F1 Score=0.6419 | Val: Loss=0.9211, F1 Score=0.8177
Epoch   4/200 | Train: Loss=0.7133, F1 Score=0.7552 | Val: Loss=0.6624, F1 Score=0.8117
Epoch   5/200 | Train: Loss=0.5859, F1 Score=0.8314 | Val: Loss=0.5651, F1 Score=0.8638
Epoch   6/200 | Train: Loss=0.5134, F1 Score=0.8374 | Val: Loss=0.6832, F1 Score=0.8770
Epoch   7/200 | Train: Loss=0.5074, F1 Score=0.8501 | Val: Loss=0.6023, F1 Score=0.7855
Epoch   8/200 | Train: Loss=0.4403, F1 Score=0.8670 | Val: Loss=0.7847, F1 Score=0.7183
Epoch   9/200 | Train: Loss=0.4228, F1 Score=0.8733 | Val: Loss=0.5125, F1 Score=0.8801
Epoch  10/200 | Train: Loss=0.4052, F1 Score=0.8728 | Val: Loss=0.4676, F1 Score=0.8511
Epoch  11/200 | Train: Loss=0.4003, F1 Score=0.8758 | Val: Loss=0.4465, F1 Score=0.9016
Epoch  12/200 | Train: Loss=0.3523, F1 Score=0.8948 | Val: Loss=0.5664, F1 Score=0.8165
Epoch  13/200 | Train: Loss=0.3815, F1 Score=0.8845 | Val: Loss=0.4014, F1 Score=0.8533
Epoch  14/200 | Train: Loss=0.3621, F1 Score=0.8942 | Val: Loss=0.5085, F1 Score=0.8884
Epoch  15/200 | Train: Loss=0.3404, F1 Score=0.8992 | Val: Loss=0.3582, F1 Score=0.8924
Epoch  16/200 | Train: Loss=0.3141, F1 Score=0.9006 | Val: Loss=0.5025, F1 Score=0.8554
Epoch  17/200 | Train: Loss=0.2383, F1 Score=0.9281 | Val: Loss=0.3718, F1 Score=0.8978
Epoch  18/200 | Train: Loss=0.2237, F1 Score=0.9293 | Val: Loss=0.3757, F1 Score=0.8939
Epoch  19/200 | Train: Loss=0.2163, F1 Score=0.9288 | Val: Loss=0.3892, F1 Score=0.8784
Epoch  20/200 | Train: Loss=0.2106, F1 Score=0.9295 | Val: Loss=0.3530, F1 Score=0.9111
Epoch  21/200 | Train: Loss=0.1973, F1 Score=0.9336 | Val: Loss=0.4263, F1 Score=0.8784
Epoch  22/200 | Train: Loss=0.1970, F1 Score=0.9354 | Val: Loss=0.3815, F1 Score=0.8739
Epoch  23/200 | Train: Loss=0.1880, F1 Score=0.9360 | Val: Loss=0.4071, F1 Score=0.9003
Epoch  24/200 | Train: Loss=0.1903, F1 Score=0.9358 | Val: Loss=0.3941, F1 Score=0.8772
Epoch  25/200 | Train: Loss=0.1769, F1 Score=0.9396 | Val: Loss=0.4768, F1 Score=0.8689
Epoch  26/200 | Train: Loss=0.1644, F1 Score=0.9421 | Val: Loss=0.4335, F1 Score=0.8753
Epoch  27/200 | Train: Loss=0.1622, F1 Score=0.9416 | Val: Loss=0.4404, F1 Score=0.8976
Epoch  28/200 | Train: Loss=0.1633, F1 Score=0.9422 | Val: Loss=0.4222, F1 Score=0.8854
Epoch  29/200 | Train: Loss=0.1560, F1 Score=0.9413 | Val: Loss=0.4398, F1 Score=0.8847
Epoch  30/200 | Train: Loss=0.1547, F1 Score=0.9444 | Val: Loss=0.4261, F1 Score=0.8861
Epoch  31/200 | Train: Loss=0.1584, F1 Score=0.9428 | Val: Loss=0.4321, F1 Score=0.8886
Epoch  32/200 | Train: Loss=0.1545, F1 Score=0.9431 | Val: Loss=0.4257, F1 Score=0.8879
Epoch  33/200 | Train: Loss=0.1542, F1 Score=0.9442 | Val: Loss=0.4241, F1 Score=0.8869
Epoch  34/200 | Train: Loss=0.1565, F1 Score=0.9418 | Val: Loss=0.4213, F1 Score=0.8883

[I 2025-11-11 18:31:36,328] Trial 33 finished with value: 0.9111390149698416 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.6251299116693558, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0006538330134780669, 'weight_decay': 1.8602555616242458e-06, 'l1_lambda': 2.136775505085545e-06, 'focal_gamma': 4.5, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 1.683584838921933}. Best is trial 27 with value: 0.9499284386309793.

Epoch  35/200 | Train: Loss=0.1533, F1 Score=0.9446 | Val: Loss=0.4262, F1 Score=0.8869
Early stopping triggered after 35 epochs.
Best model restored from epoch 20 with val_f1 0.9111
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0363, F1 Score=0.6196 | Val: Loss=0.9091, F1 Score=0.7051
Epoch   2/200 | Train: Loss=0.9163, F1 Score=0.6448 | Val: Loss=0.9990, F1 Score=0.6556
Epoch   3/200 | Train: Loss=0.8702, F1 Score=0.6478 | Val: Loss=0.8941, F1 Score=0.4692
Epoch   4/200 | Train: Loss=0.8294, F1 Score=0.6283 | Val: Loss=0.8934, F1 Score=0.6452

[I 2025-11-11 18:31:42,477] Trial 34 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.5403346499916047, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0007628952116032023, 'weight_decay': 1.2341972834122808e-05, 'l1_lambda': 5.710535106214295e-07, 'focal_gamma': 3.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 3.0393847116138715}. Best is trial 27 with value: 0.9499284386309793.

Epoch   5/200 | Train: Loss=0.8042, F1 Score=0.6461 | Val: Loss=0.8457, F1 Score=0.6088
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0401, F1 Score=0.5837 | Val: Loss=0.9876, F1 Score=0.5705
Epoch   2/200 | Train: Loss=0.9257, F1 Score=0.6488 | Val: Loss=0.9184, F1 Score=0.6153
Epoch   3/200 | Train: Loss=0.8461, F1 Score=0.6514 | Val: Loss=0.9810, F1 Score=0.4756
Epoch   4/200 | Train: Loss=0.7831, F1 Score=0.6969 | Val: Loss=0.8440, F1 Score=0.6696
Epoch   5/200 | Train: Loss=0.6810, F1 Score=0.7809 | Val: Loss=0.7437, F1 Score=0.7589

[I 2025-11-11 18:31:51,039] Trial 35 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.377607333599991, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0005489697567284839, 'weight_decay': 4.371134598564678e-06, 'l1_lambda': 8.349040837926002e-07, 'focal_gamma': 2.5, 'scheduler_patience': 6, 'scheduler_factor': 0.2, 'weight_max_norm': 2.420308349908868}. Best is trial 27 with value: 0.9499284386309793.

Epoch   6/200 | Train: Loss=0.5905, F1 Score=0.8197 | Val: Loss=0.8011, F1 Score=0.6044
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0354, F1 Score=0.6243 | Val: Loss=0.8820, F1 Score=0.6915
Epoch   2/200 | Train: Loss=0.9119, F1 Score=0.6564 | Val: Loss=0.8843, F1 Score=0.6303
Epoch   3/200 | Train: Loss=0.8421, F1 Score=0.7048 | Val: Loss=0.6574, F1 Score=0.7945
Epoch   4/200 | Train: Loss=0.6806, F1 Score=0.7907 | Val: Loss=0.6285, F1 Score=0.8130
Epoch   5/200 | Train: Loss=0.5949, F1 Score=0.8322 | Val: Loss=0.6346, F1 Score=0.7721
Epoch   6/200 | Train: Loss=0.5445, F1 Score=0.8427 | Val: Loss=0.4166, F1 Score=0.9158
Epoch   7/200 | Train: Loss=0.4953, F1 Score=0.8596 | Val: Loss=0.5143, F1 Score=0.7545
Epoch   8/200 | Train: Loss=0.4373, F1 Score=0.8596 | Val: Loss=0.4178, F1 Score=0.8922
Epoch   9/200 | Train: Loss=0.4518, F1 Score=0.8638 | Val: Loss=0.4010, F1 Score=0.8842
Epoch  10/200 | Train: Loss=0.3814, F1 Score=0.8937 | Val: Loss=0.3895, F1 Score=0.9039
Epoch  11/200 | Train: Loss=0.3676, F1 Score=0.8950 | Val: Loss=0.4898, F1 Score=0.8207
Epoch  12/200 | Train: Loss=0.2768, F1 Score=0.9160 | Val: Loss=0.2708, F1 Score=0.9221
Epoch  13/200 | Train: Loss=0.2282, F1 Score=0.9368 | Val: Loss=0.2746, F1 Score=0.8952
Epoch  14/200 | Train: Loss=0.2108, F1 Score=0.9394 | Val: Loss=0.2538, F1 Score=0.9124
Epoch  15/200 | Train: Loss=0.2094, F1 Score=0.9387 | Val: Loss=0.2609, F1 Score=0.9000
Epoch  16/200 | Train: Loss=0.1967, F1 Score=0.9385 | Val: Loss=0.2768, F1 Score=0.8922
Epoch  17/200 | Train: Loss=0.1903, F1 Score=0.9403 | Val: Loss=0.2646, F1 Score=0.9093
Epoch  18/200 | Train: Loss=0.1678, F1 Score=0.9478 | Val: Loss=0.2637, F1 Score=0.9054
Epoch  19/200 | Train: Loss=0.1655, F1 Score=0.9496 | Val: Loss=0.2572, F1 Score=0.9157
Epoch  20/200 | Train: Loss=0.1591, F1 Score=0.9524 | Val: Loss=0.2696, F1 Score=0.9131
Epoch  21/200 | Train: Loss=0.1583, F1 Score=0.9543 | Val: Loss=0.2593, F1 Score=0.9091
Epoch  22/200 | Train: Loss=0.1558, F1 Score=0.9549 | Val: Loss=0.2601, F1 Score=0.9096
Epoch  23/200 | Train: Loss=0.1500, F1 Score=0.9565 | Val: Loss=0.2567, F1 Score=0.9127
Epoch  24/200 | Train: Loss=0.1498, F1 Score=0.9570 | Val: Loss=0.2514, F1 Score=0.9098
Epoch  25/200 | Train: Loss=0.1496, F1 Score=0.9560 | Val: Loss=0.2593, F1 Score=0.9141
Epoch  26/200 | Train: Loss=0.1503, F1 Score=0.9573 | Val: Loss=0.2580, F1 Score=0.9122

[I 2025-11-11 18:32:38,008] Trial 36 finished with value: 0.9220555362970224 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.475373948375474, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0009761663729251433, 'weight_decay': 2.5367444168344292e-05, 'l1_lambda': 3.2428345679820596e-06, 'focal_gamma': 4.5, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 1.6157462112108225}. Best is trial 27 with value: 0.9499284386309793.

Epoch  27/200 | Train: Loss=0.1489, F1 Score=0.9586 | Val: Loss=0.2542, F1 Score=0.9084
Early stopping triggered after 27 epochs.
Best model restored from epoch 12 with val_f1 0.9221
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0836, F1 Score=0.5643 | Val: Loss=1.0117, F1 Score=0.7592
Epoch   2/200 | Train: Loss=0.9614, F1 Score=0.6540 | Val: Loss=0.9130, F1 Score=0.6881
Epoch   3/200 | Train: Loss=0.8730, F1 Score=0.6811 | Val: Loss=0.9725, F1 Score=0.5795
Epoch   4/200 | Train: Loss=0.8317, F1 Score=0.6641 | Val: Loss=0.7993, F1 Score=0.7151
Epoch   5/200 | Train: Loss=0.8426, F1 Score=0.6887 | Val: Loss=0.8810, F1 Score=0.7124

[I 2025-11-11 18:32:45,195] Trial 37 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.41542743363934226, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0003686645124945175, 'weight_decay': 7.502178025800815e-05, 'l1_lambda': 3.797609003943611e-07, 'focal_gamma': 3.5, 'scheduler_patience': 5, 'scheduler_factor': 0.5, 'weight_max_norm': 2.7504303971835533}. Best is trial 27 with value: 0.9499284386309793.

Epoch   6/200 | Train: Loss=0.7964, F1 Score=0.6832 | Val: Loss=0.8693, F1 Score=0.6079
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0348, F1 Score=0.6109 | Val: Loss=0.9526, F1 Score=0.6292
Epoch   2/200 | Train: Loss=0.9115, F1 Score=0.6605 | Val: Loss=0.8459, F1 Score=0.6417
Epoch   3/200 | Train: Loss=0.7347, F1 Score=0.7844 | Val: Loss=0.6163, F1 Score=0.8880
Epoch   4/200 | Train: Loss=0.6165, F1 Score=0.8365 | Val: Loss=0.7527, F1 Score=0.7162
Epoch   5/200 | Train: Loss=0.5266, F1 Score=0.8483 | Val: Loss=0.5655, F1 Score=0.8422
Epoch   6/200 | Train: Loss=0.5096, F1 Score=0.8544 | Val: Loss=0.5061, F1 Score=0.9003
Epoch   7/200 | Train: Loss=0.4475, F1 Score=0.8678 | Val: Loss=0.5059, F1 Score=0.8687
Epoch   8/200 | Train: Loss=0.4057, F1 Score=0.8786 | Val: Loss=0.4560, F1 Score=0.8641
Epoch   9/200 | Train: Loss=0.4070, F1 Score=0.8697 | Val: Loss=0.4970, F1 Score=0.8125
Epoch  10/200 | Train: Loss=0.3587, F1 Score=0.8998 | Val: Loss=0.4258, F1 Score=0.8884
Epoch  11/200 | Train: Loss=0.3230, F1 Score=0.9025 | Val: Loss=0.3586, F1 Score=0.8954
Epoch  12/200 | Train: Loss=0.3246, F1 Score=0.9000 | Val: Loss=0.3556, F1 Score=0.8853
Epoch  13/200 | Train: Loss=0.3137, F1 Score=0.9013 | Val: Loss=0.4733, F1 Score=0.8304
Epoch  14/200 | Train: Loss=0.2323, F1 Score=0.9338 | Val: Loss=0.3186, F1 Score=0.8957
Epoch  15/200 | Train: Loss=0.1872, F1 Score=0.9444 | Val: Loss=0.3497, F1 Score=0.9073
Epoch  16/200 | Train: Loss=0.1736, F1 Score=0.9465 | Val: Loss=0.3051, F1 Score=0.9073
Epoch  17/200 | Train: Loss=0.1648, F1 Score=0.9470 | Val: Loss=0.3554, F1 Score=0.8699
Epoch  18/200 | Train: Loss=0.1587, F1 Score=0.9446 | Val: Loss=0.3562, F1 Score=0.8748
Epoch  19/200 | Train: Loss=0.1548, F1 Score=0.9476 | Val: Loss=0.3348, F1 Score=0.9092
Epoch  20/200 | Train: Loss=0.1512, F1 Score=0.9455 | Val: Loss=0.3505, F1 Score=0.9157
Epoch  21/200 | Train: Loss=0.1542, F1 Score=0.9498 | Val: Loss=0.3206, F1 Score=0.8894
Epoch  22/200 | Train: Loss=0.1365, F1 Score=0.9514 | Val: Loss=0.3197, F1 Score=0.9042
Epoch  23/200 | Train: Loss=0.1306, F1 Score=0.9551 | Val: Loss=0.3414, F1 Score=0.9043
Epoch  24/200 | Train: Loss=0.1255, F1 Score=0.9555 | Val: Loss=0.3339, F1 Score=0.8964
Epoch  25/200 | Train: Loss=0.1388, F1 Score=0.9519 | Val: Loss=0.3135, F1 Score=0.9152
Epoch  26/200 | Train: Loss=0.1180, F1 Score=0.9587 | Val: Loss=0.3229, F1 Score=0.9047
Epoch  27/200 | Train: Loss=0.1267, F1 Score=0.9537 | Val: Loss=0.3973, F1 Score=0.9088
Epoch  28/200 | Train: Loss=0.1094, F1 Score=0.9652 | Val: Loss=0.3406, F1 Score=0.9058
Epoch  29/200 | Train: Loss=0.1040, F1 Score=0.9644 | Val: Loss=0.3241, F1 Score=0.9080
Epoch  30/200 | Train: Loss=0.1006, F1 Score=0.9687 | Val: Loss=0.3321, F1 Score=0.9070
Epoch  31/200 | Train: Loss=0.1008, F1 Score=0.9658 | Val: Loss=0.3332, F1 Score=0.9152
Epoch  32/200 | Train: Loss=0.0981, F1 Score=0.9677 | Val: Loss=0.3319, F1 Score=0.9117
Epoch  33/200 | Train: Loss=0.0956, F1 Score=0.9693 | Val: Loss=0.3350, F1 Score=0.9122
Epoch  34/200 | Train: Loss=0.0951, F1 Score=0.9697 | Val: Loss=0.3374, F1 Score=0.9150

[I 2025-11-11 18:33:45,520] Trial 38 finished with value: 0.9156721640654802 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.34468356591577604, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0007599473819232878, 'weight_decay': 3.052180547679385e-05, 'l1_lambda': 2.0072749221562256e-06, 'focal_gamma': 3.0, 'scheduler_patience': 6, 'scheduler_factor': 0.2, 'weight_max_norm': 1.9294937153870264}. Best is trial 27 with value: 0.9499284386309793.

Epoch  35/200 | Train: Loss=0.0914, F1 Score=0.9732 | Val: Loss=0.3396, F1 Score=0.9127
Early stopping triggered after 35 epochs.
Best model restored from epoch 20 with val_f1 0.9157
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1003, F1 Score=0.6731 | Val: Loss=1.0811, F1 Score=0.6900
Epoch   2/200 | Train: Loss=1.0949, F1 Score=0.6810 | Val: Loss=1.0769, F1 Score=0.6902
Epoch   3/200 | Train: Loss=1.0901, F1 Score=0.6953 | Val: Loss=1.0710, F1 Score=0.7135
Epoch   4/200 | Train: Loss=1.0832, F1 Score=0.6538 | Val: Loss=1.0596, F1 Score=0.7638
Epoch   5/200 | Train: Loss=1.0724, F1 Score=0.7475 | Val: Loss=1.0601, F1 Score=0.5809

[I 2025-11-11 18:33:52,829] Trial 39 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.565909530090463, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 5.801511380803098e-05, 'weight_decay': 5.37120857384415e-06, 'l1_lambda': 7.445282175555927e-07, 'focal_gamma': 4.0, 'scheduler_patience': 5, 'scheduler_factor': 0.5, 'weight_max_norm': 1.450561941345354}. Best is trial 27 with value: 0.9499284386309793.

Epoch   6/200 | Train: Loss=1.0232, F1 Score=0.6691 | Val: Loss=0.9453, F1 Score=0.7236
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.8449, F1 Score=0.5675 | Val: Loss=1.0806, F1 Score=0.7461
Epoch   2/200 | Train: Loss=1.7996, F1 Score=0.6948 | Val: Loss=1.0800, F1 Score=0.7048
Epoch   3/200 | Train: Loss=1.7559, F1 Score=0.6622 | Val: Loss=1.0715, F1 Score=0.7487
Epoch   4/200 | Train: Loss=1.7141, F1 Score=0.7024 | Val: Loss=1.0666, F1 Score=0.7271
Epoch   5/200 | Train: Loss=1.6716, F1 Score=0.6962 | Val: Loss=1.0605, F1 Score=0.7308

[I 2025-11-11 18:34:03,760] Trial 40 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.6087318874611467, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 2.980975762436186e-05, 'weight_decay': 1.1959169026815622e-05, 'l1_lambda': 4.519994220422544e-05, 'focal_gamma': 4.5, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 0.7534228831493868}. Best is trial 27 with value: 0.9499284386309793.

Epoch   6/200 | Train: Loss=1.6285, F1 Score=0.6846 | Val: Loss=1.0610, F1 Score=0.5627
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0269, F1 Score=0.5881 | Val: Loss=0.9600, F1 Score=0.6842
Epoch   2/200 | Train: Loss=0.8874, F1 Score=0.6435 | Val: Loss=1.0808, F1 Score=0.3548
Epoch   3/200 | Train: Loss=0.7538, F1 Score=0.7090 | Val: Loss=0.6125, F1 Score=0.8750
Epoch   4/200 | Train: Loss=0.5737, F1 Score=0.8236 | Val: Loss=0.5241, F1 Score=0.8837
Epoch   5/200 | Train: Loss=0.5202, F1 Score=0.8429 | Val: Loss=0.7565, F1 Score=0.7329
Epoch   6/200 | Train: Loss=0.4919, F1 Score=0.8490 | Val: Loss=0.5501, F1 Score=0.8966
Epoch   7/200 | Train: Loss=0.4545, F1 Score=0.8514 | Val: Loss=0.5570, F1 Score=0.8944
Epoch   8/200 | Train: Loss=0.4044, F1 Score=0.8753 | Val: Loss=0.4933, F1 Score=0.9020
Epoch   9/200 | Train: Loss=0.3652, F1 Score=0.8877 | Val: Loss=0.4204, F1 Score=0.8447
Epoch  10/200 | Train: Loss=0.3732, F1 Score=0.8790 | Val: Loss=0.4015, F1 Score=0.9064
Epoch  11/200 | Train: Loss=0.3265, F1 Score=0.9026 | Val: Loss=0.5531, F1 Score=0.8076
Epoch  12/200 | Train: Loss=0.3147, F1 Score=0.8977 | Val: Loss=0.3562, F1 Score=0.9172
Epoch  13/200 | Train: Loss=0.3038, F1 Score=0.9023 | Val: Loss=0.4527, F1 Score=0.8678
Epoch  14/200 | Train: Loss=0.2735, F1 Score=0.9050 | Val: Loss=0.3229, F1 Score=0.8773
Epoch  15/200 | Train: Loss=0.3025, F1 Score=0.9015 | Val: Loss=0.3542, F1 Score=0.9102
Epoch  16/200 | Train: Loss=0.2593, F1 Score=0.9041 | Val: Loss=0.3773, F1 Score=0.9061
Epoch  17/200 | Train: Loss=0.2746, F1 Score=0.9004 | Val: Loss=0.3352, F1 Score=0.9035
Epoch  18/200 | Train: Loss=0.2052, F1 Score=0.9248 | Val: Loss=0.4209, F1 Score=0.9162
Epoch  19/200 | Train: Loss=0.1578, F1 Score=0.9353 | Val: Loss=0.3321, F1 Score=0.8750
Epoch  20/200 | Train: Loss=0.1418, F1 Score=0.9402 | Val: Loss=0.3304, F1 Score=0.8800
Epoch  21/200 | Train: Loss=0.1373, F1 Score=0.9389 | Val: Loss=0.3535, F1 Score=0.8723
Epoch  22/200 | Train: Loss=0.1354, F1 Score=0.9405 | Val: Loss=0.3698, F1 Score=0.8832
Epoch  23/200 | Train: Loss=0.1325, F1 Score=0.9422 | Val: Loss=0.3209, F1 Score=0.8945
Epoch  24/200 | Train: Loss=0.1236, F1 Score=0.9444 | Val: Loss=0.3324, F1 Score=0.8909
Epoch  25/200 | Train: Loss=0.1147, F1 Score=0.9476 | Val: Loss=0.3370, F1 Score=0.8983
Epoch  26/200 | Train: Loss=0.1098, F1 Score=0.9509 | Val: Loss=0.3444, F1 Score=0.9011

[I 2025-11-11 18:34:40,530] Trial 41 finished with value: 0.9172095014736226 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.44679696729556423, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0008347209739371609, 'weight_decay': 1.7140232353030628e-06, 'l1_lambda': 1.1134981305617476e-06, 'focal_gamma': 3.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 2.1338880081742304}. Best is trial 27 with value: 0.9499284386309793.

Epoch  27/200 | Train: Loss=0.1111, F1 Score=0.9493 | Val: Loss=0.3435, F1 Score=0.8963
Early stopping triggered after 27 epochs.
Best model restored from epoch 12 with val_f1 0.9172
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0133, F1 Score=0.5786 | Val: Loss=1.0355, F1 Score=0.4503
Epoch   2/200 | Train: Loss=0.8958, F1 Score=0.6331 | Val: Loss=0.8645, F1 Score=0.7093
Epoch   3/200 | Train: Loss=0.8137, F1 Score=0.6683 | Val: Loss=0.8198, F1 Score=0.7625
Epoch   4/200 | Train: Loss=0.6818, F1 Score=0.7636 | Val: Loss=0.6719, F1 Score=0.7194
Epoch   5/200 | Train: Loss=0.5337, F1 Score=0.8303 | Val: Loss=0.5985, F1 Score=0.8071
Epoch   6/200 | Train: Loss=0.4996, F1 Score=0.8533 | Val: Loss=0.6000, F1 Score=0.7188
Epoch   7/200 | Train: Loss=0.4756, F1 Score=0.8355 | Val: Loss=0.4857, F1 Score=0.8614
Epoch   8/200 | Train: Loss=0.4272, F1 Score=0.8702 | Val: Loss=0.5565, F1 Score=0.8548
Epoch   9/200 | Train: Loss=0.3935, F1 Score=0.8715 | Val: Loss=0.5570, F1 Score=0.8666
Epoch  10/200 | Train: Loss=0.4421, F1 Score=0.8560 | Val: Loss=0.5983, F1 Score=0.8725
Epoch  11/200 | Train: Loss=0.4298, F1 Score=0.8683 | Val: Loss=0.5654, F1 Score=0.8843
Epoch  12/200 | Train: Loss=0.3466, F1 Score=0.8943 | Val: Loss=0.5437, F1 Score=0.8577
Epoch  13/200 | Train: Loss=0.3268, F1 Score=0.8945 | Val: Loss=0.5940, F1 Score=0.8376
Epoch  14/200 | Train: Loss=0.3446, F1 Score=0.8954 | Val: Loss=0.5671, F1 Score=0.8542
Epoch  15/200 | Train: Loss=0.3021, F1 Score=0.9058 | Val: Loss=0.5229, F1 Score=0.8833
Epoch  16/200 | Train: Loss=0.2682, F1 Score=0.9166 | Val: Loss=0.5391, F1 Score=0.8975
Epoch  17/200 | Train: Loss=0.2976, F1 Score=0.9017 | Val: Loss=0.4995, F1 Score=0.8726
Epoch  18/200 | Train: Loss=0.2230, F1 Score=0.9247 | Val: Loss=0.4008, F1 Score=0.8423
Epoch  19/200 | Train: Loss=0.2742, F1 Score=0.9028 | Val: Loss=0.4925, F1 Score=0.8130
Epoch  20/200 | Train: Loss=0.2345, F1 Score=0.9111 | Val: Loss=0.4986, F1 Score=0.9110
Epoch  21/200 | Train: Loss=0.2100, F1 Score=0.9276 | Val: Loss=0.3557, F1 Score=0.9043
Epoch  22/200 | Train: Loss=0.1828, F1 Score=0.9287 | Val: Loss=0.3448, F1 Score=0.9031
Epoch  23/200 | Train: Loss=0.2532, F1 Score=0.9054 | Val: Loss=0.3373, F1 Score=0.8523
Epoch  24/200 | Train: Loss=0.2090, F1 Score=0.9206 | Val: Loss=0.4330, F1 Score=0.9009
Epoch  25/200 | Train: Loss=0.2025, F1 Score=0.9207 | Val: Loss=0.3517, F1 Score=0.8957
Epoch  26/200 | Train: Loss=0.1730, F1 Score=0.9323 | Val: Loss=0.2380, F1 Score=0.9388
Epoch  27/200 | Train: Loss=0.1651, F1 Score=0.9352 | Val: Loss=0.3842, F1 Score=0.9118
Epoch  28/200 | Train: Loss=0.1543, F1 Score=0.9355 | Val: Loss=0.3205, F1 Score=0.8768
Epoch  29/200 | Train: Loss=0.1453, F1 Score=0.9337 | Val: Loss=0.3096, F1 Score=0.8692
Epoch  30/200 | Train: Loss=0.1862, F1 Score=0.9270 | Val: Loss=0.4463, F1 Score=0.8847
Epoch  31/200 | Train: Loss=0.1623, F1 Score=0.9358 | Val: Loss=0.3203, F1 Score=0.9093
Epoch  32/200 | Train: Loss=0.1513, F1 Score=0.9382 | Val: Loss=0.3672, F1 Score=0.8898
Epoch  33/200 | Train: Loss=0.1265, F1 Score=0.9451 | Val: Loss=0.2821, F1 Score=0.8860
Epoch  34/200 | Train: Loss=0.0810, F1 Score=0.9596 | Val: Loss=0.2164, F1 Score=0.9290
Epoch  35/200 | Train: Loss=0.0735, F1 Score=0.9631 | Val: Loss=0.2279, F1 Score=0.9302
Epoch  36/200 | Train: Loss=0.0722, F1 Score=0.9633 | Val: Loss=0.2245, F1 Score=0.9256
Epoch  37/200 | Train: Loss=0.0708, F1 Score=0.9658 | Val: Loss=0.2316, F1 Score=0.9267
Epoch  38/200 | Train: Loss=0.0680, F1 Score=0.9657 | Val: Loss=0.2363, F1 Score=0.9252
Epoch  39/200 | Train: Loss=0.0719, F1 Score=0.9662 | Val: Loss=0.2369, F1 Score=0.9156
Epoch  40/200 | Train: Loss=0.0679, F1 Score=0.9655 | Val: Loss=0.2626, F1 Score=0.9291

[I 2025-11-11 18:35:36,182] Trial 42 finished with value: 0.9387706484737612 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.5075718768777069, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0009571297182029895, 'weight_decay': 2.7265980827582333e-06, 'l1_lambda': 9.709561031672515e-07, 'focal_gamma': 3.5, 'scheduler_patience': 6, 'scheduler_factor': 0.2, 'weight_max_norm': 2.067139711515135}. Best is trial 27 with value: 0.9499284386309793.

Epoch  41/200 | Train: Loss=0.0620, F1 Score=0.9683 | Val: Loss=0.2521, F1 Score=0.9271
Early stopping triggered after 41 epochs.
Best model restored from epoch 26 with val_f1 0.9388
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0730, F1 Score=0.5872 | Val: Loss=0.9811, F1 Score=0.7786
Epoch   2/200 | Train: Loss=0.9468, F1 Score=0.6628 | Val: Loss=0.9644, F1 Score=0.7867
Epoch   3/200 | Train: Loss=0.8727, F1 Score=0.6517 | Val: Loss=0.9037, F1 Score=0.5712
Epoch   4/200 | Train: Loss=0.8100, F1 Score=0.6830 | Val: Loss=0.8319, F1 Score=0.6600
Epoch   5/200 | Train: Loss=0.6985, F1 Score=0.7449 | Val: Loss=0.7419, F1 Score=0.7032
Epoch   6/200 | Train: Loss=0.5808, F1 Score=0.8247 | Val: Loss=0.5129, F1 Score=0.9161
Epoch   7/200 | Train: Loss=0.5159, F1 Score=0.8378 | Val: Loss=0.4998, F1 Score=0.8760
Epoch   8/200 | Train: Loss=0.4881, F1 Score=0.8544 | Val: Loss=0.5680, F1 Score=0.8325
Epoch   9/200 | Train: Loss=0.4966, F1 Score=0.8538 | Val: Loss=0.6640, F1 Score=0.8234
Epoch  10/200 | Train: Loss=0.4381, F1 Score=0.8736 | Val: Loss=0.5101, F1 Score=0.8609
Epoch  11/200 | Train: Loss=0.4271, F1 Score=0.8812 | Val: Loss=0.5323, F1 Score=0.8678
Epoch  12/200 | Train: Loss=0.4104, F1 Score=0.8861 | Val: Loss=0.5085, F1 Score=0.8327
Epoch  13/200 | Train: Loss=0.4185, F1 Score=0.8793 | Val: Loss=0.4402, F1 Score=0.8946
Epoch  14/200 | Train: Loss=0.3449, F1 Score=0.9074 | Val: Loss=0.4489, F1 Score=0.8945
Epoch  15/200 | Train: Loss=0.3290, F1 Score=0.9109 | Val: Loss=0.4514, F1 Score=0.8797
Epoch  16/200 | Train: Loss=0.3190, F1 Score=0.9106 | Val: Loss=0.4838, F1 Score=0.8578
Epoch  17/200 | Train: Loss=0.3120, F1 Score=0.9136 | Val: Loss=0.5317, F1 Score=0.9011
Epoch  18/200 | Train: Loss=0.3056, F1 Score=0.9159 | Val: Loss=0.4655, F1 Score=0.8922
Epoch  19/200 | Train: Loss=0.2980, F1 Score=0.9146 | Val: Loss=0.5669, F1 Score=0.8678
Epoch  20/200 | Train: Loss=0.2991, F1 Score=0.9140 | Val: Loss=0.4433, F1 Score=0.8744

[I 2025-11-11 18:36:04,955] Trial 43 finished with value: 0.9160896885010951 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.5076269091610339, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0005706753863535637, 'weight_decay': 3.5869489570028002e-06, 'l1_lambda': 3.877800096129533e-06, 'focal_gamma': 4.0, 'scheduler_patience': 6, 'scheduler_factor': 0.2, 'weight_max_norm': 2.5725235160277125}. Best is trial 27 with value: 0.9499284386309793.

Epoch  21/200 | Train: Loss=0.2792, F1 Score=0.9207 | Val: Loss=0.4213, F1 Score=0.8754
Early stopping triggered after 21 epochs.
Best model restored from epoch 6 with val_f1 0.9161
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0909, F1 Score=0.5423 | Val: Loss=1.0520, F1 Score=0.7309
Epoch   2/200 | Train: Loss=1.0045, F1 Score=0.6683 | Val: Loss=0.9043, F1 Score=0.7447
Epoch   3/200 | Train: Loss=0.9281, F1 Score=0.7031 | Val: Loss=1.0293, F1 Score=0.5556
Epoch   4/200 | Train: Loss=0.8745, F1 Score=0.7078 | Val: Loss=0.8411, F1 Score=0.8082
Epoch   5/200 | Train: Loss=0.7742, F1 Score=0.7704 | Val: Loss=0.7714, F1 Score=0.8510
Epoch   6/200 | Train: Loss=0.7060, F1 Score=0.7933 | Val: Loss=0.7448, F1 Score=0.8189
Epoch   7/200 | Train: Loss=0.5791, F1 Score=0.8297 | Val: Loss=0.6300, F1 Score=0.8550
Epoch   8/200 | Train: Loss=0.5319, F1 Score=0.8551 | Val: Loss=0.6278, F1 Score=0.8570
Epoch   9/200 | Train: Loss=0.4809, F1 Score=0.8660 | Val: Loss=0.5687, F1 Score=0.8744
Epoch  10/200 | Train: Loss=0.4469, F1 Score=0.8774 | Val: Loss=0.6662, F1 Score=0.8432
Epoch  11/200 | Train: Loss=0.4280, F1 Score=0.8751 | Val: Loss=0.5755, F1 Score=0.8808
Epoch  12/200 | Train: Loss=0.4117, F1 Score=0.8847 | Val: Loss=0.5780, F1 Score=0.8549
Epoch  13/200 | Train: Loss=0.3994, F1 Score=0.8909 | Val: Loss=0.5714, F1 Score=0.9107
Epoch  14/200 | Train: Loss=0.4012, F1 Score=0.8811 | Val: Loss=0.5740, F1 Score=0.8723
Epoch  15/200 | Train: Loss=0.3788, F1 Score=0.8979 | Val: Loss=0.5716, F1 Score=0.8485
Epoch  16/200 | Train: Loss=0.3691, F1 Score=0.8968 | Val: Loss=0.5503, F1 Score=0.8838
Epoch  17/200 | Train: Loss=0.3564, F1 Score=0.9005 | Val: Loss=0.5386, F1 Score=0.8856
Epoch  18/200 | Train: Loss=0.3555, F1 Score=0.8981 | Val: Loss=0.5716, F1 Score=0.8327
Epoch  19/200 | Train: Loss=0.3473, F1 Score=0.8969 | Val: Loss=0.5948, F1 Score=0.8172
Epoch  20/200 | Train: Loss=0.3306, F1 Score=0.8982 | Val: Loss=0.5787, F1 Score=0.8731
Epoch  21/200 | Train: Loss=0.3007, F1 Score=0.9133 | Val: Loss=0.5582, F1 Score=0.8627
Epoch  22/200 | Train: Loss=0.2878, F1 Score=0.9143 | Val: Loss=0.5480, F1 Score=0.8703
Epoch  23/200 | Train: Loss=0.2835, F1 Score=0.9140 | Val: Loss=0.5308, F1 Score=0.8615
Epoch  24/200 | Train: Loss=0.2854, F1 Score=0.9157 | Val: Loss=0.5269, F1 Score=0.8780
Epoch  25/200 | Train: Loss=0.2902, F1 Score=0.9114 | Val: Loss=0.5407, F1 Score=0.8730
Epoch  26/200 | Train: Loss=0.2787, F1 Score=0.9140 | Val: Loss=0.5430, F1 Score=0.8453
Epoch  27/200 | Train: Loss=0.2823, F1 Score=0.9120 | Val: Loss=0.5325, F1 Score=0.8778

[I 2025-11-11 18:36:42,831] Trial 44 finished with value: 0.9107415172504054 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 32, 'num_layers': 2, 'dropout_rate': 0.5358339577810162, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0007384658402724047, 'weight_decay': 1.4626520496207599e-05, 'l1_lambda': 4.2965084123838177e-07, 'focal_gamma': 2.5, 'scheduler_patience': 6, 'scheduler_factor': 0.2, 'weight_max_norm': 2.9935822535377272}. Best is trial 27 with value: 0.9499284386309793.

Epoch  28/200 | Train: Loss=0.2723, F1 Score=0.9169 | Val: Loss=0.5274, F1 Score=0.8754
Early stopping triggered after 28 epochs.
Best model restored from epoch 13 with val_f1 0.9107
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0155, F1 Score=0.6155 | Val: Loss=0.8986, F1 Score=0.7830
Epoch   2/200 | Train: Loss=0.9268, F1 Score=0.6418 | Val: Loss=0.8796, F1 Score=0.7956
Epoch   3/200 | Train: Loss=0.8432, F1 Score=0.6904 | Val: Loss=0.7387, F1 Score=0.7857
Epoch   4/200 | Train: Loss=0.7511, F1 Score=0.7406 | Val: Loss=0.5628, F1 Score=0.8897
Epoch   5/200 | Train: Loss=0.6584, F1 Score=0.7970 | Val: Loss=0.5689, F1 Score=0.8712
Epoch   6/200 | Train: Loss=0.5354, F1 Score=0.8391 | Val: Loss=0.6062, F1 Score=0.7163
Epoch   7/200 | Train: Loss=0.5125, F1 Score=0.8324 | Val: Loss=0.4821, F1 Score=0.8928
Epoch   8/200 | Train: Loss=0.4483, F1 Score=0.8587 | Val: Loss=0.5401, F1 Score=0.8739
Epoch   9/200 | Train: Loss=0.4163, F1 Score=0.8698 | Val: Loss=0.4515, F1 Score=0.8483
Epoch  10/200 | Train: Loss=0.3905, F1 Score=0.8771 | Val: Loss=0.5098, F1 Score=0.8796
Epoch  11/200 | Train: Loss=0.3564, F1 Score=0.8838 | Val: Loss=0.4711, F1 Score=0.8921
Epoch  12/200 | Train: Loss=0.2713, F1 Score=0.9157 | Val: Loss=0.4385, F1 Score=0.8749
Epoch  13/200 | Train: Loss=0.2415, F1 Score=0.9201 | Val: Loss=0.4793, F1 Score=0.8801
Epoch  14/200 | Train: Loss=0.2176, F1 Score=0.9246 | Val: Loss=0.4871, F1 Score=0.8950
Epoch  15/200 | Train: Loss=0.2135, F1 Score=0.9190 | Val: Loss=0.4567, F1 Score=0.8743
Epoch  16/200 | Train: Loss=0.1908, F1 Score=0.9263 | Val: Loss=0.5502, F1 Score=0.8610
Epoch  17/200 | Train: Loss=0.1912, F1 Score=0.9266 | Val: Loss=0.5389, F1 Score=0.8729
Epoch  18/200 | Train: Loss=0.1746, F1 Score=0.9238 | Val: Loss=0.6163, F1 Score=0.8860
Epoch  19/200 | Train: Loss=0.1684, F1 Score=0.9373 | Val: Loss=0.5295, F1 Score=0.8968
Epoch  20/200 | Train: Loss=0.1466, F1 Score=0.9391 | Val: Loss=0.5256, F1 Score=0.8888
Epoch  21/200 | Train: Loss=0.1419, F1 Score=0.9424 | Val: Loss=0.5328, F1 Score=0.8946
Epoch  22/200 | Train: Loss=0.1440, F1 Score=0.9393 | Val: Loss=0.5587, F1 Score=0.8898
Epoch  23/200 | Train: Loss=0.1400, F1 Score=0.9411 | Val: Loss=0.5838, F1 Score=0.8948
Epoch  24/200 | Train: Loss=0.1366, F1 Score=0.9424 | Val: Loss=0.5477, F1 Score=0.8945
Epoch  25/200 | Train: Loss=0.1351, F1 Score=0.9425 | Val: Loss=0.5416, F1 Score=0.8898
Epoch  26/200 | Train: Loss=0.1365, F1 Score=0.9409 | Val: Loss=0.5440, F1 Score=0.8888
Epoch  27/200 | Train: Loss=0.1382, F1 Score=0.9420 | Val: Loss=0.5496, F1 Score=0.8892
Epoch  28/200 | Train: Loss=0.1326, F1 Score=0.9427 | Val: Loss=0.5486, F1 Score=0.8892
Epoch  29/200 | Train: Loss=0.1325, F1 Score=0.9428 | Val: Loss=0.5478, F1 Score=0.8897
Epoch  30/200 | Train: Loss=0.1348, F1 Score=0.9418 | Val: Loss=0.5485, F1 Score=0.8897
Epoch  31/200 | Train: Loss=0.1315, F1 Score=0.9441 | Val: Loss=0.5487, F1 Score=0.8897
Epoch  32/200 | Train: Loss=0.1304, F1 Score=0.9434 | Val: Loss=0.5483, F1 Score=0.8897
Epoch  33/200 | Train: Loss=0.1324, F1 Score=0.9451 | Val: Loss=0.5484, F1 Score=0.8897

[I 2025-11-11 18:37:29,007] Trial 45 finished with value: 0.896812813143922 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.4972915967027033, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0009996971735824606, 'weight_decay': 1.324037863282024e-06, 'l1_lambda': 2.707978786206677e-07, 'focal_gamma': 3.0, 'scheduler_patience': 3, 'scheduler_factor': 0.2, 'weight_max_norm': 1.8707792036480804}. Best is trial 27 with value: 0.9499284386309793.

Epoch  34/200 | Train: Loss=0.1309, F1 Score=0.9439 | Val: Loss=0.5486, F1 Score=0.8897
Early stopping triggered after 34 epochs.
Best model restored from epoch 19 with val_f1 0.8968
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0922, F1 Score=0.5425 | Val: Loss=1.0457, F1 Score=0.7273
Epoch   2/200 | Train: Loss=0.9841, F1 Score=0.6497 | Val: Loss=0.9413, F1 Score=0.7685
Epoch   3/200 | Train: Loss=0.9473, F1 Score=0.6567 | Val: Loss=0.9867, F1 Score=0.4624
Epoch   4/200 | Train: Loss=0.9119, F1 Score=0.6433 | Val: Loss=0.9143, F1 Score=0.5986
Epoch   5/200 | Train: Loss=0.8562, F1 Score=0.6464 | Val: Loss=0.9901, F1 Score=0.5956
Epoch   6/200 | Train: Loss=0.8679, F1 Score=0.6547 | Val: Loss=0.9058, F1 Score=0.4891

[I 2025-11-11 18:37:36,007] Trial 46 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 20, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.5959806333205575, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0005927010000805277, 'weight_decay': 2.624449360762608e-06, 'l1_lambda': 1.4352399491663048e-06, 'focal_gamma': 4.0, 'scheduler_patience': 6, 'scheduler_factor': 0.5, 'weight_max_norm': 2.4055969107778195}. Best is trial 27 with value: 0.9499284386309793.

Epoch   7/200 | Train: Loss=0.8495, F1 Score=0.7127 | Val: Loss=0.8005, F1 Score=0.7605
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0895, F1 Score=0.5444 | Val: Loss=1.0536, F1 Score=0.7595
Epoch   2/200 | Train: Loss=1.0608, F1 Score=0.6638 | Val: Loss=1.0290, F1 Score=0.6084
Epoch   3/200 | Train: Loss=0.9802, F1 Score=0.6574 | Val: Loss=0.9582, F1 Score=0.5971
Epoch   4/200 | Train: Loss=0.9101, F1 Score=0.7182 | Val: Loss=0.8502, F1 Score=0.7696
Epoch   5/200 | Train: Loss=0.8304, F1 Score=0.7382 | Val: Loss=0.9308, F1 Score=0.5934
Epoch   6/200 | Train: Loss=0.7972, F1 Score=0.7446 | Val: Loss=0.7637, F1 Score=0.8100
Epoch   7/200 | Train: Loss=0.7416, F1 Score=0.7629 | Val: Loss=0.9447, F1 Score=0.6254

[I 2025-11-11 18:37:47,637] Trial 47 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 32, 'num_layers': 1, 'dropout_rate': 0.4179472431724368, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0004897687730265077, 'weight_decay': 9.736270193499855e-06, 'l1_lambda': 2.4203572265953543e-06, 'focal_gamma': 3.5, 'scheduler_patience': 7, 'scheduler_factor': 0.2, 'weight_max_norm': 3.339057016264629}. Best is trial 27 with value: 0.9499284386309793.

Epoch   8/200 | Train: Loss=0.7241, F1 Score=0.7608 | Val: Loss=0.7273, F1 Score=0.7848
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0674, F1 Score=0.5692 | Val: Loss=0.9179, F1 Score=0.7867
Epoch   2/200 | Train: Loss=0.9358, F1 Score=0.6376 | Val: Loss=0.9104, F1 Score=0.6618
Epoch   3/200 | Train: Loss=0.8469, F1 Score=0.6730 | Val: Loss=0.8595, F1 Score=0.6413
Epoch   4/200 | Train: Loss=0.7563, F1 Score=0.7408 | Val: Loss=0.6566, F1 Score=0.7978
Epoch   5/200 | Train: Loss=0.5901, F1 Score=0.8278 | Val: Loss=0.5395, F1 Score=0.8584
Epoch   6/200 | Train: Loss=0.5061, F1 Score=0.8481 | Val: Loss=0.6355, F1 Score=0.8738
Epoch   7/200 | Train: Loss=0.4939, F1 Score=0.8653 | Val: Loss=0.5865, F1 Score=0.8153
Epoch   8/200 | Train: Loss=0.4391, F1 Score=0.8626 | Val: Loss=0.6859, F1 Score=0.8780
Epoch   9/200 | Train: Loss=0.4234, F1 Score=0.8662 | Val: Loss=0.5755, F1 Score=0.8612
Epoch  10/200 | Train: Loss=0.3686, F1 Score=0.8818 | Val: Loss=0.4572, F1 Score=0.8371
Epoch  11/200 | Train: Loss=0.3613, F1 Score=0.8900 | Val: Loss=0.3749, F1 Score=0.8853
Epoch  12/200 | Train: Loss=0.3045, F1 Score=0.9046 | Val: Loss=0.4975, F1 Score=0.8712
Epoch  13/200 | Train: Loss=0.2999, F1 Score=0.9005 | Val: Loss=0.5228, F1 Score=0.9045
Epoch  14/200 | Train: Loss=0.3152, F1 Score=0.9020 | Val: Loss=0.3344, F1 Score=0.8904
Epoch  15/200 | Train: Loss=0.2459, F1 Score=0.9149 | Val: Loss=0.3970, F1 Score=0.8883
Epoch  16/200 | Train: Loss=0.3051, F1 Score=0.9095 | Val: Loss=0.4584, F1 Score=0.8808
Epoch  17/200 | Train: Loss=0.2408, F1 Score=0.9188 | Val: Loss=0.4168, F1 Score=0.8962
Epoch  18/200 | Train: Loss=0.2251, F1 Score=0.9202 | Val: Loss=0.3544, F1 Score=0.8529
Epoch  19/200 | Train: Loss=0.1984, F1 Score=0.9256 | Val: Loss=0.3883, F1 Score=0.8416
Epoch  20/200 | Train: Loss=0.1579, F1 Score=0.9446 | Val: Loss=0.3316, F1 Score=0.8916
Epoch  21/200 | Train: Loss=0.1432, F1 Score=0.9488 | Val: Loss=0.3006, F1 Score=0.9094
Epoch  22/200 | Train: Loss=0.1448, F1 Score=0.9459 | Val: Loss=0.3067, F1 Score=0.8987
Epoch  23/200 | Train: Loss=0.1395, F1 Score=0.9487 | Val: Loss=0.3204, F1 Score=0.8868
Epoch  24/200 | Train: Loss=0.1298, F1 Score=0.9504 | Val: Loss=0.3331, F1 Score=0.8998
Epoch  25/200 | Train: Loss=0.1317, F1 Score=0.9464 | Val: Loss=0.3257, F1 Score=0.8956
Epoch  26/200 | Train: Loss=0.1371, F1 Score=0.9475 | Val: Loss=0.3225, F1 Score=0.8808
Epoch  27/200 | Train: Loss=0.1233, F1 Score=0.9501 | Val: Loss=0.3313, F1 Score=0.8754
Epoch  28/200 | Train: Loss=0.1185, F1 Score=0.9495 | Val: Loss=0.3060, F1 Score=0.9022
Epoch  29/200 | Train: Loss=0.1131, F1 Score=0.9533 | Val: Loss=0.3146, F1 Score=0.9041
Epoch  30/200 | Train: Loss=0.1127, F1 Score=0.9549 | Val: Loss=0.3078, F1 Score=0.8928
Epoch  31/200 | Train: Loss=0.1148, F1 Score=0.9530 | Val: Loss=0.3108, F1 Score=0.8986
Epoch  32/200 | Train: Loss=0.1101, F1 Score=0.9555 | Val: Loss=0.3125, F1 Score=0.9002
Epoch  33/200 | Train: Loss=0.1095, F1 Score=0.9556 | Val: Loss=0.3185, F1 Score=0.9041
Epoch  34/200 | Train: Loss=0.1085, F1 Score=0.9573 | Val: Loss=0.3164, F1 Score=0.8976
Epoch  35/200 | Train: Loss=0.1082, F1 Score=0.9570 | Val: Loss=0.3164, F1 Score=0.8977

[I 2025-11-11 18:38:49,359] Trial 48 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.4771443593592058, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0003711171759853359, 'weight_decay': 4.276193190162569e-05, 'l1_lambda': 7.080089498939243e-07, 'focal_gamma': 2.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 1.5836593533874728}. Best is trial 27 with value: 0.9499284386309793.

Epoch  36/200 | Train: Loss=0.1068, F1 Score=0.9574 | Val: Loss=0.3157, F1 Score=0.8967
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0437, F1 Score=0.6147 | Val: Loss=0.9398, F1 Score=0.6178
Epoch   2/200 | Train: Loss=0.9132, F1 Score=0.6578 | Val: Loss=0.9767, F1 Score=0.8213
Epoch   3/200 | Train: Loss=0.8868, F1 Score=0.6757 | Val: Loss=0.8571, F1 Score=0.6447
Epoch   4/200 | Train: Loss=0.7485, F1 Score=0.7393 | Val: Loss=0.8656, F1 Score=0.6679
Epoch   5/200 | Train: Loss=0.6486, F1 Score=0.7958 | Val: Loss=0.5646, F1 Score=0.8449
Epoch   6/200 | Train: Loss=0.6200, F1 Score=0.7957 | Val: Loss=0.6176, F1 Score=0.7882
Epoch   7/200 | Train: Loss=0.5761, F1 Score=0.8101 | Val: Loss=0.5415, F1 Score=0.8375
Epoch   8/200 | Train: Loss=0.4959, F1 Score=0.8431 | Val: Loss=0.5392, F1 Score=0.8500
Epoch   9/200 | Train: Loss=0.4412, F1 Score=0.8641 | Val: Loss=0.5432, F1 Score=0.8912
Epoch  10/200 | Train: Loss=0.4450, F1 Score=0.8717 | Val: Loss=0.4095, F1 Score=0.8749
Epoch  11/200 | Train: Loss=0.4123, F1 Score=0.8688 | Val: Loss=0.4444, F1 Score=0.8844
Epoch  12/200 | Train: Loss=0.3913, F1 Score=0.8852 | Val: Loss=0.6645, F1 Score=0.6932
Epoch  13/200 | Train: Loss=0.3818, F1 Score=0.8760 | Val: Loss=0.3841, F1 Score=0.8864
Epoch  14/200 | Train: Loss=0.3011, F1 Score=0.9049 | Val: Loss=0.3954, F1 Score=0.8625
Epoch  15/200 | Train: Loss=0.3384, F1 Score=0.8993 | Val: Loss=0.4751, F1 Score=0.8299
Epoch  16/200 | Train: Loss=0.2079, F1 Score=0.9267 | Val: Loss=0.3217, F1 Score=0.9037
Epoch  17/200 | Train: Loss=0.1882, F1 Score=0.9368 | Val: Loss=0.3513, F1 Score=0.8640
Epoch  18/200 | Train: Loss=0.1809, F1 Score=0.9344 | Val: Loss=0.3516, F1 Score=0.8835
Epoch  19/200 | Train: Loss=0.1697, F1 Score=0.9382 | Val: Loss=0.3376, F1 Score=0.9070
Epoch  20/200 | Train: Loss=0.1559, F1 Score=0.9392 | Val: Loss=0.3422, F1 Score=0.9108
Epoch  21/200 | Train: Loss=0.1519, F1 Score=0.9425 | Val: Loss=0.3779, F1 Score=0.8947
Epoch  22/200 | Train: Loss=0.1501, F1 Score=0.9418 | Val: Loss=0.3584, F1 Score=0.8855
Epoch  23/200 | Train: Loss=0.1378, F1 Score=0.9425 | Val: Loss=0.4057, F1 Score=0.8891
Epoch  24/200 | Train: Loss=0.1439, F1 Score=0.9427 | Val: Loss=0.3540, F1 Score=0.8868
Epoch  25/200 | Train: Loss=0.1317, F1 Score=0.9472 | Val: Loss=0.3786, F1 Score=0.8777
Epoch  26/200 | Train: Loss=0.1270, F1 Score=0.9457 | Val: Loss=0.3873, F1 Score=0.9188
Epoch  27/200 | Train: Loss=0.1295, F1 Score=0.9463 | Val: Loss=0.3247, F1 Score=0.8989
Epoch  28/200 | Train: Loss=0.1364, F1 Score=0.9389 | Val: Loss=0.3587, F1 Score=0.9098
Epoch  29/200 | Train: Loss=0.1581, F1 Score=0.9401 | Val: Loss=0.4616, F1 Score=0.8914
Epoch  30/200 | Train: Loss=0.1334, F1 Score=0.9421 | Val: Loss=0.3263, F1 Score=0.9211
Epoch  31/200 | Train: Loss=0.1140, F1 Score=0.9505 | Val: Loss=0.3499, F1 Score=0.9182
Epoch  32/200 | Train: Loss=0.1054, F1 Score=0.9584 | Val: Loss=0.3460, F1 Score=0.9236
Epoch  33/200 | Train: Loss=0.1123, F1 Score=0.9491 | Val: Loss=0.3337, F1 Score=0.9279
Epoch  34/200 | Train: Loss=0.1076, F1 Score=0.9511 | Val: Loss=0.3496, F1 Score=0.9269
Epoch  35/200 | Train: Loss=0.1090, F1 Score=0.9551 | Val: Loss=0.3836, F1 Score=0.9126
Epoch  36/200 | Train: Loss=0.1028, F1 Score=0.9537 | Val: Loss=0.3313, F1 Score=0.9286
Epoch  37/200 | Train: Loss=0.1056, F1 Score=0.9529 | Val: Loss=0.3499, F1 Score=0.9388
Epoch  38/200 | Train: Loss=0.1072, F1 Score=0.9552 | Val: Loss=0.4122, F1 Score=0.8820
Epoch  39/200 | Train: Loss=0.1031, F1 Score=0.9534 | Val: Loss=0.3561, F1 Score=0.9214
Epoch  40/200 | Train: Loss=0.0881, F1 Score=0.9605 | Val: Loss=0.3453, F1 Score=0.9322
Epoch  41/200 | Train: Loss=0.0897, F1 Score=0.9581 | Val: Loss=0.3649, F1 Score=0.9348
Epoch  42/200 | Train: Loss=0.1195, F1 Score=0.9484 | Val: Loss=0.3563, F1 Score=0.9172
Epoch  43/200 | Train: Loss=0.0904, F1 Score=0.9601 | Val: Loss=0.3456, F1 Score=0.9373
Epoch  44/200 | Train: Loss=0.0738, F1 Score=0.9680 | Val: Loss=0.3535, F1 Score=0.9342
Epoch  45/200 | Train: Loss=0.0693, F1 Score=0.9688 | Val: Loss=0.3580, F1 Score=0.9337
Epoch  46/200 | Train: Loss=0.0713, F1 Score=0.9681 | Val: Loss=0.3505, F1 Score=0.9314
Epoch  47/200 | Train: Loss=0.0670, F1 Score=0.9732 | Val: Loss=0.3585, F1 Score=0.9335
Epoch  48/200 | Train: Loss=0.0697, F1 Score=0.9690 | Val: Loss=0.3500, F1 Score=0.9374
Epoch  49/200 | Train: Loss=0.0687, F1 Score=0.9700 | Val: Loss=0.3644, F1 Score=0.9314
Epoch  50/200 | Train: Loss=0.0639, F1 Score=0.9721 | Val: Loss=0.3639, F1 Score=0.9325
Epoch  51/200 | Train: Loss=0.0662, F1 Score=0.9710 | Val: Loss=0.3628, F1 Score=0.9331

[I 2025-11-11 18:40:08,372] Trial 49 finished with value: 0.9387854956235793 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.523213212530997, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0006901340837149368, 'weight_decay': 7.380348679878528e-06, 'l1_lambda': 1.0932095374793297e-06, 'focal_gamma': 3.0, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 2.2016696892921264}. Best is trial 27 with value: 0.9499284386309793.

Epoch  52/200 | Train: Loss=0.0669, F1 Score=0.9722 | Val: Loss=0.3626, F1 Score=0.9344
Early stopping triggered after 52 epochs.
Best model restored from epoch 37 with val_f1 0.9388

--- Tuning Complete ---
Best trial number: 27
Best validation F1-score: 0.9499
Best hyperparameters found:
  WINDOW: 40
  STRIDE: 10
  hidden_size: 128
  num_layers: 3
  dropout_rate: 0.5377302226330053
  rnn_type: GRU
  bidirectional: True
  init_scheme: orthogonal
  lr: 0.0009785537478176932
  weight_decay: 1.7897780974039973e-05
  l1_lambda: 2.571348226648045e-06
  focal_gamma: 3.5
  scheduler_patience: 5
  scheduler_factor: 0.2
  weight_max_norm: 2.166420382127338

## 🧠 **Model Training**

In [58]:
# Initialize best model tracking variables
best_model = None
best_performance = float('-inf')

In [97]:
def train_one_epoch(model, train_loader, criterion, optimizer, scaler, device, l1_lambda=0, l2_lambda=0):
    """
    Perform one complete training epoch through the entire training dataset.

    Args:
        model (nn.Module): The neural network model to train
        train_loader (DataLoader): PyTorch DataLoader containing training data batches
        criterion (nn.Module): Loss function (e.g., CrossEntropyLoss, MSELoss)
        optimizer (torch.optim): Optimization algorithm (e.g., Adam, SGD)
        scaler (GradScaler): PyTorch's gradient scaler for mixed precision training
        device (torch.device): Computing device ('cuda' for GPU, 'cpu' for CPU)
        l1_lambda (float): Lambda for L1 regularization
        l2_lambda (float): Lambda for L2 regularization

    Returns:
        tuple: (average_loss, f1 score) - Training loss and f1 score for this epoch
    """
    model.train()  # Set model to training mode

    running_loss = 0.0
    all_predictions = []
    all_targets = []

    # Iterate through training batches
    for batch_idx, (inputs, targets) in enumerate(train_loader):
        # Move data to device (GPU/CPU)
        inputs, targets = inputs.to(device), targets.to(device)

        # Clear gradients from previous step
        optimizer.zero_grad(set_to_none=True)

        # Forward pass with mixed precision (if CUDA available)
        with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
            logits = model(inputs)
            loss = criterion(logits, targets)

            # Add L1 and L2 regularization
            l1_norm = sum(p.abs().sum() for p in model.parameters())
            l2_norm = sum(p.pow(2).sum() for p in model.parameters())
            loss = loss + l1_lambda * l1_norm + l2_lambda * l2_norm


        # Backward pass with gradient scaling
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        # Accumulate metrics
        running_loss += loss.item() * inputs.size(0)
        predictions = logits.argmax(dim=1)
        all_predictions.append(predictions.cpu().numpy())
        all_targets.append(targets.cpu().numpy())

    # Calculate epoch metrics
    epoch_loss = running_loss / len(train_loader.dataset)
    epoch_f1 = f1_score(
        np.concatenate(all_targets),
        np.concatenate(all_predictions),
        average='weighted'
    )

    return epoch_loss, epoch_f1

In [98]:
def validate_one_epoch(model, val_loader, criterion, device):
    """
    Perform one complete validation epoch through the entire validation dataset.

    Args:
        model (nn.Module): The neural network model to evaluate (must be in eval mode)
        val_loader (DataLoader): PyTorch DataLoader containing validation data batches
        criterion (nn.Module): Loss function used to calculate validation loss
        device (torch.device): Computing device ('cuda' for GPU, 'cpu' for CPU)

    Returns:
        tuple: (average_loss, accuracy) - Validation loss and accuracy for this epoch

    Note:
        This function automatically sets the model to evaluation mode and disables
        gradient computation for efficiency during validation.
    """
    model.eval()  # Set model to evaluation mode

    running_loss = 0.0
    all_predictions = []
    all_targets = []

    # Disable gradient computation for validation
    with torch.no_grad():
        for inputs, targets in val_loader:
            # Move data to device
            inputs, targets = inputs.to(device), targets.to(device)

            # Forward pass with mixed precision (if CUDA available)
            with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
                logits = model(inputs)
                loss = criterion(logits, targets)

            # Accumulate metrics
            running_loss += loss.item() * inputs.size(0)
            predictions = logits.argmax(dim=1)
            all_predictions.append(predictions.cpu().numpy())
            all_targets.append(targets.cpu().numpy())

    # Calculate epoch metrics
    epoch_loss = running_loss / len(val_loader.dataset)
    epoch_accuracy = f1_score(
        np.concatenate(all_targets),
        np.concatenate(all_predictions),
        average='weighted'
    )

    return epoch_loss, epoch_accuracy

In [99]:
def log_metrics_to_tensorboard(writer, epoch, train_loss, train_f1, val_loss, val_f1, model):
    """
    Log training metrics and model parameters to TensorBoard for visualization.

    Args:
        writer (SummaryWriter): TensorBoard SummaryWriter object for logging
        epoch (int): Current epoch number (used as x-axis in TensorBoard plots)
        train_loss (float): Training loss for this epoch
        train_f1 (float): Training f1 score for this epoch
        val_loss (float): Validation loss for this epoch
        val_f1 (float): Validation f1 score for this epoch
        model (nn.Module): The neural network model (for logging weights/gradients)

    Note:
        This function logs scalar metrics (loss/f1 score) and histograms of model
        parameters and gradients, which helps monitor training progress and detect
        issues like vanishing/exploding gradients.
    """
    # Log scalar metrics
    writer.add_scalar('Loss/Training', train_loss, epoch)
    writer.add_scalar('Loss/Validation', val_loss, epoch)
    writer.add_scalar('F1/Training', train_f1, epoch)
    writer.add_scalar('F1/Validation', val_f1, epoch)

    # Log model parameters and gradients
    for name, param in model.named_parameters():
        if param.requires_grad:
            # Check if the tensor is not empty before adding a histogram
            if param.numel() > 0:
                writer.add_histogram(f'{name}/weights', param.data, epoch)
            if param.grad is not None:
                # Check if the gradient tensor is not empty before adding a histogram
                if param.grad.numel() > 0:
                    if param.grad is not None and torch.isfinite(param.grad).all():
                        writer.add_histogram(f'{name}/gradients', param.grad.data, epoch)

In [100]:
import torch
import torch.nn as nn
import optuna
# Importa la funzione di utilità se necessario (anche se lo faremo manualmente) 7
# import torch.nn.utils as nn_utils 

def fit(model, train_loader, val_loader, epochs, criterion, optimizer, scaler, device,
        l1_lambda=0, l2_lambda=0, patience=0, evaluation_metric="val_f1", mode='max',
        restore_best_weights=True, writer=None, verbose=10, experiment_name="",
        trial=None, scheduler=None, weight_max_norm=None):
    """
    Train the neural network model on the training data and validate on the validation data.
    """

    # --- NUOVA FUNZIONE: Normalizzazione/Vincolo dei Pesi ---
    def apply_weight_constraint(model, max_norm):
        with torch.no_grad():
            for name, module in model.named_modules():
                # Applica solo ai layer con pesi (es. Linear, Conv1d, Conv2d)
                if isinstance(module, (nn.Linear, nn.Conv1d, nn.Conv2d)):
                    # Vincola il parametro 'weight'
                    if hasattr(module, 'weight') and module.weight is not None:
                        # Calcola la norma L2 del tensore dei pesi
                        norm = module.weight.norm(2)
                        
                        if norm > max_norm:
                            # Se la norma è maggiore del vincolo, riscala il peso.
                            # Ciò garantisce che la norma L2 sia esattamente 'max_norm' o inferiore.
                            module.weight.data.mul_(max_norm / norm)

    # Initialize metrics tracking
    training_history = {
        'train_loss': [], 'val_loss': [],
        'train_f1': [], 'val_f1': []
    }

    # Initialize best_metric before loop
    best_metric = float('-inf') if mode == 'max' else float('inf')
    best_epoch = 0
    
    if patience > 0:
        patience_counter = 0

    if verbose > 0: # Print only if verbose
        print(f"Training {epochs} epochs...")

    # Main training loop: iterate through epochs
    for epoch in range(1, epochs + 1):

        # Forward pass, compute gradients, update weights
        train_loss, train_f1 = train_one_epoch(
            model, train_loader, criterion, optimizer, scaler, device, l1_lambda, l2_lambda
        )
        
        # --- CODICE AGGIUNTO QUI: APPLICA IL VINCOLO SUI PESI ---
        if weight_max_norm is not None and weight_max_norm > 0:
            apply_weight_constraint(model, weight_max_norm)
        # --------------------------------------------------------

        # Evaluate model on validation data
        val_loss, val_f1 = validate_one_epoch(
            model, val_loader, criterion, device
        )

        # Store metrics
        training_history['train_loss'].append(train_loss)
        training_history['val_loss'].append(val_loss)
        training_history['train_f1'].append(train_f1)
        training_history['val_f1'].append(val_f1)

        # Write to TensorBoard
        if writer is not None:
            log_metrics_to_tensorboard(
                writer, epoch, train_loss, train_f1, val_loss, val_f1, model
            )

        # Print progress
        if verbose > 0:
            if epoch % verbose == 0 or epoch == 1:
                print(f"Epoch {epoch:3d}/{epochs} | "
                      f"Train: Loss={train_loss:.4f}, F1 Score={train_f1:.4f} | "
                      f"Val: Loss={val_loss:.4f}, F1 Score={val_f1:.4f}")

        # Get current metric for Pruning & Early Stopping
        current_metric = training_history[evaluation_metric][-1]

        # Scheduler Step
        if scheduler is not None:
            scheduler.step(current_metric)
        
        # Optuna Pruning
        if trial is not None:
            try:
                trial.report(current_metric, epoch)
            except Exception as e:
                # Gestione dell'errore (solo se Optuna è effettivamente usato)
                print(f"Error during Optuna report: {e}") 
                pass

            if trial.should_prune():
                # Pruning requested
                raise optuna.exceptions.TrialPruned()
        # End Pruning

        # Early stopping logic (omesso per brevità, resta invariato)
        if patience > 0:
            is_improvement = (current_metric > best_metric) if mode == 'max' else (current_metric < best_metric)

            if is_improvement:
                best_metric = current_metric
                best_epoch = epoch
                # Non uso la variabile `experiment_name` qui, assumo che sia definita in un contesto più ampio
                torch.save(model.state_dict(), "models/"+experiment_name+'_model.pt')
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= patience:
                    if verbose > 0:
                        print(f"Early stopping triggered after {epoch} epochs.")
                    break

    # Restore best model weights (omesso per brevità, resta invariato)
    if restore_best_weights and patience > 0 and best_epoch > 0:
        model.load_state_dict(torch.load("models/"+experiment_name+'_model.pt'))
        if verbose > 0:
            print(f"Best model restored from epoch {best_epoch} with {evaluation_metric} {best_metric:.4f}")

    # Save final model if no early stopping (omesso per brevità, resta invariato)
    if patience == 0:
        torch.save(model.state_dict(), "models/"+experiment_name+'_model.pt')
        if mode == 'max':
            best_metric = max(training_history[evaluation_metric])
        else:
            best_metric = min(training_history[evaluation_metric])
            
    if patience > 0 and best_epoch == 0:
         if mode == 'max':
             best_metric = max(training_history[evaluation_metric])
         else:
             best_metric = min(training_history[evaluation_metric])


    # Close TensorBoard writer
    if writer is not None:
        writer.close()

    return model, training_history, best_metric

In [ ]:
# # Create model and display architecture with parameter count
# rnn_model = RecurrentClassifier(
#     input_size=input_shape[-1], # Pass the number of features
#     hidden_size=HIDDEN_SIZE,
#     num_layers=HIDDEN_LAYERS,
#     num_classes=num_classes,
#     dropout_rate=DROPOUT_RATE,
#     bidirectional=BIDIRECTIONAL,
#     rnn_type=RNN_TYPE
#     ).to(device)
# recurrent_summary(rnn_model, input_size=input_shape)

# # Set up TensorBoard logging and save model architecture
# experiment_name = f"{RNN_TYPE}_{BIDIRECTIONAL}"
# writer = SummaryWriter("./"+logs_dir+"/"+experiment_name)
# x = torch.randn(1, input_shape[0], input_shape[1]).to(device)
# writer.add_graph(rnn_model, x)

# # Define optimizer with L2 regularization
# optimizer = torch.optim.AdamW(rnn_model.parameters(), lr=LEARNING_RATE, weight_decay=L2_LAMBDA)

# # Enable mixed precision training for GPU acceleration
# scaler = torch.amp.GradScaler(enabled=(device.type == 'cuda'))

In [ ]:
# %%time
# # Train model and track training history
# rnn_model, training_history = fit(
#     model=rnn_model,
#     train_loader=train_loader,
#     val_loader=val_loader,
#     epochs=EPOCHS,
#     criterion=criterion,
#     optimizer=optimizer,
#     scaler=scaler,
#     device=device,
#     writer=writer,
#     verbose=1,
#     experiment_name=f"{RNN_TYPE}_{BIDIRECTIONAL}",
#     patience=20
#     )

# # Update best model if current performance is superior
# if training_history['val_f1'][-1] > best_performance:
#     best_model = rnn_model
#     best_performance = training_history['val_f1'][-1]

In [102]:
# --- 4. Load the Best Model from the Study ---
print("\n--- Loading Best Model from Optuna Study ---")

best_params = study.best_params

# Re-create the best model architecture
best_model = RecurrentClassifier(
    input_size=input_shape[-1],
    hidden_size=best_params["hidden_size"],
    num_layers=best_params["num_layers"],
    num_classes=num_classes,
    dropout_rate=best_params["dropout_rate"],
    bidirectional=best_params["bidirectional"],
    rnn_type=best_params["rnn_type"]
).to(device)

# Load the saved state dict from the best trial
try:
    best_model_path = f"models/optuna_trial_{study.best_trial.number}_model.pt"
    best_model.load_state_dict(torch.load(best_model_path))
    print(f"Successfully loaded best model from {best_model_path}")
    
    # Now you can run the "Plot Confusion Matrix" cell (Cell 34)
    # to evaluate this best_model.

except FileNotFoundError:
    print(f"ERROR: Could not find model file {best_model_path}.")
    print("This might happen if the best trial was pruned before saving a model.")
    print("You may need to re-run the study or check the 'models/' directory.")

--- Loading Best Model from Optuna Study ---
Successfully loaded best model from models/optuna_trial_27_model.pt

## Plot History

In [ ]:
# @title Plot Hitory
# Create a figure with two side-by-side subplots (two columns)
fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(18, 5))

# Plot of training and validation loss on the first axis
ax1.plot(training_history['train_loss'], label='Training loss', alpha=0.3, color='#ff7f0e', linestyle='--')
ax1.plot(training_history['val_loss'], label='Validation loss', alpha=0.9, color='#ff7f0e')
ax1.set_title('Loss')
ax1.legend()
ax1.grid(alpha=0.3)

# Plot of training and validation accuracy on the second axis
ax2.plot(training_history['train_f1'], label='Training f1', alpha=0.3, color='#ff7f0e', linestyle='--')
ax2.plot(training_history['val_f1'], label='Validation f1', alpha=0.9, color='#ff7f0e')
ax2.set_title('F1 Score')
ax2.legend()
ax2.grid(alpha=0.3)

# Adjust the layout and display the plot
plt.tight_layout()
plt.subplots_adjust(right=0.85)
plt.show()

## Plot Confusion Matrix

In [ ]:
# @title Plot Confusion Matrix
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, classification_report
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Collect predictions and ground truth labels
val_preds, val_targets = [], []
with torch.no_grad():  # Disable gradient computation for inference
    for xb, yb in val_loader:
        xb = xb.to(device)

        # Forward pass: get model predictions
        logits = rnn_model(xb)
        preds = logits.argmax(dim=1).cpu().numpy()

        # Store batch results
        val_preds.append(preds)
        val_targets.append(yb.numpy())

# Combine all batches into single arrays
val_preds = np.concatenate(val_preds)
val_targets = np.concatenate(val_targets)

# --- Overall Validation Metrics (Weighted) ---
print("--- Overall Validation Metrics (Weighted) ---")
val_acc = accuracy_score(val_targets, val_preds)
val_prec = precision_score(val_targets, val_preds, average='weighted')
val_rec = recall_score(val_targets, val_preds, average='weighted')
val_f1 = f1_score(val_targets, val_preds, average='weighted')
print(f"Accuracy over the validation set: {val_acc:.4f}")
print(f"Precision over the validation set: {val_prec:.4f}")
print(f"Recall over the validation set: {val_rec:.4f}")
print(f"F1 score over the validation set: {val_f1:.4f}")

# --- Metrics Per Class ---
# (Labels based on cell [6] label_map = {'no_pain': 0, 'low_pain': 1, 'high_pain': 2})
target_names = ['no_pain', 'low_pain', 'high_pain']
print("\n--- Metrics Per Class ---")
report = classification_report(val_targets, val_preds, target_names=target_names)
print(report)


# --- Confusion Matrix ---
# Generate confusion matrix for detailed error analysis
cm = confusion_matrix(val_targets, val_preds)

# Create numeric labels for heatmap annotation
labels = np.array([f"{num}" for num in cm.flatten()]).reshape(cm.shape)

# Visualise confusion matrix
plt.figure(figsize=(8, 7))
sns.heatmap(cm, annot=labels, fmt='',
            cmap='Blues',
            xticklabels=target_names,  # Use class names for x-axis
            yticklabels=target_names   # Use class names for y-axis
           )
plt.xlabel('Predicted labels')
plt.ylabel('True labels')
plt.title('Confusion Matrix — Validation Set')
plt.tight_layout()
plt.show()

## Hyperparameter tuning

In [106]:
import torch
import numpy as np
import pandas as pd
from torch.utils.data import TensorDataset
from datetime import datetime
import os # For checking if the models directory exists

# --- Setup Assumed Parameters (If not already defined) ---
# NOTE: Replace these with the actual values from your notebook if they are missing
# These values are derived from typical notebook context for this type of problem.
# WINDOW = 40
# STRIDE = 10
# BATCH_SIZE = 64
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# num_classes = 3
# inverse_label_map = {0: 'no_pain', 1: 'low_pain', 2: 'high_pain'}

# Set the window/step parameters for test data
SEQ_LENGTH = WINDOW # Should be 40
STEP = STRIDE       # Should be 10

# --- 1. Load the Best Model from the Study ---
print("\n--- Loading Best Model from Optuna Study ---")

try:
    best_params = study.best_params

    # Re-create the best model architecture
    best_model = RecurrentClassifier(
        input_size=input_shape[-1],
        hidden_size=best_params["hidden_size"],
        num_layers=best_params["num_layers"],
        num_classes=num_classes,
        dropout_rate=best_params["dropout_rate"],
        bidirectional=best_params["bidirectional"],
        rnn_type=best_params["rnn_type"]
    ).to(device)

    # Load the saved state dict from the best trial
    best_model_path = f"models/optuna_trial_7_model.pt"
    best_model.load_state_dict(torch.load(best_model_path, map_location=device))
    print(f"Successfully loaded best model from {best_model_path}")

except FileNotFoundError:
    print(f"ERROR: Could not find model file {best_model_path}.")
    print("Please check the 'models/' directory and ensure the training completed successfully.")
    # Exit or raise error if model cannot be loaded
    # raise
except NameError as e:
    print(f"Error: A required variable or class is missing: {e}")
    # Exit or raise error if variables are missing
    # raise
except Exception as e:
    print(f"An unexpected error occurred during model loading: {e}")
    # raise

# --- 2. Define Test Sliding Window Function ---
def create_test_sliding_windows(X_df_full, feature_cols, seq_length, step):
    """
    Creates overlapping sequences (sliding windows) from flat test data, 
    grouped by 'sample_index'.
    """
    X_sequences = []
    sample_index_map = [] # To track which user each window belongs to
    
    grouped = X_df_full.groupby('sample_index')
    
    print(f"Creating test sliding windows (Length={seq_length}, Step={step})...")
    
    for sample_id, user_data in grouped:
        user_features = user_data[feature_cols].values.astype(np.float32)
        total_steps = len(user_features)
        
        for i in range(0, total_steps - seq_length + 1, step):
            window = user_features[i : i + seq_length]
            X_sequences.append(window)
            sample_index_map.append(sample_id)
            
    print(f"Created {len(X_sequences)} total test sequences.")
    return np.array(X_sequences, dtype=np.float32), sample_index_map

# --- 3. Prepare Test Data and DataLoader ---
print("--- Preparing Test Data Loader ---")

X_test_flat = df_public_test.copy()
print(f"Using {len(feature_cols)} features for test data (should be 32).")

# Reshape Test Data into Sequences
X_test_seq, test_index_map = create_test_sliding_windows(
    X_test_flat, 
    feature_cols, 
    SEQ_LENGTH, 
    STEP
)
print(f"Reshaped X_test_seq shape: {X_test_seq.shape}")

# Convert to Tensor & Create Dataset (Test dataset has no labels)
X_test_tensor = torch.from_numpy(X_test_seq)
test_ds = TensorDataset(X_test_tensor)
print(f"\nCreated test TensorDataset with {len(test_ds)} windows.")

# Create Test DataLoader
test_loader = make_loader(
    test_ds, 
    batch_size=BATCH_SIZE, 
    shuffle=False,  # No need to shuffle for prediction
    drop_last=False # Must process all test samples
)
print(f"Created test_loader. Batches: {len(test_loader)}")

# --- 4. Generate Predictions ---
print("\n--- Generating Predictions for all windows ---")
best_model.eval()   # Set model to evaluation mode
all_logits = []

with torch.no_grad():
    for (inputs,) in test_loader: # Unpack tuple (test_ds only has inputs)
        inputs = inputs.to(device)
        
        # Use mixed precision for inference if available
        # This line is good practice but assumes `torch.amp.autocast` is available
        with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
            logits = best_model(inputs)
            
        all_logits.append(logits.cpu().numpy())

final_logits_all_windows = np.concatenate(all_logits)
print(f"Generated logits for {len(final_logits_all_windows)} windows.")


# --- 5. Create Submission File (Aggregating Predictions) ---
print("\n--- Aggregating window predictions by averaging logits ---")

# Create a DataFrame to manage aggregation
pred_df = pd.DataFrame({
    'sample_index': test_index_map
})

# Add logit columns
for c in range(num_classes):
    pred_df[f'logit_{c}'] = final_logits_all_windows[:, c]

# Group by user and average the logits
logit_cols = [f'logit_{c}' for c in range(num_classes)]
submission_logits_avg = pred_df.groupby('sample_index')[logit_cols].mean()

# Get the final class by taking argmax of the *averaged* logits
final_numeric_predictions = submission_logits_avg.idxmax(axis=1).str.replace('logit_', '').astype(int)
final_numeric_predictions = final_numeric_predictions.reset_index(name='prediction')

# Map numeric predictions (0, 1, 2) back to string labels
final_labels = final_numeric_predictions['prediction'].map(inverse_label_map)

# Create final submission DataFrame
submission_df = pd.DataFrame({
    'sample_index': final_numeric_predictions['sample_index'],
    'label': final_labels
})

# Save to CSV
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
submission_filename = f'submission_{timestamp}.csv'
submission_df.to_csv(submission_filename, index=False)
print(f"\n✅ Successfully saved final submission file: **{submission_filename}** with {len(submission_df)} rows.")
print("\nFirst 5 rows of the submission file:")
print(submission_df.head())

--- Loading Best Model from Optuna Study ---
An unexpected error occurred during model loading: Error(s) in loading state_dict for RecurrentClassifier:
	size mismatch for rnn.weight_ih_l0: copying a param with shape torch.Size([192, 32]) from checkpoint, the shape in current model is torch.Size([384, 32]).
	size mismatch for rnn.weight_hh_l0: copying a param with shape torch.Size([192, 64]) from checkpoint, the shape in current model is torch.Size([384, 128]).
	size mismatch for rnn.bias_ih_l0: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.bias_hh_l0: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([192, 32]) from checkpoint, the shape in current model is torch.Size([384, 32]).
	size mismatch for rnn.weight_hh_l0_reverse: copying a param with shape torch.Size([192, 64]) from checkpoint, the shape in current model is torch.Size([384, 128]).
	size mismatch for rnn.bias_ih_l0_reverse: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.bias_hh_l0_reverse: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.weight_ih_l1: copying a param with shape torch.Size([192, 128]) from checkpoint, the shape in current model is torch.Size([384, 256]).
	size mismatch for rnn.weight_hh_l1: copying a param with shape torch.Size([192, 64]) from checkpoint, the shape in current model is torch.Size([384, 128]).
	size mismatch for rnn.bias_ih_l1: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.bias_hh_l1: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.weight_ih_l1_reverse: copying a param with shape torch.Size([192, 128]) from checkpoint, the shape in current model is torch.Size([384, 256]).
	size mismatch for rnn.weight_hh_l1_reverse: copying a param with shape torch.Size([192, 64]) from checkpoint, the shape in current model is torch.Size([384, 128]).
	size mismatch for rnn.bias_ih_l1_reverse: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.bias_hh_l1_reverse: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.weight_ih_l2: copying a param with shape torch.Size([192, 128]) from checkpoint, the shape in current model is torch.Size([384, 256]).
	size mismatch for rnn.weight_hh_l2: copying a param with shape torch.Size([192, 64]) from checkpoint, the shape in current model is torch.Size([384, 128]).
	size mismatch for rnn.bias_ih_l2: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.bias_hh_l2: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.weight_ih_l2_reverse: copying a param with shape torch.Size([192, 128]) from checkpoint, the shape in current model is torch.Size([384, 256]).
	size mismatch for rnn.weight_hh_l2_reverse: copying a param with shape torch.Size([192, 64]) from checkpoint, the shape in current model is torch.Size([384, 128]).
	size mismatch for rnn.bias_ih_l2_reverse: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for rnn.bias_hh_l2_reverse: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for classifier.weight: copying a param with shape torch.Size([3, 128]) from checkpoint, the shape in current model is torch.Size([3, 256]).
--- Preparing Test Data Loader ---
Using 32 features for test data (should be 32).
Creating test sliding windows (Length=40, Step=10)...
Created 17212 total test sequences.
Reshaped X_test_seq shape: (17212, 40, 32)

Created test TensorDataset with 17212 windows.
Created test_loader. Batches: 269

--- Generating Predictions for all windows ---
Generated logits for 17212 windows.

--- Aggregating window predictions by averaging logits ---

✅ Successfully saved final submission file: **submission_20251111_185455.csv** with 1324 rows.

First 5 rows of the submission file:
   sample_index      label
0             0   low_pain
1             1   low_pain
2             2  high_pain
3             3  high_pain
4             4  high_pain

## Predict Public tests

In [104]:
# --- 1. Check for necessary variables ---
# This code assumes 'best_model', 'df_public_test', 'feature_cols', 
# 'WINDOW', 'STRIDE', 'BATCH_SIZE', 'device', 'num_classes', and 'make_loader'
# already exist in your notebook's memory from the previous cells.

# *** NEW: Window parameters must match training (from cell [13]) ***
SEQ_LENGTH = WINDOW # Should be 40
STEP = STRIDE     # Should be 10

if 'best_model' not in locals():
    print("Error: 'best_model' not found.")
    print("Please make sure you have run the training cell and 'best_model' is in memory.")
else:
    print("--- Preparing Test Data Loader ---")

    # --- 2. Use the loaded and processed test data ---
    # We use df_public_test, which was loaded in [5] and processed in [7] & [8]
    X_test_flat = df_public_test.copy()

    # --- 3. Handle NaNs in test data ---
    # (This is already done by the preProcess and scaling cells [7] and [8])

    # --- 4. Select the same feature columns ---
    # (feature_cols was defined in cell [12])
    print(f"Using {len(feature_cols)} features for test data (should be 32).")

    # --- 5. Reshape Test Data into Sequences ---
    
    # *** NEW: Sliding Window Function for Test Set ***
    # This function matches the logic used in 'build_sequences' (cell [14])
    # for generating sliding windows (13 windows per 160 steps).
    def create_test_sliding_windows(X_df_full, feature_cols, seq_length, step):
        """
        Creates overlapping sequences (sliding windows) from flat test data, 
        grouped by 'sample_index'.
        
        Returns:
            - np.array: The 3D sequence data (num_windows, seq_length, num_features)
            - list: A list of 'sample_index' for each window, to map predictions back.
        """
        X_sequences = []
        sample_index_map = [] # To track which user each window belongs to
        
        # Group by user
        grouped = X_df_full.groupby('sample_index')
        
        print(f"Creating test sliding windows (Length={seq_length}, Step={step})...")
        
        for sample_id, user_data in grouped:
            # Ensure data is float32, matching training data (cell [10])
            user_features = user_data[feature_cols].values.astype(np.float32)
            
            # Total time steps for this user (should be 160)
            total_steps = len(user_features)
            
            # Iterate and create windows
            # (Starts: 0, 10, ... 120. 13 windows total)
            for i in range(0, total_steps - seq_length + 1, step):
                window = user_features[i : i + seq_length]
                X_sequences.append(window)
                sample_index_map.append(sample_id) # Store the user ID for this window
                
        print(f"Created {len(X_sequences)} total test sequences.")
        # Ensure final array is float32
        return np.array(X_sequences, dtype=np.float32), sample_index_map

    # We pass the full X_test_flat dataframe (which has 'sample_index')
    X_test_seq, test_index_map = create_test_sliding_windows(
        X_test_flat, 
        feature_cols, 
        SEQ_LENGTH, 
        STEP
    )
    print(f"Reshaped X_test_seq shape: {X_test_seq.shape}")

    # --- 6. Convert to Tensor & Create Dataset ---
    # Use torch.from_numpy, same as in cell [17] for training
    X_test_tensor = torch.from_numpy(X_test_seq)
    test_ds = TensorDataset(X_test_tensor) # Test dataset has no labels
    print(f"\nCreated test TensorDataset with {len(test_ds)} windows.")

    # --- 7. Create Test DataLoader ---
    # make_loader (cell [11] or [19]) is available.
    test_loader = make_loader(
        test_ds, 
        batch_size=BATCH_SIZE, 
        shuffle=False,  # No need to shuffle for prediction
        drop_last=False   # Must process all test samples
    )
    print(f"Created test_loader. Batches: {len(test_loader)}")

    # --- 8. Generate Predictions ---
    print("\n--- Generating Predictions for all windows ---")
    best_model.eval()  # Set model to evaluation mode
    all_logits = []

    with torch.no_grad():
        for (inputs,) in test_loader: # Unpack tuple (test_ds only has inputs)
            inputs = inputs.to(device)
            
            # Use mixed precision for inference if available
            with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
                logits = best_model(inputs)
                
            all_logits.append(logits.cpu().numpy())

    final_logits_all_windows = np.concatenate(all_logits)
    print(f"Generated logits for {len(final_logits_all_windows)} windows.")

    # --- 9. Create Submission File (Aggregating Predictions) ---
    print("\n--- Aggregating window predictions by averaging logits ---")
    
    # Create a DataFrame to manage aggregation
    pred_df = pd.DataFrame({
        'sample_index': test_index_map
    })
    
    # Add logit columns
    for c in range(num_classes): # num_classes should be 3 (from cell [16])
        pred_df[f'logit_{c}'] = final_logits_all_windows[:, c]

    # Group by user and average the logits
    logit_cols = [f'logit_{c}' for c in range(num_classes)]
    submission_logits_avg = pred_df.groupby('sample_index')[logit_cols].mean()
    
    # Get the final class by taking argmax of the *averaged* logits
    final_numeric_predictions = submission_logits_avg.idxmax(axis=1).str.replace('logit_', '').astype(int)
    final_numeric_predictions = final_numeric_predictions.reset_index(name='prediction')
    
    # Map numeric predictions (0, 1, 2) back to string labels
    # (This map is defined in cell [6] of the notebook)
    inverse_label_map = {0: 'no_pain', 1: 'low_pain', 2: 'high_pain'}
    final_labels = final_numeric_predictions['prediction'].map(inverse_label_map)
    
    # Create submission DataFrame
    submission_df = pd.DataFrame({
        'sample_index': final_numeric_predictions['sample_index'],
        'label': final_labels
    })

    from datetime import datetime
    # Save to CSV (Kaggle environment standard name)
    submission_df.to_csv(f'try{datetime.now()}submission.csv', index=False)
    print(f"\nSuccessfully saved 'submission.csv' with {len(submission_df)} rows.")
    print(submission_df.head())

--- Preparing Test Data Loader ---
Using 32 features for test data (should be 32).
Creating test sliding windows (Length=40, Step=10)...
Created 17212 total test sequences.
Reshaped X_test_seq shape: (17212, 40, 32)

Created test TensorDataset with 17212 windows.
Created test_loader. Batches: 269

--- Generating Predictions for all windows ---
Generated logits for 17212 windows.

--- Aggregating window predictions by averaging logits ---

Successfully saved 'submission.csv' with 1324 rows.
   sample_index    label
0             0  no_pain
1             1  no_pain
2             2  no_pain
3             3  no_pain
4             4  no_pain