In [1]:
# Set seed for reproducibility
SEED = 16

# Import necessary libraries
import os

# Set environment variables before importing modules
os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['MPLCONFIGDIR'] = os.getcwd() + '/configs/'

# Suppress warnings
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=Warning)

# Import necessary modules
import logging
import random
import numpy as np

# Set seeds for random number generators in NumPy and Python
np.random.seed(SEED)
random.seed(SEED)

# Import PyTorch
import torch
torch.manual_seed(SEED)
from torch import nn
# from torchsummary import summary
from torch.utils.tensorboard import SummaryWriter
from torch.utils.data import TensorDataset, DataLoader
logs_dir = "tensorboard"
!pkill -f tensorboard
%load_ext tensorboard
!mkdir -p models

if torch.cuda.is_available():
    device = torch.device("cuda")
    torch.cuda.manual_seed_all(SEED)
    torch.backends.cudnn.benchmark = True
else:
    device = torch.device("cpu")

print(f"PyTorch version: {torch.__version__}")
print(f"Device: {device}")

# Import other libraries
import copy
import shutil
from itertools import product
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import optuna


# Configure plot display settings
sns.set(font_scale=1.4)
sns.set_style('white')
plt.rc('font', size=14)
%matplotlib inline

2025-11-12 10:16:56.046994: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1762942616.238011      48 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1762942616.291898      48 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

PyTorch version: 2.6.0+cu124
Device: cuda

In [2]:
# Uninstall any existing conflicting versions
!pip uninstall tensorboard -y
!pip uninstall tensorflow -y
!pip uninstall tensorflow-estimator -y

Found existing installation: tensorboard 2.18.0
Uninstalling tensorboard-2.18.0:
  Successfully uninstalled tensorboard-2.18.0
Found existing installation: tensorflow 2.18.0
Uninstalling tensorflow-2.18.0:
  Successfully uninstalled tensorflow-2.18.0
WARNING: Skipping tensorflow-estimator as it is not installed.

In [3]:
# Reinstall a recent, known good version of tensorboard and the necessary TensorFlow packages
!pip install tensorboard tensorflow

Collecting tensorboard
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow
  Downloading tensorflow-2.20.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (1.74.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (3.8.2)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorboard) (25.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from tensorboard) (11.3.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (6.33.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (75.2.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard) (3.1.3)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.5)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Collecting keras>=3.10.0 (from tensorflow)
  Downloading keras-3.12.0-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.14.0)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.10.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.10.0->tensorflow) (0.16.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (2025.3.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (2022.3.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.12.0->tensorboard) (2.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Requirement already satisfied: onemkl-license==2025.3.0 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.12.0->tensorboard) (2025.3.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.12.0->tensorboard) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.12.0->tensorboard) (2022.3.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.12.0->tensorboard) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.12.0->tensorboard) (2024.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.19.2)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.12.0->tensorboard) (2024.2.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)
Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 54.3 MB/s eta 0:00:00a 0:00:01
Downloading tensorflow-2.20.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (620.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 620.6/620.6 MB 2.4 MB/s eta 0:00:00:00:0100:01
Downloading keras-3.12.0-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 56.5 MB/s eta 0:00:00
Downloading ml_dtypes-0.5.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 90.4 MB/s eta 0:00:00:00:01
Installing collected packages: ml_dtypes, tensorboard, keras, tensorflow
  Attempting uninstall: ml_dtypes
    Found existing installation: ml-dtypes 0.4.1
    Uninstalling ml-dtypes-0.4.1:
      Successfully uninstalled ml-dtypes-0.4.1
  Attempting uninstall: keras
    Found existing installation: keras 3.8.0
    Uninstalling keras-3.8.0:
      Successfully uninstalled keras-3.8.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.1.2 requires gymnasium>=1.0.0, but you have gymnasium 0.29.0 which is incompatible.
tf-keras 2.18.0 requires tensorflow<2.19,>=2.18, but you have tensorflow 2.20.0 which is incompatible.
tensorflow-decision-forests 1.11.0 requires tensorflow==2.18.0, but you have tensorflow 2.20.0 which is incompatible.
tensorflow-text 2.18.1 requires tensorflow<2.19,>=2.18.0, but you have tensorflow 2.20.0 which is incompatible.
Successfully installed keras-3.12.0 ml_dtypes-0.5.3 tensorboard-2.20.0 tensorflow-2.20.0

In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/the-pirate-pain-dataset/sample_submission.csv
/kaggle/input/the-pirate-pain-dataset/pirate_pain_test.csv
/kaggle/input/the-pirate-pain-dataset/pirate_pain_train_labels.csv
/kaggle/input/the-pirate-pain-dataset/pirate_pain_train.csv

## ⏳ **Data Loading**

## 🔎 **Exploration and Data Analysis**

In [5]:
# Load the dataset from a CSV file
df_train = pd.read_csv("/kaggle/input/the-pirate-pain-dataset/pirate_pain_train.csv")
df_public_test = pd.read_csv("/kaggle/input/the-pirate-pain-dataset/pirate_pain_test.csv")
df_labels = pd.read_csv("/kaggle/input/the-pirate-pain-dataset/pirate_pain_train_labels.csv")

# Print the shape of the DataFrame
# print(f"DataFrame sh/kaggle/input/the-pirate-pain-dataset/sample_submission.csv

## 🔄 **Data Preprocessing**

In [6]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_labels['label_encoded'] = label_encoder.fit_transform(df_labels['label'])
# This gives: ['high_pain', 'low_pain', 'no_pain']
label_map = {'no_pain': 0, 'low_pain': 1, 'high_pain': 2}
df_labels['label_encoded'] = df_labels['label'].map(label_map)

In [7]:
from sklearn.preprocessing import MinMaxScaler
# Convert static cols
def preProcess(df):
    # Changed from .min(axis=1) to .median(axis=1)
    df["pain_survey"] = np.floor(df[["pain_survey_1", "pain_survey_2", "pain_survey_3", "pain_survey_4"]].median(axis=1)).astype(int) 
    df.drop(columns=['pain_survey_1', 'pain_survey_2', 'pain_survey_3', 'pain_survey_4'], inplace=True)
    
    df['merged_n_features'] = np.where(
        (df['n_legs'] == 'two') & (df['n_hands'] == 'two') & (df['n_eyes'] == 'two'),
        0, 
        1  
    )
    
    # Calculate the count of rows where n_legs, n_hands, or n_eyes are not 'two'
    explicit_different_count = df[
        (df['n_legs'] != 'two') | (df['n_hands'] != 'two') | (df['n_eyes'] != 'two')
    ].shape[0]
    
    df.drop(columns=['n_legs', 'n_hands', 'n_eyes', "joint_30"], inplace=True)
    
    columns_to_scale = [col for col in df.columns if col not in ['time', 'sample_index']]

    scaler = MinMaxScaler()
    df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

preProcess(df_train)
preProcess(df_public_test)

df_train.head()

,sample_index,time,joint_00,joint_01,joint_02,joint_03,joint_04,joint_05,joint_06,joint_07,...,joint_22,joint_23,joint_24,joint_25,joint_26,joint_27,joint_28,joint_29,pain_survey,merged_n_features
0,0,0,0.777507,0.738252,0.779512,0.804419,0.714916,0.736643,0.639301,0.733981,...,1.374706e-06,0.000015,3.162813e-04,0.000004,0.014214,0.011376,0.018978,0.020291,0.5,0.0
1,0,1,0.806256,0.765147,0.761153,0.838021,0.735684,0.729533,0.654605,0.760554,...,4.026521e-07,0.000022,9.828599e-07,0.000000,0.010748,0.000000,0.009473,0.010006,1.0,0.0
2,0,2,0.767592,0.721439,0.772834,0.777832,0.724497,0.734962,0.692340,0.787647,...,1.440847e-08,0.000005,6.626013e-05,0.000003,0.013097,0.006830,0.017065,0.016856,1.0,0.0
3,0,3,0.666220,0.810416,0.763971,0.785928,0.679928,0.722504,0.589127,0.793524,...,3.065580e-07,0.000007,1.199337e-06,0.000000,0.009505,0.006274,0.020264,0.017981,1.0,0.0
4,0,4,0.774297,0.773366,0.772162,0.767017,0.747710,0.743156,0.677764,0.725437,...,1.723863e-08,0.000006,1.307199e-06,0.000007,0.004216,0.002132,0.023389,0.018477,1.0,0.0

In [8]:
from sklearn.preprocessing import MinMaxScaler
# Scaling
scale_cols = [f'joint_{i:02d}' for i in range(30)] + ['pain_survey', 'merged_n_features']

scaler = MinMaxScaler()

# FIT the scaler ONLY on the training data
df_train[scale_cols] = scaler.fit_transform(df_train[scale_cols])

# TRANSFORM the test data with the same scaler
df_public_test[scale_cols] = scaler.transform(df_public_test[scale_cols])

In [9]:
from sklearn.model_selection import train_test_split
# STRATIFICATION
user_labels = df_labels.copy()

train_users, val_users = train_test_split(
    user_labels['sample_index'],
    test_size=0.2,  # 20% validation
    stratify=user_labels['label'], # This is the key for imbalance
    random_state=SEED
)

df_train_full = df_train.copy()

# Filter the full dataframe to get rows for train/val users
df_train_fold = df_train_full[df_train_full['sample_index'].isin(train_users)]
df_val_fold   = df_train_full[df_train_full['sample_index'].isin(val_users)]

# Merge labels back in
df_train_fold = df_train_fold.merge(user_labels[['sample_index', 'label', 'label_encoded']], on='sample_index', how='left')
df_val_fold   = df_val_fold.merge(user_labels[['sample_index', 'label', 'label_encoded']], on='sample_index', how='left')

# Check class distribution
print("--- Training Set Class Distribution ---")
print(df_train_fold['label'].value_counts(normalize=True))
print("\n--- Validation Set Class Distribution ---")
print(df_val_fold['label'].value_counts(normalize=True))

df_train_fold = df_train_fold.drop(columns=['label'])
df_val_fold = df_val_fold.drop(columns=['label'])
print(df_train_fold.head())

# X_train_final = df_train_fold.drop(columns=['label', 'label_encoded'])
# y_train_final = df_train_fold[['sample_index', 'label_encoded']]

# X_val_final = df_val_fold.drop(columns=['label', 'label_encoded'])
# y_val_final = df_val_fold[['sample_index', 'label_encoded']]

--- Training Set Class Distribution ---
label
no_pain      0.772727
low_pain     0.142045
high_pain    0.085227
Name: proportion, dtype: float64

--- Validation Set Class Distribution ---
label
no_pain      0.774436
low_pain     0.142857
high_pain    0.082707
Name: proportion, dtype: float64
   sample_index  time  joint_00  joint_01  joint_02  joint_03  joint_04  \
0             0     0  0.777507  0.738252  0.779512  0.804419  0.714916
1             0     1  0.806256  0.765147  0.761153  0.838021  0.735684
2             0     2  0.767592  0.721439  0.772834  0.777832  0.724497
3             0     3  0.666220  0.810416  0.763971  0.785928  0.679928
4             0     4  0.774297  0.773366  0.772162  0.767017  0.747710

   joint_05  joint_06  joint_07  ...  joint_23      joint_24  joint_25  \
0  0.736643  0.639301  0.733981  ...  0.000015  3.162813e-04  0.000004
1  0.729533  0.654605  0.760554  ...  0.000022  9.828599e-07  0.000000
2  0.734962  0.692340  0.787647  ...  0.000005  6.626013e-05  0.000003
3  0.722504  0.589127  0.793524  ...  0.000007  1.199337e-06  0.000000
4  0.743156  0.677764  0.725437  ...  0.000006  1.307199e-06  0.000007

   joint_26  joint_27  joint_28  joint_29  pain_survey  merged_n_features  \
0  0.014214  0.011376  0.018978  0.020291          0.5                0.0
1  0.010748  0.000000  0.009473  0.010006          1.0                0.0
2  0.013097  0.006830  0.017065  0.016856          1.0                0.0
3  0.009505  0.006274  0.020264  0.017981          1.0                0.0
4  0.004216  0.002132  0.023389  0.018477          1.0                0.0

   label_encoded
0              0
1              0
2              0
3              0
4              0

[5 rows x 35 columns]

In [10]:
# Convert all feature columns (X) to float32
# This includes the scaled dynamic cols and the static/numeric pirate features
df_train_fold = df_train_fold.astype('float32')
df_val_fold   = df_val_fold.astype('float32')

# Convert the target label column (y) to int64
# PyTorch's CrossEntropyLoss expects class labels as LongTensors (int64)
df_train_fold['label_encoded']  = df_train_fold['label_encoded'].astype('int64')
df_val_fold['label_encoded']   = df_val_fold['label_encoded'].astype('int64')


# --- Verify the changes ---
print("--- df_train_fold (Features) dtypes ---")
# .info() will show all columns are now float32
print(df_train_fold.info())

--- df_train_fold (Features) dtypes ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84480 entries, 0 to 84479
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sample_index       84480 non-null  float32
 1   time               84480 non-null  float32
 2   joint_00           84480 non-null  float32
 3   joint_01           84480 non-null  float32
 4   joint_02           84480 non-null  float32
 5   joint_03           84480 non-null  float32
 6   joint_04           84480 non-null  float32
 7   joint_05           84480 non-null  float32
 8   joint_06           84480 non-null  float32
 9   joint_07           84480 non-null  float32
 10  joint_08           84480 non-null  float32
 11  joint_09           84480 non-null  float32
 12  joint_10           84480 non-null  float32
 13  joint_11           84480 non-null  float32
 14  joint_12           84480 non-null  float32
 15  joint_13           84480 non-null  float32
 16  joint_14           84480 non-null  float32
 17  joint_15           84480 non-null  float32
 18  joint_16           84480 non-null  float32
 19  joint_17           84480 non-null  float32
 20  joint_18           84480 non-null  float32
 21  joint_19           84480 non-null  float32
 22  joint_20           84480 non-null  float32
 23  joint_21           84480 non-null  float32
 24  joint_22           84480 non-null  float32
 25  joint_23           84480 non-null  float32
 26  joint_24           84480 non-null  float32
 27  joint_25           84480 non-null  float32
 28  joint_26           84480 non-null  float32
 29  joint_27           84480 non-null  float32
 30  joint_28           84480 non-null  float32
 31  joint_29           84480 non-null  float32
 32  pain_survey        84480 non-null  float32
 33  merged_n_features  84480 non-null  float32
 34  label_encoded      84480 non-null  int64
dtypes: float32(34), int64(1)
memory usage: 11.6 MB
None

In [11]:
df_train_fold.head(-10)

,sample_index,time,joint_00,joint_01,joint_02,joint_03,joint_04,joint_05,joint_06,joint_07,...,joint_23,joint_24,joint_25,joint_26,joint_27,joint_28,joint_29,pain_survey,merged_n_features,label_encoded
0,0.0,0.0,0.777507,0.738252,0.779512,0.804419,0.714916,0.736643,0.639301,0.733981,...,1.458410e-05,3.162813e-04,0.000004,0.014214,0.011376,0.018978,0.020291,0.5,0.0,0
1,0.0,1.0,0.806256,0.765147,0.761153,0.838021,0.735684,0.729533,0.654604,0.760554,...,2.195013e-05,9.828599e-07,0.000000,0.010748,0.000000,0.009473,0.010006,1.0,0.0,0
2,0.0,2.0,0.767592,0.721439,0.772834,0.777832,0.724497,0.734962,0.692340,0.787647,...,5.272918e-06,6.626013e-05,0.000003,0.013097,0.006830,0.017065,0.016856,1.0,0.0,0
3,0.0,3.0,0.666220,0.810416,0.763971,0.785928,0.679928,0.722504,0.589127,0.793524,...,6.737126e-06,1.199337e-06,0.000000,0.009505,0.006274,0.020264,0.017981,1.0,0.0,0
4,0.0,4.0,0.774297,0.773366,0.772162,0.767017,0.747710,0.743156,0.677764,0.725437,...,5.661887e-06,1.307199e-06,0.000007,0.004216,0.002132,0.023389,0.018477,1.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84465,660.0,145.0,0.747113,0.633353,0.556208,0.526835,0.058241,0.129760,0.648898,0.600525,...,3.068689e-06,6.187494e-06,0.000002,0.057496,0.008263,0.121502,0.054748,1.0,0.0,0
84466,660.0,146.0,0.766650,0.730096,0.596908,0.583812,0.098994,0.119217,0.706742,0.624951,...,1.851797e-06,6.117617e-06,0.000001,0.042580,0.019101,0.195717,0.102979,1.0,0.0,0
84467,660.0,147.0,0.746536,0.704494,0.650648,0.585991,0.064944,0.182338,0.678559,0.596394,...,5.101990e-06,6.046634e-06,0.000001,0.036764,0.012704,0.125387,0.075700,1.0,0.0,0
84468,660.0,148.0,0.719192,0.599540,0.572594,0.605968,0.097262,0.170702,0.676817,0.604818,...,1.269752e-07,5.974558e-06,0.000008,0.015018,0.008760,0.137120,0.082437,1.0,0.0,0
84469,660.0,149.0,0.680471,0.659945,0.589452,0.596914,0.108154,0.159792,0.659558,0.559143,...,1.104031e-07,1.136757e-05,0.000001,0.012745,0.011485,0.067033,0.106066,0.5,0.0,0

## Prepare data for training

In [12]:
def make_loader(ds, batch_size, shuffle, drop_last):
    # Determine optimal number of worker processes for data loading
    cpu_cores = os.cpu_count() or 2
    num_workers = max(2, min(4, cpu_cores))

    # Create DataLoader with performance optimizations
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
        pin_memory=True,  # Faster GPU transfer
        pin_memory_device="cuda" if torch.cuda.is_available() else "",
        prefetch_factor=4,  # Load 4 batches ahead
    )

In [13]:
feature_cols = [col for col in df_train.columns if col not in ["sample_index", "time"]]

In [14]:
WINDOW = 40
STRIDE = 10

BATCH_SIZE = 64
num_features = len(feature_cols)

In [15]:
import numpy as np

def build_sequences(df, feature_cols, id_col='sample_index', label_col='label_encoded', window=200, stride=200):
    """
    Builds sequences from a time-series dataframe.
    
    Args:
        df (pd.DataFrame): The input DataFrame (e.g., df_train_fold) containing
                           features, IDs, and labels.
        feature_cols (list): A list of column names to be used as features.
        id_col (str): The name of the column for unique sample IDs.
        label_col (str): The name of the column for the labels.
        window (int): The size of each sequence (window).
        stride (int): The step size between sequences.
    """
    # Sanity check
    # assert window % stride == 0
    
    num_features = len(feature_cols)
    dataset = []
    labels = []

    # Iterate over unique sample IDs
    for sample_id in df[id_col].unique():
        
        # Get the dataframe for the current sample
        temp_df = df[df[id_col] == sample_id]

        # Extract feature data for the current ID
        temp_features = temp_df[feature_cols].values

        # Retrieve the single label for the current ID
        # (Assumes all rows for one ID have the same label)
        label = temp_df[label_col].values[0]

        # Calculate padding length to ensure full windows
        # This logic correctly handles cases where length is already a multiple
        padding_len = (window - len(temp_features) % window) % window
        
        if padding_len > 0:
            # Create zero padding and concatenate with the data
            padding = np.zeros((padding_len, num_features), dtype='float32')
            temp_features = np.concatenate((temp_features, padding))

        # Build feature windows and associate them with labels
        idx = 0
        while idx + window <= len(temp_features):
            dataset.append(temp_features[idx:idx + window])
            labels.append(label)
            idx += stride

    # Convert lists to numpy arrays for further processing
    dataset = np.array(dataset)
    labels = np.array(labels)

    return dataset, labels

In [16]:
# Generate sequences and labels for the training set
X_train, y_train = build_sequences(
    df_train_fold, 
    feature_cols=feature_cols, 
    id_col='sample_index',
    label_col='label_encoded',
    window=WINDOW, 
    stride=STRIDE
)

# Generate sequences and labels for the validation set
X_val, y_val = build_sequences(
    df_val_fold, 
    feature_cols=feature_cols,
    id_col='sample_index',
    label_col='label_encoded',
    window=WINDOW, 
    stride=STRIDE
)

# Print the shapes of the generated datasets and their labels
X_train.shape, y_train.shape, X_val.shape, y_val.shape

((6864, 40, 32), (6864,), (1729, 40, 32), (1729,))

In [17]:
# Define the input shape based on the training data
input_shape = X_train.shape[1:]

num_classes = 3

In [18]:
# Convert numpy arrays to PyTorch datasets (pairs features with labels)
train_ds = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
val_ds   = TensorDataset(torch.from_numpy(X_val), torch.from_numpy(y_val))

In [19]:
def make_loader(ds, batch_size, shuffle, drop_last):
    # Determine optimal number of worker processes for data loading
    cpu_cores = os.cpu_count() or 2
    num_workers = max(2, min(4, cpu_cores))

    # Create DataLoader with performance optimizations
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
        pin_memory=True,  # Faster GPU transfer
        pin_memory_device="cuda" if torch.cuda.is_available() else "",
        prefetch_factor=4,  # Load 4 batches ahead
    )

In [20]:
# Create data loaders with different settings for each phase
train_loader = make_loader(train_ds, batch_size=BATCH_SIZE, shuffle=True, drop_last=False)
val_loader   = make_loader(val_ds, batch_size=BATCH_SIZE, shuffle=False, drop_last=False)

In [21]:
import math
import torch
from torch.optim import Optimizer

class Ranger(Optimizer):
    def __init__(self, params, lr=1e-3, alpha=0.5, k=6, betas=(0.95, 0.999), eps=1e-5, weight_decay=0):
        """
        Ranger = RAdam + Lookahead
        Args:
            params: model parameters
            lr: learning rate
            alpha: lookahead step size (0.5 is default)
            k: lookahead steps before sync (6 is default)
            betas: RAdam betas
            eps: numerical stability
            weight_decay: L2 regularization
        """
        defaults = dict(lr=lr, alpha=alpha, k=k, betas=betas, eps=eps, weight_decay=weight_decay)
        super(Ranger, self).__init__(params, defaults)
        self._step = 0

        for group in self.param_groups:
            group["slow_params"] = [p.clone().detach() for p in group["params"] if p.requires_grad]

    def step(self, closure=None):
        loss = None
        if closure is not None:
            loss = closure()

        for group in self.param_groups:
            for p, sp in zip(group["params"], group["slow_params"]):
                if p.grad is None:
                    continue

                grad = p.grad.data
                if grad.is_sparse:
                    raise RuntimeError("Ranger does not support sparse gradients")

                state = self.state[p]

                # State initialization
                if len(state) == 0:
                    state["step"] = 0
                    state["exp_avg"] = torch.zeros_like(p.data)
                    state["exp_avg_sq"] = torch.zeros_like(p.data)

                exp_avg, exp_avg_sq = state["exp_avg"], state["exp_avg_sq"]
                beta1, beta2 = group["betas"]

                state["step"] += 1
                self._step += 1

                # Apply weight decay
                if group["weight_decay"] != 0:
                    grad = grad.add(p.data, alpha=group["weight_decay"])

                # Update exponential moving averages
                exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
                exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1 - beta2)

                # Compute rectified term (RAdam)
                bias_correction1 = 1 - beta1 ** state["step"]
                bias_correction2 = 1 - beta2 ** state["step"]
                n_sma_max = 2 / (1 - beta2) - 1
                n_sma = n_sma_max - 2 * state["step"] * (beta2 ** state["step"]) / bias_correction2

                if n_sma >= 5:
                    step_size = group["lr"] * math.sqrt(
                        ((1 - beta2 ** state["step"]) * (n_sma - 4) / (n_sma_max - 4)) *
                        ((n_sma - 2) / n_sma) * (n_sma_max / (n_sma_max - 2))
                    ) / bias_correction1
                    denom = exp_avg_sq.sqrt().add_(group["eps"])
                    p.data.addcdiv_(exp_avg, denom, value=-step_size)
                else:
                    step_size = group["lr"] / bias_correction1
                    p.data.add_(exp_avg, alpha=-step_size)

                # Lookahead updates
                if self._step % group["k"] == 0:
                    sp.add_(p.data - sp, alpha=group["alpha"])
                    p.data.copy_(sp)

        return loss

## 🛠️ **Model Building**

In [22]:
def recurrent_summary(model, input_size):
    """
    Custom summary function that emulates torchinfo's output while correctly
    counting parameters for RNN/GRU/LSTM layers.

    This function is designed for models whose direct children are
    nn.Linear, nn.RNN, nn.GRU, or nn.LSTM layers.

    Args:
        model (nn.Module): The model to analyze.
        input_size (tuple): Shape of the input tensor (e.g., (seq_len, features)).
    """

    # Dictionary to store output shapes captured by forward hooks
    output_shapes = {}
    # List to track hook handles for later removal
    hooks = []

    def get_hook(name):
        """Factory function to create a forward hook for a specific module."""
        def hook(module, input, output):
            # Handle RNN layer outputs (returns a tuple)
            if isinstance(output, tuple):
                # output[0]: all hidden states with shape (batch, seq_len, hidden*directions)
                shape1 = list(output[0].shape)
                shape1[0] = -1  # Replace batch dimension with -1

                # output[1]: final hidden state h_n (or tuple (h_n, c_n) for LSTM)
                if isinstance(output[1], tuple):  # LSTM case: (h_n, c_n)
                    shape2 = list(output[1][0].shape)  # Extract h_n only
                else:  # RNN/GRU case: h_n only
                    shape2 = list(output[1].shape)

                # Replace batch dimension (middle position) with -1
                shape2[1] = -1

                output_shapes[name] = f"[{shape1}, {shape2}]"

            # Handle standard layer outputs (e.g., Linear)
            else:
                shape = list(output.shape)
                shape[0] = -1  # Replace batch dimension with -1
                output_shapes[name] = f"{shape}"
        return hook

    # 1. Determine the device where model parameters reside
    try:
        device = next(model.parameters()).device
    except StopIteration:
        device = torch.device("cpu")  # Fallback for models without parameters

    # 2. Create a dummy input tensor with batch_size=1
    dummy_input = torch.randn(1, *input_size).to(device)

    # 3. Register forward hooks on target layers
    # Iterate through direct children of the model (e.g., self.rnn, self.classifier)
    for name, module in model.named_children():
        if isinstance(module, (nn.Linear, nn.RNN, nn.GRU, nn.LSTM)):
            # Register the hook and store its handle for cleanup
            hook_handle = module.register_forward_hook(get_hook(name))
            hooks.append(hook_handle)

    # 4. Execute a dummy forward pass in evaluation mode
    model.eval()
    with torch.no_grad():
        try:
            model(dummy_input)
        except Exception as e:
            print(f"Error during dummy forward pass: {e}")
            # Clean up hooks even if an error occurs
            for h in hooks:
                h.remove()
            return

    # 5. Remove all registered hooks
    for h in hooks:
        h.remove()

    # --- 6. Print the summary table ---

    print("-" * 79)
    # Column headers
    print(f"{'Layer (type)':<25} {'Output Shape':<28} {'Param #':<18}")
    print("=" * 79)

    total_params = 0
    total_trainable_params = 0

    # Iterate through modules again to collect and display parameter information
    for name, module in model.named_children():
        if name in output_shapes:
            # Count total and trainable parameters for this module
            module_params = sum(p.numel() for p in module.parameters())
            trainable_params = sum(p.numel() for p in module.parameters() if p.requires_grad)

            total_params += module_params
            total_trainable_params += trainable_params

            # Format strings for display
            layer_name = f"{name} ({type(module).__name__})"
            output_shape_str = str(output_shapes[name])
            params_str = f"{trainable_params:,}"

            print(f"{layer_name:<25} {output_shape_str:<28} {params_str:<15}")

    print("=" * 79)
    print(f"Total params: {total_params:,}")
    print(f"Trainable params: {total_trainable_params:,}")
    print(f"Non-trainable params: {total_params - total_trainable_params:,}")
    print("-" * 79)

In [23]:
class RecurrentClassifier(nn.Module):
    """
    Generic RNN classifier (RNN, LSTM, GRU).
    Uses the last hidden state for classification.
    """
    def __init__(
            self,
            input_size,
            hidden_size,
            num_layers,
            num_classes,
            rnn_type='GRU',        # 'RNN', 'LSTM', or 'GRU'
            bidirectional=False,
            dropout_rate=0.2
            ):
        super().__init__()

        self.rnn_type = rnn_type
        self.num_layers = num_layers
        self.hidden_size = hidden_size
        self.bidirectional = bidirectional

        # Map string name to PyTorch RNN class
        rnn_map = {
            'RNN': nn.RNN,
            'LSTM': nn.LSTM,
            'GRU': nn.GRU
        }

        if rnn_type not in rnn_map:
            raise ValueError("rnn_type must be 'RNN', 'LSTM', or 'GRU'")

        rnn_module = rnn_map[rnn_type]

        # Dropout is only applied between layers (if num_layers > 1)
        dropout_val = dropout_rate if num_layers > 1 else 0

        # Create the recurrent layer
        self.rnn = rnn_module(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,       # Input shape: (batch, seq_len, features)
            bidirectional=bidirectional,
            dropout=dropout_val
        )

        # Calculate input size for the final classifier
        if self.bidirectional:
            classifier_input_size = hidden_size * 2 # Concat fwd + bwd
        else:
            classifier_input_size = hidden_size

        # Final classification layer
        self.classifier = nn.Linear(classifier_input_size, num_classes)

    def forward(self, x):
        """
        x shape: (batch_size, seq_length, input_size)
        """

        # rnn_out shape: (batch_size, seq_len, hidden_size * num_directions)
        rnn_out, hidden = self.rnn(x)

        # LSTM returns (h_n, c_n), we only need h_n
        if self.rnn_type == 'LSTM':
            hidden = hidden[0]

        # hidden shape: (num_layers * num_directions, batch_size, hidden_size)

        if self.bidirectional:
            # Reshape to (num_layers, 2, batch_size, hidden_size)
            hidden = hidden.view(self.num_layers, 2, -1, self.hidden_size)

            # Concat last fwd (hidden[-1, 0, ...]) and bwd (hidden[-1, 1, ...])
            # Final shape: (batch_size, hidden_size * 2)
            hidden_to_classify = torch.cat([hidden[-1, 0, :, :], hidden[-1, 1, :, :]], dim=1)
        else:
            # Take the last layer's hidden state
            # Final shape: (batch_size, hidden_size)
            hidden_to_classify = hidden[-1]

        # Get logits
        logits = self.classifier(hidden_to_classify)
        return logits

In [24]:
def initialize_weights(model, init_scheme='xavier_uniform'):
    """Initializes weights using the specified scheme."""
    for name, param in model.named_parameters():
        if 'weight_ih' in name or 'weight_hh' in name:
            # Recurrent weights
            if init_scheme == 'xavier_uniform':
                torch.nn.init.xavier_uniform_(param.data)
            elif init_scheme == 'orthogonal':
                # Often preferred for RNNs to maintain gradient scale
                torch.nn.init.orthogonal_(param.data)
        elif 'weight' in name:
            # Linear or Convolutional weights (e.g., in the final layer)
            if init_scheme == 'xavier_uniform':
                torch.nn.init.xavier_uniform_(param.data)
            elif init_scheme == 'kaiming_normal':
                 # Good for ReLU/Leaky ReLU (common in surrounding layers)
                torch.nn.init.kaiming_normal_(param.data, mode='fan_in', nonlinearity='relu')
        elif 'bias' in name:
            # Set biases to zero, which is common
            torch.nn.init.constant_(param.data, 0)
            
            # Optional: initialize forget gate bias to a positive value (e.g., 1.0 or 2.0)
            if 'bias_hh' in name and 'LSTM' in name: 
                 n = param.shape[0]
                 start, end = n // 4, n // 2
                 param.data[start:end].fill_(1.0) # For LSTM forget gate bias

In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class FocalLoss(nn.Module):
    """
    Focal Loss for multi-class classification.
    Reference: https://arxiv.org/abs/1708.02002 (Lin et al. 2017)

    Args:
        alpha (float or list): Weighting factor for classes (balances class imbalance)
        gamma (float): Focusing parameter to reduce the loss for well-classified examples
        reduction (str): 'none' | 'mean' | 'sum'
    """
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        super(FocalLoss, self).__init__()
        if isinstance(alpha, (float, int)):
            self.alpha = torch.tensor([alpha])
        else:
            self.alpha = torch.tensor(alpha) if alpha is not None else None
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        """
        Args:
            inputs: Predictions (logits), shape [batch_size, num_classes]
            targets: Ground truth labels, shape [batch_size]
        """
        # Compute log-probabilities
        log_probs = F.log_softmax(inputs, dim=1)
        probs = torch.exp(log_probs)

        # Select log-probability of the correct class
        log_probs_true = log_probs.gather(1, targets.unsqueeze(1)).squeeze(1)
        probs_true = probs.gather(1, targets.unsqueeze(1)).squeeze(1)

        # Compute focal weight
        focal_weight = (1 - probs_true) ** self.gamma

        # Apply alpha (class weight)
        if self.alpha is not None:
            if self.alpha.device != inputs.device:
                self.alpha = self.alpha.to(inputs.device)
            alpha_factor = self.alpha[targets]
            focal_weight = alpha_factor * focal_weight

        # Compute final loss
        loss = -focal_weight * log_probs_true

        if self.reduction == 'mean':
            return loss.mean()
        elif self.reduction == 'sum':
            return loss.sum()
        else:
            return loss

## 🧮 **Network and Training Hyperparameters**

In [26]:
from sklearn.utils.class_weight import compute_class_weight

# --- Calculate Class Weights ---
labels = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=labels,
    y=y_train
)

weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)

print(f"Original label counts: {np.bincount(y_train)}")
print(f"Calculated weights: {weights_tensor}")

Original label counts: [5304  975  585]
Calculated weights: tensor([0.4314, 2.3467, 3.9111], device='cuda:0')

## 🧠 **Model Training**

In [38]:
# Initialize best model tracking variables
best_model = None
best_performance = float('-inf')

In [39]:
def train_one_epoch(model, train_loader, criterion, optimizer, scaler, device, l1_lambda=0, l2_lambda=0):
    """
    Perform one complete training epoch through the entire training dataset.

    Args:
        model (nn.Module): The neural network model to train
        train_loader (DataLoader): PyTorch DataLoader containing training data batches
        criterion (nn.Module): Loss function (e.g., CrossEntropyLoss, MSELoss)
        optimizer (torch.optim): Optimization algorithm (e.g., Adam, SGD)
        scaler (GradScaler): PyTorch's gradient scaler for mixed precision training
        device (torch.device): Computing device ('cuda' for GPU, 'cpu' for CPU)
        l1_lambda (float): Lambda for L1 regularization
        l2_lambda (float): Lambda for L2 regularization

    Returns:
        tuple: (average_loss, f1 score) - Training loss and f1 score for this epoch
    """
    model.train()  # Set model to training mode

    running_loss = 0.0
    all_predictions = []
    all_targets = []

    # Iterate through training batches
    for batch_idx, (inputs, targets) in enumerate(train_loader):
        # Move data to device (GPU/CPU)
        inputs, targets = inputs.to(device), targets.to(device)

        # Clear gradients from previous step
        optimizer.zero_grad(set_to_none=True)

        # Forward pass with mixed precision (if CUDA available)
        with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
            logits = model(inputs)
            loss = criterion(logits, targets)

            # Add L1 and L2 regularization
            l1_norm = sum(p.abs().sum() for p in model.parameters())
            l2_norm = sum(p.pow(2).sum() for p in model.parameters())
            loss = loss + l1_lambda * l1_norm + l2_lambda * l2_norm


        # Backward pass with gradient scaling
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        # Accumulate metrics
        running_loss += loss.item() * inputs.size(0)
        predictions = logits.argmax(dim=1)
        all_predictions.append(predictions.cpu().numpy())
        all_targets.append(targets.cpu().numpy())

    # Calculate epoch metrics
    epoch_loss = running_loss / len(train_loader.dataset)
    epoch_f1 = f1_score(
        np.concatenate(all_targets),
        np.concatenate(all_predictions),
        average='weighted'
    )

    return epoch_loss, epoch_f1

In [40]:
def validate_one_epoch(model, val_loader, criterion, device):
    """
    Perform one complete validation epoch through the entire validation dataset.

    Args:
        model (nn.Module): The neural network model to evaluate (must be in eval mode)
        val_loader (DataLoader): PyTorch DataLoader containing validation data batches
        criterion (nn.Module): Loss function used to calculate validation loss
        device (torch.device): Computing device ('cuda' for GPU, 'cpu' for CPU)

    Returns:
        tuple: (average_loss, accuracy) - Validation loss and accuracy for this epoch

    Note:
        This function automatically sets the model to evaluation mode and disables
        gradient computation for efficiency during validation.
    """
    model.eval()  # Set model to evaluation mode

    running_loss = 0.0
    all_predictions = []
    all_targets = []

    # Disable gradient computation for validation
    with torch.no_grad():
        for inputs, targets in val_loader:
            # Move data to device
            inputs, targets = inputs.to(device), targets.to(device)

            # Forward pass with mixed precision (if CUDA available)
            with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
                logits = model(inputs)
                loss = criterion(logits, targets)

            # Accumulate metrics
            running_loss += loss.item() * inputs.size(0)
            predictions = logits.argmax(dim=1)
            all_predictions.append(predictions.cpu().numpy())
            all_targets.append(targets.cpu().numpy())

    # Calculate epoch metrics
    epoch_loss = running_loss / len(val_loader.dataset)
    epoch_accuracy = f1_score(
        np.concatenate(all_targets),
        np.concatenate(all_predictions),
        average='weighted'
    )

    return epoch_loss, epoch_accuracy

In [41]:
def log_metrics_to_tensorboard(writer, epoch, train_loss, train_f1, val_loss, val_f1, model):
    """
    Log training metrics and model parameters to TensorBoard for visualization.

    Args:
        writer (SummaryWriter): TensorBoard SummaryWriter object for logging
        epoch (int): Current epoch number (used as x-axis in TensorBoard plots)
        train_loss (float): Training loss for this epoch
        train_f1 (float): Training f1 score for this epoch
        val_loss (float): Validation loss for this epoch
        val_f1 (float): Validation f1 score for this epoch
        model (nn.Module): The neural network model (for logging weights/gradients)

    Note:
        This function logs scalar metrics (loss/f1 score) and histograms of model
        parameters and gradients, which helps monitor training progress and detect
        issues like vanishing/exploding gradients.
    """
    # Log scalar metrics
    writer.add_scalar('Loss/Training', train_loss, epoch)
    writer.add_scalar('Loss/Validation', val_loss, epoch)
    writer.add_scalar('F1/Training', train_f1, epoch)
    writer.add_scalar('F1/Validation', val_f1, epoch)

    # Log model parameters and gradients
    for name, param in model.named_parameters():
        if param.requires_grad:
            # Check if the tensor is not empty before adding a histogram
            if param.numel() > 0:
                writer.add_histogram(f'{name}/weights', param.data, epoch)
            if param.grad is not None:
                # Check if the gradient tensor is not empty before adding a histogram
                if param.grad.numel() > 0:
                    if param.grad is not None and torch.isfinite(param.grad).all():
                        writer.add_histogram(f'{name}/gradients', param.grad.data, epoch)

In [42]:
import torch
import torch.nn as nn
import optuna
# Importa la funzione di utilità se necessario (anche se lo faremo manualmente) 7
# import torch.nn.utils as nn_utils 

def fit(model, train_loader, val_loader, epochs, criterion, optimizer, scaler, device,
        l1_lambda=0, l2_lambda=0, patience=0, evaluation_metric="val_f1", mode='max',
        restore_best_weights=True, writer=None, verbose=10, experiment_name="",
        trial=None, scheduler=None, weight_max_norm=None):
    """
    Train the neural network model on the training data and validate on the validation data.
    """

    # --- NUOVA FUNZIONE: Normalizzazione/Vincolo dei Pesi ---
    def apply_weight_constraint(model, max_norm):
        with torch.no_grad():
            for name, module in model.named_modules():
                # Applica solo ai layer con pesi (es. Linear, Conv1d, Conv2d)
                if isinstance(module, (nn.Linear, nn.Conv1d, nn.Conv2d)):
                    # Vincola il parametro 'weight'
                    if hasattr(module, 'weight') and module.weight is not None:
                        # Calcola la norma L2 del tensore dei pesi
                        norm = module.weight.norm(2)
                        
                        if norm > max_norm:
                            # Se la norma è maggiore del vincolo, riscala il peso.
                            # Ciò garantisce che la norma L2 sia esattamente 'max_norm' o inferiore.
                            module.weight.data.mul_(max_norm / norm)

    # Initialize metrics tracking
    training_history = {
        'train_loss': [], 'val_loss': [],
        'train_f1': [], 'val_f1': []
    }

    # Initialize best_metric before loop
    best_metric = float('-inf') if mode == 'max' else float('inf')
    best_epoch = 0
    
    if patience > 0:
        patience_counter = 0

    if verbose > 0: # Print only if verbose
        print(f"Training {epochs} epochs...")

    # Main training loop: iterate through epochs
    for epoch in range(1, epochs + 1):

        # Forward pass, compute gradients, update weights
        train_loss, train_f1 = train_one_epoch(
            model, train_loader, criterion, optimizer, scaler, device, l1_lambda, l2_lambda
        )
        
        # --- CODICE AGGIUNTO QUI: APPLICA IL VINCOLO SUI PESI ---
        if weight_max_norm is not None and weight_max_norm > 0:
            apply_weight_constraint(model, weight_max_norm)
        # --------------------------------------------------------

        # Evaluate model on validation data
        val_loss, val_f1 = validate_one_epoch(
            model, val_loader, criterion, device
        )

        # Store metrics
        training_history['train_loss'].append(train_loss)
        training_history['val_loss'].append(val_loss)
        training_history['train_f1'].append(train_f1)
        training_history['val_f1'].append(val_f1)

        # Write to TensorBoard
        if writer is not None:
            log_metrics_to_tensorboard(
                writer, epoch, train_loss, train_f1, val_loss, val_f1, model
            )

        # Print progress
        if verbose > 0:
            if epoch % verbose == 0 or epoch == 1:
                print(f"Epoch {epoch:3d}/{epochs} | "
                      f"Train: Loss={train_loss:.4f}, F1 Score={train_f1:.4f} | "
                      f"Val: Loss={val_loss:.4f}, F1 Score={val_f1:.4f}")

        # Get current metric for Pruning & Early Stopping
        current_metric = training_history[evaluation_metric][-1]

        # Scheduler Step
        if scheduler is not None:
            scheduler.step(current_metric)
        
        # Optuna Pruning
        if trial is not None:
            try:
                trial.report(current_metric, epoch)
            except Exception as e:
                # Gestione dell'errore (solo se Optuna è effettivamente usato)
                print(f"Error during Optuna report: {e}") 
                pass

            if trial.should_prune():
                # Pruning requested
                raise optuna.exceptions.TrialPruned()
        # End Pruning

        # Early stopping logic (omesso per brevità, resta invariato)
        if patience > 0:
            is_improvement = (current_metric > best_metric) if mode == 'max' else (current_metric < best_metric)

            if is_improvement:
                best_metric = current_metric
                best_epoch = epoch
                # Non uso la variabile `experiment_name` qui, assumo che sia definita in un contesto più ampio
                torch.save(model.state_dict(), "models/"+experiment_name+'_model.pt')
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= patience:
                    if verbose > 0:
                        print(f"Early stopping triggered after {epoch} epochs.")
                    break

    # Restore best model weights (omesso per brevità, resta invariato)
    if restore_best_weights and patience > 0 and best_epoch > 0:
        model.load_state_dict(torch.load("models/"+experiment_name+'_model.pt'))
        if verbose > 0:
            print(f"Best model restored from epoch {best_epoch} with {evaluation_metric} {best_metric:.4f}")

    # Save final model if no early stopping (omesso per brevità, resta invariato)
    if patience == 0:
        torch.save(model.state_dict(), "models/"+experiment_name+'_model.pt')
        if mode == 'max':
            best_metric = max(training_history[evaluation_metric])
        else:
            best_metric = min(training_history[evaluation_metric])
            
    if patience > 0 and best_epoch == 0:
         if mode == 'max':
             best_metric = max(training_history[evaluation_metric])
         else:
             best_metric = min(training_history[evaluation_metric])


    # Close TensorBoard writer
    if writer is not None:
        writer.close()

    return model, training_history, best_metric

In [47]:
# Assuming necessary imports (torch, optuna, FocalLoss, RecurrentClassifier, initialize_weights, 
# build_sequences, make_loader, TensorDataset, etc.) and global variables (BATCH_SIZE, 
# df_train_fold, df_val_fold, feature_cols, weights_tensor, input_shape, num_classes, device)
# are defined elsewhere in your Kaggle notebook.

# --- 1. Define Global Training Constants ---
BATCH_SIZE = 32
EPOCHS = 200
PATIENCE = 15 # Used as the maximum patience for Early Stopping, 
              # but now we will tune a separate patience for the LR scheduler.

# --- 2. Define the Optuna Objective Function ---
def objective(trial):
    
    # --- 1. Tune Window and Stride (Data Generation) ---
    # Expanded range for better exploration
    window_hp = trial.suggest_categorical("WINDOW", [20, 40])
    stride_hp = trial.suggest_categorical("STRIDE", [5, 10, 15, 20, 30])

    # Prune if stride is larger than the window
    if stride_hp >= window_hp:
        raise optuna.exceptions.TrialPruned()

    # --- 2. Build Dynamic Datasets and Loaders ---
    # Generate sequences for this trial
    X_train, y_train = build_sequences(
        df_train_fold, 
        feature_cols=feature_cols, 
        id_col='sample_index',
        label_col='label_encoded',
        window=window_hp, 
        stride=stride_hp
    )
    X_val, y_val = build_sequences(
        df_val_fold, 
        feature_cols=feature_cols,
        id_col='sample_index',
        label_col='label_encoded',
        window=window_hp, 
        stride=stride_hp
    )

    # Create TensorDatasets for this trial
    train_ds = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
    val_ds   = TensorDataset(torch.from_numpy(X_val), torch.from_numpy(y_val))

    # Create DataLoaders for this trial
    train_loader = make_loader(train_ds, batch_size=BATCH_SIZE, shuffle=True, drop_last=False)
    val_loader   = make_loader(val_ds, batch_size=BATCH_SIZE, shuffle=False, drop_last=False)
    
    # --- 3. Suggest Other Hyperparameters ---
    
    hidden_size_hp = trial.suggest_categorical("hidden_size", [32, 64, 128]) # Reduced range
    num_layers_hp = trial.suggest_int("num_layers", 1, 3)
    dropout_hp = trial.suggest_float("dropout_rate", 0.1, 0.7) # Increased max
    rnn_type_hp = trial.suggest_categorical("rnn_type", ["GRU"])
    bidirectional_hp = trial.suggest_categorical("bidirectional", [True, False])
    
    # Initialization (SYNTAX FIX: Removed the extra closing parenthesis)
    init_scheme_hp = trial.suggest_categorical(
        "init_scheme", 
        ["xavier_uniform", "orthogonal", "kaiming_normal"]
    )
    
    # Optimization Parameters (L2)
    lr_hp = trial.suggest_float("lr", 1e-5, 1e-3, log=True)
    weight_decay_hp = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
    
    # NEW L1 Regularization (For sparsity/simplification)
    l1_lambda_hp = trial.suggest_float("l1_lambda", 1e-7, 1e-4, log=True)
    
    # Focal Loss Parameters (gamma=0.0 now includes CrossEntropy)
    focal_gamma_hp = trial.suggest_float("focal_gamma", 0.0, 5.0, step=0.5)
    
    # Scheduler Parameters
    scheduler_patience_hp = trial.suggest_int("scheduler_patience", 3, 10, step=1)
    scheduler_factor_hp = trial.suggest_categorical("scheduler_factor", [0.1, 0.2, 0.5])
    
    # --- 4. Create Model, Criterion, Optimizer, and Scheduler ---
    
    # Criterion: Using FocalLoss
    criterion = nn.CrossEntropyLoss(weight=weights_tensor)
    
    # Model Definition
    model = RecurrentClassifier(
        input_size=input_shape[-1], 
        hidden_size=hidden_size_hp,
        num_layers=num_layers_hp,
        num_classes=num_classes,
        dropout_rate=dropout_hp,
        bidirectional=bidirectional_hp,
        rnn_type=rnn_type_hp
    ).to(device)

    # --- APPLY INITIALIZATION (NEW) ---
    initialize_weights(model, init_scheme=init_scheme_hp) 

    optimizer = torch.optim.AdamW(
        model.parameters(), 
        lr=lr_hp, 
        weight_decay=weight_decay_hp 
    )
    
    # Scheduler Definition (ReduceLROnPlateau)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, 
        mode='max',
        factor=scheduler_factor_hp, 
        patience=scheduler_patience_hp, 
        verbose=False,
        threshold=1e-4,
        min_lr=1e-7
    )

    scaler = torch.amp.GradScaler(enabled=(device.type == 'cuda'))
    weight_max_norm_hp = trial.suggest_float("weight_max_norm", low=0.1, high=6.0, log=False)
    # --- 5. Run Training ---
    try:
        _, _, best_val_f1 = fit(
            model=model,
            train_loader=train_loader, 
            val_loader=val_loader,     
            epochs=EPOCHS,
            criterion=criterion,
            optimizer=optimizer,
            scaler=scaler,
            device=device,
            l1_lambda=l1_lambda_hp, # <-- PASSED THE TUNED L1 PARAMETER
            l2_lambda=0,            # L2 still handled by optimizer
            patience=PATIENCE,
            evaluation_metric="val_f1",
            mode='max',
            restore_best_weights=True,
            writer=None,
            verbose=1,
            experiment_name=f"optuna_trial_{trial.number}",
            trial=trial,
            scheduler=scheduler,
            weight_max_norm = weight_max_norm_hp
        )
        
        return best_val_f1

    except optuna.exceptions.TrialPruned:
        return 0.0 
    except Exception as e:
        print(f"Trial {trial.number} failed with exception: {e}")
        return 0.0 

# --- 6. Create and Run the Optuna Study ---
print("--- Starting Optuna Hyperparameter Tuning ---")

study = optuna.create_study(
    direction="maximize", 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=5, n_startup_trials=3)
)

study.optimize(objective, n_trials=50) 

print("\n--- Tuning Complete ---")
print(f"Best trial number: {study.best_trial.number}")
print(f"Best validation F1-score: {study.best_value:.4f}")
print("Best hyperparameters found:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

[I 2025-11-12 11:05:39,133] A new study created in memory with name: no-name-91d0126b-ae56-4bdf-811c-d503135173c7

--- Starting Optuna Hyperparameter Tuning ---
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0470, F1 Score=0.6465 | Val: Loss=0.8552, F1 Score=0.7300
Epoch   2/200 | Train: Loss=0.9227, F1 Score=0.6675 | Val: Loss=0.8315, F1 Score=0.7312
Epoch   3/200 | Train: Loss=0.8256, F1 Score=0.6972 | Val: Loss=0.6980, F1 Score=0.7641
Epoch   4/200 | Train: Loss=0.6213, F1 Score=0.8147 | Val: Loss=0.5174, F1 Score=0.8409
Epoch   5/200 | Train: Loss=0.5480, F1 Score=0.8364 | Val: Loss=0.4800, F1 Score=0.8666
Epoch   6/200 | Train: Loss=0.4995, F1 Score=0.8420 | Val: Loss=0.4597, F1 Score=0.8796
Epoch   7/200 | Train: Loss=0.4800, F1 Score=0.8500 | Val: Loss=0.4757, F1 Score=0.8576
Epoch   8/200 | Train: Loss=0.4394, F1 Score=0.8635 | Val: Loss=0.5646, F1 Score=0.7894
Epoch   9/200 | Train: Loss=0.4319, F1 Score=0.8710 | Val: Loss=0.5032, F1 Score=0.8630
Epoch  10/200 | Train: Loss=0.3898, F1 Score=0.8759 | Val: Loss=0.4378, F1 Score=0.8513
Epoch  11/200 | Train: Loss=0.3616, F1 Score=0.8844 | Val: Loss=0.5457, F1 Score=0.8851
Epoch  12/200 | Train: Loss=0.3638, F1 Score=0.8767 | Val: Loss=0.5664, F1 Score=0.8554
Epoch  13/200 | Train: Loss=0.3332, F1 Score=0.8947 | Val: Loss=0.5754, F1 Score=0.8526
Epoch  14/200 | Train: Loss=0.3123, F1 Score=0.8977 | Val: Loss=0.4414, F1 Score=0.8749
Epoch  15/200 | Train: Loss=0.3142, F1 Score=0.9020 | Val: Loss=0.5181, F1 Score=0.8898
Epoch  16/200 | Train: Loss=0.2600, F1 Score=0.9094 | Val: Loss=0.3876, F1 Score=0.8573
Epoch  17/200 | Train: Loss=0.2611, F1 Score=0.9104 | Val: Loss=0.3653, F1 Score=0.8676
Epoch  18/200 | Train: Loss=0.2650, F1 Score=0.9138 | Val: Loss=0.4331, F1 Score=0.8881
Epoch  19/200 | Train: Loss=0.2242, F1 Score=0.9245 | Val: Loss=0.3705, F1 Score=0.8575
Epoch  20/200 | Train: Loss=0.2200, F1 Score=0.9194 | Val: Loss=0.3441, F1 Score=0.8756
Epoch  21/200 | Train: Loss=0.2059, F1 Score=0.9209 | Val: Loss=0.3685, F1 Score=0.9154
Epoch  22/200 | Train: Loss=0.2079, F1 Score=0.9154 | Val: Loss=0.3135, F1 Score=0.9030
Epoch  23/200 | Train: Loss=0.1752, F1 Score=0.9282 | Val: Loss=0.3884, F1 Score=0.8558
Epoch  24/200 | Train: Loss=0.2080, F1 Score=0.9209 | Val: Loss=0.3450, F1 Score=0.9124
Epoch  25/200 | Train: Loss=0.1845, F1 Score=0.9272 | Val: Loss=0.3528, F1 Score=0.9230
Epoch  26/200 | Train: Loss=0.1626, F1 Score=0.9316 | Val: Loss=0.4196, F1 Score=0.8843
Epoch  27/200 | Train: Loss=0.1727, F1 Score=0.9284 | Val: Loss=0.3646, F1 Score=0.8936
Epoch  28/200 | Train: Loss=0.1811, F1 Score=0.9303 | Val: Loss=0.6372, F1 Score=0.8450
Epoch  29/200 | Train: Loss=0.1647, F1 Score=0.9315 | Val: Loss=0.3702, F1 Score=0.8732
Epoch  30/200 | Train: Loss=0.1792, F1 Score=0.9310 | Val: Loss=0.4743, F1 Score=0.8145
Epoch  31/200 | Train: Loss=0.1591, F1 Score=0.9345 | Val: Loss=0.2979, F1 Score=0.8984
Epoch  32/200 | Train: Loss=0.1144, F1 Score=0.9502 | Val: Loss=0.3174, F1 Score=0.9077
Epoch  33/200 | Train: Loss=0.1091, F1 Score=0.9527 | Val: Loss=0.3246, F1 Score=0.9022
Epoch  34/200 | Train: Loss=0.1117, F1 Score=0.9523 | Val: Loss=0.3403, F1 Score=0.9006
Epoch  35/200 | Train: Loss=0.1071, F1 Score=0.9547 | Val: Loss=0.3453, F1 Score=0.8979
Epoch  36/200 | Train: Loss=0.1102, F1 Score=0.9528 | Val: Loss=0.3384, F1 Score=0.8923
Epoch  37/200 | Train: Loss=0.1055, F1 Score=0.9550 | Val: Loss=0.3326, F1 Score=0.9049
Epoch  38/200 | Train: Loss=0.1045, F1 Score=0.9553 | Val: Loss=0.3327, F1 Score=0.9005
Epoch  39/200 | Train: Loss=0.1056, F1 Score=0.9537 | Val: Loss=0.3333, F1 Score=0.8992

[I 2025-11-12 11:08:16,329] Trial 0 finished with value: 0.9229877069999509 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.6158936118881411, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00021303011928093207, 'weight_decay': 4.995983041119166e-06, 'l1_lambda': 6.641088077874692e-07, 'focal_gamma': 0.0, 'scheduler_patience': 5, 'scheduler_factor': 0.1, 'weight_max_norm': 1.0049640059663087}. Best is trial 0 with value: 0.9229877069999509.

Epoch  40/200 | Train: Loss=0.1047, F1 Score=0.9533 | Val: Loss=0.3334, F1 Score=0.9016
Early stopping triggered after 40 epochs.
Best model restored from epoch 25 with val_f1 0.9230
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1387, F1 Score=0.6079 | Val: Loss=0.9028, F1 Score=0.5629
Epoch   2/200 | Train: Loss=1.0124, F1 Score=0.6620 | Val: Loss=0.8044, F1 Score=0.7421
Epoch   3/200 | Train: Loss=0.9077, F1 Score=0.7013 | Val: Loss=0.6019, F1 Score=0.8268
Epoch   4/200 | Train: Loss=0.7874, F1 Score=0.7717 | Val: Loss=0.5875, F1 Score=0.8022
Epoch   5/200 | Train: Loss=0.6991, F1 Score=0.8062 | Val: Loss=0.5224, F1 Score=0.8340
Epoch   6/200 | Train: Loss=0.6463, F1 Score=0.8129 | Val: Loss=0.5543, F1 Score=0.8062
Epoch   7/200 | Train: Loss=0.5642, F1 Score=0.8553 | Val: Loss=0.4226, F1 Score=0.8907
Epoch   8/200 | Train: Loss=0.5205, F1 Score=0.8641 | Val: Loss=0.3765, F1 Score=0.8876
Epoch   9/200 | Train: Loss=0.4852, F1 Score=0.8725 | Val: Loss=0.3953, F1 Score=0.8444
Epoch  10/200 | Train: Loss=0.4292, F1 Score=0.8793 | Val: Loss=0.3577, F1 Score=0.8520
Epoch  11/200 | Train: Loss=0.3746, F1 Score=0.8987 | Val: Loss=0.2914, F1 Score=0.9150
Epoch  12/200 | Train: Loss=0.3470, F1 Score=0.9004 | Val: Loss=0.2634, F1 Score=0.9176
Epoch  13/200 | Train: Loss=0.3551, F1 Score=0.9033 | Val: Loss=0.2550, F1 Score=0.9112
Epoch  14/200 | Train: Loss=0.3142, F1 Score=0.9107 | Val: Loss=0.3062, F1 Score=0.8896
Epoch  15/200 | Train: Loss=0.3344, F1 Score=0.9121 | Val: Loss=0.3029, F1 Score=0.8681
Epoch  16/200 | Train: Loss=0.2950, F1 Score=0.9143 | Val: Loss=0.2551, F1 Score=0.9198
Epoch  17/200 | Train: Loss=0.2736, F1 Score=0.9201 | Val: Loss=0.2429, F1 Score=0.8908
Epoch  18/200 | Train: Loss=0.2413, F1 Score=0.9281 | Val: Loss=0.3400, F1 Score=0.8493
Epoch  19/200 | Train: Loss=0.3124, F1 Score=0.9129 | Val: Loss=0.2541, F1 Score=0.9063
Epoch  20/200 | Train: Loss=0.2707, F1 Score=0.9231 | Val: Loss=0.2147, F1 Score=0.9285
Epoch  21/200 | Train: Loss=0.2259, F1 Score=0.9397 | Val: Loss=0.2293, F1 Score=0.9073
Epoch  22/200 | Train: Loss=0.2335, F1 Score=0.9348 | Val: Loss=0.2332, F1 Score=0.9006
Epoch  23/200 | Train: Loss=0.2389, F1 Score=0.9400 | Val: Loss=0.2253, F1 Score=0.9384
Epoch  24/200 | Train: Loss=0.2249, F1 Score=0.9463 | Val: Loss=0.2974, F1 Score=0.9224
Epoch  25/200 | Train: Loss=0.2014, F1 Score=0.9473 | Val: Loss=0.2308, F1 Score=0.9296
Epoch  26/200 | Train: Loss=0.2172, F1 Score=0.9392 | Val: Loss=0.3354, F1 Score=0.9135
Epoch  27/200 | Train: Loss=0.2167, F1 Score=0.9433 | Val: Loss=0.2778, F1 Score=0.9110
Epoch  28/200 | Train: Loss=0.2777, F1 Score=0.9343 | Val: Loss=0.2492, F1 Score=0.9042
Epoch  29/200 | Train: Loss=0.1754, F1 Score=0.9597 | Val: Loss=0.2480, F1 Score=0.9095
Epoch  30/200 | Train: Loss=0.1434, F1 Score=0.9745 | Val: Loss=0.2338, F1 Score=0.9244
Epoch  31/200 | Train: Loss=0.1348, F1 Score=0.9747 | Val: Loss=0.2272, F1 Score=0.9352
Epoch  32/200 | Train: Loss=0.1317, F1 Score=0.9796 | Val: Loss=0.2233, F1 Score=0.9301
Epoch  33/200 | Train: Loss=0.1300, F1 Score=0.9788 | Val: Loss=0.2168, F1 Score=0.9340
Epoch  34/200 | Train: Loss=0.1291, F1 Score=0.9784 | Val: Loss=0.2426, F1 Score=0.9476
Epoch  35/200 | Train: Loss=0.1238, F1 Score=0.9830 | Val: Loss=0.2360, F1 Score=0.9353
Epoch  36/200 | Train: Loss=0.1210, F1 Score=0.9824 | Val: Loss=0.2376, F1 Score=0.9373
Epoch  37/200 | Train: Loss=0.1237, F1 Score=0.9822 | Val: Loss=0.2550, F1 Score=0.9342
Epoch  38/200 | Train: Loss=0.1200, F1 Score=0.9820 | Val: Loss=0.2446, F1 Score=0.9303
Epoch  39/200 | Train: Loss=0.1213, F1 Score=0.9815 | Val: Loss=0.2548, F1 Score=0.9444
Epoch  40/200 | Train: Loss=0.1226, F1 Score=0.9818 | Val: Loss=0.2429, F1 Score=0.9341
Epoch  41/200 | Train: Loss=0.1102, F1 Score=0.9878 | Val: Loss=0.2436, F1 Score=0.9371
Epoch  42/200 | Train: Loss=0.1085, F1 Score=0.9895 | Val: Loss=0.2468, F1 Score=0.9376
Epoch  43/200 | Train: Loss=0.1099, F1 Score=0.9876 | Val: Loss=0.2429, F1 Score=0.9372
Epoch  44/200 | Train: Loss=0.1083, F1 Score=0.9896 | Val: Loss=0.2487, F1 Score=0.9371
Epoch  45/200 | Train: Loss=0.1091, F1 Score=0.9886 | Val: Loss=0.2525, F1 Score=0.9370
Epoch  46/200 | Train: Loss=0.1070, F1 Score=0.9895 | Val: Loss=0.2540, F1 Score=0.9360
Epoch  47/200 | Train: Loss=0.1058, F1 Score=0.9895 | Val: Loss=0.2551, F1 Score=0.9354
Epoch  48/200 | Train: Loss=0.1055, F1 Score=0.9899 | Val: Loss=0.2537, F1 Score=0.9359

[I 2025-11-12 11:11:06,869] Trial 1 finished with value: 0.9475612112569565 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.4763346637068767, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.00033630369891680397, 'weight_decay': 0.0005419922806778623, 'l1_lambda': 5.476622340693204e-06, 'focal_gamma': 2.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 4.276606221618911}. Best is trial 1 with value: 0.9475612112569565.

Epoch  49/200 | Train: Loss=0.1043, F1 Score=0.9918 | Val: Loss=0.2548, F1 Score=0.9359
Early stopping triggered after 49 epochs.
Best model restored from epoch 34 with val_f1 0.9476
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0283, F1 Score=0.6614 | Val: Loss=0.9053, F1 Score=0.6696
Epoch   2/200 | Train: Loss=0.8357, F1 Score=0.7576 | Val: Loss=0.7012, F1 Score=0.8146
Epoch   3/200 | Train: Loss=0.6927, F1 Score=0.8172 | Val: Loss=0.6490, F1 Score=0.8136
Epoch   4/200 | Train: Loss=0.6124, F1 Score=0.8269 | Val: Loss=0.4903, F1 Score=0.8878
Epoch   5/200 | Train: Loss=0.5388, F1 Score=0.8424 | Val: Loss=0.5177, F1 Score=0.8327
Epoch   6/200 | Train: Loss=0.4936, F1 Score=0.8533 | Val: Loss=0.4379, F1 Score=0.8754
Epoch   7/200 | Train: Loss=0.4474, F1 Score=0.8631 | Val: Loss=0.4424, F1 Score=0.8772
Epoch   8/200 | Train: Loss=0.3977, F1 Score=0.8770 | Val: Loss=0.5073, F1 Score=0.8567
Epoch   9/200 | Train: Loss=0.3684, F1 Score=0.8849 | Val: Loss=0.4274, F1 Score=0.8693
Epoch  10/200 | Train: Loss=0.3584, F1 Score=0.8893 | Val: Loss=0.4325, F1 Score=0.8682
Epoch  11/200 | Train: Loss=0.3008, F1 Score=0.9137 | Val: Loss=0.3971, F1 Score=0.8740
Epoch  12/200 | Train: Loss=0.2888, F1 Score=0.9161 | Val: Loss=0.4324, F1 Score=0.8813
Epoch  13/200 | Train: Loss=0.2825, F1 Score=0.9129 | Val: Loss=0.4089, F1 Score=0.8735
Epoch  14/200 | Train: Loss=0.2747, F1 Score=0.9155 | Val: Loss=0.4328, F1 Score=0.8638
Epoch  15/200 | Train: Loss=0.2747, F1 Score=0.9157 | Val: Loss=0.4109, F1 Score=0.8792
Epoch  16/200 | Train: Loss=0.2739, F1 Score=0.9157 | Val: Loss=0.4129, F1 Score=0.8757
Epoch  17/200 | Train: Loss=0.2660, F1 Score=0.9160 | Val: Loss=0.4212, F1 Score=0.8809
Epoch  18/200 | Train: Loss=0.2651, F1 Score=0.9191 | Val: Loss=0.4245, F1 Score=0.8773

[I 2025-11-12 11:12:07,308] Trial 2 finished with value: 0.8878165483371201 and parameters: {'WINDOW': 40, 'STRIDE': 5, 'hidden_size': 32, 'num_layers': 1, 'dropout_rate': 0.4409249181226804, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0007381431720622401, 'weight_decay': 0.00010289290026979918, 'l1_lambda': 9.560730370182035e-07, 'focal_gamma': 0.5, 'scheduler_patience': 5, 'scheduler_factor': 0.1, 'weight_max_norm': 1.4068771058586769}. Best is trial 1 with value: 0.9475612112569565.

Epoch  19/200 | Train: Loss=0.2634, F1 Score=0.9184 | Val: Loss=0.4201, F1 Score=0.8780
Early stopping triggered after 19 epochs.
Best model restored from epoch 4 with val_f1 0.8878
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0968, F1 Score=0.6696 | Val: Loss=1.0529, F1 Score=0.7240
Epoch   2/200 | Train: Loss=1.0762, F1 Score=0.7230 | Val: Loss=0.9920, F1 Score=0.7388
Epoch   3/200 | Train: Loss=0.9842, F1 Score=0.6810 | Val: Loss=0.9161, F1 Score=0.6884
Epoch   4/200 | Train: Loss=0.9343, F1 Score=0.6985 | Val: Loss=0.8922, F1 Score=0.7155

[I 2025-11-12 11:12:17,134] Trial 3 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 32, 'num_layers': 1, 'dropout_rate': 0.1751629982165504, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0003535109201407447, 'weight_decay': 2.584846410470076e-05, 'l1_lambda': 4.237855093776577e-06, 'focal_gamma': 2.5, 'scheduler_patience': 7, 'scheduler_factor': 0.1, 'weight_max_norm': 3.0652005851048583}. Best is trial 1 with value: 0.9475612112569565.

Epoch   5/200 | Train: Loss=0.9111, F1 Score=0.7167 | Val: Loss=0.8728, F1 Score=0.7183
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1034, F1 Score=0.6093 | Val: Loss=1.0384, F1 Score=0.6019
Epoch   2/200 | Train: Loss=1.0327, F1 Score=0.6335 | Val: Loss=0.8902, F1 Score=0.7792
Epoch   3/200 | Train: Loss=0.9604, F1 Score=0.6763 | Val: Loss=1.0179, F1 Score=0.3640
Epoch   4/200 | Train: Loss=0.9015, F1 Score=0.6711 | Val: Loss=0.8634, F1 Score=0.6849

[I 2025-11-12 11:12:25,185] Trial 4 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.36769059959220596, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'xavier_uniform', 'lr': 0.00022798649564390107, 'weight_decay': 8.466498811489202e-05, 'l1_lambda': 8.184370809463286e-06, 'focal_gamma': 1.0, 'scheduler_patience': 7, 'scheduler_factor': 0.1, 'weight_max_norm': 3.253288019430987}. Best is trial 1 with value: 0.9475612112569565.

Epoch   5/200 | Train: Loss=0.8487, F1 Score=0.7029 | Val: Loss=0.9263, F1 Score=0.5684
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0959, F1 Score=0.5574 | Val: Loss=1.0517, F1 Score=0.5794
Epoch   2/200 | Train: Loss=1.0515, F1 Score=0.6230 | Val: Loss=0.8995, F1 Score=0.7878
Epoch   3/200 | Train: Loss=0.9818, F1 Score=0.6530 | Val: Loss=0.8731, F1 Score=0.6813
Epoch   4/200 | Train: Loss=0.9337, F1 Score=0.6594 | Val: Loss=0.8010, F1 Score=0.7503

[I 2025-11-12 11:12:39,553] Trial 5 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.6378043292338493, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'xavier_uniform', 'lr': 6.448942092203927e-05, 'weight_decay': 0.00037087516291894884, 'l1_lambda': 1.5537550689761112e-07, 'focal_gamma': 2.5, 'scheduler_patience': 3, 'scheduler_factor': 0.2, 'weight_max_norm': 2.3555679424648783}. Best is trial 1 with value: 0.9475612112569565.

Epoch   5/200 | Train: Loss=0.8909, F1 Score=0.6835 | Val: Loss=0.7489, F1 Score=0.7707
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0966, F1 Score=0.6537 | Val: Loss=1.0592, F1 Score=0.5105
Epoch   2/200 | Train: Loss=1.0572, F1 Score=0.6760 | Val: Loss=0.9903, F1 Score=0.6740
Epoch   3/200 | Train: Loss=0.9933, F1 Score=0.6830 | Val: Loss=0.8371, F1 Score=0.7752
Epoch   4/200 | Train: Loss=0.9417, F1 Score=0.6819 | Val: Loss=0.9314, F1 Score=0.6459

[I 2025-11-12 11:12:52,599] Trial 6 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.6605708094105001, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 7.557614091062882e-05, 'weight_decay': 1.2625501395774197e-06, 'l1_lambda': 3.280511330296802e-06, 'focal_gamma': 1.0, 'scheduler_patience': 4, 'scheduler_factor': 0.1, 'weight_max_norm': 5.000528611984666}. Best is trial 1 with value: 0.9475612112569565.

Epoch   5/200 | Train: Loss=0.9001, F1 Score=0.6873 | Val: Loss=0.8208, F1 Score=0.7162
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.2504, F1 Score=0.6598 | Val: Loss=1.0431, F1 Score=0.6935
Epoch   2/200 | Train: Loss=1.2366, F1 Score=0.6515 | Val: Loss=1.0419, F1 Score=0.6954
Epoch   3/200 | Train: Loss=1.2243, F1 Score=0.6694 | Val: Loss=1.0344, F1 Score=0.6928
Epoch   4/200 | Train: Loss=1.2131, F1 Score=0.6824 | Val: Loss=1.0227, F1 Score=0.7166

[I 2025-11-12 11:13:05,603] Trial 7 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.37479141653302905, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 1.4781203837773444e-05, 'weight_decay': 1.3159268738339464e-06, 'l1_lambda': 2.3610199049712e-05, 'focal_gamma': 2.0, 'scheduler_patience': 3, 'scheduler_factor': 0.1, 'weight_max_norm': 2.4428993286395015}. Best is trial 1 with value: 0.9475612112569565.

Epoch   5/200 | Train: Loss=1.2012, F1 Score=0.6908 | Val: Loss=1.0200, F1 Score=0.7040
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.2745, F1 Score=0.6514 | Val: Loss=1.0914, F1 Score=0.6026
Epoch   2/200 | Train: Loss=1.2440, F1 Score=0.6875 | Val: Loss=1.0610, F1 Score=0.7620
Epoch   3/200 | Train: Loss=1.1829, F1 Score=0.7298 | Val: Loss=0.9226, F1 Score=0.6843
Epoch   4/200 | Train: Loss=1.0682, F1 Score=0.7011 | Val: Loss=0.8259, F1 Score=0.7334
Epoch   5/200 | Train: Loss=1.0233, F1 Score=0.7012 | Val: Loss=0.8156, F1 Score=0.7473

[I 2025-11-12 11:13:32,524] Trial 8 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 5, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.42438250773887864, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'kaiming_normal', 'lr': 3.525507331486936e-05, 'weight_decay': 4.822079568365739e-05, 'l1_lambda': 1.7325693518661533e-05, 'focal_gamma': 5.0, 'scheduler_patience': 3, 'scheduler_factor': 0.5, 'weight_max_norm': 0.4491371658925656}. Best is trial 1 with value: 0.9475612112569565.

Epoch   6/200 | Train: Loss=0.9888, F1 Score=0.6947 | Val: Loss=0.8610, F1 Score=0.7141
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1271, F1 Score=0.6701 | Val: Loss=1.0516, F1 Score=0.6528
Epoch   2/200 | Train: Loss=1.1170, F1 Score=0.6874 | Val: Loss=1.0424, F1 Score=0.7015
Epoch   3/200 | Train: Loss=1.1068, F1 Score=0.7141 | Val: Loss=1.0322, F1 Score=0.7401
Epoch   4/200 | Train: Loss=1.0972, F1 Score=0.7245 | Val: Loss=1.0272, F1 Score=0.7582
Epoch   5/200 | Train: Loss=1.0846, F1 Score=0.7464 | Val: Loss=1.0209, F1 Score=0.7031

[I 2025-11-12 11:13:59,716] Trial 9 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 5, 'hidden_size': 32, 'num_layers': 1, 'dropout_rate': 0.555885944566438, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 3.427421832495478e-05, 'weight_decay': 6.115992792927952e-06, 'l1_lambda': 3.572818685663511e-05, 'focal_gamma': 0.5, 'scheduler_patience': 6, 'scheduler_factor': 0.1, 'weight_max_norm': 2.2952321592320493}. Best is trial 1 with value: 0.9475612112569565.

Epoch   6/200 | Train: Loss=1.0691, F1 Score=0.7429 | Val: Loss=0.9920, F1 Score=0.6927
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.5128, F1 Score=0.5623 | Val: Loss=0.9906, F1 Score=0.7593
Epoch   2/200 | Train: Loss=1.2110, F1 Score=0.6100 | Val: Loss=0.9056, F1 Score=0.7538
Epoch   3/200 | Train: Loss=1.1196, F1 Score=0.6365 | Val: Loss=0.8837, F1 Score=0.7982
Epoch   4/200 | Train: Loss=1.0811, F1 Score=0.6406 | Val: Loss=0.9548, F1 Score=0.4357
Epoch   5/200 | Train: Loss=1.0257, F1 Score=0.6539 | Val: Loss=0.8240, F1 Score=0.7415

[I 2025-11-12 11:14:08,569] Trial 10 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 30, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.2202425195042984, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.0009909259885392705, 'weight_decay': 0.0009518392825134473, 'l1_lambda': 9.166595627230286e-05, 'focal_gamma': 4.0, 'scheduler_patience': 10, 'scheduler_factor': 0.2, 'weight_max_norm': 5.911740168345637}. Best is trial 1 with value: 0.9475612112569565.

Epoch   6/200 | Train: Loss=1.0281, F1 Score=0.6534 | Val: Loss=0.8628, F1 Score=0.6304
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1013, F1 Score=0.5725 | Val: Loss=1.0389, F1 Score=0.7275
Epoch   2/200 | Train: Loss=1.0401, F1 Score=0.6511 | Val: Loss=0.9090, F1 Score=0.7814
Epoch   3/200 | Train: Loss=0.9822, F1 Score=0.6573 | Val: Loss=0.9758, F1 Score=0.5385
Epoch   4/200 | Train: Loss=0.9333, F1 Score=0.6519 | Val: Loss=0.9159, F1 Score=0.6817
Epoch   5/200 | Train: Loss=0.9052, F1 Score=0.6871 | Val: Loss=0.8652, F1 Score=0.7423
Epoch   6/200 | Train: Loss=0.8687, F1 Score=0.6761 | Val: Loss=0.9407, F1 Score=0.5142

[I 2025-11-12 11:14:23,611] Trial 11 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 20, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.5358818440431163, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.0002095926377016297, 'weight_decay': 8.44655738692578e-06, 'l1_lambda': 6.450173122165068e-07, 'focal_gamma': 3.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 4.126283667563042}. Best is trial 1 with value: 0.9475612112569565.

Epoch   7/200 | Train: Loss=0.8496, F1 Score=0.6679 | Val: Loss=0.7977, F1 Score=0.8032
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0111, F1 Score=0.6192 | Val: Loss=0.8585, F1 Score=0.6404
Epoch   2/200 | Train: Loss=0.8825, F1 Score=0.6758 | Val: Loss=0.8554, F1 Score=0.7833
Epoch   3/200 | Train: Loss=0.7414, F1 Score=0.7691 | Val: Loss=0.4999, F1 Score=0.8805
Epoch   4/200 | Train: Loss=0.5996, F1 Score=0.8277 | Val: Loss=0.5097, F1 Score=0.8536
Epoch   5/200 | Train: Loss=0.5349, F1 Score=0.8479 | Val: Loss=0.5758, F1 Score=0.7722
Epoch   6/200 | Train: Loss=0.4735, F1 Score=0.8613 | Val: Loss=0.5272, F1 Score=0.8488
Epoch   7/200 | Train: Loss=0.4416, F1 Score=0.8710 | Val: Loss=0.5087, F1 Score=0.7804
Epoch   8/200 | Train: Loss=0.3792, F1 Score=0.8900 | Val: Loss=0.4175, F1 Score=0.8812
Epoch   9/200 | Train: Loss=0.3357, F1 Score=0.8923 | Val: Loss=0.3491, F1 Score=0.8715
Epoch  10/200 | Train: Loss=0.2872, F1 Score=0.9063 | Val: Loss=0.3119, F1 Score=0.9163
Epoch  11/200 | Train: Loss=0.2740, F1 Score=0.9032 | Val: Loss=0.4029, F1 Score=0.8663
Epoch  12/200 | Train: Loss=0.2787, F1 Score=0.9032 | Val: Loss=0.3445, F1 Score=0.8966
Epoch  13/200 | Train: Loss=0.2335, F1 Score=0.9181 | Val: Loss=0.3731, F1 Score=0.8995
Epoch  14/200 | Train: Loss=0.2369, F1 Score=0.9157 | Val: Loss=0.3198, F1 Score=0.8955
Epoch  15/200 | Train: Loss=0.1983, F1 Score=0.9245 | Val: Loss=0.4213, F1 Score=0.8969
Epoch  16/200 | Train: Loss=0.2169, F1 Score=0.9181 | Val: Loss=0.3809, F1 Score=0.8775
Epoch  17/200 | Train: Loss=0.2015, F1 Score=0.9226 | Val: Loss=0.4977, F1 Score=0.7729
Epoch  18/200 | Train: Loss=0.1954, F1 Score=0.9264 | Val: Loss=0.3816, F1 Score=0.8692
Epoch  19/200 | Train: Loss=0.1875, F1 Score=0.9269 | Val: Loss=0.3884, F1 Score=0.9136
Epoch  20/200 | Train: Loss=0.1738, F1 Score=0.9335 | Val: Loss=0.4077, F1 Score=0.8553
Epoch  21/200 | Train: Loss=0.1319, F1 Score=0.9443 | Val: Loss=0.3159, F1 Score=0.8984
Epoch  22/200 | Train: Loss=0.1247, F1 Score=0.9476 | Val: Loss=0.4426, F1 Score=0.8598
Epoch  23/200 | Train: Loss=0.1273, F1 Score=0.9444 | Val: Loss=0.3818, F1 Score=0.8944

[I 2025-11-12 11:15:41,068] Trial 12 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.5272061928190626, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.00035609494821572653, 'weight_decay': 8.149168555351584e-06, 'l1_lambda': 8.860050671496852e-07, 'focal_gamma': 0.0, 'scheduler_patience': 9, 'scheduler_factor': 0.5, 'weight_max_norm': 4.318069431186587}. Best is trial 1 with value: 0.9475612112569565.

Epoch  24/200 | Train: Loss=0.1323, F1 Score=0.9456 | Val: Loss=0.4253, F1 Score=0.8902
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1021, F1 Score=0.5881 | Val: Loss=1.0913, F1 Score=0.7046
Epoch   2/200 | Train: Loss=1.0974, F1 Score=0.7030 | Val: Loss=1.0794, F1 Score=0.7429
Epoch   3/200 | Train: Loss=1.0431, F1 Score=0.6829 | Val: Loss=0.9851, F1 Score=0.7117
Epoch   4/200 | Train: Loss=0.9664, F1 Score=0.6812 | Val: Loss=1.0720, F1 Score=0.4999
Epoch   5/200 | Train: Loss=0.9499, F1 Score=0.6424 | Val: Loss=0.9393, F1 Score=0.7493

[I 2025-11-12 11:15:54,183] Trial 13 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 20, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.6997944565650696, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00013439270030265267, 'weight_decay': 0.0003495306313233688, 'l1_lambda': 2.506847831493342e-07, 'focal_gamma': 1.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 0.2112012797719912}. Best is trial 1 with value: 0.9475612112569565.

Epoch   6/200 | Train: Loss=0.9183, F1 Score=0.6706 | Val: Loss=0.9039, F1 Score=0.6740
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0660, F1 Score=0.5765 | Val: Loss=0.8654, F1 Score=0.7775
Epoch   2/200 | Train: Loss=0.9293, F1 Score=0.6641 | Val: Loss=0.9137, F1 Score=0.4892
Epoch   3/200 | Train: Loss=0.8290, F1 Score=0.7142 | Val: Loss=0.5538, F1 Score=0.8657
Epoch   4/200 | Train: Loss=0.6534, F1 Score=0.8246 | Val: Loss=0.6386, F1 Score=0.8117
Epoch   5/200 | Train: Loss=0.5932, F1 Score=0.8350 | Val: Loss=0.4996, F1 Score=0.8912
Epoch   6/200 | Train: Loss=0.5378, F1 Score=0.8513 | Val: Loss=0.4325, F1 Score=0.8913
Epoch   7/200 | Train: Loss=0.5094, F1 Score=0.8540 | Val: Loss=0.5115, F1 Score=0.8462
Epoch   8/200 | Train: Loss=0.4717, F1 Score=0.8653 | Val: Loss=0.5552, F1 Score=0.7405
Epoch   9/200 | Train: Loss=0.4118, F1 Score=0.8710 | Val: Loss=0.3948, F1 Score=0.8815
Epoch  10/200 | Train: Loss=0.3945, F1 Score=0.8899 | Val: Loss=0.3539, F1 Score=0.8809
Epoch  11/200 | Train: Loss=0.3750, F1 Score=0.8909 | Val: Loss=0.3655, F1 Score=0.8998
Epoch  12/200 | Train: Loss=0.3415, F1 Score=0.8958 | Val: Loss=0.5336, F1 Score=0.8112
Epoch  13/200 | Train: Loss=0.3302, F1 Score=0.9015 | Val: Loss=0.4166, F1 Score=0.8523
Epoch  14/200 | Train: Loss=0.2707, F1 Score=0.9182 | Val: Loss=0.3649, F1 Score=0.8752
Epoch  15/200 | Train: Loss=0.2868, F1 Score=0.9045 | Val: Loss=0.3368, F1 Score=0.8973
Epoch  16/200 | Train: Loss=0.2589, F1 Score=0.9140 | Val: Loss=0.4170, F1 Score=0.8547
Epoch  17/200 | Train: Loss=0.2610, F1 Score=0.9159 | Val: Loss=0.3093, F1 Score=0.9073
Epoch  18/200 | Train: Loss=0.2452, F1 Score=0.9211 | Val: Loss=0.3342, F1 Score=0.9008
Epoch  19/200 | Train: Loss=0.2425, F1 Score=0.9264 | Val: Loss=0.4305, F1 Score=0.8340
Epoch  20/200 | Train: Loss=0.2218, F1 Score=0.9260 | Val: Loss=0.5371, F1 Score=0.8241
Epoch  21/200 | Train: Loss=0.2494, F1 Score=0.9156 | Val: Loss=0.3216, F1 Score=0.8873
Epoch  22/200 | Train: Loss=0.1910, F1 Score=0.9318 | Val: Loss=0.3845, F1 Score=0.8768
Epoch  23/200 | Train: Loss=0.2061, F1 Score=0.9342 | Val: Loss=0.4007, F1 Score=0.8996

[I 2025-11-12 11:16:49,020] Trial 14 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.2643328097720846, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.000457336468012576, 'weight_decay': 2.7048309403073475e-06, 'l1_lambda': 2.1870280079671562e-06, 'focal_gamma': 3.5, 'scheduler_patience': 8, 'scheduler_factor': 0.2, 'weight_max_norm': 3.993925752776374}. Best is trial 1 with value: 0.9475612112569565.

Epoch  24/200 | Train: Loss=0.2159, F1 Score=0.9299 | Val: Loss=0.4044, F1 Score=0.8637
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0993, F1 Score=0.5902 | Val: Loss=1.0721, F1 Score=0.6760
Epoch   2/200 | Train: Loss=1.0901, F1 Score=0.6516 | Val: Loss=1.0706, F1 Score=0.7631
Epoch   3/200 | Train: Loss=1.0752, F1 Score=0.6867 | Val: Loss=1.0461, F1 Score=0.7728
Epoch   4/200 | Train: Loss=1.0448, F1 Score=0.6813 | Val: Loss=1.0060, F1 Score=0.6560
Epoch   5/200 | Train: Loss=0.9902, F1 Score=0.6329 | Val: Loss=0.9557, F1 Score=0.6999
Epoch   6/200 | Train: Loss=0.9543, F1 Score=0.6542 | Val: Loss=0.9411, F1 Score=0.6836

[I 2025-11-12 11:17:00,608] Trial 15 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 30, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.5963247271885112, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00013989114539823523, 'weight_decay': 1.8470688064620248e-05, 'l1_lambda': 3.033493604743002e-07, 'focal_gamma': 5.0, 'scheduler_patience': 6, 'scheduler_factor': 0.5, 'weight_max_norm': 1.0851463747678813}. Best is trial 1 with value: 0.9475612112569565.

Epoch   7/200 | Train: Loss=0.9375, F1 Score=0.6593 | Val: Loss=0.9177, F1 Score=0.6928
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0242, F1 Score=0.6405 | Val: Loss=0.8729, F1 Score=0.7076
Epoch   2/200 | Train: Loss=0.8230, F1 Score=0.7292 | Val: Loss=0.5807, F1 Score=0.8079
Epoch   3/200 | Train: Loss=0.6196, F1 Score=0.8249 | Val: Loss=0.7146, F1 Score=0.7414
Epoch   4/200 | Train: Loss=0.5402, F1 Score=0.8375 | Val: Loss=0.5237, F1 Score=0.8519
Epoch   5/200 | Train: Loss=0.4879, F1 Score=0.8469 | Val: Loss=0.5152, F1 Score=0.8658
Epoch   6/200 | Train: Loss=0.4393, F1 Score=0.8637 | Val: Loss=0.4498, F1 Score=0.8472
Epoch   7/200 | Train: Loss=0.4055, F1 Score=0.8842 | Val: Loss=0.4854, F1 Score=0.8188
Epoch   8/200 | Train: Loss=0.3392, F1 Score=0.8928 | Val: Loss=0.5031, F1 Score=0.8798
Epoch   9/200 | Train: Loss=0.3210, F1 Score=0.8942 | Val: Loss=0.3504, F1 Score=0.9058
Epoch  10/200 | Train: Loss=0.2978, F1 Score=0.9024 | Val: Loss=0.3451, F1 Score=0.9098
Epoch  11/200 | Train: Loss=0.2673, F1 Score=0.9160 | Val: Loss=0.3569, F1 Score=0.8987
Epoch  12/200 | Train: Loss=0.2630, F1 Score=0.9057 | Val: Loss=0.4054, F1 Score=0.8606
Epoch  13/200 | Train: Loss=0.2293, F1 Score=0.9156 | Val: Loss=0.3533, F1 Score=0.8560
Epoch  14/200 | Train: Loss=0.2120, F1 Score=0.9216 | Val: Loss=0.4969, F1 Score=0.8299
Epoch  15/200 | Train: Loss=0.2177, F1 Score=0.9223 | Val: Loss=0.4501, F1 Score=0.8486
Epoch  16/200 | Train: Loss=0.1450, F1 Score=0.9463 | Val: Loss=0.3466, F1 Score=0.8837
Epoch  17/200 | Train: Loss=0.1295, F1 Score=0.9508 | Val: Loss=0.3119, F1 Score=0.9103
Epoch  18/200 | Train: Loss=0.1172, F1 Score=0.9540 | Val: Loss=0.3201, F1 Score=0.9292
Epoch  19/200 | Train: Loss=0.1152, F1 Score=0.9569 | Val: Loss=0.3118, F1 Score=0.9221
Epoch  20/200 | Train: Loss=0.1085, F1 Score=0.9584 | Val: Loss=0.3732, F1 Score=0.9062
Epoch  21/200 | Train: Loss=0.1073, F1 Score=0.9597 | Val: Loss=0.3673, F1 Score=0.9033
Epoch  22/200 | Train: Loss=0.1054, F1 Score=0.9606 | Val: Loss=0.3540, F1 Score=0.9050
Epoch  23/200 | Train: Loss=0.0995, F1 Score=0.9589 | Val: Loss=0.3702, F1 Score=0.9030
Epoch  24/200 | Train: Loss=0.0865, F1 Score=0.9687 | Val: Loss=0.3635, F1 Score=0.9147
Epoch  25/200 | Train: Loss=0.0866, F1 Score=0.9690 | Val: Loss=0.3653, F1 Score=0.9093
Epoch  26/200 | Train: Loss=0.0845, F1 Score=0.9698 | Val: Loss=0.3563, F1 Score=0.9143
Epoch  27/200 | Train: Loss=0.0844, F1 Score=0.9704 | Val: Loss=0.3613, F1 Score=0.9223
Epoch  28/200 | Train: Loss=0.0816, F1 Score=0.9729 | Val: Loss=0.3615, F1 Score=0.9154
Epoch  29/200 | Train: Loss=0.0802, F1 Score=0.9707 | Val: Loss=0.3608, F1 Score=0.9207
Epoch  30/200 | Train: Loss=0.0777, F1 Score=0.9737 | Val: Loss=0.3575, F1 Score=0.9223
Epoch  31/200 | Train: Loss=0.0797, F1 Score=0.9731 | Val: Loss=0.3570, F1 Score=0.9224
Epoch  32/200 | Train: Loss=0.0787, F1 Score=0.9741 | Val: Loss=0.3608, F1 Score=0.9171

[I 2025-11-12 11:18:45,899] Trial 16 finished with value: 0.9291877968176734 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.4884102154588764, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0005903269735484916, 'weight_decay': 0.0002008237619178866, 'l1_lambda': 1.6850353266138382e-06, 'focal_gamma': 0.0, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 5.3224476905922184}. Best is trial 1 with value: 0.9475612112569565.

Epoch  33/200 | Train: Loss=0.0787, F1 Score=0.9726 | Val: Loss=0.3613, F1 Score=0.9170
Early stopping triggered after 33 epochs.
Best model restored from epoch 18 with val_f1 0.9292
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0956, F1 Score=0.6104 | Val: Loss=0.9283, F1 Score=0.4800
Epoch   2/200 | Train: Loss=0.9339, F1 Score=0.6723 | Val: Loss=0.6950, F1 Score=0.8181
Epoch   3/200 | Train: Loss=0.7189, F1 Score=0.8122 | Val: Loss=0.5497, F1 Score=0.8826
Epoch   4/200 | Train: Loss=0.5972, F1 Score=0.8449 | Val: Loss=0.5356, F1 Score=0.8122
Epoch   5/200 | Train: Loss=0.5743, F1 Score=0.8433 | Val: Loss=0.5791, F1 Score=0.7817
Epoch   6/200 | Train: Loss=0.5205, F1 Score=0.8520 | Val: Loss=0.5673, F1 Score=0.7833
Epoch   7/200 | Train: Loss=0.5216, F1 Score=0.8496 | Val: Loss=0.4885, F1 Score=0.8910
Epoch   8/200 | Train: Loss=0.4492, F1 Score=0.8762 | Val: Loss=0.4393, F1 Score=0.8313
Epoch   9/200 | Train: Loss=0.4197, F1 Score=0.8844 | Val: Loss=0.3860, F1 Score=0.8902
Epoch  10/200 | Train: Loss=0.3688, F1 Score=0.9010 | Val: Loss=0.4217, F1 Score=0.8462

[I 2025-11-12 11:19:18,019] Trial 17 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.47176993441162635, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.0006078853059390671, 'weight_decay': 0.0002590151305021872, 'l1_lambda': 6.888641875776708e-06, 'focal_gamma': 3.5, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 5.943238587617542}. Best is trial 1 with value: 0.9475612112569565.

Epoch  11/200 | Train: Loss=0.3681, F1 Score=0.8895 | Val: Loss=0.3752, F1 Score=0.8732
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0270, F1 Score=0.6146 | Val: Loss=0.9440, F1 Score=0.5574
Epoch   2/200 | Train: Loss=0.8893, F1 Score=0.6731 | Val: Loss=0.7082, F1 Score=0.8117
Epoch   3/200 | Train: Loss=0.7149, F1 Score=0.7694 | Val: Loss=0.6345, F1 Score=0.8126
Epoch   4/200 | Train: Loss=0.5801, F1 Score=0.8226 | Val: Loss=0.4359, F1 Score=0.8979
Epoch   5/200 | Train: Loss=0.5379, F1 Score=0.8232 | Val: Loss=0.4172, F1 Score=0.8912
Epoch   6/200 | Train: Loss=0.4576, F1 Score=0.8604 | Val: Loss=0.4857, F1 Score=0.8723
Epoch   7/200 | Train: Loss=0.4152, F1 Score=0.8767 | Val: Loss=0.4002, F1 Score=0.8840
Epoch   8/200 | Train: Loss=0.4223, F1 Score=0.8800 | Val: Loss=0.4369, F1 Score=0.8620
Epoch   9/200 | Train: Loss=0.3859, F1 Score=0.8919 | Val: Loss=0.3446, F1 Score=0.9113
Epoch  10/200 | Train: Loss=0.3213, F1 Score=0.9070 | Val: Loss=0.4928, F1 Score=0.8285
Epoch  11/200 | Train: Loss=0.3428, F1 Score=0.8981 | Val: Loss=0.3273, F1 Score=0.8965
Epoch  12/200 | Train: Loss=0.2893, F1 Score=0.9107 | Val: Loss=0.4348, F1 Score=0.8932
Epoch  13/200 | Train: Loss=0.2646, F1 Score=0.9158 | Val: Loss=0.3602, F1 Score=0.8902
Epoch  14/200 | Train: Loss=0.2815, F1 Score=0.9003 | Val: Loss=0.4982, F1 Score=0.8502
Epoch  15/200 | Train: Loss=0.2116, F1 Score=0.9328 | Val: Loss=0.3549, F1 Score=0.8640
Epoch  16/200 | Train: Loss=0.1858, F1 Score=0.9372 | Val: Loss=0.3371, F1 Score=0.8896
Epoch  17/200 | Train: Loss=0.1723, F1 Score=0.9402 | Val: Loss=0.3122, F1 Score=0.9143
Epoch  18/200 | Train: Loss=0.1695, F1 Score=0.9400 | Val: Loss=0.3109, F1 Score=0.9004
Epoch  19/200 | Train: Loss=0.1702, F1 Score=0.9385 | Val: Loss=0.3020, F1 Score=0.9132
Epoch  20/200 | Train: Loss=0.1642, F1 Score=0.9382 | Val: Loss=0.3479, F1 Score=0.8877
Epoch  21/200 | Train: Loss=0.1601, F1 Score=0.9440 | Val: Loss=0.3120, F1 Score=0.8946
Epoch  22/200 | Train: Loss=0.1531, F1 Score=0.9402 | Val: Loss=0.3119, F1 Score=0.9084
Epoch  23/200 | Train: Loss=0.1406, F1 Score=0.9470 | Val: Loss=0.3140, F1 Score=0.9116
Epoch  24/200 | Train: Loss=0.1407, F1 Score=0.9465 | Val: Loss=0.3145, F1 Score=0.9079

[I 2025-11-12 11:20:37,968] Trial 18 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.3044706321993768, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0005054514660879176, 'weight_decay': 0.0008084190228499123, 'l1_lambda': 1.74146433493686e-06, 'focal_gamma': 2.0, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 5.107043257616127}. Best is trial 1 with value: 0.9475612112569565.

Epoch  25/200 | Train: Loss=0.1362, F1 Score=0.9490 | Val: Loss=0.3104, F1 Score=0.8986
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1136, F1 Score=0.5500 | Val: Loss=1.0561, F1 Score=0.4310
Epoch   2/200 | Train: Loss=1.0152, F1 Score=0.6326 | Val: Loss=0.8916, F1 Score=0.7652
Epoch   3/200 | Train: Loss=0.9576, F1 Score=0.6496 | Val: Loss=0.8817, F1 Score=0.6138
Epoch   4/200 | Train: Loss=0.8661, F1 Score=0.7035 | Val: Loss=0.8111, F1 Score=0.7011
Epoch   5/200 | Train: Loss=0.7152, F1 Score=0.7850 | Val: Loss=0.6567, F1 Score=0.8305
Epoch   6/200 | Train: Loss=0.6433, F1 Score=0.8196 | Val: Loss=0.5956, F1 Score=0.8994
Epoch   7/200 | Train: Loss=0.5846, F1 Score=0.8374 | Val: Loss=0.5260, F1 Score=0.8791
Epoch   8/200 | Train: Loss=0.5856, F1 Score=0.8396 | Val: Loss=0.5474, F1 Score=0.8922
Epoch   9/200 | Train: Loss=0.5062, F1 Score=0.8521 | Val: Loss=0.5102, F1 Score=0.8614
Epoch  10/200 | Train: Loss=0.5148, F1 Score=0.8498 | Val: Loss=0.4800, F1 Score=0.8944
Epoch  11/200 | Train: Loss=0.4774, F1 Score=0.8657 | Val: Loss=0.4926, F1 Score=0.8891
Epoch  12/200 | Train: Loss=0.4661, F1 Score=0.8674 | Val: Loss=0.4440, F1 Score=0.8910
Epoch  13/200 | Train: Loss=0.4427, F1 Score=0.8719 | Val: Loss=0.4445, F1 Score=0.8734
Epoch  14/200 | Train: Loss=0.3814, F1 Score=0.9100 | Val: Loss=0.4307, F1 Score=0.8801
Epoch  15/200 | Train: Loss=0.3641, F1 Score=0.9142 | Val: Loss=0.4311, F1 Score=0.8929
Epoch  16/200 | Train: Loss=0.3509, F1 Score=0.9150 | Val: Loss=0.4411, F1 Score=0.8825
Epoch  17/200 | Train: Loss=0.3463, F1 Score=0.9135 | Val: Loss=0.4216, F1 Score=0.8770
Epoch  18/200 | Train: Loss=0.3546, F1 Score=0.9007 | Val: Loss=0.4366, F1 Score=0.8945

[I 2025-11-12 11:21:11,334] Trial 19 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 20, 'hidden_size': 32, 'num_layers': 2, 'dropout_rate': 0.4706927826314636, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.0009590422387847192, 'weight_decay': 0.00012845747127581406, 'l1_lambda': 1.0039286993595586e-05, 'focal_gamma': 2.5, 'scheduler_patience': 6, 'scheduler_factor': 0.2, 'weight_max_norm': 5.012363993454975}. Best is trial 1 with value: 0.9475612112569565.
[I 2025-11-12 11:21:11,339] Trial 20 pruned.

Epoch  19/200 | Train: Loss=0.3330, F1 Score=0.9113 | Val: Loss=0.4246, F1 Score=0.8669
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0370, F1 Score=0.6369 | Val: Loss=1.0506, F1 Score=0.4379
Epoch   2/200 | Train: Loss=0.9167, F1 Score=0.6697 | Val: Loss=0.8374, F1 Score=0.6779
Epoch   3/200 | Train: Loss=0.8401, F1 Score=0.6995 | Val: Loss=0.6351, F1 Score=0.8169
Epoch   4/200 | Train: Loss=0.6602, F1 Score=0.7998 | Val: Loss=0.4949, F1 Score=0.8453
Epoch   5/200 | Train: Loss=0.5620, F1 Score=0.8347 | Val: Loss=0.4537, F1 Score=0.8915
Epoch   6/200 | Train: Loss=0.5168, F1 Score=0.8421 | Val: Loss=0.4603, F1 Score=0.8720
Epoch   7/200 | Train: Loss=0.4611, F1 Score=0.8562 | Val: Loss=0.4475, F1 Score=0.8620
Epoch   8/200 | Train: Loss=0.4480, F1 Score=0.8641 | Val: Loss=0.4303, F1 Score=0.8737
Epoch   9/200 | Train: Loss=0.4076, F1 Score=0.8658 | Val: Loss=0.4085, F1 Score=0.8809
Epoch  10/200 | Train: Loss=0.3671, F1 Score=0.8845 | Val: Loss=0.3656, F1 Score=0.8777
Epoch  11/200 | Train: Loss=0.3358, F1 Score=0.8897 | Val: Loss=0.3672, F1 Score=0.9026
Epoch  12/200 | Train: Loss=0.3005, F1 Score=0.8957 | Val: Loss=0.4338, F1 Score=0.8633
Epoch  13/200 | Train: Loss=0.3661, F1 Score=0.8875 | Val: Loss=0.3791, F1 Score=0.8838
Epoch  14/200 | Train: Loss=0.2509, F1 Score=0.9119 | Val: Loss=0.3510, F1 Score=0.8656
Epoch  15/200 | Train: Loss=0.2413, F1 Score=0.9155 | Val: Loss=0.4269, F1 Score=0.8534
Epoch  16/200 | Train: Loss=0.2307, F1 Score=0.9128 | Val: Loss=0.3273, F1 Score=0.9053
Epoch  17/200 | Train: Loss=0.2410, F1 Score=0.9105 | Val: Loss=0.3746, F1 Score=0.8652
Epoch  18/200 | Train: Loss=0.2254, F1 Score=0.9124 | Val: Loss=0.3251, F1 Score=0.8880
Epoch  19/200 | Train: Loss=0.2026, F1 Score=0.9244 | Val: Loss=0.4680, F1 Score=0.8490
Epoch  20/200 | Train: Loss=0.1957, F1 Score=0.9210 | Val: Loss=0.3958, F1 Score=0.8519
Epoch  21/200 | Train: Loss=0.1843, F1 Score=0.9280 | Val: Loss=0.3986, F1 Score=0.8845
Epoch  22/200 | Train: Loss=0.1721, F1 Score=0.9311 | Val: Loss=0.3539, F1 Score=0.8662
Epoch  23/200 | Train: Loss=0.1294, F1 Score=0.9404 | Val: Loss=0.2926, F1 Score=0.9093

[I 2025-11-12 11:22:45,499] Trial 21 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.5948665039717304, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00023079274592167806, 'weight_decay': 0.00022003136284668896, 'l1_lambda': 4.511768897068645e-07, 'focal_gamma': 0.0, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 3.6412911512222976}. Best is trial 1 with value: 0.9475612112569565.

Epoch  24/200 | Train: Loss=0.1217, F1 Score=0.9461 | Val: Loss=0.3200, F1 Score=0.8917
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0367, F1 Score=0.6110 | Val: Loss=0.9518, F1 Score=0.6281
Epoch   2/200 | Train: Loss=0.9046, F1 Score=0.6659 | Val: Loss=0.7373, F1 Score=0.7739
Epoch   3/200 | Train: Loss=0.7397, F1 Score=0.7606 | Val: Loss=0.5434, F1 Score=0.8216
Epoch   4/200 | Train: Loss=0.5946, F1 Score=0.8301 | Val: Loss=0.5543, F1 Score=0.8716
Epoch   5/200 | Train: Loss=0.5348, F1 Score=0.8436 | Val: Loss=0.4367, F1 Score=0.8792
Epoch   6/200 | Train: Loss=0.4851, F1 Score=0.8687 | Val: Loss=0.4520, F1 Score=0.8538
Epoch   7/200 | Train: Loss=0.4374, F1 Score=0.8795 | Val: Loss=0.3655, F1 Score=0.9021
Epoch   8/200 | Train: Loss=0.3878, F1 Score=0.8933 | Val: Loss=0.4395, F1 Score=0.8686
Epoch   9/200 | Train: Loss=0.3533, F1 Score=0.9037 | Val: Loss=0.5833, F1 Score=0.8037
Epoch  10/200 | Train: Loss=0.3050, F1 Score=0.9086 | Val: Loss=0.4110, F1 Score=0.8800
Epoch  11/200 | Train: Loss=0.3444, F1 Score=0.8973 | Val: Loss=0.4309, F1 Score=0.8671
Epoch  12/200 | Train: Loss=0.3004, F1 Score=0.9173 | Val: Loss=0.3884, F1 Score=0.9230
Epoch  13/200 | Train: Loss=0.2647, F1 Score=0.9133 | Val: Loss=0.3575, F1 Score=0.8739
Epoch  14/200 | Train: Loss=0.2726, F1 Score=0.9112 | Val: Loss=0.4568, F1 Score=0.8755
Epoch  15/200 | Train: Loss=0.2094, F1 Score=0.9253 | Val: Loss=0.3595, F1 Score=0.8792
Epoch  16/200 | Train: Loss=0.2044, F1 Score=0.9269 | Val: Loss=0.3263, F1 Score=0.8886
Epoch  17/200 | Train: Loss=0.2790, F1 Score=0.9117 | Val: Loss=0.4239, F1 Score=0.8517
Epoch  18/200 | Train: Loss=0.1608, F1 Score=0.9419 | Val: Loss=0.2860, F1 Score=0.9054
Epoch  19/200 | Train: Loss=0.1453, F1 Score=0.9485 | Val: Loss=0.3008, F1 Score=0.8982
Epoch  20/200 | Train: Loss=0.1381, F1 Score=0.9493 | Val: Loss=0.2957, F1 Score=0.9179
Epoch  21/200 | Train: Loss=0.1333, F1 Score=0.9531 | Val: Loss=0.3327, F1 Score=0.9096
Epoch  22/200 | Train: Loss=0.1317, F1 Score=0.9510 | Val: Loss=0.3210, F1 Score=0.9151
Epoch  23/200 | Train: Loss=0.1199, F1 Score=0.9571 | Val: Loss=0.3019, F1 Score=0.9150
Epoch  24/200 | Train: Loss=0.1156, F1 Score=0.9574 | Val: Loss=0.3092, F1 Score=0.9202
Epoch  25/200 | Train: Loss=0.1132, F1 Score=0.9610 | Val: Loss=0.3102, F1 Score=0.9143
Epoch  26/200 | Train: Loss=0.1160, F1 Score=0.9591 | Val: Loss=0.3151, F1 Score=0.9142

[I 2025-11-12 11:24:30,947] Trial 22 finished with value: 0.922997496667182 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.5019309712909894, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0003549088863355454, 'weight_decay': 0.0005444259367823477, 'l1_lambda': 1.4547612408579766e-06, 'focal_gamma': 0.0, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 4.5826096065776145}. Best is trial 1 with value: 0.9475612112569565.

Epoch  27/200 | Train: Loss=0.1117, F1 Score=0.9618 | Val: Loss=0.2998, F1 Score=0.9122
Early stopping triggered after 27 epochs.
Best model restored from epoch 12 with val_f1 0.9230
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0378, F1 Score=0.6457 | Val: Loss=0.8571, F1 Score=0.6769
Epoch   2/200 | Train: Loss=0.9017, F1 Score=0.6636 | Val: Loss=0.8734, F1 Score=0.5788
Epoch   3/200 | Train: Loss=0.7189, F1 Score=0.7736 | Val: Loss=0.5208, F1 Score=0.8680
Epoch   4/200 | Train: Loss=0.5923, F1 Score=0.8320 | Val: Loss=0.4433, F1 Score=0.8915
Epoch   5/200 | Train: Loss=0.4906, F1 Score=0.8574 | Val: Loss=0.4859, F1 Score=0.8608
Epoch   6/200 | Train: Loss=0.4523, F1 Score=0.8663 | Val: Loss=0.3804, F1 Score=0.8848
Epoch   7/200 | Train: Loss=0.4056, F1 Score=0.8839 | Val: Loss=0.3854, F1 Score=0.8949
Epoch   8/200 | Train: Loss=0.3696, F1 Score=0.8888 | Val: Loss=0.3922, F1 Score=0.8697
Epoch   9/200 | Train: Loss=0.3201, F1 Score=0.9051 | Val: Loss=0.3455, F1 Score=0.8789
Epoch  10/200 | Train: Loss=0.3068, F1 Score=0.9020 | Val: Loss=0.3225, F1 Score=0.9192
Epoch  11/200 | Train: Loss=0.2770, F1 Score=0.9132 | Val: Loss=0.3229, F1 Score=0.9252
Epoch  12/200 | Train: Loss=0.2288, F1 Score=0.9183 | Val: Loss=0.2847, F1 Score=0.9095
Epoch  13/200 | Train: Loss=0.2367, F1 Score=0.9170 | Val: Loss=0.2857, F1 Score=0.9218
Epoch  14/200 | Train: Loss=0.2121, F1 Score=0.9253 | Val: Loss=0.2927, F1 Score=0.9043
Epoch  15/200 | Train: Loss=0.2141, F1 Score=0.9233 | Val: Loss=0.4342, F1 Score=0.8097
Epoch  16/200 | Train: Loss=0.2000, F1 Score=0.9260 | Val: Loss=0.4355, F1 Score=0.8614
Epoch  17/200 | Train: Loss=0.1458, F1 Score=0.9435 | Val: Loss=0.3120, F1 Score=0.9218
Epoch  18/200 | Train: Loss=0.1341, F1 Score=0.9497 | Val: Loss=0.2989, F1 Score=0.8984
Epoch  19/200 | Train: Loss=0.1282, F1 Score=0.9515 | Val: Loss=0.3248, F1 Score=0.8980
Epoch  20/200 | Train: Loss=0.1265, F1 Score=0.9527 | Val: Loss=0.3530, F1 Score=0.8918
Epoch  21/200 | Train: Loss=0.1214, F1 Score=0.9558 | Val: Loss=0.3153, F1 Score=0.9337
Epoch  22/200 | Train: Loss=0.1151, F1 Score=0.9584 | Val: Loss=0.2794, F1 Score=0.9245
Epoch  23/200 | Train: Loss=0.1155, F1 Score=0.9574 | Val: Loss=0.3227, F1 Score=0.8800
Epoch  24/200 | Train: Loss=0.1143, F1 Score=0.9601 | Val: Loss=0.2931, F1 Score=0.9141
Epoch  25/200 | Train: Loss=0.1047, F1 Score=0.9625 | Val: Loss=0.2751, F1 Score=0.9331
Epoch  26/200 | Train: Loss=0.1043, F1 Score=0.9632 | Val: Loss=0.2889, F1 Score=0.9197
Epoch  27/200 | Train: Loss=0.0907, F1 Score=0.9711 | Val: Loss=0.2937, F1 Score=0.9222
Epoch  28/200 | Train: Loss=0.0889, F1 Score=0.9736 | Val: Loss=0.2877, F1 Score=0.9255
Epoch  29/200 | Train: Loss=0.0894, F1 Score=0.9725 | Val: Loss=0.2848, F1 Score=0.9355
Epoch  30/200 | Train: Loss=0.0870, F1 Score=0.9744 | Val: Loss=0.2984, F1 Score=0.9204
Epoch  31/200 | Train: Loss=0.0882, F1 Score=0.9722 | Val: Loss=0.2996, F1 Score=0.9234
Epoch  32/200 | Train: Loss=0.0881, F1 Score=0.9707 | Val: Loss=0.2985, F1 Score=0.9247
Epoch  33/200 | Train: Loss=0.0878, F1 Score=0.9722 | Val: Loss=0.3243, F1 Score=0.9011
Epoch  34/200 | Train: Loss=0.0820, F1 Score=0.9751 | Val: Loss=0.2941, F1 Score=0.9348
Epoch  35/200 | Train: Loss=0.0838, F1 Score=0.9754 | Val: Loss=0.2976, F1 Score=0.9311
Epoch  36/200 | Train: Loss=0.0827, F1 Score=0.9743 | Val: Loss=0.2988, F1 Score=0.9297
Epoch  37/200 | Train: Loss=0.0797, F1 Score=0.9770 | Val: Loss=0.2967, F1 Score=0.9325
Epoch  38/200 | Train: Loss=0.0811, F1 Score=0.9783 | Val: Loss=0.3025, F1 Score=0.9265
Epoch  39/200 | Train: Loss=0.0819, F1 Score=0.9748 | Val: Loss=0.2969, F1 Score=0.9320
Epoch  40/200 | Train: Loss=0.0812, F1 Score=0.9769 | Val: Loss=0.2972, F1 Score=0.9307

[I 2025-11-12 11:27:11,486] Trial 23 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.4932989523539488, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00035885323225267105, 'weight_decay': 0.0006761969283541699, 'l1_lambda': 1.4388725092041108e-06, 'focal_gamma': 1.0, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 4.641535819961829}. Best is trial 1 with value: 0.9475612112569565.

Epoch  41/200 | Train: Loss=0.0800, F1 Score=0.9765 | Val: Loss=0.2973, F1 Score=0.9316
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0367, F1 Score=0.6338 | Val: Loss=0.7686, F1 Score=0.7612
Epoch   2/200 | Train: Loss=0.8890, F1 Score=0.6750 | Val: Loss=0.7539, F1 Score=0.7619
Epoch   3/200 | Train: Loss=0.7415, F1 Score=0.7548 | Val: Loss=0.5235, F1 Score=0.8611
Epoch   4/200 | Train: Loss=0.6398, F1 Score=0.8057 | Val: Loss=0.4956, F1 Score=0.8853
Epoch   5/200 | Train: Loss=0.5305, F1 Score=0.8432 | Val: Loss=0.4447, F1 Score=0.8487
Epoch   6/200 | Train: Loss=0.5101, F1 Score=0.8488 | Val: Loss=0.4160, F1 Score=0.8605
Epoch   7/200 | Train: Loss=0.4323, F1 Score=0.8759 | Val: Loss=0.4028, F1 Score=0.8938
Epoch   8/200 | Train: Loss=0.3902, F1 Score=0.8873 | Val: Loss=0.4871, F1 Score=0.8648
Epoch   9/200 | Train: Loss=0.3814, F1 Score=0.8891 | Val: Loss=0.6159, F1 Score=0.7430
Epoch  10/200 | Train: Loss=0.3622, F1 Score=0.8873 | Val: Loss=0.3206, F1 Score=0.9074
Epoch  11/200 | Train: Loss=0.3613, F1 Score=0.8923 | Val: Loss=0.3372, F1 Score=0.9158
Epoch  12/200 | Train: Loss=0.2924, F1 Score=0.9086 | Val: Loss=0.3476, F1 Score=0.9117
Epoch  13/200 | Train: Loss=0.2991, F1 Score=0.9009 | Val: Loss=0.3243, F1 Score=0.8818
Epoch  14/200 | Train: Loss=0.2719, F1 Score=0.9133 | Val: Loss=0.2907, F1 Score=0.9165
Epoch  15/200 | Train: Loss=0.2596, F1 Score=0.9122 | Val: Loss=0.3297, F1 Score=0.9012
Epoch  16/200 | Train: Loss=0.2292, F1 Score=0.9270 | Val: Loss=0.2935, F1 Score=0.8963
Epoch  17/200 | Train: Loss=0.2367, F1 Score=0.9232 | Val: Loss=0.3306, F1 Score=0.8756
Epoch  18/200 | Train: Loss=0.2174, F1 Score=0.9235 | Val: Loss=0.3257, F1 Score=0.9156
Epoch  19/200 | Train: Loss=0.3010, F1 Score=0.9090 | Val: Loss=0.2803, F1 Score=0.9077
Epoch  20/200 | Train: Loss=0.1725, F1 Score=0.9422 | Val: Loss=0.2772, F1 Score=0.9163
Epoch  21/200 | Train: Loss=0.1529, F1 Score=0.9495 | Val: Loss=0.2803, F1 Score=0.9189
Epoch  22/200 | Train: Loss=0.1477, F1 Score=0.9532 | Val: Loss=0.2868, F1 Score=0.9093
Epoch  23/200 | Train: Loss=0.1419, F1 Score=0.9540 | Val: Loss=0.2953, F1 Score=0.9046
Epoch  24/200 | Train: Loss=0.1384, F1 Score=0.9556 | Val: Loss=0.3131, F1 Score=0.8990
Epoch  25/200 | Train: Loss=0.1329, F1 Score=0.9574 | Val: Loss=0.3036, F1 Score=0.9174
Epoch  26/200 | Train: Loss=0.1326, F1 Score=0.9596 | Val: Loss=0.3161, F1 Score=0.9067
Epoch  27/200 | Train: Loss=0.1177, F1 Score=0.9638 | Val: Loss=0.3210, F1 Score=0.9097
Epoch  28/200 | Train: Loss=0.1166, F1 Score=0.9649 | Val: Loss=0.3277, F1 Score=0.9140
Epoch  29/200 | Train: Loss=0.1126, F1 Score=0.9668 | Val: Loss=0.3312, F1 Score=0.9248
Epoch  30/200 | Train: Loss=0.1128, F1 Score=0.9688 | Val: Loss=0.3295, F1 Score=0.9031
Epoch  31/200 | Train: Loss=0.1100, F1 Score=0.9685 | Val: Loss=0.3225, F1 Score=0.9142
Epoch  32/200 | Train: Loss=0.1112, F1 Score=0.9672 | Val: Loss=0.3226, F1 Score=0.9198
Epoch  33/200 | Train: Loss=0.1112, F1 Score=0.9672 | Val: Loss=0.3134, F1 Score=0.9197

[I 2025-11-12 11:29:00,640] Trial 24 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.3815008667364328, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0006484193266840224, 'weight_decay': 0.0004734883048990837, 'l1_lambda': 4.23380944897339e-06, 'focal_gamma': 0.5, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 5.430742554956584}. Best is trial 1 with value: 0.9475612112569565.

Epoch  34/200 | Train: Loss=0.1084, F1 Score=0.9686 | Val: Loss=0.3243, F1 Score=0.9125
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0960, F1 Score=0.6272 | Val: Loss=0.8453, F1 Score=0.7816
Epoch   2/200 | Train: Loss=0.9481, F1 Score=0.6617 | Val: Loss=0.7526, F1 Score=0.8002
Epoch   3/200 | Train: Loss=0.8709, F1 Score=0.6717 | Val: Loss=0.7530, F1 Score=0.7716
Epoch   4/200 | Train: Loss=0.7819, F1 Score=0.7288 | Val: Loss=0.6044, F1 Score=0.8286
Epoch   5/200 | Train: Loss=0.6707, F1 Score=0.7969 | Val: Loss=0.5149, F1 Score=0.8881
Epoch   6/200 | Train: Loss=0.6085, F1 Score=0.8180 | Val: Loss=0.5931, F1 Score=0.8649
Epoch   7/200 | Train: Loss=0.5760, F1 Score=0.8258 | Val: Loss=0.4603, F1 Score=0.8605
Epoch   8/200 | Train: Loss=0.5521, F1 Score=0.8306 | Val: Loss=0.4230, F1 Score=0.8708
Epoch   9/200 | Train: Loss=0.5090, F1 Score=0.8397 | Val: Loss=0.4320, F1 Score=0.9047
Epoch  10/200 | Train: Loss=0.4593, F1 Score=0.8590 | Val: Loss=0.4983, F1 Score=0.7924
Epoch  11/200 | Train: Loss=0.4281, F1 Score=0.8580 | Val: Loss=0.3500, F1 Score=0.8728
Epoch  12/200 | Train: Loss=0.4102, F1 Score=0.8550 | Val: Loss=0.4267, F1 Score=0.8956
Epoch  13/200 | Train: Loss=0.4333, F1 Score=0.8604 | Val: Loss=0.4008, F1 Score=0.8933
Epoch  14/200 | Train: Loss=0.3292, F1 Score=0.8928 | Val: Loss=0.3571, F1 Score=0.8813
Epoch  15/200 | Train: Loss=0.3119, F1 Score=0.8958 | Val: Loss=0.3418, F1 Score=0.8948
Epoch  16/200 | Train: Loss=0.3053, F1 Score=0.8991 | Val: Loss=0.3379, F1 Score=0.8953
Epoch  17/200 | Train: Loss=0.3044, F1 Score=0.8996 | Val: Loss=0.3179, F1 Score=0.8960
Epoch  18/200 | Train: Loss=0.2847, F1 Score=0.9073 | Val: Loss=0.3072, F1 Score=0.8904
Epoch  19/200 | Train: Loss=0.2823, F1 Score=0.9125 | Val: Loss=0.3045, F1 Score=0.8980
Epoch  20/200 | Train: Loss=0.2806, F1 Score=0.9130 | Val: Loss=0.3215, F1 Score=0.9010
Epoch  21/200 | Train: Loss=0.2707, F1 Score=0.9133 | Val: Loss=0.3273, F1 Score=0.9066
Epoch  22/200 | Train: Loss=0.2723, F1 Score=0.9171 | Val: Loss=0.2991, F1 Score=0.8931
Epoch  23/200 | Train: Loss=0.2699, F1 Score=0.9062 | Val: Loss=0.3171, F1 Score=0.9064

[I 2025-11-12 11:30:06,728] Trial 25 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 15, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.31244281401138735, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00030004122009796066, 'weight_decay': 0.0001686677353699966, 'l1_lambda': 2.2800694297998205e-06, 'focal_gamma': 1.5, 'scheduler_patience': 3, 'scheduler_factor': 0.2, 'weight_max_norm': 4.5966420766226}. Best is trial 1 with value: 0.9475612112569565.

Epoch  24/200 | Train: Loss=0.2705, F1 Score=0.9172 | Val: Loss=0.3087, F1 Score=0.9017
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0765, F1 Score=0.5799 | Val: Loss=0.9933, F1 Score=0.5374
Epoch   2/200 | Train: Loss=0.9585, F1 Score=0.6586 | Val: Loss=0.8156, F1 Score=0.7422
Epoch   3/200 | Train: Loss=0.8877, F1 Score=0.6664 | Val: Loss=0.9071, F1 Score=0.5536
Epoch   4/200 | Train: Loss=0.8194, F1 Score=0.6970 | Val: Loss=0.7042, F1 Score=0.7928
Epoch   5/200 | Train: Loss=0.7374, F1 Score=0.7317 | Val: Loss=0.5875, F1 Score=0.8158
Epoch   6/200 | Train: Loss=0.6582, F1 Score=0.7747 | Val: Loss=0.5102, F1 Score=0.8731
Epoch   7/200 | Train: Loss=0.5877, F1 Score=0.8204 | Val: Loss=0.4605, F1 Score=0.8918
Epoch   8/200 | Train: Loss=0.5288, F1 Score=0.8496 | Val: Loss=0.5066, F1 Score=0.8516
Epoch   9/200 | Train: Loss=0.4789, F1 Score=0.8556 | Val: Loss=0.4686, F1 Score=0.8696
Epoch  10/200 | Train: Loss=0.4575, F1 Score=0.8538 | Val: Loss=0.4335, F1 Score=0.8896

[I 2025-11-12 11:30:38,667] Trial 26 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.49928710959755324, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.00015373260326118974, 'weight_decay': 4.9720062191238675e-05, 'l1_lambda': 1.282811102909429e-06, 'focal_gamma': 4.5, 'scheduler_patience': 4, 'scheduler_factor': 0.2, 'weight_max_norm': 5.432544235717192}. Best is trial 1 with value: 0.9475612112569565.

Epoch  11/200 | Train: Loss=0.4293, F1 Score=0.8588 | Val: Loss=0.4839, F1 Score=0.8825
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0501, F1 Score=0.6257 | Val: Loss=0.9241, F1 Score=0.5856
Epoch   2/200 | Train: Loss=0.9055, F1 Score=0.6592 | Val: Loss=0.7150, F1 Score=0.8035
Epoch   3/200 | Train: Loss=0.8251, F1 Score=0.7117 | Val: Loss=0.6452, F1 Score=0.7768
Epoch   4/200 | Train: Loss=0.7181, F1 Score=0.7737 | Val: Loss=0.5433, F1 Score=0.8409
Epoch   5/200 | Train: Loss=0.6143, F1 Score=0.8132 | Val: Loss=0.4517, F1 Score=0.8392

[I 2025-11-12 11:30:53,838] Trial 27 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.5557261375522912, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.000492655478339992, 'weight_decay': 0.0004969344474317169, 'l1_lambda': 5.400346576338594e-06, 'focal_gamma': 3.0, 'scheduler_patience': 6, 'scheduler_factor': 0.5, 'weight_max_norm': 3.499414500160535}. Best is trial 1 with value: 0.9475612112569565.

Epoch   6/200 | Train: Loss=0.5501, F1 Score=0.8466 | Val: Loss=0.4759, F1 Score=0.8322
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.4246, F1 Score=0.6704 | Val: Loss=0.8723, F1 Score=0.7586
Epoch   2/200 | Train: Loss=1.2148, F1 Score=0.6813 | Val: Loss=0.8445, F1 Score=0.7107
Epoch   3/200 | Train: Loss=1.1146, F1 Score=0.6736 | Val: Loss=0.9249, F1 Score=0.6111
Epoch   4/200 | Train: Loss=1.0539, F1 Score=0.6720 | Val: Loss=0.8113, F1 Score=0.7019

[I 2025-11-12 11:31:11,839] Trial 28 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.4209005169548445, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 9.788051398199555e-05, 'weight_decay': 0.0002601894960770823, 'l1_lambda': 1.4183520860646808e-05, 'focal_gamma': 1.5, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 3.815402381903306}. Best is trial 1 with value: 0.9475612112569565.

Epoch   5/200 | Train: Loss=0.9952, F1 Score=0.6729 | Val: Loss=0.7479, F1 Score=0.7777
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.1212, F1 Score=0.6025 | Val: Loss=1.0505, F1 Score=0.6234
Epoch   2/200 | Train: Loss=1.1172, F1 Score=0.5557 | Val: Loss=1.0610, F1 Score=0.6119
Epoch   3/200 | Train: Loss=1.1019, F1 Score=0.5291 | Val: Loss=1.0616, F1 Score=0.6246
Epoch   4/200 | Train: Loss=1.1027, F1 Score=0.5160 | Val: Loss=1.0601, F1 Score=0.6782

[I 2025-11-12 11:31:31,694] Trial 29 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 32, 'num_layers': 3, 'dropout_rate': 0.4440455406316205, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 1.0836896888967934e-05, 'weight_decay': 6.360752076361516e-05, 'l1_lambda': 1.0600289225896938e-07, 'focal_gamma': 0.5, 'scheduler_patience': 7, 'scheduler_factor': 0.2, 'weight_max_norm': 4.524819968801535}. Best is trial 1 with value: 0.9475612112569565.
[I 2025-11-12 11:31:31,698] Trial 30 pruned.

Epoch   5/200 | Train: Loss=1.1004, F1 Score=0.5106 | Val: Loss=1.0540, F1 Score=0.6726
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.9491, F1 Score=0.6453 | Val: Loss=0.7768, F1 Score=0.7398
Epoch   2/200 | Train: Loss=0.6650, F1 Score=0.7724 | Val: Loss=0.6011, F1 Score=0.7890
Epoch   3/200 | Train: Loss=0.4773, F1 Score=0.8617 | Val: Loss=0.4239, F1 Score=0.8916
Epoch   4/200 | Train: Loss=0.4157, F1 Score=0.8799 | Val: Loss=0.5411, F1 Score=0.8287
Epoch   5/200 | Train: Loss=0.3559, F1 Score=0.8961 | Val: Loss=0.4061, F1 Score=0.8897
Epoch   6/200 | Train: Loss=0.3072, F1 Score=0.9011 | Val: Loss=0.3467, F1 Score=0.8900
Epoch   7/200 | Train: Loss=0.2539, F1 Score=0.9133 | Val: Loss=0.4148, F1 Score=0.8654
Epoch   8/200 | Train: Loss=0.2361, F1 Score=0.9171 | Val: Loss=0.4790, F1 Score=0.8564
Epoch   9/200 | Train: Loss=0.2128, F1 Score=0.9197 | Val: Loss=0.4320, F1 Score=0.8657
Epoch  10/200 | Train: Loss=0.1400, F1 Score=0.9428 | Val: Loss=0.3603, F1 Score=0.8763
Epoch  11/200 | Train: Loss=0.1284, F1 Score=0.9467 | Val: Loss=0.3591, F1 Score=0.8861

[I 2025-11-12 11:32:58,107] Trial 31 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 5, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.5947736274568757, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0002741031622612554, 'weight_decay': 4.24087816828101e-06, 'l1_lambda': 4.246879436647814e-07, 'focal_gamma': 0.0, 'scheduler_patience': 5, 'scheduler_factor': 0.1, 'weight_max_norm': 1.832421116861783}. Best is trial 1 with value: 0.9475612112569565.

Epoch  12/200 | Train: Loss=0.1222, F1 Score=0.9469 | Val: Loss=0.3576, F1 Score=0.8874
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0561, F1 Score=0.6365 | Val: Loss=0.8664, F1 Score=0.6968
Epoch   2/200 | Train: Loss=0.9114, F1 Score=0.6613 | Val: Loss=0.8688, F1 Score=0.5957
Epoch   3/200 | Train: Loss=0.8488, F1 Score=0.6842 | Val: Loss=0.7372, F1 Score=0.7683
Epoch   4/200 | Train: Loss=0.7350, F1 Score=0.7613 | Val: Loss=1.0559, F1 Score=0.5094
Epoch   5/200 | Train: Loss=0.6422, F1 Score=0.7945 | Val: Loss=0.5359, F1 Score=0.8701
Epoch   6/200 | Train: Loss=0.6076, F1 Score=0.8189 | Val: Loss=0.5167, F1 Score=0.8495

[I 2025-11-12 11:33:25,978] Trial 32 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.4987279492306937, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00018137423758444305, 'weight_decay': 0.00014449145568604674, 'l1_lambda': 8.29356362387304e-07, 'focal_gamma': 0.0, 'scheduler_patience': 5, 'scheduler_factor': 0.1, 'weight_max_norm': 5.42505400939106}. Best is trial 1 with value: 0.9475612112569565.

Epoch   7/200 | Train: Loss=0.5515, F1 Score=0.8265 | Val: Loss=0.5591, F1 Score=0.8056
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0327, F1 Score=0.6195 | Val: Loss=0.8931, F1 Score=0.6448
Epoch   2/200 | Train: Loss=0.8925, F1 Score=0.7067 | Val: Loss=0.7948, F1 Score=0.6576
Epoch   3/200 | Train: Loss=0.6926, F1 Score=0.8050 | Val: Loss=0.4726, F1 Score=0.8877
Epoch   4/200 | Train: Loss=0.6138, F1 Score=0.8325 | Val: Loss=0.4366, F1 Score=0.8912
Epoch   5/200 | Train: Loss=0.5337, F1 Score=0.8530 | Val: Loss=0.4188, F1 Score=0.8835
Epoch   6/200 | Train: Loss=0.4565, F1 Score=0.8703 | Val: Loss=0.4220, F1 Score=0.8640
Epoch   7/200 | Train: Loss=0.4164, F1 Score=0.8775 | Val: Loss=0.4994, F1 Score=0.8209
Epoch   8/200 | Train: Loss=0.3637, F1 Score=0.8940 | Val: Loss=0.3765, F1 Score=0.8459
Epoch   9/200 | Train: Loss=0.3484, F1 Score=0.8977 | Val: Loss=0.4570, F1 Score=0.8308
Epoch  10/200 | Train: Loss=0.2609, F1 Score=0.9183 | Val: Loss=0.3204, F1 Score=0.8910
Epoch  11/200 | Train: Loss=0.2235, F1 Score=0.9304 | Val: Loss=0.3071, F1 Score=0.8940
Epoch  12/200 | Train: Loss=0.2082, F1 Score=0.9340 | Val: Loss=0.3038, F1 Score=0.8951
Epoch  13/200 | Train: Loss=0.1951, F1 Score=0.9366 | Val: Loss=0.2838, F1 Score=0.9127
Epoch  14/200 | Train: Loss=0.1900, F1 Score=0.9377 | Val: Loss=0.2983, F1 Score=0.9110
Epoch  15/200 | Train: Loss=0.1795, F1 Score=0.9412 | Val: Loss=0.3021, F1 Score=0.8902
Epoch  16/200 | Train: Loss=0.1708, F1 Score=0.9427 | Val: Loss=0.3289, F1 Score=0.8886
Epoch  17/200 | Train: Loss=0.1698, F1 Score=0.9407 | Val: Loss=0.3050, F1 Score=0.9020
Epoch  18/200 | Train: Loss=0.1575, F1 Score=0.9458 | Val: Loss=0.3009, F1 Score=0.8916
Epoch  19/200 | Train: Loss=0.1521, F1 Score=0.9465 | Val: Loss=0.3040, F1 Score=0.8929
Epoch  20/200 | Train: Loss=0.1524, F1 Score=0.9446 | Val: Loss=0.2999, F1 Score=0.8977
Epoch  21/200 | Train: Loss=0.1460, F1 Score=0.9491 | Val: Loss=0.3025, F1 Score=0.8980
Epoch  22/200 | Train: Loss=0.1505, F1 Score=0.9472 | Val: Loss=0.3007, F1 Score=0.9030
Epoch  23/200 | Train: Loss=0.1479, F1 Score=0.9473 | Val: Loss=0.3075, F1 Score=0.8949
Epoch  24/200 | Train: Loss=0.1485, F1 Score=0.9450 | Val: Loss=0.3065, F1 Score=0.8953

[I 2025-11-12 11:35:04,318] Trial 33 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.6377526240966558, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0007751656193355932, 'weight_decay': 1.2632953534720728e-05, 'l1_lambda': 1.1435515784046434e-06, 'focal_gamma': 0.5, 'scheduler_patience': 4, 'scheduler_factor': 0.1, 'weight_max_norm': 0.7340310452789129}. Best is trial 1 with value: 0.9475612112569565.

Epoch  25/200 | Train: Loss=0.1445, F1 Score=0.9463 | Val: Loss=0.3051, F1 Score=0.8965
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0971, F1 Score=0.5291 | Val: Loss=1.0557, F1 Score=0.6835
Epoch   2/200 | Train: Loss=1.0401, F1 Score=0.6593 | Val: Loss=0.9657, F1 Score=0.6774
Epoch   3/200 | Train: Loss=0.9685, F1 Score=0.6396 | Val: Loss=0.9570, F1 Score=0.7077
Epoch   4/200 | Train: Loss=0.9320, F1 Score=0.6485 | Val: Loss=1.0466, F1 Score=0.5706

[I 2025-11-12 11:35:14,038] Trial 34 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 15, 'hidden_size': 32, 'num_layers': 3, 'dropout_rate': 0.4528453242217809, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0003945704014477122, 'weight_decay': 0.0006019417628548045, 'l1_lambda': 3.0247301082064003e-06, 'focal_gamma': 0.0, 'scheduler_patience': 5, 'scheduler_factor': 0.2, 'weight_max_norm': 1.7793373284179224}. Best is trial 1 with value: 0.9475612112569565.

Epoch   5/200 | Train: Loss=0.8925, F1 Score=0.6692 | Val: Loss=0.9260, F1 Score=0.6569
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0171, F1 Score=0.6240 | Val: Loss=0.8285, F1 Score=0.7520
Epoch   2/200 | Train: Loss=0.8788, F1 Score=0.6781 | Val: Loss=0.8179, F1 Score=0.6665
Epoch   3/200 | Train: Loss=0.7499, F1 Score=0.7497 | Val: Loss=0.5442, F1 Score=0.8282
Epoch   4/200 | Train: Loss=0.5929, F1 Score=0.8208 | Val: Loss=0.4330, F1 Score=0.8823
Epoch   5/200 | Train: Loss=0.5111, F1 Score=0.8444 | Val: Loss=0.4753, F1 Score=0.8724
Epoch   6/200 | Train: Loss=0.4801, F1 Score=0.8593 | Val: Loss=0.5465, F1 Score=0.8040
Epoch   7/200 | Train: Loss=0.4158, F1 Score=0.8794 | Val: Loss=0.5088, F1 Score=0.8868
Epoch   8/200 | Train: Loss=0.4175, F1 Score=0.8823 | Val: Loss=0.5374, F1 Score=0.7925
Epoch   9/200 | Train: Loss=0.3879, F1 Score=0.8884 | Val: Loss=0.4315, F1 Score=0.8806
Epoch  10/200 | Train: Loss=0.3607, F1 Score=0.8954 | Val: Loss=0.4569, F1 Score=0.8915
Epoch  11/200 | Train: Loss=0.3285, F1 Score=0.9045 | Val: Loss=0.3593, F1 Score=0.9032
Epoch  12/200 | Train: Loss=0.3170, F1 Score=0.9091 | Val: Loss=0.4383, F1 Score=0.8952
Epoch  13/200 | Train: Loss=0.3049, F1 Score=0.9039 | Val: Loss=0.3991, F1 Score=0.8715
Epoch  14/200 | Train: Loss=0.2791, F1 Score=0.9100 | Val: Loss=0.6460, F1 Score=0.7371
Epoch  15/200 | Train: Loss=0.2923, F1 Score=0.9084 | Val: Loss=0.3962, F1 Score=0.9054
Epoch  16/200 | Train: Loss=0.2543, F1 Score=0.9159 | Val: Loss=0.3445, F1 Score=0.9080
Epoch  17/200 | Train: Loss=0.2532, F1 Score=0.9122 | Val: Loss=0.7304, F1 Score=0.7578
Epoch  18/200 | Train: Loss=0.2495, F1 Score=0.9173 | Val: Loss=0.3120, F1 Score=0.9067
Epoch  19/200 | Train: Loss=0.2127, F1 Score=0.9173 | Val: Loss=0.3262, F1 Score=0.9367
Epoch  20/200 | Train: Loss=0.2003, F1 Score=0.9239 | Val: Loss=0.3147, F1 Score=0.9112
Epoch  21/200 | Train: Loss=0.1851, F1 Score=0.9269 | Val: Loss=0.6808, F1 Score=0.7156
Epoch  22/200 | Train: Loss=0.2011, F1 Score=0.9192 | Val: Loss=0.2614, F1 Score=0.9025
Epoch  23/200 | Train: Loss=0.1832, F1 Score=0.9250 | Val: Loss=0.2621, F1 Score=0.9261
Epoch  24/200 | Train: Loss=0.2174, F1 Score=0.9135 | Val: Loss=0.2848, F1 Score=0.9254
Epoch  25/200 | Train: Loss=0.1723, F1 Score=0.9302 | Val: Loss=0.2557, F1 Score=0.9337
Epoch  26/200 | Train: Loss=0.1588, F1 Score=0.9354 | Val: Loss=0.3122, F1 Score=0.9090
Epoch  27/200 | Train: Loss=0.1214, F1 Score=0.9474 | Val: Loss=0.2887, F1 Score=0.9074
Epoch  28/200 | Train: Loss=0.1081, F1 Score=0.9504 | Val: Loss=0.3120, F1 Score=0.9019
Epoch  29/200 | Train: Loss=0.1066, F1 Score=0.9521 | Val: Loss=0.3220, F1 Score=0.9039
Epoch  30/200 | Train: Loss=0.1063, F1 Score=0.9498 | Val: Loss=0.3310, F1 Score=0.9025
Epoch  31/200 | Train: Loss=0.1040, F1 Score=0.9555 | Val: Loss=0.3345, F1 Score=0.9026
Epoch  32/200 | Train: Loss=0.1001, F1 Score=0.9538 | Val: Loss=0.3486, F1 Score=0.8963
Epoch  33/200 | Train: Loss=0.1013, F1 Score=0.9538 | Val: Loss=0.3772, F1 Score=0.8902

[I 2025-11-12 11:37:03,462] Trial 35 finished with value: 0.9366702628884941 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.33142270229915083, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0002743405134194895, 'weight_decay': 9.74432695071814e-05, 'l1_lambda': 5.588330692974738e-07, 'focal_gamma': 1.0, 'scheduler_patience': 6, 'scheduler_factor': 0.1, 'weight_max_norm': 2.817028806749527}. Best is trial 1 with value: 0.9475612112569565.

Epoch  34/200 | Train: Loss=0.1006, F1 Score=0.9496 | Val: Loss=0.3502, F1 Score=0.9035
Early stopping triggered after 34 epochs.
Best model restored from epoch 19 with val_f1 0.9367
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0210, F1 Score=0.5973 | Val: Loss=0.8739, F1 Score=0.7091
Epoch   2/200 | Train: Loss=0.8805, F1 Score=0.6926 | Val: Loss=0.7053, F1 Score=0.8033
Epoch   3/200 | Train: Loss=0.7493, F1 Score=0.7643 | Val: Loss=0.5601, F1 Score=0.8569
Epoch   4/200 | Train: Loss=0.6328, F1 Score=0.8117 | Val: Loss=0.5078, F1 Score=0.8595
Epoch   5/200 | Train: Loss=0.5727, F1 Score=0.8286 | Val: Loss=0.4310, F1 Score=0.8841
Epoch   6/200 | Train: Loss=0.4950, F1 Score=0.8562 | Val: Loss=0.4973, F1 Score=0.8410
Epoch   7/200 | Train: Loss=0.4767, F1 Score=0.8591 | Val: Loss=0.5407, F1 Score=0.7869
Epoch   8/200 | Train: Loss=0.4269, F1 Score=0.8712 | Val: Loss=0.4905, F1 Score=0.8155
Epoch   9/200 | Train: Loss=0.4088, F1 Score=0.8801 | Val: Loss=0.4251, F1 Score=0.8915
Epoch  10/200 | Train: Loss=0.3749, F1 Score=0.8834 | Val: Loss=0.4098, F1 Score=0.8810

[I 2025-11-12 11:37:39,350] Trial 36 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.32972017682412325, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0002654021760402282, 'weight_decay': 0.00010096802253810902, 'l1_lambda': 5.350826810299416e-07, 'focal_gamma': 1.0, 'scheduler_patience': 6, 'scheduler_factor': 0.1, 'weight_max_norm': 2.7522198982768553}. Best is trial 1 with value: 0.9475612112569565.

Epoch  11/200 | Train: Loss=0.3556, F1 Score=0.8919 | Val: Loss=0.4052, F1 Score=0.8620
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0176, F1 Score=0.6238 | Val: Loss=0.8042, F1 Score=0.7467
Epoch   2/200 | Train: Loss=0.8615, F1 Score=0.7045 | Val: Loss=0.7356, F1 Score=0.7120
Epoch   3/200 | Train: Loss=0.7247, F1 Score=0.7751 | Val: Loss=0.6563, F1 Score=0.8019
Epoch   4/200 | Train: Loss=0.6857, F1 Score=0.7778 | Val: Loss=0.5340, F1 Score=0.8857
Epoch   5/200 | Train: Loss=0.5803, F1 Score=0.8160 | Val: Loss=0.4627, F1 Score=0.8707
Epoch   6/200 | Train: Loss=0.5265, F1 Score=0.8328 | Val: Loss=0.4205, F1 Score=0.9005
Epoch   7/200 | Train: Loss=0.4792, F1 Score=0.8565 | Val: Loss=0.4660, F1 Score=0.8338
Epoch   8/200 | Train: Loss=0.4523, F1 Score=0.8622 | Val: Loss=0.3993, F1 Score=0.8806
Epoch   9/200 | Train: Loss=0.4282, F1 Score=0.8718 | Val: Loss=0.4542, F1 Score=0.8860
Epoch  10/200 | Train: Loss=0.3688, F1 Score=0.8867 | Val: Loss=0.5484, F1 Score=0.8881
Epoch  11/200 | Train: Loss=0.3798, F1 Score=0.8761 | Val: Loss=0.3820, F1 Score=0.8786
Epoch  12/200 | Train: Loss=0.3432, F1 Score=0.8931 | Val: Loss=0.3239, F1 Score=0.9120
Epoch  13/200 | Train: Loss=0.2953, F1 Score=0.9101 | Val: Loss=0.5653, F1 Score=0.8121
Epoch  14/200 | Train: Loss=0.2880, F1 Score=0.9026 | Val: Loss=0.4153, F1 Score=0.8562
Epoch  15/200 | Train: Loss=0.2579, F1 Score=0.9112 | Val: Loss=0.4168, F1 Score=0.8825
Epoch  16/200 | Train: Loss=0.2463, F1 Score=0.9185 | Val: Loss=0.4450, F1 Score=0.8822
Epoch  17/200 | Train: Loss=0.2657, F1 Score=0.9146 | Val: Loss=0.4016, F1 Score=0.9013
Epoch  18/200 | Train: Loss=0.2160, F1 Score=0.9212 | Val: Loss=0.3827, F1 Score=0.8978
Epoch  19/200 | Train: Loss=0.2293, F1 Score=0.9156 | Val: Loss=0.4997, F1 Score=0.8392
Epoch  20/200 | Train: Loss=0.1995, F1 Score=0.9241 | Val: Loss=0.4412, F1 Score=0.8968
Epoch  21/200 | Train: Loss=0.1593, F1 Score=0.9388 | Val: Loss=0.3721, F1 Score=0.9100
Epoch  22/200 | Train: Loss=0.1612, F1 Score=0.9366 | Val: Loss=0.3611, F1 Score=0.9136
Epoch  23/200 | Train: Loss=0.1724, F1 Score=0.9346 | Val: Loss=0.4458, F1 Score=0.8530
Epoch  24/200 | Train: Loss=0.1425, F1 Score=0.9440 | Val: Loss=0.3714, F1 Score=0.9049

[I 2025-11-12 11:38:40,679] Trial 37 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.1582382677545262, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.0006009893992399913, 'weight_decay': 0.00033295810141273304, 'l1_lambda': 2.644162108943022e-06, 'focal_gamma': 2.0, 'scheduler_patience': 7, 'scheduler_factor': 0.5, 'weight_max_norm': 3.1133795247162084}. Best is trial 1 with value: 0.9475612112569565.

Epoch  25/200 | Train: Loss=0.1470, F1 Score=0.9413 | Val: Loss=0.3877, F1 Score=0.8944
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.9687, F1 Score=0.6232 | Val: Loss=0.8481, F1 Score=0.6827
Epoch   2/200 | Train: Loss=0.6736, F1 Score=0.7907 | Val: Loss=0.4161, F1 Score=0.8862
Epoch   3/200 | Train: Loss=0.5163, F1 Score=0.8437 | Val: Loss=0.4508, F1 Score=0.8543
Epoch   4/200 | Train: Loss=0.4633, F1 Score=0.8605 | Val: Loss=0.5519, F1 Score=0.7627
Epoch   5/200 | Train: Loss=0.3982, F1 Score=0.8718 | Val: Loss=0.3829, F1 Score=0.8859
Epoch   6/200 | Train: Loss=0.3562, F1 Score=0.8895 | Val: Loss=0.4467, F1 Score=0.8741
Epoch   7/200 | Train: Loss=0.2359, F1 Score=0.9297 | Val: Loss=0.3584, F1 Score=0.8819
Epoch   8/200 | Train: Loss=0.2161, F1 Score=0.9316 | Val: Loss=0.3286, F1 Score=0.9164
Epoch   9/200 | Train: Loss=0.1949, F1 Score=0.9334 | Val: Loss=0.3700, F1 Score=0.8815
Epoch  10/200 | Train: Loss=0.1787, F1 Score=0.9349 | Val: Loss=0.3481, F1 Score=0.8977
Epoch  11/200 | Train: Loss=0.1711, F1 Score=0.9336 | Val: Loss=0.3554, F1 Score=0.8957
Epoch  12/200 | Train: Loss=0.1535, F1 Score=0.9373 | Val: Loss=0.3494, F1 Score=0.9033
Epoch  13/200 | Train: Loss=0.1381, F1 Score=0.9421 | Val: Loss=0.3665, F1 Score=0.8935
Epoch  14/200 | Train: Loss=0.1319, F1 Score=0.9435 | Val: Loss=0.3592, F1 Score=0.9033
Epoch  15/200 | Train: Loss=0.1308, F1 Score=0.9448 | Val: Loss=0.3694, F1 Score=0.8929
Epoch  16/200 | Train: Loss=0.1277, F1 Score=0.9447 | Val: Loss=0.3551, F1 Score=0.8992
Epoch  17/200 | Train: Loss=0.1233, F1 Score=0.9477 | Val: Loss=0.3567, F1 Score=0.8972
Epoch  18/200 | Train: Loss=0.1218, F1 Score=0.9472 | Val: Loss=0.3593, F1 Score=0.8984
Epoch  19/200 | Train: Loss=0.1243, F1 Score=0.9467 | Val: Loss=0.3604, F1 Score=0.8979
Epoch  20/200 | Train: Loss=0.1210, F1 Score=0.9475 | Val: Loss=0.3619, F1 Score=0.8967
Epoch  21/200 | Train: Loss=0.1200, F1 Score=0.9476 | Val: Loss=0.3605, F1 Score=0.8983
Epoch  22/200 | Train: Loss=0.1228, F1 Score=0.9466 | Val: Loss=0.3605, F1 Score=0.8982

[I 2025-11-12 11:39:54,798] Trial 38 finished with value: 0.9163973147741653 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.10930720319698528, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 0.0007980017988999625, 'weight_decay': 0.0001874263527738079, 'l1_lambda': 2.887939111230451e-07, 'focal_gamma': 0.5, 'scheduler_patience': 3, 'scheduler_factor': 0.2, 'weight_max_norm': 3.4035272645482566}. Best is trial 1 with value: 0.9475612112569565.

Epoch  23/200 | Train: Loss=0.1194, F1 Score=0.9478 | Val: Loss=0.3608, F1 Score=0.8987
Early stopping triggered after 23 epochs.
Best model restored from epoch 8 with val_f1 0.9164
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0890, F1 Score=0.6542 | Val: Loss=0.8974, F1 Score=0.7706
Epoch   2/200 | Train: Loss=0.9561, F1 Score=0.6962 | Val: Loss=0.8014, F1 Score=0.7512
Epoch   3/200 | Train: Loss=0.8762, F1 Score=0.7015 | Val: Loss=0.8275, F1 Score=0.7042
Epoch   4/200 | Train: Loss=0.8203, F1 Score=0.7020 | Val: Loss=0.8753, F1 Score=0.6459

[I 2025-11-12 11:40:15,115] Trial 39 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 5, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.3559856458724074, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 0.00010095015975008, 'weight_decay': 3.185532010522359e-05, 'l1_lambda': 4.4082348417635876e-06, 'focal_gamma': 1.0, 'scheduler_patience': 6, 'scheduler_factor': 0.1, 'weight_max_norm': 2.8235019284505998}. Best is trial 1 with value: 0.9475612112569565.
[I 2025-11-12 11:40:15,120] Trial 40 pruned.

Epoch   5/200 | Train: Loss=0.7158, F1 Score=0.7514 | Val: Loss=0.6440, F1 Score=0.8169
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0268, F1 Score=0.6234 | Val: Loss=0.8172, F1 Score=0.7925
Epoch   2/200 | Train: Loss=0.9071, F1 Score=0.6710 | Val: Loss=0.9329, F1 Score=0.4941
Epoch   3/200 | Train: Loss=0.7748, F1 Score=0.7471 | Val: Loss=0.4986, F1 Score=0.8983
Epoch   4/200 | Train: Loss=0.5937, F1 Score=0.8274 | Val: Loss=0.5748, F1 Score=0.7874
Epoch   5/200 | Train: Loss=0.5190, F1 Score=0.8499 | Val: Loss=0.4314, F1 Score=0.8659
Epoch   6/200 | Train: Loss=0.4518, F1 Score=0.8660 | Val: Loss=0.6973, F1 Score=0.6902
Epoch   7/200 | Train: Loss=0.4104, F1 Score=0.8767 | Val: Loss=0.3547, F1 Score=0.8926
Epoch   8/200 | Train: Loss=0.3801, F1 Score=0.8863 | Val: Loss=0.4643, F1 Score=0.8266
Epoch   9/200 | Train: Loss=0.3341, F1 Score=0.8962 | Val: Loss=0.6059, F1 Score=0.7994
Epoch  10/200 | Train: Loss=0.2586, F1 Score=0.9188 | Val: Loss=0.3472, F1 Score=0.8871
Epoch  11/200 | Train: Loss=0.2321, F1 Score=0.9242 | Val: Loss=0.3436, F1 Score=0.9055
Epoch  12/200 | Train: Loss=0.2250, F1 Score=0.9281 | Val: Loss=0.3493, F1 Score=0.8721
Epoch  13/200 | Train: Loss=0.2185, F1 Score=0.9265 | Val: Loss=0.3687, F1 Score=0.8690
Epoch  14/200 | Train: Loss=0.2094, F1 Score=0.9307 | Val: Loss=0.3422, F1 Score=0.8809
Epoch  15/200 | Train: Loss=0.2050, F1 Score=0.9308 | Val: Loss=0.3652, F1 Score=0.8816
Epoch  16/200 | Train: Loss=0.2000, F1 Score=0.9321 | Val: Loss=0.3373, F1 Score=0.8859
Epoch  17/200 | Train: Loss=0.1946, F1 Score=0.9340 | Val: Loss=0.3413, F1 Score=0.8960
Epoch  18/200 | Train: Loss=0.1836, F1 Score=0.9384 | Val: Loss=0.3432, F1 Score=0.8878
Epoch  19/200 | Train: Loss=0.1860, F1 Score=0.9362 | Val: Loss=0.3422, F1 Score=0.8918
Epoch  20/200 | Train: Loss=0.1852, F1 Score=0.9364 | Val: Loss=0.3450, F1 Score=0.8869
Epoch  21/200 | Train: Loss=0.1842, F1 Score=0.9374 | Val: Loss=0.3461, F1 Score=0.8884
Epoch  22/200 | Train: Loss=0.1829, F1 Score=0.9374 | Val: Loss=0.3463, F1 Score=0.8882
Epoch  23/200 | Train: Loss=0.1835, F1 Score=0.9353 | Val: Loss=0.3425, F1 Score=0.8920

[I 2025-11-12 11:41:32,424] Trial 41 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.3938471576283413, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0003025217480402267, 'weight_decay': 7.946118159828912e-05, 'l1_lambda': 7.945925080648156e-07, 'focal_gamma': 0.0, 'scheduler_patience': 5, 'scheduler_factor': 0.1, 'weight_max_norm': 1.4527978404819553}. Best is trial 1 with value: 0.9475612112569565.

Epoch  24/200 | Train: Loss=0.1808, F1 Score=0.9376 | Val: Loss=0.3430, F1 Score=0.8913
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0628, F1 Score=0.6302 | Val: Loss=0.9231, F1 Score=0.6582
Epoch   2/200 | Train: Loss=0.9344, F1 Score=0.6727 | Val: Loss=0.8343, F1 Score=0.7010
Epoch   3/200 | Train: Loss=0.8865, F1 Score=0.6842 | Val: Loss=0.7775, F1 Score=0.7475
Epoch   4/200 | Train: Loss=0.8128, F1 Score=0.7094 | Val: Loss=0.7542, F1 Score=0.7348
Epoch   5/200 | Train: Loss=0.6497, F1 Score=0.8077 | Val: Loss=0.5197, F1 Score=0.8748
Epoch   6/200 | Train: Loss=0.5898, F1 Score=0.8404 | Val: Loss=0.4677, F1 Score=0.8812
Epoch   7/200 | Train: Loss=0.5277, F1 Score=0.8457 | Val: Loss=0.4238, F1 Score=0.8887
Epoch   8/200 | Train: Loss=0.4983, F1 Score=0.8519 | Val: Loss=0.5973, F1 Score=0.7921
Epoch   9/200 | Train: Loss=0.4704, F1 Score=0.8656 | Val: Loss=0.4991, F1 Score=0.8492
Epoch  10/200 | Train: Loss=0.4534, F1 Score=0.8722 | Val: Loss=0.4790, F1 Score=0.8483

[I 2025-11-12 11:42:03,445] Trial 42 finished with value: 0.0 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.4129130242536152, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'orthogonal', 'lr': 0.00019010045428392847, 'weight_decay': 0.00041659408455155223, 'l1_lambda': 1.5164796148372584e-06, 'focal_gamma': 0.5, 'scheduler_patience': 4, 'scheduler_factor': 0.1, 'weight_max_norm': 4.964771479783199}. Best is trial 1 with value: 0.9475612112569565.

Epoch  11/200 | Train: Loss=0.4507, F1 Score=0.8738 | Val: Loss=0.5895, F1 Score=0.7982
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0113, F1 Score=0.5922 | Val: Loss=0.8723, F1 Score=0.6199
Epoch   2/200 | Train: Loss=0.8393, F1 Score=0.6988 | Val: Loss=0.5402, F1 Score=0.8704
Epoch   3/200 | Train: Loss=0.6241, F1 Score=0.8160 | Val: Loss=0.6186, F1 Score=0.7358
Epoch   4/200 | Train: Loss=0.5215, F1 Score=0.8441 | Val: Loss=0.4874, F1 Score=0.8409
Epoch   5/200 | Train: Loss=0.4380, F1 Score=0.8684 | Val: Loss=0.4083, F1 Score=0.8902
Epoch   6/200 | Train: Loss=0.3661, F1 Score=0.8899 | Val: Loss=0.4128, F1 Score=0.9046
Epoch   7/200 | Train: Loss=0.3331, F1 Score=0.8930 | Val: Loss=0.5214, F1 Score=0.7525
Epoch   8/200 | Train: Loss=0.3063, F1 Score=0.8996 | Val: Loss=0.4982, F1 Score=0.8481
Epoch   9/200 | Train: Loss=0.3037, F1 Score=0.9008 | Val: Loss=0.4075, F1 Score=0.8596
Epoch  10/200 | Train: Loss=0.2855, F1 Score=0.9027 | Val: Loss=0.2714, F1 Score=0.9241
Epoch  11/200 | Train: Loss=0.2177, F1 Score=0.9188 | Val: Loss=0.3274, F1 Score=0.9096
Epoch  12/200 | Train: Loss=0.1986, F1 Score=0.9242 | Val: Loss=0.3162, F1 Score=0.8955
Epoch  13/200 | Train: Loss=0.1983, F1 Score=0.9188 | Val: Loss=0.4002, F1 Score=0.8396
Epoch  14/200 | Train: Loss=0.2007, F1 Score=0.9175 | Val: Loss=0.3961, F1 Score=0.8925
Epoch  15/200 | Train: Loss=0.1203, F1 Score=0.9465 | Val: Loss=0.2846, F1 Score=0.9142
Epoch  16/200 | Train: Loss=0.1035, F1 Score=0.9530 | Val: Loss=0.2808, F1 Score=0.9207
Epoch  17/200 | Train: Loss=0.1008, F1 Score=0.9549 | Val: Loss=0.2737, F1 Score=0.9214
Epoch  18/200 | Train: Loss=0.0973, F1 Score=0.9561 | Val: Loss=0.2862, F1 Score=0.9117
Epoch  19/200 | Train: Loss=0.0896, F1 Score=0.9593 | Val: Loss=0.2890, F1 Score=0.9056
Epoch  20/200 | Train: Loss=0.0910, F1 Score=0.9580 | Val: Loss=0.2887, F1 Score=0.9045
Epoch  21/200 | Train: Loss=0.0898, F1 Score=0.9569 | Val: Loss=0.2842, F1 Score=0.9118
Epoch  22/200 | Train: Loss=0.0907, F1 Score=0.9586 | Val: Loss=0.2847, F1 Score=0.9109
Epoch  23/200 | Train: Loss=0.0892, F1 Score=0.9593 | Val: Loss=0.2851, F1 Score=0.9109
Epoch  24/200 | Train: Loss=0.0883, F1 Score=0.9583 | Val: Loss=0.2849, F1 Score=0.9109

[I 2025-11-12 11:43:41,465] Trial 43 finished with value: 0.9240991900765788 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.26566050587744305, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0004356150829909807, 'weight_decay': 1.8199678317818195e-06, 'l1_lambda': 1.8289299072777114e-07, 'focal_gamma': 1.0, 'scheduler_patience': 3, 'scheduler_factor': 0.1, 'weight_max_norm': 4.1196590775381585}. Best is trial 1 with value: 0.9475612112569565.

Epoch  25/200 | Train: Loss=0.0884, F1 Score=0.9579 | Val: Loss=0.2853, F1 Score=0.9105
Early stopping triggered after 25 epochs.
Best model restored from epoch 10 with val_f1 0.9241
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0005, F1 Score=0.6096 | Val: Loss=0.8213, F1 Score=0.6974
Epoch   2/200 | Train: Loss=0.8219, F1 Score=0.7345 | Val: Loss=0.5526, F1 Score=0.8238
Epoch   3/200 | Train: Loss=0.6130, F1 Score=0.8285 | Val: Loss=0.5876, F1 Score=0.8409
Epoch   4/200 | Train: Loss=0.5366, F1 Score=0.8481 | Val: Loss=0.5335, F1 Score=0.8328
Epoch   5/200 | Train: Loss=0.4642, F1 Score=0.8652 | Val: Loss=0.3552, F1 Score=0.9108
Epoch   6/200 | Train: Loss=0.3958, F1 Score=0.8761 | Val: Loss=0.5988, F1 Score=0.6938
Epoch   7/200 | Train: Loss=0.3093, F1 Score=0.8980 | Val: Loss=0.4226, F1 Score=0.8198
Epoch   8/200 | Train: Loss=0.3114, F1 Score=0.8910 | Val: Loss=0.3697, F1 Score=0.9310
Epoch   9/200 | Train: Loss=0.2816, F1 Score=0.9046 | Val: Loss=0.3482, F1 Score=0.8730
Epoch  10/200 | Train: Loss=0.2451, F1 Score=0.9106 | Val: Loss=0.3124, F1 Score=0.9153
Epoch  11/200 | Train: Loss=0.2040, F1 Score=0.9247 | Val: Loss=0.5633, F1 Score=0.8359
Epoch  12/200 | Train: Loss=0.1970, F1 Score=0.9225 | Val: Loss=0.4079, F1 Score=0.9189
Epoch  13/200 | Train: Loss=0.1437, F1 Score=0.9435 | Val: Loss=0.2900, F1 Score=0.9164
Epoch  14/200 | Train: Loss=0.1185, F1 Score=0.9508 | Val: Loss=0.2875, F1 Score=0.9163
Epoch  15/200 | Train: Loss=0.1109, F1 Score=0.9524 | Val: Loss=0.2838, F1 Score=0.9254
Epoch  16/200 | Train: Loss=0.1055, F1 Score=0.9541 | Val: Loss=0.3053, F1 Score=0.9098
Epoch  17/200 | Train: Loss=0.0990, F1 Score=0.9548 | Val: Loss=0.3006, F1 Score=0.9122
Epoch  18/200 | Train: Loss=0.0970, F1 Score=0.9570 | Val: Loss=0.2931, F1 Score=0.9184
Epoch  19/200 | Train: Loss=0.0956, F1 Score=0.9585 | Val: Loss=0.2939, F1 Score=0.9167
Epoch  20/200 | Train: Loss=0.0962, F1 Score=0.9584 | Val: Loss=0.2946, F1 Score=0.9161
Epoch  21/200 | Train: Loss=0.0956, F1 Score=0.9588 | Val: Loss=0.2940, F1 Score=0.9171
Epoch  22/200 | Train: Loss=0.0939, F1 Score=0.9576 | Val: Loss=0.2934, F1 Score=0.9175

[I 2025-11-12 11:45:11,931] Trial 44 finished with value: 0.9310441690491166 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.25626440748662127, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.00046914671070935246, 'weight_decay': 1.8980238933778934e-06, 'l1_lambda': 1.35837340007305e-07, 'focal_gamma': 2.5, 'scheduler_patience': 3, 'scheduler_factor': 0.1, 'weight_max_norm': 4.315793723934009}. Best is trial 1 with value: 0.9475612112569565.

Epoch  23/200 | Train: Loss=0.0947, F1 Score=0.9574 | Val: Loss=0.2929, F1 Score=0.9175
Early stopping triggered after 23 epochs.
Best model restored from epoch 8 with val_f1 0.9310
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.9876, F1 Score=0.6259 | Val: Loss=0.8771, F1 Score=0.5915
Epoch   2/200 | Train: Loss=0.7685, F1 Score=0.7471 | Val: Loss=0.5399, F1 Score=0.8798
Epoch   3/200 | Train: Loss=0.5606, F1 Score=0.8388 | Val: Loss=0.5635, F1 Score=0.7718
Epoch   4/200 | Train: Loss=0.4979, F1 Score=0.8492 | Val: Loss=0.4024, F1 Score=0.9142
Epoch   5/200 | Train: Loss=0.3906, F1 Score=0.8835 | Val: Loss=0.3736, F1 Score=0.8647
Epoch   6/200 | Train: Loss=0.3286, F1 Score=0.8983 | Val: Loss=0.3159, F1 Score=0.8950
Epoch   7/200 | Train: Loss=0.2729, F1 Score=0.9025 | Val: Loss=0.4011, F1 Score=0.8318
Epoch   8/200 | Train: Loss=0.2584, F1 Score=0.9035 | Val: Loss=0.3634, F1 Score=0.9063
Epoch   9/200 | Train: Loss=0.1738, F1 Score=0.9366 | Val: Loss=0.2760, F1 Score=0.8950
Epoch  10/200 | Train: Loss=0.1412, F1 Score=0.9413 | Val: Loss=0.2712, F1 Score=0.9037
Epoch  11/200 | Train: Loss=0.1320, F1 Score=0.9440 | Val: Loss=0.2851, F1 Score=0.9031
Epoch  12/200 | Train: Loss=0.1262, F1 Score=0.9442 | Val: Loss=0.2887, F1 Score=0.9052
Epoch  13/200 | Train: Loss=0.1204, F1 Score=0.9457 | Val: Loss=0.2893, F1 Score=0.9023
Epoch  14/200 | Train: Loss=0.1179, F1 Score=0.9451 | Val: Loss=0.2910, F1 Score=0.9022
Epoch  15/200 | Train: Loss=0.1179, F1 Score=0.9454 | Val: Loss=0.2896, F1 Score=0.9021
Epoch  16/200 | Train: Loss=0.1162, F1 Score=0.9458 | Val: Loss=0.2884, F1 Score=0.9021
Epoch  17/200 | Train: Loss=0.1154, F1 Score=0.9470 | Val: Loss=0.2890, F1 Score=0.9013
Epoch  18/200 | Train: Loss=0.1133, F1 Score=0.9472 | Val: Loss=0.2893, F1 Score=0.9013

[I 2025-11-12 11:46:12,888] Trial 45 finished with value: 0.9142071799812168 and parameters: {'WINDOW': 20, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.26843401373378833, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'xavier_uniform', 'lr': 0.000441444964188507, 'weight_decay': 1.7332352672700478e-06, 'l1_lambda': 1.2787054535719574e-07, 'focal_gamma': 3.0, 'scheduler_patience': 3, 'scheduler_factor': 0.1, 'weight_max_norm': 4.21492439433632}. Best is trial 1 with value: 0.9475612112569565.

Epoch  19/200 | Train: Loss=0.1150, F1 Score=0.9459 | Val: Loss=0.2895, F1 Score=0.9013
Early stopping triggered after 19 epochs.
Best model restored from epoch 4 with val_f1 0.9142
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.9922, F1 Score=0.6307 | Val: Loss=0.8183, F1 Score=0.7276
Epoch   2/200 | Train: Loss=0.8176, F1 Score=0.7158 | Val: Loss=0.5971, F1 Score=0.8224
Epoch   3/200 | Train: Loss=0.6539, F1 Score=0.7991 | Val: Loss=0.5118, F1 Score=0.8188
Epoch   4/200 | Train: Loss=0.5433, F1 Score=0.8400 | Val: Loss=0.3800, F1 Score=0.9121
Epoch   5/200 | Train: Loss=0.4458, F1 Score=0.8637 | Val: Loss=0.5117, F1 Score=0.8674
Epoch   6/200 | Train: Loss=0.3867, F1 Score=0.8842 | Val: Loss=0.2863, F1 Score=0.9210
Epoch   7/200 | Train: Loss=0.3164, F1 Score=0.8928 | Val: Loss=0.4401, F1 Score=0.8597
Epoch   8/200 | Train: Loss=0.2504, F1 Score=0.9092 | Val: Loss=0.3443, F1 Score=0.8858
Epoch   9/200 | Train: Loss=0.2501, F1 Score=0.9079 | Val: Loss=0.3244, F1 Score=0.9001
Epoch  10/200 | Train: Loss=0.1743, F1 Score=0.9338 | Val: Loss=0.3275, F1 Score=0.9040
Epoch  11/200 | Train: Loss=0.1107, F1 Score=0.9511 | Val: Loss=0.2953, F1 Score=0.9176
Epoch  12/200 | Train: Loss=0.0987, F1 Score=0.9575 | Val: Loss=0.2999, F1 Score=0.9172
Epoch  13/200 | Train: Loss=0.0925, F1 Score=0.9613 | Val: Loss=0.2992, F1 Score=0.9166
Epoch  14/200 | Train: Loss=0.0860, F1 Score=0.9604 | Val: Loss=0.2992, F1 Score=0.9306
Epoch  15/200 | Train: Loss=0.0829, F1 Score=0.9668 | Val: Loss=0.3125, F1 Score=0.9177
Epoch  16/200 | Train: Loss=0.0782, F1 Score=0.9655 | Val: Loss=0.3196, F1 Score=0.9183
Epoch  17/200 | Train: Loss=0.0794, F1 Score=0.9652 | Val: Loss=0.3250, F1 Score=0.9229
Epoch  18/200 | Train: Loss=0.0684, F1 Score=0.9709 | Val: Loss=0.3098, F1 Score=0.9220
Epoch  19/200 | Train: Loss=0.0656, F1 Score=0.9689 | Val: Loss=0.3207, F1 Score=0.9249
Epoch  20/200 | Train: Loss=0.0629, F1 Score=0.9727 | Val: Loss=0.3201, F1 Score=0.9281
Epoch  21/200 | Train: Loss=0.0626, F1 Score=0.9745 | Val: Loss=0.3208, F1 Score=0.9271
Epoch  22/200 | Train: Loss=0.0609, F1 Score=0.9749 | Val: Loss=0.3208, F1 Score=0.9293
Epoch  23/200 | Train: Loss=0.0612, F1 Score=0.9766 | Val: Loss=0.3207, F1 Score=0.9295
Epoch  24/200 | Train: Loss=0.0606, F1 Score=0.9754 | Val: Loss=0.3208, F1 Score=0.9290
Epoch  25/200 | Train: Loss=0.0601, F1 Score=0.9762 | Val: Loss=0.3208, F1 Score=0.9290
Epoch  26/200 | Train: Loss=0.0611, F1 Score=0.9761 | Val: Loss=0.3210, F1 Score=0.9290
Epoch  27/200 | Train: Loss=0.0592, F1 Score=0.9755 | Val: Loss=0.3210, F1 Score=0.9290
Epoch  28/200 | Train: Loss=0.0606, F1 Score=0.9761 | Val: Loss=0.3210, F1 Score=0.9290

[I 2025-11-12 11:47:54,512] Trial 46 finished with value: 0.9305588387662858 and parameters: {'WINDOW': 40, 'STRIDE': 10, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.2044170686329254, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0005379792156501612, 'weight_decay': 2.0152873174718444e-06, 'l1_lambda': 1.932045271624181e-07, 'focal_gamma': 3.0, 'scheduler_patience': 3, 'scheduler_factor': 0.1, 'weight_max_norm': 3.8237021632843895}. Best is trial 1 with value: 0.9475612112569565.

Epoch  29/200 | Train: Loss=0.0598, F1 Score=0.9756 | Val: Loss=0.3210, F1 Score=0.9290
Early stopping triggered after 29 epochs.
Best model restored from epoch 14 with val_f1 0.9306
Training 200 epochs...
Epoch   1/200 | Train: Loss=1.0957, F1 Score=0.6799 | Val: Loss=1.0585, F1 Score=0.5961
Epoch   2/200 | Train: Loss=1.0843, F1 Score=0.6242 | Val: Loss=1.0611, F1 Score=0.5528
Epoch   3/200 | Train: Loss=1.0797, F1 Score=0.5937 | Val: Loss=1.0600, F1 Score=0.5518
Epoch   4/200 | Train: Loss=1.0765, F1 Score=0.5761 | Val: Loss=1.0545, F1 Score=0.5650

[I 2025-11-12 11:48:03,542] Trial 47 finished with value: 0.0 and parameters: {'WINDOW': 40, 'STRIDE': 15, 'hidden_size': 32, 'num_layers': 1, 'dropout_rate': 0.16439814951207488, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'kaiming_normal', 'lr': 3.86003690650633e-05, 'weight_decay': 3.674921038725019e-06, 'l1_lambda': 2.0461437515838094e-07, 'focal_gamma': 3.0, 'scheduler_patience': 3, 'scheduler_factor': 0.1, 'weight_max_norm': 3.872655520874504}. Best is trial 1 with value: 0.9475612112569565.

Epoch   5/200 | Train: Loss=1.0721, F1 Score=0.5796 | Val: Loss=1.0525, F1 Score=0.5708
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.9261, F1 Score=0.6654 | Val: Loss=0.6575, F1 Score=0.8214
Epoch   2/200 | Train: Loss=0.5970, F1 Score=0.8255 | Val: Loss=0.3968, F1 Score=0.9083
Epoch   3/200 | Train: Loss=0.4684, F1 Score=0.8597 | Val: Loss=0.4492, F1 Score=0.8856
Epoch   4/200 | Train: Loss=0.3610, F1 Score=0.8867 | Val: Loss=0.3287, F1 Score=0.8968
Epoch   5/200 | Train: Loss=0.3105, F1 Score=0.9033 | Val: Loss=0.2332, F1 Score=0.9187
Epoch   6/200 | Train: Loss=0.2438, F1 Score=0.9147 | Val: Loss=0.2361, F1 Score=0.9263
Epoch   7/200 | Train: Loss=0.2180, F1 Score=0.9225 | Val: Loss=0.2658, F1 Score=0.8944
Epoch   8/200 | Train: Loss=0.1730, F1 Score=0.9300 | Val: Loss=0.7650, F1 Score=0.8067
Epoch   9/200 | Train: Loss=0.1671, F1 Score=0.9374 | Val: Loss=0.2566, F1 Score=0.9016
Epoch  10/200 | Train: Loss=0.1498, F1 Score=0.9411 | Val: Loss=0.1991, F1 Score=0.9297
Epoch  11/200 | Train: Loss=0.1129, F1 Score=0.9524 | Val: Loss=0.1951, F1 Score=0.9285
Epoch  12/200 | Train: Loss=0.1117, F1 Score=0.9531 | Val: Loss=0.2859, F1 Score=0.9411
Epoch  13/200 | Train: Loss=0.0963, F1 Score=0.9601 | Val: Loss=0.2900, F1 Score=0.9110
Epoch  14/200 | Train: Loss=0.0879, F1 Score=0.9609 | Val: Loss=0.3773, F1 Score=0.8886
Epoch  15/200 | Train: Loss=0.0883, F1 Score=0.9601 | Val: Loss=0.3086, F1 Score=0.9210
Epoch  16/200 | Train: Loss=0.1016, F1 Score=0.9616 | Val: Loss=0.2424, F1 Score=0.9128
Epoch  17/200 | Train: Loss=0.0463, F1 Score=0.9797 | Val: Loss=0.1941, F1 Score=0.9325
Epoch  18/200 | Train: Loss=0.0357, F1 Score=0.9845 | Val: Loss=0.1822, F1 Score=0.9481
Epoch  19/200 | Train: Loss=0.0311, F1 Score=0.9877 | Val: Loss=0.1936, F1 Score=0.9433
Epoch  20/200 | Train: Loss=0.0285, F1 Score=0.9883 | Val: Loss=0.1868, F1 Score=0.9484
Epoch  21/200 | Train: Loss=0.0263, F1 Score=0.9897 | Val: Loss=0.1883, F1 Score=0.9554
Epoch  22/200 | Train: Loss=0.0292, F1 Score=0.9882 | Val: Loss=0.1960, F1 Score=0.9417
Epoch  23/200 | Train: Loss=0.0228, F1 Score=0.9912 | Val: Loss=0.1993, F1 Score=0.9532
Epoch  24/200 | Train: Loss=0.0214, F1 Score=0.9924 | Val: Loss=0.2110, F1 Score=0.9443
Epoch  25/200 | Train: Loss=0.0253, F1 Score=0.9890 | Val: Loss=0.1960, F1 Score=0.9526
Epoch  26/200 | Train: Loss=0.0196, F1 Score=0.9924 | Val: Loss=0.1972, F1 Score=0.9522
Epoch  27/200 | Train: Loss=0.0182, F1 Score=0.9929 | Val: Loss=0.1986, F1 Score=0.9519
Epoch  28/200 | Train: Loss=0.0176, F1 Score=0.9927 | Val: Loss=0.1999, F1 Score=0.9527
Epoch  29/200 | Train: Loss=0.0174, F1 Score=0.9936 | Val: Loss=0.2010, F1 Score=0.9510
Epoch  30/200 | Train: Loss=0.0168, F1 Score=0.9937 | Val: Loss=0.2010, F1 Score=0.9513
Epoch  31/200 | Train: Loss=0.0165, F1 Score=0.9939 | Val: Loss=0.2005, F1 Score=0.9519
Epoch  32/200 | Train: Loss=0.0169, F1 Score=0.9941 | Val: Loss=0.2002, F1 Score=0.9519
Epoch  33/200 | Train: Loss=0.0166, F1 Score=0.9938 | Val: Loss=0.2002, F1 Score=0.9519
Epoch  34/200 | Train: Loss=0.0167, F1 Score=0.9939 | Val: Loss=0.2002, F1 Score=0.9519
Epoch  35/200 | Train: Loss=0.0164, F1 Score=0.9941 | Val: Loss=0.2002, F1 Score=0.9519

[I 2025-11-12 11:51:07,558] Trial 48 finished with value: 0.9554406912323543 and parameters: {'WINDOW': 40, 'STRIDE': 5, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.2138414584361557, 'rnn_type': 'GRU', 'bidirectional': True, 'init_scheme': 'orthogonal', 'lr': 0.0005523476931659252, 'weight_decay': 2.7230560823050085e-06, 'l1_lambda': 1.5004159529243442e-07, 'focal_gamma': 2.0, 'scheduler_patience': 3, 'scheduler_factor': 0.1, 'weight_max_norm': 3.7286597477852714}. Best is trial 48 with value: 0.9554406912323543.

Epoch  36/200 | Train: Loss=0.0168, F1 Score=0.9942 | Val: Loss=0.2002, F1 Score=0.9519
Early stopping triggered after 36 epochs.
Best model restored from epoch 21 with val_f1 0.9554
Training 200 epochs...
Epoch   1/200 | Train: Loss=0.9249, F1 Score=0.6557 | Val: Loss=0.5233, F1 Score=0.8562
Epoch   2/200 | Train: Loss=0.6166, F1 Score=0.8183 | Val: Loss=0.7096, F1 Score=0.6892
Epoch   3/200 | Train: Loss=0.4293, F1 Score=0.8666 | Val: Loss=0.6040, F1 Score=0.7897
Epoch   4/200 | Train: Loss=0.3530, F1 Score=0.8904 | Val: Loss=0.3525, F1 Score=0.9133
Epoch   5/200 | Train: Loss=0.2895, F1 Score=0.9054 | Val: Loss=0.3420, F1 Score=0.8795
Epoch   6/200 | Train: Loss=0.2628, F1 Score=0.9062 | Val: Loss=0.3421, F1 Score=0.8992
Epoch   7/200 | Train: Loss=0.1934, F1 Score=0.9307 | Val: Loss=0.3834, F1 Score=0.8926
Epoch   8/200 | Train: Loss=0.1890, F1 Score=0.9328 | Val: Loss=0.2869, F1 Score=0.9375
Epoch   9/200 | Train: Loss=0.1504, F1 Score=0.9420 | Val: Loss=0.3028, F1 Score=0.9268
Epoch  10/200 | Train: Loss=0.1301, F1 Score=0.9476 | Val: Loss=0.2541, F1 Score=0.9283
Epoch  11/200 | Train: Loss=0.1159, F1 Score=0.9515 | Val: Loss=0.3235, F1 Score=0.9114
Epoch  12/200 | Train: Loss=0.0959, F1 Score=0.9559 | Val: Loss=0.3066, F1 Score=0.9112
Epoch  13/200 | Train: Loss=0.1123, F1 Score=0.9515 | Val: Loss=0.2614, F1 Score=0.9194
Epoch  14/200 | Train: Loss=0.1001, F1 Score=0.9567 | Val: Loss=0.2948, F1 Score=0.9372
Epoch  15/200 | Train: Loss=0.0686, F1 Score=0.9685 | Val: Loss=0.3033, F1 Score=0.9488
Epoch  16/200 | Train: Loss=0.1167, F1 Score=0.9600 | Val: Loss=0.2073, F1 Score=0.9404
Epoch  17/200 | Train: Loss=0.0645, F1 Score=0.9659 | Val: Loss=0.2437, F1 Score=0.9349
Epoch  18/200 | Train: Loss=0.1331, F1 Score=0.9511 | Val: Loss=0.1997, F1 Score=0.9473
Epoch  19/200 | Train: Loss=0.0772, F1 Score=0.9644 | Val: Loss=0.2444, F1 Score=0.9419
Epoch  20/200 | Train: Loss=0.0691, F1 Score=0.9697 | Val: Loss=0.2351, F1 Score=0.9280
Epoch  21/200 | Train: Loss=0.0638, F1 Score=0.9680 | Val: Loss=0.2287, F1 Score=0.9357
Epoch  22/200 | Train: Loss=0.0887, F1 Score=0.9663 | Val: Loss=0.3028, F1 Score=0.9276
Epoch  23/200 | Train: Loss=0.0494, F1 Score=0.9733 | Val: Loss=0.2825, F1 Score=0.9215
Epoch  24/200 | Train: Loss=0.0804, F1 Score=0.9644 | Val: Loss=0.2543, F1 Score=0.9196
Epoch  25/200 | Train: Loss=0.0319, F1 Score=0.9839 | Val: Loss=0.2118, F1 Score=0.9363
Epoch  26/200 | Train: Loss=0.0267, F1 Score=0.9867 | Val: Loss=0.2021, F1 Score=0.9466
Epoch  27/200 | Train: Loss=0.0242, F1 Score=0.9886 | Val: Loss=0.2042, F1 Score=0.9450
Epoch  28/200 | Train: Loss=0.0230, F1 Score=0.9894 | Val: Loss=0.2284, F1 Score=0.9285
Epoch  29/200 | Train: Loss=0.0214, F1 Score=0.9890 | Val: Loss=0.2068, F1 Score=0.9469
Epoch  30/200 | Train: Loss=0.0215, F1 Score=0.9894 | Val: Loss=0.2082, F1 Score=0.9490
Epoch  31/200 | Train: Loss=0.0214, F1 Score=0.9893 | Val: Loss=0.2284, F1 Score=0.9410
Epoch  32/200 | Train: Loss=0.0207, F1 Score=0.9897 | Val: Loss=0.2139, F1 Score=0.9507
Epoch  33/200 | Train: Loss=0.0166, F1 Score=0.9933 | Val: Loss=0.2593, F1 Score=0.9264
Epoch  34/200 | Train: Loss=0.0182, F1 Score=0.9920 | Val: Loss=0.2401, F1 Score=0.9429
Epoch  35/200 | Train: Loss=0.0150, F1 Score=0.9934 | Val: Loss=0.2771, F1 Score=0.9280
Epoch  36/200 | Train: Loss=0.0170, F1 Score=0.9929 | Val: Loss=0.2438, F1 Score=0.9418
Epoch  37/200 | Train: Loss=0.0144, F1 Score=0.9936 | Val: Loss=0.2669, F1 Score=0.9417
Epoch  38/200 | Train: Loss=0.0178, F1 Score=0.9917 | Val: Loss=0.2342, F1 Score=0.9518
Epoch  39/200 | Train: Loss=0.0115, F1 Score=0.9956 | Val: Loss=0.2475, F1 Score=0.9504
Epoch  40/200 | Train: Loss=0.0121, F1 Score=0.9948 | Val: Loss=0.2526, F1 Score=0.9530
Epoch  41/200 | Train: Loss=0.0112, F1 Score=0.9953 | Val: Loss=0.2879, F1 Score=0.9432
Epoch  42/200 | Train: Loss=0.0137, F1 Score=0.9939 | Val: Loss=0.2409, F1 Score=0.9528
Epoch  43/200 | Train: Loss=0.0125, F1 Score=0.9947 | Val: Loss=0.2552, F1 Score=0.9523
Epoch  44/200 | Train: Loss=0.0099, F1 Score=0.9965 | Val: Loss=0.2915, F1 Score=0.9468
Epoch  45/200 | Train: Loss=0.0086, F1 Score=0.9971 | Val: Loss=0.2907, F1 Score=0.9375
Epoch  46/200 | Train: Loss=0.0086, F1 Score=0.9973 | Val: Loss=0.2790, F1 Score=0.9540
Epoch  47/200 | Train: Loss=0.0125, F1 Score=0.9950 | Val: Loss=0.2618, F1 Score=0.9528
Epoch  48/200 | Train: Loss=0.0078, F1 Score=0.9972 | Val: Loss=0.2530, F1 Score=0.9574
Epoch  49/200 | Train: Loss=0.0155, F1 Score=0.9948 | Val: Loss=0.2476, F1 Score=0.9568
Epoch  50/200 | Train: Loss=0.0075, F1 Score=0.9981 | Val: Loss=0.2969, F1 Score=0.9516
Epoch  51/200 | Train: Loss=0.0093, F1 Score=0.9974 | Val: Loss=0.3222, F1 Score=0.9469
Epoch  52/200 | Train: Loss=0.0127, F1 Score=0.9950 | Val: Loss=0.2804, F1 Score=0.9466
Epoch  53/200 | Train: Loss=0.0090, F1 Score=0.9967 | Val: Loss=0.2909, F1 Score=0.9548
Epoch  54/200 | Train: Loss=0.0167, F1 Score=0.9955 | Val: Loss=0.2706, F1 Score=0.9517
Epoch  55/200 | Train: Loss=0.0124, F1 Score=0.9945 | Val: Loss=0.2783, F1 Score=0.9510
Epoch  56/200 | Train: Loss=0.0076, F1 Score=0.9981 | Val: Loss=0.2738, F1 Score=0.9519
Epoch  57/200 | Train: Loss=0.0072, F1 Score=0.9980 | Val: Loss=0.2740, F1 Score=0.9599
Epoch  58/200 | Train: Loss=0.0091, F1 Score=0.9971 | Val: Loss=0.2865, F1 Score=0.9550
Epoch  59/200 | Train: Loss=0.0063, F1 Score=0.9989 | Val: Loss=0.2977, F1 Score=0.9534
Epoch  60/200 | Train: Loss=0.0065, F1 Score=0.9986 | Val: Loss=0.2980, F1 Score=0.9535
Epoch  61/200 | Train: Loss=0.0111, F1 Score=0.9965 | Val: Loss=0.3003, F1 Score=0.9520
Epoch  62/200 | Train: Loss=0.0068, F1 Score=0.9980 | Val: Loss=0.2931, F1 Score=0.9556
Epoch  63/200 | Train: Loss=0.0114, F1 Score=0.9966 | Val: Loss=0.2876, F1 Score=0.9527
Epoch  64/200 | Train: Loss=0.0102, F1 Score=0.9965 | Val: Loss=0.3012, F1 Score=0.9541
Epoch  65/200 | Train: Loss=0.0059, F1 Score=0.9989 | Val: Loss=0.3040, F1 Score=0.9517
Epoch  66/200 | Train: Loss=0.0098, F1 Score=0.9967 | Val: Loss=0.3342, F1 Score=0.9387
Epoch  67/200 | Train: Loss=0.0134, F1 Score=0.9926 | Val: Loss=0.3298, F1 Score=0.9468
Epoch  68/200 | Train: Loss=0.0103, F1 Score=0.9959 | Val: Loss=0.3244, F1 Score=0.9470
Epoch  69/200 | Train: Loss=0.0078, F1 Score=0.9978 | Val: Loss=0.3199, F1 Score=0.9461
Epoch  70/200 | Train: Loss=0.0060, F1 Score=0.9991 | Val: Loss=0.3138, F1 Score=0.9481
Epoch  71/200 | Train: Loss=0.0054, F1 Score=0.9994 | Val: Loss=0.3131, F1 Score=0.9472

[I 2025-11-12 11:56:24,516] Trial 49 finished with value: 0.9598559395575468 and parameters: {'WINDOW': 40, 'STRIDE': 5, 'hidden_size': 128, 'num_layers': 3, 'dropout_rate': 0.21297996228664284, 'rnn_type': 'GRU', 'bidirectional': False, 'init_scheme': 'xavier_uniform', 'lr': 0.0007604025215493779, 'weight_decay': 1.0251409364626312e-06, 'l1_lambda': 1.4561880351637829e-07, 'focal_gamma': 2.0, 'scheduler_patience': 8, 'scheduler_factor': 0.1, 'weight_max_norm': 2.752565252052378}. Best is trial 49 with value: 0.9598559395575468.

Epoch  72/200 | Train: Loss=0.0052, F1 Score=0.9995 | Val: Loss=0.3110, F1 Score=0.9480
Early stopping triggered after 72 epochs.
Best model restored from epoch 57 with val_f1 0.9599

--- Tuning Complete ---
Best trial number: 49
Best validation F1-score: 0.9599
Best hyperparameters found:
  WINDOW: 40
  STRIDE: 5
  hidden_size: 128
  num_layers: 3
  dropout_rate: 0.21297996228664284
  rnn_type: GRU
  bidirectional: False
  init_scheme: xavier_uniform
  lr: 0.0007604025215493779
  weight_decay: 1.0251409364626312e-06
  l1_lambda: 1.4561880351637829e-07
  focal_gamma: 2.0
  scheduler_patience: 8
  scheduler_factor: 0.1
  weight_max_norm: 2.752565252052378

# Visulization and evaluation of the optuna study

In [48]:
def load_model_from_study(study, trial_number, input_shape, num_classes, device):
    """
    Load a model from an Optuna study given a specific trial number.

    Args:
        study (optuna.Study): The Optuna study object.
        trial_number (int): Trial number to load.
        input_shape (tuple): Shape of input data (e.g., X_train.shape).
        num_classes (int): Number of output classes.
        device (torch.device): Device to load the model on.

    Returns:
        model (torch.nn.Module or None): Loaded PyTorch model or None if file not found.
    """

    # Find trial parameters
    trial = None
    for t in study.trials:
        if t.number == trial_number:
            trial = t
            break
    
    if trial is None:
        print(f"ERROR: Trial number {trial_number} not found in study.")
        return None
    
    params = trial.params

    # Re-create the model architecture
    model = RecurrentClassifier(
        input_size=input_shape[-1],
        hidden_size=params["hidden_size"],
        num_layers=params["num_layers"],
        num_classes=num_classes,
        dropout_rate=params["dropout_rate"],
        bidirectional=params["bidirectional"],
        rnn_type=params["rnn_type"]
    ).to(device)

    # Load the saved state dict
    model_path = f"models/optuna_trial_{trial_number}_model.pt"
    try:
        model.load_state_dict(torch.load(model_path))
        print(f"Successfully loaded model from trial {trial_number} -> {model_path}")
        return model
    except FileNotFoundError:
        print(f"ERROR: Could not find model file {model_path}.")
        print("This might happen if the trial was pruned before saving a model.")
        return None
        
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
trial_num = 1  # Change this to the trial number you want to load

loaded_model = load_model_from_study(study, trial_num, input_shape, num_classes, device)

if loaded_model is not None:
    # Evaluate the model, e.g., plot confusion matrix
    pass

Successfully loaded model from trial 1 -> models/optuna_trial_1_model.pt

In [49]:
import optuna
from optuna.visualization import (
    plot_optimization_history,
    plot_param_importances,
    plot_parallel_coordinate,
    plot_contour,
    plot_intermediate_values
)

In [50]:
fig = plot_param_importances(study)
fig.show()

In [51]:
fig = plot_contour(study)
fig.show()

[W 2025-11-12 11:57:53,334] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,338] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,340] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,343] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,347] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,350] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,353] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,356] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,358] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,361] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,362] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,363] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,363] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,364] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,365] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,366] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,367] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,367] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,368] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,369] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,370] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,370] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,371] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,372] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,374] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,377] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,379] Param rnn_type unique value length is less than 2.
[W 2025-11-12 11:57:53,382] Param rnn_type unique value length is less than 2.

## Predict Public tests

In [52]:
def generate_submission_from_trial(
    study, 
    trial_number, 
    input_shape, 
    num_classes, 
    device,
    df_test,
    feature_cols,
    BATCH_SIZE,
    make_loader,
    model_class,
    inverse_label_map
):
    """
    Generalized test inference pipeline for a given Optuna trial.

    Args:
        study (optuna.Study): Your Optuna study object.
        trial_number (int): Trial number to load.
        input_shape (tuple): Shape of training data (used for input_size).
        num_classes (int): Number of output classes.
        device (torch.device): CPU or GPU.
        df_test (pd.DataFrame): Test dataframe with 'sample_index' and features.
        feature_cols (list): List of feature columns.
        BATCH_SIZE (int): Batch size for inference.
        make_loader (function): Function to create DataLoader.
        model_class (torch.nn.Module): Class for the model to instantiate.
        inverse_label_map (dict): Map numeric labels to string labels.

    Returns:
        submission_df (pd.DataFrame): Submission with 'sample_index' and 'label'.
    """

    # --- 1. Load the model ---
    model = load_model_from_study(
        study=study,
        trial_number=trial_number,
        input_shape=input_shape,
        num_classes=num_classes,
        device=device
    )
    if model is None:
        return None

    # --- 2. Get WINDOW and STRIDE from trial ---
    trial = next(t for t in study.trials if t.number == trial_number)
    SEQ_LENGTH = trial.params["WINDOW"]
    STEP = trial.params["STRIDE"]

    # --- 3. Create sliding windows ---
    def create_test_sliding_windows(X_df_full, feature_cols, seq_length, step):
        X_sequences, sample_index_map = [], []
        grouped = X_df_full.groupby('sample_index')
        for sample_id, user_data in grouped:
            user_features = user_data[feature_cols].values.astype(np.float32)
            for i in range(0, len(user_features) - seq_length + 1, step):
                X_sequences.append(user_features[i:i + seq_length])
                sample_index_map.append(sample_id)
        return np.array(X_sequences, dtype=np.float32), sample_index_map

    X_test_seq, test_index_map = create_test_sliding_windows(
        df_test, feature_cols, SEQ_LENGTH, STEP
    )
    print(f"Created test sequences: {X_test_seq.shape}")

    # --- 4. TensorDataset & DataLoader ---
    X_test_tensor = torch.from_numpy(X_test_seq)
    test_ds = TensorDataset(X_test_tensor)
    test_loader = make_loader(test_ds, batch_size=BATCH_SIZE, shuffle=False, drop_last=False)

    # --- 5. Generate predictions ---
    model.eval()
    all_logits = []
    with torch.no_grad():
        for (inputs,) in test_loader:
            inputs = inputs.to(device)
            with torch.amp.autocast(device_type=device.type, enabled=(device.type == 'cuda')):
                logits = model(inputs)
            all_logits.append(logits.cpu().numpy())

    final_logits_all_windows = np.concatenate(all_logits)
    print(f"Generated logits for {len(final_logits_all_windows)} windows.")

    # --- 6. Aggregate predictions ---
    pred_df = pd.DataFrame({'sample_index': test_index_map})
    for c in range(num_classes):
        pred_df[f'logit_{c}'] = final_logits_all_windows[:, c]

    submission_logits_avg = pred_df.groupby('sample_index')[[f'logit_{c}' for c in range(num_classes)]].mean()
    final_numeric_predictions = submission_logits_avg.idxmax(axis=1).str.replace('logit_', '').astype(int)
    final_numeric_predictions = final_numeric_predictions.reset_index(name='prediction')
    final_labels = final_numeric_predictions['prediction'].map(inverse_label_map)

    submission_df = pd.DataFrame({
        'sample_index': final_numeric_predictions['sample_index'],
        'label': final_labels
    })

    from datetime import datetime
    submission_df.to_csv(f'try_{datetime.now().strftime("%Y%m%d_%H%M%S")}_submission.csv', index=False)
    print(f"Submission saved with {len(submission_df)} rows.")
    print(submission_df.head())

    return submission_df
trial_num = 1 
submission_df = generate_submission_from_trial(
    study=study,
    trial_number=trial_num,
    input_shape=input_shape,
    num_classes=num_classes,
    device=device,
    df_test=df_public_test,
    feature_cols=feature_cols,
    BATCH_SIZE=BATCH_SIZE,
    make_loader=make_loader,
    model_class=RecurrentClassifier,
    inverse_label_map={0: 'no_pain', 1: 'low_pain', 2: 'high_pain'}
)

Successfully loaded model from trial 1 -> models/optuna_trial_1_model.pt
Created test sequences: (17212, 40, 32)
Generated logits for 17212 windows.
Submission saved with 1324 rows.
   sample_index    label
0             0  no_pain
1             1  no_pain
2             2  no_pain
3             3  no_pain
4             4  no_pain